# Generated by Django 3.2.12 on 2022-09-14 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sede', '0003_alter_sede_options'),
        ('cotizacion', '0038_cotizacionventadetalle_tiempo_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('sociedad', '0022_sociedad_pie_pagina'),
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_despacho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Despacho')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo Anulación')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('confirmacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.confirmacionventa')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Despacho_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Despacho_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['numero_despacho'],
            },
        ),
        migrations.CreateModel(
            name='NotaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salida', models.CharField(max_length=50, verbose_name='Número Salida')),
                ('observacion_adicional', models.TextField(blank=True, null=True, verbose_name='Observación Adicional')),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo Anulación')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('confirmacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizacion.confirmacionventa')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaSalida_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Salida',
                'verbose_name_plural': 'Notas de Salida',
                'ordering': ['numero_salida'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPrestamoMaterialesDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('cantidad_prestamo', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Cantidad Prestamo')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SolicitudPrestamoMaterialesDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SolicitudPrestamoMaterialesDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Prestamo Materiales Detalle',
                'verbose_name_plural': 'Solicitudes Prestamo Materiales Detalle',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPrestamoMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prestamo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Prestamo')),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha Prestamo')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo Anulación')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('cliente_interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clienteinterlocutor')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SolicitudPrestamoMateriales_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SolicitudPrestamoMateriales_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Prestamo Materiales',
                'verbose_name_plural': 'Solicitudes Prestamo Materiales',
                'ordering': ['numero_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='NotaSalidaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad_salida', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Cantidad Salida')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('confirmacion_venta_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizacion.confirmacionventadetalle', verbose_name='Confirmación Venta Detalle')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaSalidaDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.notasalida')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaSalidaDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Salida Detalle',
                'verbose_name_plural': 'Notas de Salida Detalle',
                'ordering': ['item'],
            },
        ),
        migrations.AddField(
            model_name='notasalida',
            name='solicitud_prestamo_materiales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.solicitudprestamomateriales'),
        ),
        migrations.AddField(
            model_name='notasalida',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaSalida_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DespachoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad_despachada', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Cantidad Despachada')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('confirmacion_venta_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.confirmacionventadetalle')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DespachoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.despacho')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DespachoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despacho Detalle',
                'verbose_name_plural': 'Despachos Detalle',
                'ordering': ['item'],
            },
        ),
    ]
