# Generated by Django 3.2.12 on 2022-09-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1),
        ),
        migrations.AlterField(
            model_name='despachodetalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1),
        ),
        migrations.AlterField(
            model_name='notasalida',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1),
        ),
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1),
        ),
        migrations.AlterField(
            model_name='solicitudprestamomateriales',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1),
        ),
        migrations.AlterField(
            model_name='solicitudprestamomaterialesdetalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1),
        ),
    ]
