# Generated by Django 3.2.12 on 2022-09-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_auto_20220916_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamomaterialesdetalle',
            name='solicitud_prestamo_materiales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistica.solicitudprestamomateriales'),
        ),
    ]
