# Generated by Django 3.2.12 on 2022-09-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_solicitudprestamomaterialesdetalle_solicitud_prestamo_materiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprestamomateriales',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'FINALIZADO SIN CONFIRMAR'), (3, 'CONFIRMADO'), (4, 'ANULADO'), (5, 'CONCLUIDO')], default=1),
        ),
    ]
