# Generated by Django 3.2.12 on 2022-09-22 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistica', '0004_alter_solicitudprestamomateriales_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPrestamoMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='', verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoPrestamoMateriales_created_by', to=settings.AUTH_USER_MODEL)),
                ('solicitud_prestamo_materiales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistica.solicitudprestamomateriales')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoPrestamoMateriales_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Prestamo Materiales',
                'verbose_name_plural': 'Documentos Prestamo Materiales',
            },
        ),
    ]
