# Generated by Django 3.2.12 on 2022-09-27 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_documentoprestamomateriales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudprestamomaterialesdetalle',
            name='estado',
        ),
        migrations.AlterField(
            model_name='solicitudprestamomaterialesdetalle',
            name='solicitud_prestamo_materiales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SolicitudPrestamoMaterialesDetalle_solicitud_prestamo_materiales', to='logistica.solicitudprestamomateriales'),
        ),
    ]
