# Generated by Django 3.2.12 on 2022-10-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_auto_20220927_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'DESPACHADO'), (3, 'ANULADO'), (4, 'CONCLUIDO SIN GUIA'), (5, 'CONCLUIDO CON GUIA')], default=1),
        ),
        migrations.AlterField(
            model_name='notasalida',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'ATENDIDO'), (3, 'ANULADO')], default=1),
        ),
    ]
