# Generated by Django 3.2.12 on 2022-10-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_auto_20220927_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachodetalle',
            name='despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DespachoDetalle_despacho', to='logistica.despacho'),
        ),
    ]
