# Generated by Django 3.2.12 on 2022-10-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_auto_20221004_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
        migrations.AlterField(
            model_name='despachodetalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
        migrations.AlterField(
            model_name='notasalida',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
    ]
