# Generated by Django 3.2.12 on 2022-10-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('sociedad', '0022_sociedad_pie_pagina'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('logistica', '0007_alter_despachodetalle_despacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='confirmacion_venta',
        ),
        migrations.RemoveField(
            model_name='despachodetalle',
            name='confirmacion_venta_detalle',
        ),
        migrations.AddField(
            model_name='despacho',
            name='fecha_despacho',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Despacho'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='nota_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistica.notasalida'),
        ),
        migrations.AddField(
            model_name='despachodetalle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='despachodetalle',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad'),
        ),
    ]
