# Generated by Django 3.2.12 on 2022-10-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('almacenes', '0001_initial'),
        ('cotizacion', '0044_alter_cotizacionventa_numero_cotizacion'),
        ('logistica', '0007_auto_20221004_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasalida',
            name='confirmacion_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cotizacion.confirmacionventa'),
        ),
        migrations.AlterField(
            model_name='notasalida',
            name='numero_salida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Salida'),
        ),
        migrations.AlterField(
            model_name='notasalida',
            name='solicitud_prestamo_materiales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.solicitudprestamomateriales'),
        ),
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen'),
        ),
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='cantidad_salida',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=22, null=True, verbose_name='Cantidad Salida'),
        ),
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='confirmacion_venta_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cotizacion.confirmacionventadetalle'),
        ),
        migrations.AlterField(
            model_name='solicitudprestamomaterialesdetalle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
