# Generated by Django 3.2.12 on 2022-10-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_auto_20221005_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotaSalidaDetalle',
        ),
    ]
