# Generated by Django 3.2.12 on 2022-10-05 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0003_alter_sede_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0044_alter_cotizacionventa_numero_cotizacion'),
        ('almacenes', '0001_initial'),
        ('logistica', '0009_delete_notasalidadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaSalidaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad_salida', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=22, null=True, verbose_name='Cantidad Salida')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('confirmacion_venta_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cotizacion.confirmacionventadetalle')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaSalidaDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.notasalida')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
                ('solicitud_prestamo_materiales_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.solicitudprestamomaterialesdetalle')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaSalidaDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Salida Detalle',
                'verbose_name_plural': 'Notas de Salida Detalle',
                'ordering': ['item'],
            },
        ),
    ]
