# Generated by Django 3.2.12 on 2022-10-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_notasalidadetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasalida',
            name='numero_salida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Salida'),
        ),
        migrations.AlterField(
            model_name='solicitudprestamomateriales',
            name='numero_prestamo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Prestamo'),
        ),
    ]
