# Generated by Django 3.2.12 on 2022-10-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0011_auto_20221005_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='numero_despacho',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Despacho'),
        ),
    ]
