# Generated by Django 3.2.12 on 2022-10-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_alter_despacho_numero_despacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudprestamomateriales',
            name='cliente_interlocutor',
        ),
    ]
