# Generated by Django 3.2.12 on 2022-10-05 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('logistica', '0013_remove_solicitudprestamomateriales_cliente_interlocutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamomateriales',
            name='interlocutor_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente'),
        ),
    ]
