# Generated by Django 3.2.12 on 2022-10-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_auto_20221005_1436'),
        ('logistica', '0008_auto_20221007_1544'),
        ('logistica', '0014_solicitudprestamomateriales_interlocutor_cliente'),
    ]

    operations = [
    ]
