# Generated by Django 3.2.12 on 2022-10-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0015_merge_20221007_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'DESPACHADO'), (3, 'ANULADO'), (4, 'CONCLUIDO SIN GUIA'), (5, 'CONCLUIDO CON GUIA')], default=1),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='numero_despacho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Despacho'),
        ),
        migrations.AlterField(
            model_name='notasalida',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'ATENDIDO'), (3, 'ANULADO')], default=1),
        ),
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='cantidad_salida',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Cantidad Salida'),
        ),
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='nota_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotaSalidaDetalle_nota_salida', to='logistica.notasalida'),
        ),
    ]
