# Generated by Django 3.2.12 on 2022-10-12 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0016_auto_20221011_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='solicitud_prestamo_materiales_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotaSalidaDetalle_solicitud_prestamo_materiales_detalle', to='logistica.solicitudprestamomaterialesdetalle'),
        ),
    ]
