# Generated by Django 3.2.12 on 2022-10-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0016_auto_20221010_1050'),
        ('logistica', '0017_alter_notasalidadetalle_solicitud_prestamo_materiales_detalle'),
    ]

    operations = [
    ]
