# Generated by Django 3.2.12 on 2022-10-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0018_merge_20221012_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='cliente',
        ),
    ]
