# Generated by Django 3.2.12 on 2022-10-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_remove_clienteanexo_ubigeo'),
        ('logistica', '0019_remove_despacho_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
