# Generated by Django 3.2.12 on 2022-10-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0020_despacho_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='nota_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Despacho_nota_salida', to='logistica.notasalida'),
        ),
    ]
