# Generated by Django 3.2.12 on 2022-11-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0021_alter_despacho_nota_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'DESPACHADO'), (3, 'ANULADO'), (4, 'CONCLUIDO SIN GUIA'), (5, 'CONCLUIDO CON GUIA'), (6, 'GUIA ANULADA')], default=1),
        ),
    ]
