# Generated by Django 3.2.12 on 2022-12-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0023_validadserienotasalidadetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validadserienotasalidadetalle',
            name='estado',
        ),
    ]
