# Generated by Django 3.2.12 on 2022-12-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0019_auto_20221215_1711'),
        ('logistica', '0025_remove_validadserienotasalidadetalle_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='validadserienotasalidadetalle',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie'),
        ),
    ]
