# Generated by Django 3.2.12 on 2022-12-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0027_auto_20221220_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validarserienotasalidadetalle',
            name='nota_salida_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieNotaSalidaDetalle_nota_salida_detalle', to='logistica.notasalidadetalle'),
        ),
    ]
