# Generated by Django 3.2.12 on 2022-12-27 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0058_alter_confirmacionordencompra_documento'),
        ('logistica', '0028_alter_validarserienotasalidadetalle_nota_salida_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasalida',
            name='confirmacion_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaSalida_confirmacion_venta', to='cotizacion.confirmacionventa'),
        ),
        migrations.AlterField(
            model_name='notasalida',
            name='solicitud_prestamo_materiales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistica.solicitudprestamomateriales'),
        ),
    ]
