# Generated by Django 3.2.12 on 2022-12-27 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0058_alter_confirmacionordencompra_documento'),
        ('logistica', '0029_auto_20221227_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='confirmacion_venta_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaSalidaDetalle_confirmacion_venta_detalle', to='cotizacion.confirmacionventadetalle'),
        ),
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='solicitud_prestamo_materiales_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NotaSalidaDetalle_solicitud_prestamo_materiales_detalle', to='logistica.solicitudprestamomaterialesdetalle'),
        ),
    ]
