# Generated by Django 3.2.12 on 2023-01-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0030_auto_20221227_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notasalida',
            options={'ordering': ['-numero_salida'], 'verbose_name': 'Nota de Salida', 'verbose_name_plural': 'Notas de Salida'},
        ),
    ]
