# Generated by Django 3.2.12 on 2023-01-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0031_alter_notasalida_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validarserienotasalidadetalle',
            options={'ordering': ['created_at'], 'verbose_name': 'Validar Series Nota de Salida Detalle', 'verbose_name_plural': 'Validar Series Notas de Salida Detalle'},
        ),
    ]
