# Generated by Django 3.2.12 on 2023-01-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0032_alter_validarserienotasalidadetalle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despacho',
            options={'ordering': ['-numero_despacho'], 'verbose_name': 'Despacho', 'verbose_name_plural': 'Despachos'},
        ),
        migrations.AlterField(
            model_name='despacho',
            name='numero_despacho',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Despacho'),
        ),
    ]
