# Generated by Django 3.2.12 on 2023-01-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_alter_interlocutorcliente_tipo_documento'),
        ('logistica', '0033_auto_20230109_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprestamomateriales',
            name='interlocutor_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SolicitudPrestamoMateriales_interlocutor_cliente', to='clientes.interlocutorcliente'),
        ),
    ]
