# Generated by Django 3.2.12 on 2023-01-16 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0034_alter_solicitudprestamomateriales_interlocutor_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasalida',
            name='solicitud_prestamo_materiales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NotaSalida_solicitud_prestamo_materiales', to='logistica.solicitudprestamomateriales'),
        ),
    ]
