# Generated by Django 3.2.12 on 2023-01-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0035_alter_notasalida_solicitud_prestamo_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasalida',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
