# Generated by Django 3.2.12 on 2023-01-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logistica', '0036_notasalida_id_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasalida',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
