# Generated by Django 3.2.12 on 2023-01-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0037_notasalida_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasalida',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notasalida',
            name='id_registro',
        ),
    ]
