# Generated by Django 3.2.12 on 2023-01-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logistica', '0038_auto_20230125_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaSalidaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('nota_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotaSalidaDocumento_nota_salida', to='logistica.notasalida')),
            ],
            options={
                'verbose_name': 'Nota Salida Documento',
                'verbose_name_plural': 'Nota Salida Documentos',
            },
        ),
    ]
