# Generated by Django 3.2.12 on 2023-01-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0040_auto_20230125_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasalida',
            name='solicitud_prestamo_materiales',
        ),
    ]
