# Generated by Django 3.2.12 on 2023-01-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0041_remove_notasalida_solicitud_prestamo_materiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasalida',
            name='confirmacion_venta',
        ),
    ]
