# Generated by Django 3.2.12 on 2023-01-26 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logistica', '0042_remove_notasalida_confirmacion_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasalidadetalle',
            name='content_type_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notasalidadetalle',
            name='id_registro_detalle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
