# Generated by Django 3.2.12 on 2023-01-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0043_auto_20230126_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasalidadetalle',
            name='confirmacion_venta_detalle',
        ),
        migrations.RemoveField(
            model_name='notasalidadetalle',
            name='solicitud_prestamo_materiales_detalle',
        ),
    ]
