# Generated by Django 3.2.12 on 2023-02-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0045_imagenesdespacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenesdespacho',
            name='despacho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistica.despacho'),
            preserve_default=False,
        ),
    ]
