# Generated by Django 3.2.12 on 2023-02-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0046_imagenesdespacho_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesdespacho',
            name='despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImagenesDespacho_despacho', to='logistica.despacho'),
        ),
    ]
