# Generated by Django 3.2.12 on 2023-02-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0048_inventariomateriales_inventariomaterialesdetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariomateriales',
            name='fecha_inventario',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Inventario'),
        ),
    ]
