# Generated by Django 3.2.12 on 2023-02-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0049_alter_inventariomateriales_fecha_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariomaterialesdetalle',
            name='inventario_materiales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistica.inventariomateriales'),
            preserve_default=False,
        ),
    ]
