# Generated by Django 3.2.12 on 2023-02-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0050_inventariomaterialesdetalle_inventario_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariomaterialesdetalle',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
