# Generated by Django 3.2.12 on 2023-02-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0051_inventariomaterialesdetalle_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariomaterialesdetalle',
            name='inventario_materiales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InventarioMaterialesDetalle_inventario_materiales', to='logistica.inventariomateriales'),
        ),
    ]
