# Generated by Django 3.2.12 on 2023-02-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0052_alter_inventariomaterialesdetalle_inventario_materiales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariomaterialesdetalle',
            options={'ordering': ['item'], 'verbose_name': 'Inventario Materiales Detalle', 'verbose_name_plural': 'Inventarios Materiales Detalle'},
        ),
    ]
