# Generated by Django 3.2.12 on 2023-02-13 16:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0039_material_id_multiplay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimiento_almacen', '0013_alter_movimientosalmacen_options'),
        ('usuario', '0006_alter_datosusuario_tipo_documento'),
        ('almacenes', '0004_alter_almacen_sede'),
        ('sede', '0006_alter_sede_sociedad'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('logistica', '0053_alter_inventariomaterialesdetalle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventarioMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ajuste_inventario', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Inventario')),
                ('hora_ajuste_inventario', models.TimeField(auto_now_add=True, verbose_name='Hora de Inventario')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDO'), (3, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AjusteInventarioMateriales_created_by', to=settings.AUTH_USER_MODEL)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.datosusuario')),
            ],
            options={
                'verbose_name': 'Ajuste Inventario Materiales',
                'verbose_name_plural': 'Ajuste Inventarios Materiales',
            },
        ),
        migrations.AlterField(
            model_name='inventariomateriales',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.datosusuario'),
        ),
        migrations.CreateModel(
            name='AjusteInventarioMaterialesDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('ajuste_inventario_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AjusteInventarioMaterialesDetalle_ajuste_inventario_materiales', to='logistica.ajusteinventariomateriales')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AjusteInventarioMaterialesDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('tipo_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AjusteInventarioMaterialesDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste Inventario Materiales Detalle',
                'verbose_name_plural': 'Ajuste Inventarios Materiales Detalle',
                'ordering': ['item'],
            },
        ),
        migrations.AddField(
            model_name='ajusteinventariomateriales',
            name='inventario_materiales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistica.inventariomateriales'),
        ),
        migrations.AddField(
            model_name='ajusteinventariomateriales',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.sede'),
        ),
        migrations.AddField(
            model_name='ajusteinventariomateriales',
            name='sociedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad'),
        ),
        migrations.AddField(
            model_name='ajusteinventariomateriales',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AjusteInventarioMateriales_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
