# Generated by Django 3.2.12 on 2023-02-13 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistica', '0054_auto_20230213_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajusteinventariomateriales',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='inventariomateriales',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ajusteinventariomateriales',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AjusteInventarioMateriales_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='inventariomateriales',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InventarioMateriales_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
