# Generated by Django 3.2.12 on 2023-02-21 17:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0055_auto_20230213_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajusteinventariomaterialesdetalle',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='ajusteinventariomaterialesdetalle',
            name='cantidad_contada',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad Contada'),
        ),
        migrations.AddField(
            model_name='ajusteinventariomaterialesdetalle',
            name='cantidad_stock',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad Stock'),
        ),
    ]
