# Generated by Django 3.2.12 on 2023-03-22 21:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0056_auto_20230221_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesdespacho',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='img/imagenes-despacho/'),
        ),
    ]
