# Generated by Django 3.2.12 on 2023-03-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0057_alter_imagenesdespacho_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajusteinventariomaterialesdetalle',
            options={'ordering': ['ajuste_inventario_materiales', 'item'], 'verbose_name': 'Ajuste Inventario Materiales Detalle', 'verbose_name_plural': 'Ajuste Inventarios Materiales Detalle'},
        ),
        migrations.AlterModelOptions(
            name='despachodetalle',
            options={'ordering': ['despacho', 'item'], 'verbose_name': 'Despacho Detalle', 'verbose_name_plural': 'Despachos Detalle'},
        ),
        migrations.AlterModelOptions(
            name='inventariomaterialesdetalle',
            options={'ordering': ['inventario_materiales', 'item'], 'verbose_name': 'Inventario Materiales Detalle', 'verbose_name_plural': 'Inventarios Materiales Detalle'},
        ),
        migrations.AlterModelOptions(
            name='notasalidadetalle',
            options={'ordering': ['nota_salida', 'item'], 'verbose_name': 'Nota de Salida Detalle', 'verbose_name_plural': 'Notas de Salida Detalle'},
        ),
        migrations.AlterModelOptions(
            name='solicitudprestamomaterialesdetalle',
            options={'ordering': ['solicitud_prestamo_materiales', 'item'], 'verbose_name': 'Solicitud Prestamo Materiales Detalle', 'verbose_name_plural': 'Solicitudes Prestamo Materiales Detalle'},
        ),
    ]
