# Generated by Django 3.2.12 on 2023-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0059_merge_0058_auto_20230324_1647_0058_auto_20230328_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachodetalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1),
        ),
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1),
        ),
    ]
