# Generated by Django 3.2.12 on 2023-04-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0061_merge_0060_auto_20230401_1229_0060_auto_20230401_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachodetalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
        migrations.AlterField(
            model_name='notasalidadetalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
    ]
