# Generated by Django 3.2.12 on 2023-08-14 19:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0029_alter_sociedad_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0038_alter_cliente_estado_crm'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('logistica', '0062_auto_20230411_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionPrestamoMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devolucion', models.IntegerField(blank=True, null=True, verbose_name='Número Prestamo')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha Prestamo')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo Anulación')),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'CONFIRMADO'), (3, 'ANULADO')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionPrestamoMateriales_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionPrestamoMateriales_interlocutor_cliente', to='clientes.interlocutorcliente')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionPrestamoMateriales_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolucion Prestamo Materiales',
                'verbose_name_plural': 'Devoluciones Prestamo Materiales',
                'ordering': ['numero_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionPrestamoMaterialesDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('cantidad_devolucion', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad Prestamo')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionPrestamoMaterialesDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('devolucion_materiales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DevolucionPrestamoMaterialesDetalle_devolucion_materiales', to='logistica.devolucionprestamomateriales')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionPrestamoMaterialesDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolucion Prestamo Materiales Detalle',
                'verbose_name_plural': 'Devoluciones Prestamo Materiales Detalle',
                'ordering': ['devolucion_materiales', 'item'],
            },
        ),
    ]
