# Generated by Django 3.2.12 on 2023-08-14 22:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0063_devolucionprestamomateriales_devolucionprestamomaterialesdetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucionprestamomateriales',
            name='solicitud_prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistica.solicitudprestamomateriales'),
        ),
        migrations.AlterField(
            model_name='devolucionprestamomateriales',
            name='fecha_devolucion',
            field=models.DateField(verbose_name='Fecha Devolución'),
        ),
        migrations.AlterField(
            model_name='devolucionprestamomateriales',
            name='numero_devolucion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Devolución'),
        ),
        migrations.AlterField(
            model_name='devolucionprestamomaterialesdetalle',
            name='cantidad_devolucion',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad Devuelta'),
        ),
    ]
