# Generated by Django 3.2.12 on 2023-08-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0064_auto_20230814_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudprestamomateriales',
            options={'ordering': ['estado', '-numero_prestamo'], 'verbose_name': 'Solicitud Prestamo Materiales', 'verbose_name_plural': 'Solicitudes Prestamo Materiales'},
        ),
    ]
