# Generated by Django 3.2.12 on 2023-08-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0006_alter_almacen_estado_alta_baja'),
        ('logistica', '0065_alter_solicitudprestamomateriales_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucionprestamomaterialesdetalle',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen'),
        ),
    ]
