# Generated by Django 3.2.12 on 2023-08-22 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0061_alter_historialestadoserie_options'),
        ('logistica', '0066_devolucionprestamomaterialesdetalle_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprestamomateriales',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'FINALIZADO SIN CONFIRMAR'), (3, 'CONFIRMADO'), (4, 'ANULADO'), (5, 'CONCLUIDO'), (6, 'DEVUELTO')], default=1),
        ),
        migrations.CreateModel(
            name='ValidarSerieDevolucionPrestamoMaterialesDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieDevolucionPrestamoMaterialesDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('devolucion_prestamo_materiales_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ValidarSerieDevolucionPrestamoMaterialesDetalle_devolucion_prestamo_materiales_detalle', to='logistica.devolucionprestamomaterialesdetalle')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieDevolucionPrestamoMaterialesDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validar Series Devoluciones Prestamo Materiales Detalle',
                'verbose_name_plural': 'Validar Series Devoluciones Prestamo Materiales Detalle',
                'ordering': ['created_at'],
            },
        ),
    ]
