# Generated by Django 3.2.12 on 2023-08-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0067_auto_20230822_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validarseriedevolucionprestamomaterialesdetalle',
            name='devolucion_prestamo_materiales_detalle',
        ),
        migrations.AddField(
            model_name='validarseriedevolucionprestamomaterialesdetalle',
            name='devolucion_materiales_detalle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ValidarSerieDevolucionPrestamoMaterialesDetalle_devolucion_materiales_detalle', to='logistica.devolucionprestamomaterialesdetalle'),
            preserve_default=False,
        ),
    ]
