# Generated by Django 3.2.12 on 2023-08-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0068_auto_20230825_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucionprestamomateriales',
            name='despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistica.despacho'),
        ),
    ]
