# Generated by Django 3.2.12 on 2023-08-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0069_devolucionprestamomateriales_despacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucionprestamomateriales',
            name='despacho',
        ),
    ]
