# Generated by Django 3.2.12 on 2022-10-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='tipo_documento',
            field=models.CharField(choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)')], max_length=1, verbose_name='Tipo de Documento'),
        ),
    ]
