# Generated by Django 3.2.12 on 2023-06-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio_clientes', '0002_alter_transportista_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='condicion_sunat',
            field=models.IntegerField(choices=[(1, 'Habido'), (2, 'No hallado'), (3, 'No habido')], default=1, verbose_name='Condición SUNAT'),
        ),
        migrations.AddField(
            model_name='transportista',
            name='estado_sunat',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspensión temporal'), (3, 'Baja provisional'), (4, 'Baja definitiva'), (5, 'Baja provisional de oficio'), (6, 'Baja definitiva de oficio'), (7, 'Baja interna')], default=1, verbose_name='Estado SUNAT'),
        ),
    ]
