# Generated by Django 3.2.12 on 2024-06-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envio_clientes', '0005_alter_transportista_tipo_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportista',
            options={'ordering': ['razon_social'], 'verbose_name': 'Transportista', 'verbose_name_plural': 'Transportistas'},
        ),
    ]
