# Generated by Django 3.2.12 on 2023-08-25 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sociedad', '0029_alter_sociedad_options'),
        ('almacenes', '0006_alter_almacen_estado_alta_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('calidad', '0061_alter_historialestadoserie_options'),
        ('sede', '0008_alter_sede_estado'),
        ('movimiento_almacen', '0014_movimientosalmacen_transformacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioSociedadStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cambio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro. Cambio')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDO'), (3, 'ANULADO')], default=1, null=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CambioSociedadStock_created_by', to=settings.AUTH_USER_MODEL)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sede.sede')),
                ('sociedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CambioSociedadStock_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio Sociedad Stock',
                'verbose_name_plural': 'Cambios Sociedad Stock',
                'ordering': ['-nro_cambio'],
            },
        ),
        migrations.CreateModel(
            name='CambioSociedadStockDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad de Cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen')),
                ('cambio_sociedad_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CambioSociedadStockDetalle_cambio_sociedad_stock', to='cambio_sociedad.cambiosociedadstock')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CambioSociedadStockDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('tipo_stock_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CambioSociedadStockDetalle_tipo_stock_final', to='movimiento_almacen.tipostock')),
                ('tipo_stock_inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CambioSociedadStockDetalle_tipo_stock_inicial', to='movimiento_almacen.tipostock')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CambioSociedadStockDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio Sociedad Stock Detalle',
                'verbose_name_plural': 'Cambios Sociedad Stock Detalle',
            },
        ),
        migrations.CreateModel(
            name='ValidarSerieCambioSociedadStockDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cambio_sociedad_stock_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieCambioSociedadStockDetalle_cambio_sociedad_stock_detalle', to='cambio_sociedad.cambiosociedadstockdetalle')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieCambioSociedadStockDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieCambioSociedadStockDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validar Series Cambio Sociedad Stock Detalle',
                'verbose_name_plural': 'Validar Series Cambios Sociedad Stock Detalle',
                'ordering': ['created_at'],
            },
        ),
    ]
