# Generated by Django 3.2.12 on 2023-08-28 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0029_alter_sociedad_options'),
        ('movimiento_almacen', '0014_movimientosalmacen_transformacion'),
        ('cambio_sociedad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambiosociedadstock',
            name='sociedad',
        ),
        migrations.RemoveField(
            model_name='cambiosociedadstockdetalle',
            name='tipo_stock_final',
        ),
        migrations.RemoveField(
            model_name='cambiosociedadstockdetalle',
            name='tipo_stock_inicial',
        ),
        migrations.AddField(
            model_name='cambiosociedadstock',
            name='sociedad_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CambioSociedadStock_sociedad_final', to='sociedad.sociedad'),
        ),
        migrations.AddField(
            model_name='cambiosociedadstock',
            name='sociedad_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CambioSociedadStock_sociedad_inicial', to='sociedad.sociedad'),
        ),
        migrations.AddField(
            model_name='cambiosociedadstockdetalle',
            name='tipo_stock',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='CambioSociedadStockDetalle_tipo_stock', to='movimiento_almacen.tipostock'),
            preserve_default=False,
        ),
    ]
