# Generated by Django 3.2.12 on 2023-09-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio_sociedad', '0002_auto_20230828_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cambiosociedadstockdetalle',
            options={'ordering': ('item',), 'verbose_name': 'Cambio Sociedad Stock Detalle', 'verbose_name_plural': 'Cambios Sociedad Stock Detalle'},
        ),
        migrations.AlterField(
            model_name='cambiosociedadstock',
            name='nro_cambio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro. Cambio'),
        ),
    ]
