# Generated by Django 3.2.12 on 2022-05-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0017_alter_sociedad_distrito'),
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='sociedad',
        ),
        migrations.AddField(
            model_name='sede',
            name='sociedad',
            field=models.ManyToManyField(to='sociedad.Sociedad'),
        ),
    ]
