# Generated by Django 3.2.12 on 2022-05-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0002_auto_20220512_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['estado', 'nombre'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
    ]
