# Generated by Django 3.2.12 on 2022-10-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('sede', '0005_alter_sede_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='sociedad',
            field=models.ManyToManyField(related_name='Sede_sociedad', to='sociedad.Sociedad'),
        ),
    ]
