# Generated by Django 3.2.12 on 2022-10-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=500, verbose_name='Nombre Completo')),
                ('documento', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('telefono', models.CharField(max_length=50, verbose_name='Número de Telefono')),
                ('correo', models.CharField(max_length=500, verbose_name='Correo electrónico')),
                ('premio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Premio')),
                ('elegido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['premio'],
            },
        ),
    ]
