# Generated by Django 3.2.12 on 2022-10-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_webinar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='documento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Documento'),
        ),
    ]
