# Generated by Django 3.2.12 on 2023-06-11 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('material', '0042_auto_20230411_0924'),
        ('datos_globales', '0047_auto_20230411_0924'),
        ('proveedores', '0013_auto_20230411_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='AtributoMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='AtributoMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atributo Merchandising',
                'verbose_name_plural': 'Atributos Merchandising',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClaseMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(default='img/merchandising/clase/default_image.png', upload_to='img/merchandising/clase/', verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ClaseMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ClaseMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase Merchandising',
                'verbose_name_plural': 'Clases Merchandising',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ComponenteMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ComponenteMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Componente Merchandising',
                'verbose_name_plural': 'Componentes Merchandising',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FamiliaMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('atributos', models.ManyToManyField(blank=True, to='merchandising.AtributoMerchandising')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FamiliaMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FamiliaMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Familia Merchandising',
                'verbose_name_plural': 'Familias Merchandising',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MarcaMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=42, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='MarcaMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marca Merchandising',
                'verbose_name_plural': 'Marcas Merchandising',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Merchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_venta', models.CharField(max_length=150, verbose_name='Descripción Venta')),
                ('descripcion_corta', models.CharField(max_length=55, verbose_name='Descripción Corta')),
                ('peso_unidad_base', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso Unidad Base')),
                ('control_serie', models.BooleanField(default=False, verbose_name='Control Serie')),
                ('control_lote', models.BooleanField(default=False, verbose_name='Control Lote')),
                ('control_calidad', models.BooleanField(default=False, verbose_name='Control Calidad')),
                ('estado_alta_baja', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado')),
                ('mostrar', models.BooleanField(default=False, verbose_name='Mostrar')),
                ('traduccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Traducción')),
                ('partida', models.CharField(blank=True, max_length=30, null=True, verbose_name='Partida')),
                ('uso_funcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Uso función')),
                ('compuesto_por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Compuesto por')),
                ('es_componente', models.BooleanField(default=False, verbose_name='Es componente')),
                ('id_producto_temporal', models.IntegerField(blank=True, null=True)),
                ('id_multiplay', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('atributo', models.ManyToManyField(related_name='Merchandising_atributo', to='merchandising.AtributoMerchandising', verbose_name='Atributo')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Merchandising_clase', to='merchandising.clasemerchandising')),
            ],
            options={
                'verbose_name': 'Merchandising',
                'verbose_name_plural': 'Merchandising',
                'ordering': ['estado_alta_baja', 'descripcion_venta'],
            },
        ),
        migrations.CreateModel(
            name='VideoMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción video merchandising')),
                ('url', models.URLField(verbose_name='URL video merchandising')),
                ('estado_alta_baja', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='VideoMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.merchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='VideoMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Merchandising',
                'verbose_name_plural': 'Videos Merchandising',
                'ordering': ['estado_alta_baja'],
            },
        ),
        migrations.CreateModel(
            name='SubFamiliaMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('componentes', models.ManyToManyField(blank=True, to='merchandising.ComponenteMerchandising')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SubFamiliaMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchandising.familiamerchandising')),
                ('unidad', models.ManyToManyField(to='datos_globales.Unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SubFamiliaMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubFamilia Merchandising',
                'verbose_name_plural': 'SubFamilias Merchandising',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RelacionMerchandisingComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('componentemerchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.componentemerchandising', verbose_name='Componente merchandising')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RelacionMerchandisingComponente_created_by', to=settings.AUTH_USER_MODEL)),
                ('merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.merchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RelacionMerchandisingComponente_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relacion Merchandising Componente',
                'verbose_name_plural': 'Relacion Merchandising Componentes',
            },
        ),
        migrations.CreateModel(
            name='ProveedorMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('estado_alta_baja', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ProveedorMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ProveedorMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor Merchandising',
                'verbose_name_plural': 'Proveedores Merchandising',
                'ordering': ['estado_alta_baja'],
            },
        ),
        migrations.CreateModel(
            name='ModeloMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=41, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ModeloMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ModeloMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo Merchandising',
                'verbose_name_plural': 'Modelos Merchandising',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='merchandising',
            name='componente',
            field=models.ManyToManyField(related_name='Merchandising_componente', through='merchandising.RelacionMerchandisingComponente', to='merchandising.ComponenteMerchandising', verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='merchandising',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Merchandising_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchandising',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Merchandising_marca', to='merchandising.marcamerchandising'),
        ),
        migrations.AddField(
            model_name='merchandising',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Merchandising_modelo', to='merchandising.modelomerchandising'),
        ),
        migrations.AddField(
            model_name='merchandising',
            name='producto_sunat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Merchandising_producto_sunat', to='datos_globales.productosunat'),
        ),
        migrations.AddField(
            model_name='merchandising',
            name='subfamilia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Merchandising_subfamilia', to='merchandising.subfamiliamerchandising'),
        ),
        migrations.AddField(
            model_name='merchandising',
            name='unidad_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Merchandising_unidad_base', to='datos_globales.unidad'),
        ),
        migrations.AddField(
            model_name='merchandising',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Merchandising_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marcamerchandising',
            name='modelos',
            field=models.ManyToManyField(to='merchandising.ModeloMerchandising'),
        ),
        migrations.AddField(
            model_name='marcamerchandising',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='MarcaMerchandising_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImagenMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción imagen merchandising')),
                ('imagen', models.ImageField(upload_to='img/merchandising/imagen/', verbose_name='Imagen merchandising')),
                ('estado_alta_baja', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ImagenMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.merchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ImagenMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen Merchandising',
                'verbose_name_plural': 'Imagenes Merchandising',
                'ordering': ['estado_alta_baja'],
            },
        ),
        migrations.CreateModel(
            name='IdiomaMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traduccion', models.CharField(max_length=50, verbose_name='Traducción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='IdiomaMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.idioma')),
                ('merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.merchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='IdiomaMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idioma Merchandising',
                'verbose_name_plural': 'Idiomas Merchandising',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('atributomerchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.atributomerchandising', verbose_name='Atributo Merchandising')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EspecificacionMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.merchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EspecificacionMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Especificacion Merchandising',
                'verbose_name_plural': 'Especificaciones Merchandising',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EquivalenciaUnidadMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_base', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad Base')),
                ('cantidad_nueva_unidad', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad Nueva')),
                ('estado_alta_baja', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EquivalenciaUnidadMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.merchandising')),
                ('nueva_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EquivalenciaUnidadMerchandising_nueva_unidad', to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EquivalenciaUnidadMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equivalencia Unidad Merchandising',
                'verbose_name_plural': 'Equivalencia Unidades Merchandising',
                'ordering': ['estado_alta_baja'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='file/merchandising/archivo_datasheet/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DatasheetMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.merchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DatasheetMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datasheet Merchandising',
                'verbose_name_plural': 'Datasheets Merchandising',
            },
        ),
    ]
