# Generated by Django 3.2.12 on 2023-07-03 16:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0014_movimientosalmacen_transformacion'),
        ('sociedad', '0026_alter_representantelegal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sede', '0008_alter_sede_estado'),
        ('almacenes', '0006_alter_almacen_estado_alta_baja'),
        ('merchandising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventarioMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ajuste_inventario', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Inventario')),
                ('hora_ajuste_inventario', models.TimeField(auto_now_add=True, verbose_name='Hora de Inventario')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDO'), (3, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AjusteInventarioMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste Inventario Merchandising',
                'verbose_name_plural': 'Ajuste Inventarios Merchandising',
            },
        ),
        migrations.CreateModel(
            name='InventarioMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inventario', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Inventario')),
                ('hora_inventario', models.TimeField(auto_now_add=True, verbose_name='Hora de Inventario')),
                ('estado', models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InventarioMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InventarioMerchandising_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
                ('sociedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InventarioMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario Merchandising',
                'verbose_name_plural': 'Inventarios Merchandising',
            },
        ),
        migrations.CreateModel(
            name='InventarioMerchandisingDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InventarioMerchandisingDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('inventario_merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InventarioMerchandisingDetalle_inventario_merchandising', to='merchandising.inventariomerchandising')),
                ('merchandising', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchandising.merchandising')),
                ('tipo_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InventarioMerchandisingDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario Merchandising Detalle',
                'verbose_name_plural': 'Inventarios Merchandising Detalle',
                'ordering': ['inventario_merchandising', 'item'],
            },
        ),
        migrations.CreateModel(
            name='AjusteInventarioMerchandisingDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad_stock', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad Stock')),
                ('cantidad_contada', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad Contada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('ajuste_inventario_merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AjusteInventarioMerchandisingDetalle_ajuste_inventario_merchandising', to='merchandising.ajusteinventariomerchandising')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AjusteInventarioMerchandisingDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('merchandising', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchandising.merchandising')),
                ('tipo_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AjusteInventarioMerchandisingDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste Inventario Merchandising Detalle',
                'verbose_name_plural': 'Ajuste Inventarios Merchandising Detalle',
                'ordering': ['ajuste_inventario_merchandising', 'item'],
            },
        ),
        migrations.AddField(
            model_name='ajusteinventariomerchandising',
            name='inventario_merchandising',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchandising.inventariomerchandising'),
        ),
        migrations.AddField(
            model_name='ajusteinventariomerchandising',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AjusteInventarioMerchandising_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='ajusteinventariomerchandising',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.sede'),
        ),
        migrations.AddField(
            model_name='ajusteinventariomerchandising',
            name='sociedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad'),
        ),
        migrations.AddField(
            model_name='ajusteinventariomerchandising',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AjusteInventarioMerchandising_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
