# Generated by Django 3.2.12 on 2023-08-15 22:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('merchandising', '0002_auto_20230703_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaRequerimientoMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ListaRequerimientoMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ListaRequerimientoMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Requerimiento Merchandising',
                'verbose_name_plural': 'Listas de Requerimiento Merchandising',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfertaProveedorMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('tiempo_estimado_entrega', models.IntegerField(blank=True, null=True, verbose_name='Tiempo estimado de entrega (dias)')),
                ('forma_pago', models.TextField(blank=True, null=True, verbose_name='Forma de pago')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones')),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'APROBADO'), (3, 'RECHAZADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OfertaProveedorMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('lista_requerimiento_merchandising', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='OfertaProveedorMerchandising_lista_requerimiento_merchandising', to='merchandising.listarequerimientomerchandising')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OfertaProveedorMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta Proveedor Merchandising',
                'verbose_name_plural': 'Ofertas Proveedor Merchandising',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfertaProveedorMerchandisingDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('proveedor_material', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio Unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Sub Total')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OfertaProveedorMerchandisingDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('oferta_proveedor_merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OfertaProveedorMerchandisingDetalle_oferta_proveedor', to='merchandising.ofertaproveedormerchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OfertaProveedorMerchandisingDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta Proveedor Detalle Merchandising',
                'verbose_name_plural': 'Ofertas Proveedor Detalle Merchandising',
                'ordering': ['oferta_proveedor_merchandising', 'item'],
            },
        ),
        migrations.CreateModel(
            name='ListaRequerimientoMerchandisingDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('merchandising', models.TextField()),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ListaRequerimientoMerchandisingDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('lista_requerimiento_merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ListaRequerimientoMerchandisingDetalle_requerimiento_material', to='merchandising.listarequerimientomerchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ListaRequerimientoMerchandisingDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Requerimiento Merchandising Detalle',
                'verbose_name_plural': 'Listas de Requerimiento Merchandising Detalle',
                'ordering': ['item'],
            },
        ),
    ]
