# Generated by Django 3.2.12 on 2023-08-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('merchandising', '0003_listarequerimientomerchandising_listarequerimientomerchandisingdetalle_ofertaproveedormerchandising_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listarequerimientomerchandisingdetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='listarequerimientomerchandisingdetalle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='listarequerimientomerchandisingdetalle',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listarequerimientomerchandisingdetalle',
            name='lista_requerimiento_merchandising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ListaRequerimientoMerchandisingDetalle_lista_requerimiento_merchandising', to='merchandising.listarequerimientomerchandising'),
        ),
        migrations.AlterField(
            model_name='listarequerimientomerchandisingdetalle',
            name='merchandising',
            field=models.CharField(max_length=150, verbose_name='Merchandising'),
        ),
    ]
