# Generated by Django 3.2.12 on 2023-08-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0004_auto_20230821_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='proveedor_material',
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='numero_oferta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Oferta'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='proveedor',
            field=models.CharField(default=1, max_length=50, verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='tipo_igv',
            field=models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], default=8, verbose_name='Tipo de IGV'),
        ),
        migrations.AlterField(
            model_name='listarequerimientomerchandisingdetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Cantidad'),
        ),
    ]
