# Generated by Django 3.2.12 on 2023-08-25 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
        ('merchandising', '0005_auto_20230825_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandising',
            options={'ordering': ['estado_alta_baja', 'descripcion_corta'], 'verbose_name': 'Merchandising', 'verbose_name_plural': 'Merchandising'},
        ),
        migrations.RemoveField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='proveedor',
            field=models.CharField(default=1, max_length=50, verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='atributo',
            field=models.ManyToManyField(blank=True, max_length=55, null=True, related_name='Merchandising_atributo', to='merchandising.AtributoMerchandising', verbose_name='Atributo'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='componente',
            field=models.ManyToManyField(blank=True, max_length=55, null=True, related_name='Merchandising_componente', through='merchandising.RelacionMerchandisingComponente', to='merchandising.ComponenteMerchandising', verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='control_calidad',
            field=models.BooleanField(blank=True, default=False, max_length=55, null=True, verbose_name='Control Calidad'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='control_lote',
            field=models.BooleanField(blank=True, default=False, max_length=55, null=True, verbose_name='Control Lote'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='control_serie',
            field=models.BooleanField(blank=True, default=False, max_length=55, null=True, verbose_name='Control Serie'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='descripcion_venta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Venta'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='peso_unidad_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, max_length=55, null=True, verbose_name='Peso Unidad Base'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='unidad_base',
            field=models.ForeignKey(blank=True, max_length=55, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Merchandising_unidad_base', to='datos_globales.unidad'),
        ),
        migrations.AlterField(
            model_name='ofertaproveedormerchandising',
            name='lista_requerimiento_merchandising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OfertaProveedorMerchandising_lista_requerimiento_merchandising', to='merchandising.listarequerimientomerchandising'),
        ),
    ]
