# Generated by Django 3.2.12 on 2023-08-31 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('merchandising', '0006_auto_20230825_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listarequerimientomerchandisingdetalle',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='listarequerimientomerchandisingdetalle',
            name='id_registro',
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='merchandising',
            field=models.CharField(default=1, max_length=150, verbose_name='Merchandising'),
            preserve_default=False,
        ),
    ]
