# Generated by Django 3.2.12 on 2023-09-04 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0007_auto_20230831_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandising',
            name='subfamilia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Merchandising_subfamilia', to='merchandising.subfamiliamerchandising'),
        ),
        migrations.AlterField(
            model_name='proveedormerchandising',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='proveedormerchandising',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='proveedormerchandising',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
