# Generated by Django 3.2.12 on 2023-09-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0008_auto_20230903_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='evaluada',
            field=models.BooleanField(default=False),
        ),
    ]
