# Generated by Django 3.2.12 on 2023-09-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0009_ofertaproveedormerchandising_evaluada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedormerchandising',
            name='proveedor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proveedor'),
        ),
    ]
