# Generated by Django 3.2.12 on 2023-09-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0012_auto_20230907_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompramerchandisingdetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad'),
        ),
    ]
