# Generated by Django 3.2.12 on 2023-09-08 21:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0013_alter_comprobantecompramerchandisingdetalle_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='precio_final_con_igv',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio Final con IGV'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='precio_unitario_con_igv',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio Unitario con IGV'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='precio_unitario_sin_igv',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio Unitario sin IGV'),
        ),
    ]
