# Generated by Django 3.2.12 on 2023-09-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0014_auto_20230908_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='internacional_nacional',
            field=models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], default=1, verbose_name='Internacional-Nacional'),
        ),
    ]
