# Generated by Django 3.2.12 on 2023-09-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0015_ofertaproveedormerchandising_internacional_nacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='precio_unitario',
        ),
    ]
