# Generated by Django 3.2.12 on 2023-09-08 23:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0016_remove_ofertaproveedormerchandisingdetalle_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompramerchandising',
            name='internacional_nacional',
            field=models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], default=1, verbose_name='INTERNACIONAL-NACIONAL'),
        ),
        migrations.AddField(
            model_name='ordencompramerchandisingdetalle',
            name='precio_unitario_sin_igv',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio unitario sin igv'),
        ),
    ]
