# Generated by Django 3.2.12 on 2023-09-08 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('merchandising', '0017_auto_20230908_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompramerchandisingdetalle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='ordencompramerchandisingdetalle',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
