# Generated by Django 3.2.12 on 2023-09-08 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('merchandising', '0020_auto_20230908_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompramerchandisingdetalle',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordencompramerchandisingdetalle',
            name='id_registro',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
