# Generated by Django 3.2.12 on 2023-09-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0021_auto_20230908_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompramerchandisingdetalle',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
