# Generated by Django 3.2.12 on 2023-09-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0022_alter_ordencompramerchandisingdetalle_id_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompramerchandisingdetalle',
            name='id_registro',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
