# Generated by Django 3.2.12 on 2023-09-10 01:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0042_auto_20230411_0924'),
        ('merchandising', '0023_alter_ordencompramerchandisingdetalle_id_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Descuento Global'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='total_anticipo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Anticipo'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='total_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Descuento'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='total_exonerada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Exonerada'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='total_gratuita',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Gratuita'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='total_gravada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Gravada'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='total_icbper',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total ICBPER'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='total_igv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total IGV'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='total_inafecta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Inafecta'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandising',
            name='total_otros_cargos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Otros Cargos'),
        ),
        migrations.AddField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='proveedor_material',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='material.proveedormaterial'),
            preserve_default=False,
        ),
    ]
