# Generated by Django 3.2.12 on 2023-09-10 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0042_auto_20230411_0924'),
        ('merchandising', '0024_auto_20230909_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedormerchandisingdetalle',
            name='proveedor_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.proveedormaterial'),
        ),
    ]
