# Generated by Django 3.2.12 on 2023-09-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0025_alter_ofertaproveedormerchandisingdetalle_proveedor_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandising',
            name='atributo',
            field=models.ManyToManyField(blank=True, max_length=55, related_name='Merchandising_atributo', to='merchandising.AtributoMerchandising', verbose_name='Atributo'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='componente',
            field=models.ManyToManyField(blank=True, max_length=55, related_name='Merchandising_componente', through='merchandising.RelacionMerchandisingComponente', to='merchandising.ComponenteMerchandising', verbose_name='Componente'),
        ),
    ]
