# Generated by Django 3.2.12 on 2023-09-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0026_auto_20230911_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertaproveedormerchandising',
            options={'ordering': ['-fecha', '-updated_at', '-created_at'], 'verbose_name': 'Oferta Proveedor Merchandising', 'verbose_name_plural': 'Ofertas Proveedor Merchandising'},
        ),
        migrations.AlterModelOptions(
            name='ordencompramerchandising',
            options={'ordering': ['-numero_orden_compra', '-updated_at', '-created_at'], 'verbose_name': 'Orden Compra Merchandising', 'verbose_name_plural': 'Ordenes Compra Merchandising'},
        ),
        migrations.AlterField(
            model_name='ofertaproveedormerchandising',
            name='internacional_nacional',
            field=models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], default=2, verbose_name='Internacional-Nacional'),
        ),
    ]
