# Generated by Django 3.2.12 on 2023-09-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0027_auto_20230912_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompramerchandising',
            name='internacional_nacional',
            field=models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], default=2, verbose_name='INTERNACIONAL-NACIONAL'),
        ),
    ]
