# Generated by Django 3.2.12 on 2023-09-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0028_alter_ordencompramerchandising_internacional_nacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompramerchandising',
            name='internacional_nacional',
            field=models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], default=2, verbose_name='Internacional-Nacional'),
        ),
    ]
