# Generated by Django 3.2.12 on 2023-09-18 21:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0029_comprobantecompramerchandising_internacional_nacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantecompramerchandising',
            name='slug',
        ),
        migrations.AddField(
            model_name='comprobantecompramerchandising',
            name='total_exonerada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Exonerada'),
        ),
        migrations.AddField(
            model_name='comprobantecompramerchandising',
            name='total_gratuita',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Gratuita'),
        ),
        migrations.AddField(
            model_name='comprobantecompramerchandising',
            name='total_icbper',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total ICBPER'),
        ),
        migrations.AddField(
            model_name='comprobantecompramerchandising',
            name='total_inafecta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Inafecta'),
        ),
    ]
