# Generated by Django 3.2.12 on 2023-09-25 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0013_auto_20230411_0924'),
        ('sociedad', '0029_alter_sociedad_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacenes', '0006_alter_almacen_estado_alta_baja'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('merchandising', '0031_recepcioncompramerchandising'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaIngresoMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota_ingreso', models.IntegerField(blank=True, help_text='Correlativo', null=True, verbose_name='Número de Nota de Ingreso')),
                ('id_registro', models.IntegerField()),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación')),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'FINALIZADO'), (3, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Ingreso Merchandising',
                'verbose_name_plural': 'Notas de Ingreso Merchandising',
            },
        ),
        migrations.AlterModelOptions(
            name='recepcioncompramerchandising',
            options={'verbose_name': 'Recepción de Compra Merchandising', 'verbose_name_plural': 'Recepciones de Compras Merchandising'},
        ),
        migrations.CreateModel(
            name='NotaIngresoMerchandisingDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField()),
                ('cantidad_conteo', models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad del conteo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMerchandisingDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMerchandisingDetalle_nota_ingreso', to='merchandising.notaingresomerchandising')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMerchandisingDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Ingreso Detalle Merchandising',
                'verbose_name_plural': 'Notas de Ingreso Merchandising Detalles',
                'ordering': ['nota_ingreso', 'item'],
            },
        ),
        migrations.CreateModel(
            name='FotoRecepcionCompraMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='file/recepcion merchandising/foto recepcion', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FotoRecepcionCompraMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('recepcion_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.recepcioncompramerchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FotoRecepcionCompraMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de Comprobante de Compra Merchandising',
                'verbose_name_plural': 'Fotos de Comprobantes de Compra Merchandising',
                'ordering': ['recepcion_compra', 'foto'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoRecepcionCompraMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='file/recepcion merchandising/archivo recepcion', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArchivoRecepcionCompraMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('recepcion_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.recepcioncompramerchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArchivoRecepcionCompraMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Comprobante de Compra Merchandising',
                'verbose_name_plural': 'Archivos de Comprobantes de Compra Merchandising',
                'ordering': ['recepcion_compra', 'archivo'],
            },
        ),
    ]
