# Generated by Django 3.2.12 on 2023-09-28 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchandising', '0032_auto_20230925_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantecompramerchandising',
            name='logistico',
        ),
        migrations.AlterField(
            model_name='archivorecepcioncompramerchandising',
            name='archivo',
            field=models.FileField(upload_to='file/recepcion merchandising/archivo recepcion/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='fotorecepcioncompramerchandising',
            name='foto',
            field=models.ImageField(upload_to='file/recepcion merchandising/foto recepcion/', verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='ArchivoOfertaProveedorMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='file/merchandising/oferta_proveedor/detalle/archivo/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ArchivoOfertaProveedorMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('oferta_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchandising.ofertaproveedormerchandising')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ArchivoOfertaProveedorMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Oferta Proveedor Merchandising',
                'verbose_name_plural': 'Archivos Oferta Proveedor Merchandising',
            },
        ),
        migrations.CreateModel(
            name='ArchivoComprobanteCompraMerchandising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='file/merchandising/comprobante_compra/archivo/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('comprobante_compra_merchandising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.comprobantecompramerchandising')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArchivoComprobanteCompraMerchandising_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArchivoComprobanteCompraMerchandising_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Comprobante de Compra Merchandising',
                'verbose_name_plural': 'Archivos de Comprobantes de Compra Merchandising',
            },
        ),
    ]
