# Generated by Django 3.2.12 on 2023-11-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0033_auto_20230928_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandising',
            options={'ordering': ['created_at', 'estado_alta_baja'], 'verbose_name': 'Merchandising', 'verbose_name_plural': 'Merchandising'},
        ),
    ]
