# Generated by Django 3.2.12 on 2023-11-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0034_alter_merchandising_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandising',
            options={'ordering': ['-descripcion_corta'], 'verbose_name': 'Merchandising', 'verbose_name_plural': 'Merchandising'},
        ),
    ]
