# Generated by Django 3.2.12 on 2023-11-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0036_alter_merchandising_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandising',
            options={'ordering': ['estado_alta_baja', 'descripcion_venta'], 'verbose_name': 'Merchandising', 'verbose_name_plural': 'Merchandising'},
        ),
    ]
