# Generated by Django 3.2.12 on 2022-07-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0015_auto_20220601_1956'),
        ('clientes', '0016_alter_correocliente_options'),
        ('encuesta', '0002_auto_20220713_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.cargo'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='interlocutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='nombre_interlocutor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Interlocutor'),
        ),
    ]
