# Generated by Django 3.2.12 on 2022-07-13 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0015_auto_20220601_1956'),
        ('encuesta', '0003_auto_20220713_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='cargo',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='tipo_interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.tipointerlocutor'),
        ),
    ]
