# Generated by Django 3.2.12 on 2022-07-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_alter_correocliente_options'),
        ('encuesta', '0005_alter_respuesta_tipo_interlocutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente'),
        ),
    ]
