# Generated by Django 3.2.12 on 2022-07-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0006_alter_respuesta_interlocutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestadetalle',
            name='alternativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.alternativa'),
        ),
        migrations.AlterField(
            model_name='respuestadetalle',
            name='texto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texto'),
        ),
    ]
