# Generated by Django 3.2.12 on 2022-07-15 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0007_auto_20220713_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['pregunta', 'orden'], 'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['-created_by'], 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Alternativa_pregunta', to='encuesta.pregunta'),
        ),
        migrations.AlterField(
            model_name='respuestadetalle',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RespuestaDetalle_respuesta', to='encuesta.respuesta'),
        ),
    ]
