# Generated by Django 3.2.12 on 2022-07-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0008_auto_20220715_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=100, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=100, verbose_name='Texto'),
        ),
    ]
