# Generated by Django 3.2.12 on 2022-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0009_auto_20220720_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=150, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=150, verbose_name='Texto'),
        ),
    ]
