# Generated by Django 3.2.12 on 2023-01-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_alter_interlocutorcliente_tipo_documento'),
        ('encuesta', '0010_auto_20220720_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Respuesta_interlocutor', to='clientes.interlocutorcliente'),
        ),
    ]
