# Generated by Django 3.2.12 on 2022-10-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallamaterial',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
