# Generated by Django 3.2.12 on 2022-11-08 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nota_ingreso', '0005_alter_notaingreso_nro_nota_ingreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0002_alter_fallamaterial_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCalidadStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota_calidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro. Nota Calidad')),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación')),
                ('comentario', models.TextField()),
                ('estado', models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDA')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NotaCalidadStock_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota_ingreso.notaingreso')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NotaCalidadStock_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Calidad Stock',
                'verbose_name_plural': 'Notas Calidad Stock',
            },
        ),
        migrations.CreateModel(
            name='NotaCalidadStockDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad_calidad', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Cantidad Calidad')),
                ('inspeccion', models.IntegerField(choices=[(1, 'BUENO'), (2, 'DAÑADO')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NotaCalidadStockDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_calidad_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.notacalidadstock')),
                ('nota_ingreso_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota_ingreso.notaingresodetalle')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NotaCalidadStockDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Calidad Stock Detalle',
                'verbose_name_plural': 'Notas Calidad Stock Detalle',
            },
        ),
    ]
