# Generated by Django 3.2.12 on 2022-11-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0004_auto_20221108_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacontrolcalidadstock',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
