# Generated by Django 3.2.12 on 2022-11-14 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0005_alter_notacontrolcalidadstock_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacontrolcalidadstock',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDA'), (3, 'ANULADA')], default=1),
        ),
        migrations.AlterField(
            model_name='notacontrolcalidadstockdetalle',
            name='cantidad_calidad',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='notacontrolcalidadstockdetalle',
            name='inspeccion',
            field=models.IntegerField(choices=[(1, 'BUENO'), (2, 'DAÑADO')], verbose_name='Estado Inspección'),
        ),
        migrations.AlterField(
            model_name='notacontrolcalidadstockdetalle',
            name='nota_control_calidad_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotaControlCalidadStockDetalle_nota_control_calidad_stock', to='calidad.notacontrolcalidadstock'),
        ),
    ]
