# Generated by Django 3.2.12 on 2022-11-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0006_auto_20221114_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacontrolcalidadstockdetalle',
            name='inspeccion',
            field=models.IntegerField(choices=[(1, 'BUENO'), (2, 'DAÑADO')], default=1, verbose_name='Estado Inspección'),
        ),
    ]
