# Generated by Django 3.2.12 on 2022-11-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0007_alter_notacontrolcalidadstockdetalle_inspeccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='estado_serie',
        ),
    ]
