# Generated by Django 3.2.12 on 2022-11-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nota_ingreso', '0005_alter_notaingreso_nro_nota_ingreso'),
        ('calidad', '0008_remove_serie_estado_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='sociedad',
        ),
        migrations.AlterField(
            model_name='notacontrolcalidadstockdetalle',
            name='nota_ingreso_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotaControlCalidadStockDetalle_nota_ingreso_detalle', to='nota_ingreso.notaingresodetalle'),
        ),
    ]
