# Generated by Django 3.2.12 on 2022-11-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('calidad', '0009_auto_20221116_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='estado_serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calidad.estadoserie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='sociedad',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad'),
            preserve_default=False,
        ),
    ]
