# Generated by Django 3.2.12 on 2022-11-17 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0010_auto_20221117_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadoserie',
            name='falla_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.fallamaterial'),
        ),
        migrations.AlterField(
            model_name='historialestadoserie',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
