# Generated by Django 3.2.12 on 2022-11-17 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0010_alter_movimientosalmacen_movimiento_anterior'),
        ('calidad', '0011_auto_20221117_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='nota_control_calidad_stock_detalle',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='calidad.notacontrolcalidadstockdetalle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='serie_movimiento_almacen',
            field=models.ManyToManyField(to='movimiento_almacen.MovimientosAlmacen'),
        ),
    ]
