# Generated by Django 3.2.12 on 2022-11-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0012_auto_20221117_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='estado_serie',
        ),
    ]
