# Generated by Django 3.2.12 on 2022-11-23 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0013_remove_serie_estado_serie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialestadoserie',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Historial Estado Serie', 'verbose_name_plural': 'Historial Estado Series'},
        ),
        migrations.AlterField(
            model_name='historialestadoserie',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='historialestadoserie',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistorialEstadoSerie_serie', to='calidad.serie'),
        ),
    ]
