# Generated by Django 3.2.12 on 2022-11-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0014_auto_20221123_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notacontrolcalidadstockdetalle',
            options={'ordering': ['item'], 'verbose_name': 'Nota Control Calidad Stock Detalle', 'verbose_name_plural': 'Notas Control Calidad Stock Detalle'},
        ),
    ]
