# Generated by Django 3.2.12 on 2022-11-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0015_alter_notacontrolcalidadstockdetalle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notacontrolcalidadstock',
            options={'ordering': ['nro_nota_calidad'], 'verbose_name': 'Nota Control Calidad Stock', 'verbose_name_plural': 'Notas Control Calidad Stock'},
        ),
    ]
