# Generated by Django 3.2.12 on 2022-11-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0016_alter_notacontrolcalidadstock_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='serie_base',
            field=models.CharField(max_length=200, verbose_name='Nro. Serie'),
        ),
    ]
