# Generated by Django 3.2.12 on 2022-12-14 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('calidad', '0017_alter_serie_serie_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_base', models.CharField(max_length=200, verbose_name='Nro. Serie')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'SUBIDO')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SerieConsulta_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SerieConsulta_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serie Consulta',
                'verbose_name_plural': 'Series Consultas',
            },
        ),
    ]
