# Generated by Django 3.2.12 on 2022-12-15 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_auto_20221123_1859'),
        ('material', '0038_proveedormaterial_unidad'),
        ('calidad', '0018_serieconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='serieconsulta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='serieconsulta',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material'),
        ),
    ]
