# Generated by Django 3.2.12 on 2022-12-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0019_auto_20221215_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialestadoserie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial Estado Serie', 'verbose_name_plural': 'Historial Estado Series'},
        ),
    ]
