# Generated by Django 3.2.12 on 2022-12-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0020_alter_historialestadoserie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacontrolcalidadstock',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'POR REGISTRAR SERIES'), (3, 'CONCLUIDA'), (4, 'ANULADA')], default=1),
        ),
    ]
