# Generated by Django 3.2.12 on 2022-12-22 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0021_alter_notacontrolcalidadstock_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=200, verbose_name='Nro. Serie')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SerieCalidad_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_control_calidad_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.notacontrolcalidadstockdetalle')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SerieCalidad_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serie Calidad',
                'verbose_name_plural': 'Series Calidad',
            },
        ),
    ]
