# Generated by Django 3.2.12 on 2022-12-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0022_seriecalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriecalidad',
            name='falla_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.fallamaterial'),
        ),
        migrations.AddField(
            model_name='seriecalidad',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
