# Generated by Django 3.2.12 on 2022-12-22 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0023_auto_20221221_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seriecalidad',
            old_name='nota_control_calidad_detalle',
            new_name='nota_control_calidad_stock_detalle',
        ),
    ]
