# Generated by Django 3.2.12 on 2022-12-22 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0024_rename_nota_control_calidad_detalle_seriecalidad_nota_control_calidad_stock_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriecalidad',
            name='estado',
            field=models.IntegerField(choices=[(1, 'DISPONIBLE'), (2, 'DUPLICADO')], default=1),
        ),
        migrations.AlterField(
            model_name='seriecalidad',
            name='nota_control_calidad_stock_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SerieCalidad_nota_control_calidad_stock_detalle', to='calidad.notacontrolcalidadstockdetalle'),
        ),
    ]
