# Generated by Django 3.2.12 on 2022-12-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0010_alter_movimientosalmacen_movimiento_anterior'),
        ('material', '0038_proveedormaterial_unidad'),
        ('calidad', '0025_auto_20221221_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallamaterial',
            name='sub_familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FallaMaterial_sub_familia', to='material.subfamilia'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='serie_movimiento_almacen',
            field=models.ManyToManyField(blank=True, to='movimiento_almacen.MovimientosAlmacen'),
        ),
    ]
