# Generated by Django 3.2.12 on 2022-12-22 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0026_auto_20221222_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolucionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('comentario', models.TextField()),
                ('visible', models.BooleanField()),
                ('falla_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SolucionMaterial_falla_material', to='calidad.fallamaterial')),
            ],
            options={
                'verbose_name': 'Solución Material',
                'verbose_name_plural': 'Soluciones Materiales',
            },
        ),
        migrations.AddField(
            model_name='historialestadoserie',
            name='solucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.solucionmaterial'),
        ),
    ]
