# Generated by Django 3.2.12 on 2022-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0010_alter_movimientosalmacen_movimiento_anterior'),
        ('calidad', '0027_auto_20221222_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='serie_movimiento_almacen',
            field=models.ManyToManyField(blank=True, related_name='Serie_serie_movimiento_almacen', to='movimiento_almacen.MovimientosAlmacen'),
        ),
    ]
