# Generated by Django 3.2.12 on 2023-01-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0028_alter_serie_serie_movimiento_almacen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notacontrolcalidadstock',
            options={'ordering': ['-nro_nota_calidad'], 'verbose_name': 'Nota Control Calidad Stock', 'verbose_name_plural': 'Notas Control Calidad Stock'},
        ),
    ]
