# Generated by Django 3.2.12 on 2023-01-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0029_alter_notacontrolcalidadstock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialestadoserie',
            options={'ordering': ['created_at'], 'verbose_name': 'Historial Estado Serie', 'verbose_name_plural': 'Historial Estado Series'},
        ),
        migrations.AlterModelOptions(
            name='seriecalidad',
            options={'ordering': ['created_at'], 'verbose_name': 'Serie Calidad', 'verbose_name_plural': 'Series Calidad'},
        ),
    ]
