# Generated by Django 3.2.12 on 2023-02-06 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0030_auto_20230109_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudConsumoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.IntegerField(blank=True, null=True, verbose_name='Número de Solicitud')),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha Solicitud')),
                ('fecha_consumo', models.DateField(blank=True, null=True, verbose_name='Fecha Consumo')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('estado', models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'POR APROBACIÓN'), (3, 'ANULADO'), (4, 'RECHAZADO')], default=1)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SolicitudConsumoInterno_created_by', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SolicitudConsumoInterno_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Consumo Interno',
                'verbose_name_plural': 'Solicitudes Consumo Interno',
                'ordering': ['-fecha_solicitud', '-numero_solicitud'],
            },
        ),
    ]
