# Generated by Django 3.2.12 on 2023-02-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0031_solicitudconsumointerno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudconsumointerno',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
    ]
