# Generated by Django 3.2.12 on 2023-02-07 19:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacenes', '0004_alter_almacen_sede'),
        ('sede', '0006_alter_sede_sociedad'),
        ('material', '0039_material_id_multiplay'),
        ('calidad', '0032_alter_solicitudconsumointerno_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudConsumoInternoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad Consumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SolicitudConsumoInternoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
                ('solicitud_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SolicitudConsumoInternoDetalle_solicitud_consumo', to='calidad.solicitudconsumointerno')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SolicitudConsumoInternoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Consumo Interno Detalle',
                'verbose_name_plural': 'Solicitudes Consumo Interno Detalles',
                'ordering': ['solicitud_consumo', 'item'],
            },
        ),
    ]
