# Generated by Django 3.2.12 on 2023-02-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('calidad', '0033_solicitudconsumointernodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudconsumointerno',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sociedad.sociedad'),
        ),
        migrations.AlterField(
            model_name='solicitudconsumointerno',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'EN PROCESO'), (3, 'ANULADO'), (4, 'POR APROBACIÓN'), (5, 'RECHAZADO')], default=1),
        ),
    ]
