# Generated by Django 3.2.12 on 2023-02-10 23:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_alter_almacen_sede'),
        ('material', '0039_material_id_multiplay'),
        ('sede', '0006_alter_sede_sociedad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0034_auto_20230209_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionConsumoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aprobacion', models.IntegerField(blank=True, null=True, verbose_name='Número de aprobacion')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha aprobacion')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'APROBADO'), (3, 'RECHAZADO'), (4, 'ANULADO')], default=1)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='AprobacionConsumoInterno_created_by', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('solicitud_consumo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calidad.solicitudconsumointerno')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='AprobacionConsumoInterno_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobacion de Consumo Interno',
                'verbose_name_plural': 'Aprobaciones de Consumo Interno',
                'ordering': ['-fecha_aprobacion', '-numero_aprobacion'],
            },
        ),
        migrations.CreateModel(
            name='AprobacionConsumoInternoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad Consumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('aprobacion_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AprobacionConsumoInternoDetalle_aprobacion_consumo', to='calidad.aprobacionconsumointerno')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='AprobacionConsumoInternoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='AprobacionConsumoInternoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobacion Consumo Interno Detalle',
                'verbose_name_plural': 'Aprobaciones Consumo Interno Detalles',
                'ordering': ['aprobacion_consumo', 'item'],
            },
        ),
    ]
