# Generated by Django 3.2.12 on 2023-02-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0035_aprobacionconsumointerno_aprobacionconsumointernodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacionconsumointernodetalle',
            name='aprobacion_consumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AprobacionConsumoInternoDetalle_aprobacion_consumo', to='calidad.aprobacionconsumointerno'),
        ),
    ]
