# Generated by Django 3.2.12 on 2023-02-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0036_alter_aprobacionconsumointernodetalle_aprobacion_consumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudconsumointerno',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'EN PROCESO'), (3, 'ANULADO'), (4, 'POR APROBACIÓN'), (5, 'RECHAZADO'), (6, 'APROBADO')], default=1),
        ),
    ]
