# Generated by Django 3.2.12 on 2023-02-14 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0037_alter_solicitudconsumointerno_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidarSerieSolicitudConsumoInternoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieSolicitudConsumoInternoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie')),
                ('solicitud_consumo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieSolicitudConsumoInternoDetalle_solicitud_consumo_detalle', to='calidad.solicitudconsumointernodetalle')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieSolicitudConsumoInternoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validar Series Solicitud de Consumo Detalle',
                'verbose_name_plural': 'Validar Series Solicitudes de Consumo Detalle',
                'ordering': ['created_at'],
            },
        ),
    ]
