# Generated by Django 3.2.12 on 2023-02-24 23:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0013_alter_movimientosalmacen_options'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('almacenes', '0004_alter_almacen_sede'),
        ('sede', '0006_alter_sede_sociedad'),
        ('material', '0039_material_id_multiplay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0038_validarseriesolicitudconsumointernodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformacionProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transformacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Transformación')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransformacionProductos_created_by', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransformacionProductos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('sociedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransformacionProductos_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transformación de Productos',
                'verbose_name_plural': 'Transformaciones de Productos',
            },
        ),
        migrations.CreateModel(
            name='SalidaTransformacionProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalidaTransformacionProductos_created_by', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
                ('tipo_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock')),
                ('transformacion_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SalidaTransformacionProductos_transformacion_productos', to='calidad.transformacionproductos')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalidaTransformacionProductos_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida Transformación de Productos',
                'verbose_name_plural': 'Salida Transformaciones de Productos',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='EntradaTransformacionProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EntradaTransformacionProductos_created_by', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
                ('tipo_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock')),
                ('transformacion_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EntradaTransformacionProductos_transformacion_productos', to='calidad.transformacionproductos')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EntradaTransformacionProductos_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada Transformación de Productos',
                'verbose_name_plural': 'Entrada Transformaciones de Productos',
                'ordering': ['item'],
            },
        ),
    ]
