# Generated by Django 3.2.12 on 2023-03-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0038_validarseriesolicitudconsumointernodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='nota_control_calidad_stock_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.notacontrolcalidadstockdetalle'),
        ),
    ]
