# Generated by Django 3.2.12 on 2023-03-01 21:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('sede', '0006_alter_sede_sociedad'),
        ('material', '0039_material_id_multiplay'),
        ('almacenes', '0004_alter_almacen_sede'),
        ('calidad', '0038_validarseriesolicitudconsumointernodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReparacionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reparacion', models.IntegerField(blank=True, null=True, verbose_name='Número de Reparación')),
                ('fecha_reparacion_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio de reparación')),
                ('fecha_reparacion_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin de reparacion')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('tiempo_estimado', models.TimeField(blank=True, null=True, verbose_name='Tiempo estimado')),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'EN PROCESO'), (3, 'CONCLUIDO'), (4, 'ANULADO')], default=1)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReparacionMaterial_created_by', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReparacionMaterial_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reparación de Material',
                'verbose_name_plural': 'Reparaciónes de Materiales',
                'ordering': ['-fecha_reparacion_inicio', '-numero_reparacion'],
            },
        ),
        migrations.CreateModel(
            name='ReparacionMaterialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad Consumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReparacionMaterialDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReparacionMaterialDetalle_reparacion', to='calidad.reparacionmaterial')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReparacionMaterialDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reparación de Material Detalle',
                'verbose_name_plural': 'Reparaciónes de Materiales Detalles',
                'ordering': ['reparacion', 'item'],
            },
        ),
    ]
