# Generated by Django 3.2.12 on 2023-03-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0039_reparacionmaterial_reparacionmaterialdetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacionmaterial',
            name='tiempo_estimado',
        ),
    ]
