# Generated by Django 3.2.12 on 2023-03-03 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0039_entradatransformacionproductos_salidatransformacionproductos_transformacionproductos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidarSerieEntradaTransformacionProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieEntradaTransformacionProductos_created_by', to=settings.AUTH_USER_MODEL)),
                ('entrada_transformacion_productos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieEntradaTransformacionProductos_entrada_transformacion_productos', to='calidad.entradatransformacionproductos')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieEntradaTransformacionProductos_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validar Series Entrada Transformacion Productos',
                'verbose_name_plural': 'Validar Series Entradas Transformacion Productos',
                'ordering': ['created_at'],
            },
        ),
    ]
