# Generated by Django 3.2.12 on 2023-03-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0013_alter_movimientosalmacen_options'),
        ('calidad', '0040_validarserieentradatransformacionproductos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradatransformacionproductos',
            name='tipo_stock',
        ),
        migrations.RemoveField(
            model_name='salidatransformacionproductos',
            name='tipo_stock',
        ),
        migrations.AddField(
            model_name='transformacionproductos',
            name='tipo_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock'),
            preserve_default=False,
        ),
    ]
