# Generated by Django 3.2.12 on 2023-03-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0040_remove_reparacionmaterial_tiempo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacionmaterial',
            name='tiempo_estimado',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiempo estimado'),
        ),
    ]
