# Generated by Django 3.2.12 on 2023-03-02 21:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0041_reparacionmaterial_tiempo_estimado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacionmaterialdetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad a reparar'),
        ),
        migrations.CreateModel(
            name='ValidarSerieReparacionMaterialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieReparacionMaterialDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('reparacion_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieReparacionMaterialDetalle_solicitud_consumo_detalle', to='calidad.reparacionmaterialdetalle')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie')),
                ('solucion_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.solucionmaterial')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieReparacionMaterialDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validar Series Reparación de Material Detalle',
                'verbose_name_plural': 'Validar Series Reparaciones de Materiales Detalles',
                'ordering': ['created_at'],
            },
        ),
    ]
