# Generated by Django 3.2.12 on 2023-03-04 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0042_auto_20230302_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucionmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solucionmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SolucionMaterial_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solucionmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='solucionmaterial',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SolucionMaterial_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validarseriereparacionmaterialdetalle',
            name='reparacion_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieReparacionMaterialDetalle_reparacion_detalle', to='calidad.reparacionmaterialdetalle'),
        ),
    ]
