# Generated by Django 3.2.12 on 2023-03-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0042_validarseriesalidatransformacionproductos'),
        ('calidad', '0043_auto_20230304_1216'),
    ]

    operations = [
    ]
