# Generated by Django 3.2.12 on 2023-03-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0039_alter_serie_nota_control_calidad_stock_detalle'),
        ('calidad', '0044_merge_20230309_1732'),
    ]

    operations = [
    ]
