# Generated by Django 3.2.12 on 2023-03-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0045_merge_20230310_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='seriecalidad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Serie Calidad', 'verbose_name_plural': 'Series Calidad'},
        ),
        migrations.AlterModelOptions(
            name='serieconsulta',
            options={'ordering': ['-created_at'], 'verbose_name': 'Serie Consulta', 'verbose_name_plural': 'Series Consultas'},
        ),
    ]
