# Generated by Django 3.2.12 on 2023-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0045_merge_20230310_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transformacionproductos',
            options={'ordering': ['-numero_transformacion'], 'verbose_name': 'Transformación de Productos', 'verbose_name_plural': 'Transformaciones de Productos'},
        ),
        migrations.AddField(
            model_name='transformacionproductos',
            name='numero_transformacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Transformación'),
        ),
    ]
