# Generated by Django 3.2.12 on 2023-03-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0047_auto_20230315_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacontrolcalidadstock',
            name='nota_ingreso',
        ),
    ]
