# Generated by Django 3.2.12 on 2023-03-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0046_auto_20230315_1044'),
        ('calidad', '0048_remove_notacontrolcalidadstock_nota_ingreso'),
    ]

    operations = [
    ]
