# Generated by Django 3.2.12 on 2023-03-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('calidad', '0049_merge_20230315_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacontrolcalidadstockdetalle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notacontrolcalidadstockdetalle',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
