# Generated by Django 3.2.12 on 2023-03-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0050_auto_20230315_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacontrolcalidadstockdetalle',
            name='nota_ingreso_detalle',
        ),
    ]
