# Generated by Django 3.2.12 on 2023-03-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0051_remove_notacontrolcalidadstockdetalle_nota_ingreso_detalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoserie',
            options={'ordering': ['numero_estado'], 'verbose_name': 'Estado Serie', 'verbose_name_plural': 'Estados Serie'},
        ),
        migrations.AlterModelOptions(
            name='historialestadoserie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial Estado Serie', 'verbose_name_plural': 'Historial Estado Series'},
        ),
    ]
