# Generated by Django 3.2.12 on 2023-03-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0052_auto_20230322_1159'),
        ('calidad', '0052_auto_20230322_1517'),
    ]

    operations = [
    ]
