# Generated by Django 3.2.12 on 2023-03-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0052_auto_20230322_1055'),
        ('calidad', '0053_merge_0052_auto_20230322_1159_0052_auto_20230322_1517'),
    ]

    operations = [
    ]
