# Generated by Django 3.2.12 on 2023-03-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0053_merge_0052_auto_20230322_1159_0052_auto_20230322_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradatransformacionproductos',
            options={'ordering': ['transformacion_productos', 'item'], 'verbose_name': 'Entrada Transformación de Productos', 'verbose_name_plural': 'Entrada Transformaciones de Productos'},
        ),
        migrations.AlterModelOptions(
            name='notacontrolcalidadstockdetalle',
            options={'ordering': ['nota_control_calidad_stock', 'item'], 'verbose_name': 'Nota Control Calidad Stock Detalle', 'verbose_name_plural': 'Notas Control Calidad Stock Detalle'},
        ),
        migrations.AlterModelOptions(
            name='salidatransformacionproductos',
            options={'ordering': ['transformacion_productos', 'item'], 'verbose_name': 'Salida Transformación de Productos', 'verbose_name_plural': 'Salida Transformaciones de Productos'},
        ),
    ]
