# Generated by Django 3.2.12 on 2023-03-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0054_auto_20230328_1500'),
        ('calidad', '0055_auto_20230324_1647'),
    ]

    operations = [
    ]
