# Generated by Django 3.2.12 on 2023-04-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0056_merge_0054_auto_20230328_1500_0055_auto_20230324_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallamaterial',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
