# Generated by Django 3.2.12 on 2023-04-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0057_alter_fallamaterial_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucionmaterial',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
