# Generated by Django 3.2.12 on 2023-05-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0058_alter_solucionmaterial_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='validarseriereparacionmaterialdetalle',
            name='nueva_serie',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nueva Serie'),
        ),
    ]
