# Generated by Django 3.2.12 on 2023-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0059_validarseriereparacionmaterialdetalle_nueva_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriecalidad',
            name='estado',
            field=models.IntegerField(choices=[(1, 'DISPONIBLE'), (2, 'DUPLICADO'), (3, 'DEVOLUCIÓN')], default=1),
        ),
    ]
