# Generated by Django 3.2.12 on 2023-07-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0060_alter_seriecalidad_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialestadoserie',
            options={'ordering': ['-updated_at', '-created_at', '-id'], 'verbose_name': 'Historial Estado Serie', 'verbose_name_plural': 'Historial Estado Series'},
        ),
    ]
