# Generated by Django 3.2.12 on 2023-09-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0006_alter_almacen_estado_alta_baja'),
        ('clientes', '0041_cliente_estado_cliente'),
        ('movimiento_almacen', '0014_movimientosalmacen_transformacion'),
        ('calidad', '0061_alter_historialestadoserie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='almacen_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen'),
        ),
        migrations.AddField(
            model_name='serie',
            name='cliente_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='serie',
            name='estado_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.estadoserie'),
        ),
        migrations.AddField(
            model_name='serie',
            name='tipo_stock_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock'),
        ),
    ]
