# Generated by Django 3.2.12 on 2023-10-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0062_auto_20230915_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='almacen_temporal',
            new_name='almacen',
        ),
    ]
