# Generated by Django 3.2.12 on 2023-11-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0063_rename_almacen_temporal_serie_almacen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='tipo_stock_temporal',
            new_name='tipo_stock',
        ),
    ]
