# Generated by Django 3.2.12 on 2024-08-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0006_alter_almacen_estado_alta_baja'),
        ('calidad', '0064_rename_tipo_stock_temporal_serie_tipo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacionmaterialdetalle',
            name='almacen_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReparacionMaterialDetalle_almacen_final', to='almacenes.almacen'),
        ),
        migrations.AlterField(
            model_name='reparacionmaterialdetalle',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReparacionMaterialDetalle_almacen', to='almacenes.almacen'),
        ),
    ]
