# Generated by Django 3.2.12 on 2024-09-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0065_auto_20240808_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacionmaterial',
            name='origen',
            field=models.IntegerField(choices=[(1, 'BLOQUEO POR QA'), (2, 'BLOQUEO POR DESGUACE')], default=1),
        ),
    ]
