# Generated by Django 3.2.12 on 2023-05-18 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='apoyo',
            field=models.ManyToManyField(blank=True, related_name='Tarea_apoyo', to=settings.AUTH_USER_MODEL, verbose_name='Apoyo'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cierre'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Limite'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.IntegerField(blank=True, choices=[(1, 'ALTA'), (2, 'MEDIA'), (3, 'BAJA')], null=True, verbose_name='Prioridad'),
        ),
        migrations.CreateModel(
            name='HistorialComentarioTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='HistorialComentarioTarea_created_by', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Tarea', to='tarea.tarea')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='HistorialComentarioTarea_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Comentario Tarea',
                'verbose_name_plural': 'Historial Comentarios Tarea',
            },
        ),
    ]
