# Generated by Django 3.2.12 on 2023-05-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_auto_20230518_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelOptions(
            name='tipotarea',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Tarea', 'verbose_name_plural': 'Tipos de Tarea'},
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo_tarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarea', to='tarea.tipotarea'),
            preserve_default=False,
        ),
    ]
