# Generated by Django 3.2.12 on 2023-06-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0003_auto_20230531_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-created_at', '-prioridad'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
