# Generated by Django 3.2.12 on 2023-06-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0004_alter_tarea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
