# Generated by Django 3.2.12 on 2023-07-10 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarea', '0006_alter_tarea_apoyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='apoyo',
            field=models.ManyToManyField(blank=True, related_name='Tarea_apoyo', to=settings.AUTH_USER_MODEL, verbose_name='Apoyo'),
        ),
    ]
