# Generated by Django 3.2.12 on 2023-08-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0007_alter_tarea_apoyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ASIGNADO'), (2, 'EN PROCESO'), (3, 'FINALIZADO'), (4, 'REAPERTURADO')], default=1, verbose_name='Estado'),
        ),
    ]
