# Generated by Django 3.2.12 on 2023-08-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0008_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipotarea',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tipo de Tarea', 'verbose_name_plural': 'Tipos de Tarea'},
        ),
    ]
