# Generated by Django 3.2.12 on 2023-10-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0009_alter_tipotarea_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_culminación',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Culminación'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Real'),
        ),
    ]
