# Generated by Django 3.2.12 on 2023-10-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0010_auto_20231002_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_culminación',
            new_name='fecha_culminacion',
        ),
    ]
