# Generated by Django 3.2.12 on 2023-10-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0011_rename_fecha_culminación_tarea_fecha_culminacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_culminacion',
        ),
    ]
