# Generated by Django 3.2.12 on 2023-10-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0012_remove_tarea_fecha_culminacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-created_at'], 'permissions': [('ver_tareas', 'Puede ver las tareas de todos los usuarios')], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
