# Generated by Django 3.2.12 on 2023-02-09 15:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0029_alter_interlocutorcliente_tipo_documento'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('calidad', '0030_auto_20230109_1149'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoReclamoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_ingreso_garantia', models.IntegerField(blank=True, help_text='Correlativo', null=True, verbose_name='Número de Ingreso Reclamo Garantia')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IngresoReclamoGarantia_cliente', to='clientes.cliente')),
                ('cliente_interlocutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IngresoReclamoGarantia_interlocutor', to='clientes.interlocutorcliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IngresoReclamoGarantia_created_by', to=settings.AUTH_USER_MODEL)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IngresoReclamoGarantia_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso Reclamo Garantia',
                'verbose_name_plural': 'Ingresos Reclamo Garantia',
            },
        ),
        migrations.CreateModel(
            name='SalidaReclamoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalidaReclamoGarantia_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalidaReclamoGarantia_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida Reclamo Garantia',
                'verbose_name_plural': 'Salida Reclamos Garantia',
            },
        ),
        migrations.CreateModel(
            name='IngresoReclamoGarantiaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad')),
                ('precio_venta', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio Venta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IngresoReclamoGarantiaDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('ingreso_garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IngresoReclamoGarantiaDetalle_ingreso_garantia', to='garantia.ingresoreclamogarantia')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='IngresoReclamoGarantiaDetalle_serie', to='calidad.serie')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IngresoReclamoGarantiaDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso Reclamo Garantia Detalle',
                'verbose_name_plural': 'Ingresos Reclamo Garantia Detalle',
            },
        ),
        migrations.CreateModel(
            name='ControlCalidadReclamoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ControlCalidadReclamoGarantia_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ControlCalidadReclamoGarantia_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control Calidad Reclamo Garantia',
                'verbose_name_plural': 'Control Calidad Reclamos Garantia',
            },
        ),
    ]
