# Generated by Django 3.2.12 on 2023-02-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresoreclamogarantia',
            old_name='observaciones',
            new_name='observacion',
        ),
    ]
