# Generated by Django 3.2.12 on 2023-02-14 22:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0030_auto_20230109_1149'),
        ('garantia', '0002_rename_observaciones_ingresoreclamogarantia_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoreclamogarantiadetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=22, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ingresoreclamogarantiadetalle',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=22, null=True, verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='ingresoreclamogarantiadetalle',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IngresoReclamoGarantiaDetalle_serie', to='calidad.serie'),
        ),
    ]
