# Generated by Django 3.2.12 on 2023-02-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0003_auto_20230214_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoreclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
    ]
