# Generated by Django 3.2.12 on 2023-02-21 17:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('calidad', '0030_auto_20230109_1149'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0029_alter_interlocutorcliente_tipo_documento'),
        ('garantia', '0004_ingresoreclamogarantia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidadreclamogarantia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ControlCalidadReclamoGarantia_cliente', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantia',
            name='cliente_interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ControlCalidadReclamoGarantia_interlocutor', to='clientes.interlocutorcliente'),
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantia',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantia',
            name='fecha_control',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Control'),
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantia',
            name='ingreso_garantia',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ControlCalidadReclamoGarantia_ingreso_garantia', to='garantia.ingresoreclamogarantia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantia',
            name='nro_calidad_garantia',
            field=models.IntegerField(blank=True, help_text='Correlativo', null=True, verbose_name='Número de Control Reclamo Garantia'),
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantia',
            name='observacion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantia',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad'),
        ),
        migrations.AddField(
            model_name='salidareclamogarantia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalidaReclamoGarantia_cliente', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='salidareclamogarantia',
            name='cliente_interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalidaReclamoGarantia_interlocutor', to='clientes.interlocutorcliente'),
        ),
        migrations.AddField(
            model_name='salidareclamogarantia',
            name='control_garantia',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='SalidaReclamoGarantia_ingreso_garantia', to='garantia.controlcalidadreclamogarantia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salidareclamogarantia',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidareclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='salidareclamogarantia',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Salida'),
        ),
        migrations.AddField(
            model_name='salidareclamogarantia',
            name='nro_salida_garantia',
            field=models.IntegerField(blank=True, help_text='Correlativo', null=True, verbose_name='Número de Salida Reclamo Garantia'),
        ),
        migrations.AddField(
            model_name='salidareclamogarantia',
            name='observacion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='salidareclamogarantia',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad'),
        ),
        migrations.CreateModel(
            name='SalidaReclamoGarantiaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=22, null=True, verbose_name='Cantidad')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=22, null=True, verbose_name='Precio Venta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalidaReclamoGarantiaDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('salida_garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SalidaReclamoGarantiaDetalle_calidad_garantia', to='garantia.salidareclamogarantia')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalidaReclamoGarantiaDetalle_serie', to='calidad.serie')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalidaReclamoGarantiaDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida Reclamo Garantia Detalle',
                'verbose_name_plural': 'Salida Reclamo Garantia Detalles',
            },
        ),
        migrations.CreateModel(
            name='ControlCalidadReclamoGarantiaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=22, null=True, verbose_name='Cantidad')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=22, null=True, verbose_name='Precio Venta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('calidad_garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ControlCalidadReclamoGarantiaDetalle_calidad_garantia', to='garantia.controlcalidadreclamogarantia')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ControlCalidadReclamoGarantiaDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ControlCalidadReclamoGarantiaDetalle_serie', to='calidad.serie')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ControlCalidadReclamoGarantiaDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control Calidad Reclamo Garantia Detalle',
                'verbose_name_plural': 'Control Calidad Reclamo Garantia Detalles',
            },
        ),
    ]
