# Generated by Django 3.2.12 on 2023-03-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0005_auto_20230221_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidadreclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'PENDIENTE'), (3, 'CONTROL'), (4, 'ANULADO'), (5, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ingresoreclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'PENDIENTE'), (3, 'CONTROL'), (4, 'ANULADO'), (5, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='salidareclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'PENDIENTE'), (3, 'CONTROL'), (4, 'ANULADO'), (5, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='salidareclamogarantiadetalle',
            name='salida_garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SalidaReclamoGarantiaDetalle_salida_garantia', to='garantia.salidareclamogarantia'),
        ),
    ]
