# Generated by Django 3.2.12 on 2023-03-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0006_auto_20230306_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresoreclamogarantiadetalle',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='ingresoreclamogarantiadetalle',
            name='serie',
        ),
    ]
