# Generated by Django 3.2.12 on 2023-03-07 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0038_validarseriesolicitudconsumointernodetalle'),
        ('garantia', '0007_auto_20230306_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieIngresoReclamoGarantiaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SerieIngresoReclamoGarantiaDetalle_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serie Ingreso Reclamo Garantia Detalle',
                'verbose_name_plural': 'Serie Ingreso Reclamo Garantia Detalles',
            },
        ),
        migrations.CreateModel(
            name='SerieReclamoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SerieReclamoHistorial_created_by', to=settings.AUTH_USER_MODEL)),
                ('historia_estado_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.historialestadoserie')),
                ('serie_ingreso_reclamo_garantia_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garantia.serieingresoreclamogarantiadetalle')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SerieReclamoHistorial_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serie Reclamo Historial',
                'verbose_name_plural': 'Serie Reclamo Historiales',
            },
        ),
        migrations.RenameField(
            model_name='ingresoreclamogarantia',
            old_name='nro_ingreso_garantia',
            new_name='nro_ingreso_reclamo_garantia',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantia',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantia',
            name='cliente_interlocutor',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantia',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantia',
            name='fecha_control',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantia',
            name='ingreso_garantia',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantia',
            name='nro_calidad_garantia',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantia',
            name='sociedad',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='calidad_garantia',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='id_registro',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='item',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='ingresoreclamogarantiadetalle',
            name='ingreso_garantia',
        ),
        migrations.RemoveField(
            model_name='salidareclamogarantia',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='salidareclamogarantia',
            name='cliente_interlocutor',
        ),
        migrations.RemoveField(
            model_name='salidareclamogarantia',
            name='control_garantia',
        ),
        migrations.RemoveField(
            model_name='salidareclamogarantia',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='salidareclamogarantia',
            name='nro_salida_garantia',
        ),
        migrations.RemoveField(
            model_name='salidareclamogarantia',
            name='sociedad',
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantia',
            name='ingreso_reclamo_garantia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ControlCalidadReclamoGarantia_ingreso_reclamo_garantia', to='garantia.ingresoreclamogarantia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='control_calidad_reclamo_garantia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='garantia.controlcalidadreclamogarantia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='serie_cambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie'),
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='tipo_analisis',
            field=models.IntegerField(blank=True, choices=[(1, 'SOLUCIONADO'), (2, 'CAMBIO'), (3, 'DEVOLUCIÓN')], null=True),
        ),
        migrations.AddField(
            model_name='ingresoreclamogarantiadetalle',
            name='ingreso_reclamo_garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IngresoReclamoGarantiaDetalle_ingreso_reclamo_garantia', to='garantia.ingresoreclamogarantia'),
        ),
        migrations.AddField(
            model_name='salidareclamogarantia',
            name='control_calidad_reclamo_garantia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='garantia.controlcalidadreclamogarantia'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SalidaReclamoGarantiaDetalle',
        ),
        migrations.AddField(
            model_name='serieingresoreclamogarantiadetalle',
            name='ingreso_reclamo_garantia_detalle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garantia.ingresoreclamogarantiadetalle'),
        ),
        migrations.AddField(
            model_name='serieingresoreclamogarantiadetalle',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.serie'),
        ),
        migrations.AddField(
            model_name='serieingresoreclamogarantiadetalle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SerieIngresoReclamoGarantiaDetalle_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='serie_ingreso_reclamo_garantia_detalle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='garantia.serieingresoreclamogarantiadetalle'),
            preserve_default=False,
        ),
    ]
