# Generated by Django 3.2.12 on 2023-03-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0008_auto_20230307_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serieingresoreclamogarantiadetalle',
            old_name='content_type',
            new_name='content_type_documento',
        ),
        migrations.RenameField(
            model_name='serieingresoreclamogarantiadetalle',
            old_name='id_registro',
            new_name='id_registro_documento',
        ),
        migrations.AlterField(
            model_name='serieingresoreclamogarantiadetalle',
            name='ingreso_reclamo_garantia_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SerieIngresoReclamoGarantiaDetalle_ingreso_reclamo_garantia_detalle', to='garantia.ingresoreclamogarantiadetalle'),
        ),
    ]
