# Generated by Django 3.2.12 on 2023-03-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0009_auto_20230307_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresoreclamogarantia',
            options={'ordering': ['fecha_ingreso'], 'verbose_name': 'Ingreso Reclamo Garantia', 'verbose_name_plural': 'Ingresos Reclamo Garantia'},
        ),
        migrations.AlterModelOptions(
            name='ingresoreclamogarantiadetalle',
            options={'ordering': ['ingreso_reclamo_garantia', 'item'], 'verbose_name': 'Ingreso Reclamo Garantia Detalle', 'verbose_name_plural': 'Ingresos Reclamo Garantia Detalle'},
        ),
    ]
