# Generated by Django 3.2.12 on 2023-03-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_alter_almacen_sede'),
        ('garantia', '0010_auto_20230309_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serieingresoreclamogarantiadetalle',
            options={'ordering': ['ingreso_reclamo_garantia_detalle', '-created_at'], 'verbose_name': 'Serie Ingreso Reclamo Garantia Detalle', 'verbose_name_plural': 'Serie Ingreso Reclamo Garantia Detalles'},
        ),
        migrations.AlterModelOptions(
            name='seriereclamohistorial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Serie Reclamo Historial', 'verbose_name_plural': 'Serie Reclamo Historiales'},
        ),
        migrations.AddField(
            model_name='ingresoreclamogarantia',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen'),
        ),
    ]
