# Generated by Django 3.2.12 on 2023-03-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0011_auto_20230311_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidadreclamogarantia',
            name='ingreso_reclamo_garantia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ControlCalidadReclamoGarantia_ingreso_reclamo_garantia', to='garantia.ingresoreclamogarantia'),
        ),
        migrations.AlterField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='control_calidad_reclamo_garantia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ControlCalidadReclamoGarantiaDetalle_control_calidad_reclamo_garantia', to='garantia.controlcalidadreclamogarantia'),
        ),
        migrations.AlterField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='serie_ingreso_reclamo_garantia_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ControlCalidadReclamoGarantiaDetalle_serie_ingreso_reclamo_garantia_detalle', to='garantia.serieingresoreclamogarantiadetalle'),
        ),
        migrations.AlterField(
            model_name='salidareclamogarantia',
            name='control_calidad_reclamo_garantia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SalidaReclamoGarantia_control_calidad_reclamo_garantia', to='garantia.controlcalidadreclamogarantia'),
        ),
        migrations.AlterField(
            model_name='seriereclamohistorial',
            name='serie_ingreso_reclamo_garantia_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SerieReclamoHistorial_serie_ingreso_reclamo_garantia_detalle', to='garantia.serieingresoreclamogarantiadetalle'),
        ),
    ]
