# Generated by Django 3.2.12 on 2023-03-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0051_remove_notacontrolcalidadstockdetalle_nota_ingreso_detalle'),
        ('garantia', '0012_auto_20230315_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriereclamohistorial',
            name='historia_estado_serie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SerieReclamoHistorial_historia_estado_serie', to='calidad.historialestadoserie'),
        ),
    ]
