# Generated by Django 3.2.12 on 2023-03-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0013_alter_seriereclamohistorial_historia_estado_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidadreclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'PENDIENTE'), (3, 'CONTROL'), (4, 'ANULADO'), (5, 'POR ENTREGAR'), (6, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ingresoreclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'PENDIENTE'), (3, 'CONTROL'), (4, 'ANULADO'), (5, 'POR ENTREGAR'), (6, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='salidareclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'PENDIENTE'), (3, 'CONTROL'), (4, 'ANULADO'), (5, 'POR ENTREGAR'), (6, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
    ]
