# Generated by Django 3.2.12 on 2023-03-28 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garantia', '0013_alter_seriereclamohistorial_historia_estado_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidadreclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'PENDIENTE'), (3, 'CONTROL'), (4, 'ANULADO'), (5, 'POR ENTREGAR'), (6, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ingresoreclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'PENDIENTE'), (3, 'CONTROL'), (4, 'ANULADO'), (5, 'POR ENTREGAR'), (6, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='salidareclamogarantia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'PENDIENTE'), (3, 'CONTROL'), (4, 'ANULADO'), (5, 'POR ENTREGAR'), (6, 'CONCLUIDO')], default=1, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='CondicionesGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CondicionesGarantia_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CondicionesGarantia_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Condiciones Garantia',
                'verbose_name_plural': 'Condiciones Garantias',
            },
        ),
    ]
