# Generated by Django 3.2.12 on 2023-04-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0005_alter_almacen_estado_alta_baja'),
        ('garantia', '0015_merge_0014_auto_20230324_1647_0014_auto_20230328_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen'),
        ),
    ]
