# Generated by Django 3.2.12 on 2023-08-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0016_controlcalidadreclamogarantiadetalle_almacen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicionesgarantia',
            options={'ordering': ['created_at'], 'verbose_name': 'Condiciones Garantia', 'verbose_name_plural': 'Condiciones Garantias'},
        ),
        migrations.AlterModelOptions(
            name='controlcalidadreclamogarantia',
            options={'ordering': ['-ingreso_reclamo_garantia', 'created_at'], 'verbose_name': 'Control Calidad Reclamo Garantia', 'verbose_name_plural': 'Control Calidad Reclamos Garantia'},
        ),
        migrations.AlterModelOptions(
            name='controlcalidadreclamogarantiadetalle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Control Calidad Reclamo Garantia Detalle', 'verbose_name_plural': 'Control Calidad Reclamo Garantia Detalles'},
        ),
        migrations.AlterModelOptions(
            name='ingresoreclamogarantia',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Ingreso Reclamo Garantia', 'verbose_name_plural': 'Ingresos Reclamo Garantia'},
        ),
        migrations.AlterModelOptions(
            name='ingresoreclamogarantiadetalle',
            options={'ordering': ['-ingreso_reclamo_garantia', 'item'], 'verbose_name': 'Ingreso Reclamo Garantia Detalle', 'verbose_name_plural': 'Ingresos Reclamo Garantia Detalle'},
        ),
        migrations.AlterModelOptions(
            name='salidareclamogarantia',
            options={'ordering': ['-fecha_salida'], 'verbose_name': 'Salida Reclamo Garantia', 'verbose_name_plural': 'Salida Reclamos Garantia'},
        ),
        migrations.AlterModelOptions(
            name='serieingresoreclamogarantiadetalle',
            options={'ordering': ['-ingreso_reclamo_garantia_detalle', 'created_at'], 'verbose_name': 'Serie Ingreso Reclamo Garantia Detalle', 'verbose_name_plural': 'Serie Ingreso Reclamo Garantia Detalles'},
        ),
    ]
