# Generated by Django 3.2.12 on 2023-08-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0017_auto_20230811_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlcalidadreclamogarantia',
            options={'ordering': ['estado', '-ingreso_reclamo_garantia', 'created_at'], 'verbose_name': 'Control Calidad Reclamo Garantia', 'verbose_name_plural': 'Control Calidad Reclamos Garantia'},
        ),
        migrations.AlterModelOptions(
            name='ingresoreclamogarantia',
            options={'ordering': ['estado', '-fecha_ingreso'], 'verbose_name': 'Ingreso Reclamo Garantia', 'verbose_name_plural': 'Ingresos Reclamo Garantia'},
        ),
        migrations.AlterModelOptions(
            name='salidareclamogarantia',
            options={'ordering': ['estado', '-fecha_salida'], 'verbose_name': 'Salida Reclamo Garantia', 'verbose_name_plural': 'Salida Reclamos Garantia'},
        ),
    ]
