# Generated by Django 3.2.12 on 2023-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0018_auto_20230816_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidadreclamogarantiadetalle',
            name='tipo_analisis',
            field=models.IntegerField(blank=True, choices=[(1, 'SOLUCIONADO'), (2, 'CAMBIO'), (3, 'DEVOLUCIÓN'), (4, 'CAMBIO DE PRODUCTO')], null=True),
        ),
    ]
