# Generated by Django 3.2.12 on 2022-04-19 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de Alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja'), (3, 'Historico')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='HistoricoUser_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='HistoricoUser_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HistoricoUser_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Id de Usuario')),
            ],
            options={
                'verbose_name': 'Histórico Usuario',
                'verbose_name_plural': 'Histórico Usuarios',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)')], max_length=1, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=15, verbose_name='Número de Documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(default='img/usuario/datos_usuario', upload_to='img/usuario/datos_usuario/', verbose_name='Foto de Perfil')),
                ('direccion', models.CharField(max_length=254, verbose_name='Dirección')),
                ('telefono_personal', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Teléfono Personal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DatosUsuario_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DatosUsuario_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='DatosUsuario_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos del Usuario',
                'verbose_name_plural': 'Datos de los Usuarios',
            },
        ),
        migrations.AddConstraint(
            model_name='historicouser',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 1)), fields=('usuario',), name='usuario de alta'),
        ),
    ]
