# Generated by Django 3.2.12 on 2022-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='foto',
            field=models.ImageField(default='img/usuario/datos_usuario/default-avatar.png', upload_to='img/usuario/datos_usuario/', verbose_name='Foto de Perfil'),
        ),
    ]
