# Generated by Django 3.2.12 on 2022-04-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_datosusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='recuperar_password',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Recuperar password'),
        ),
    ]
