# Generated by Django 3.2.12 on 2022-04-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_datosusuario_recuperar_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuario',
            name='recuperar_password',
        ),
    ]
