# Generated by Django 3.2.12 on 2022-05-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_datosusuario_recuperar_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='tipo_documento',
            field=models.CharField(choices=[('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD')], max_length=1, verbose_name='Tipo de Documento'),
        ),
    ]
