# Generated by Django 3.2.12 on 2024-10-03 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0008_alter_datosusuario_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_vacaciones', models.PositiveIntegerField(default=0)),
                ('estado', models.IntegerField(choices=[(1, 'REGISTRADO'), (2, 'INICIADAS'), (3, 'TERMINADAS')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Vacaciones_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Vacaciones_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.datosusuario')),
            ],
        ),
        migrations.AlterModelOptions(
            name='historicouser',
            options={'ordering': ['estado', 'usuario__username'], 'verbose_name': 'Histórico Usuario', 'verbose_name_plural': 'Histórico Usuarios'},
        ),
        migrations.CreateModel(
            name='VacacionesDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'APROBADO'), (3, 'RECHAZADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='VacacionesDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='VacacionesDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vacaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VacacionesDetalle_vacaciones', to='usuario.vacaciones')),
            ],
        ),
    ]
