# Generated by Django 3.2.12 on 2024-10-09 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0009_auto_20241003_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacaciones',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='Vacaciones_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
