# Generated by Django 3.2.12 on 2024-10-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_alter_vacaciones_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacaciones',
            options={'ordering': ['-created_at', 'estado'], 'verbose_name': 'Vacacion', 'verbose_name_plural': 'Vacaciones'},
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='dias_vacaciones',
            field=models.PositiveIntegerField(),
        ),
    ]
