# Generated by Django 3.2.12 on 2024-10-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20241024_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacaciones',
            options={'ordering': ['estado', '-created_at'], 'verbose_name': 'Vacacion', 'verbose_name_plural': 'Vacaciones'},
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='estado',
            field=models.IntegerField(choices=[(1, 'REGISTRADAS'), (2, 'INICIADAS'), (3, 'TERMINADAS')], default=1, verbose_name='Estado'),
        ),
    ]
