# Generated by Django 3.2.12 on 2024-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_auto_20241025_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacacionesdetalle',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'PENDIENTE'), (2, 'APROBADO'), (3, 'RECHAZADO')], null=True, verbose_name='Estado'),
        ),
    ]
