# Generated by Django 3.2.12 on 2025-01-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0047_alter_sociedad_color'),
        ('usuario', '0015_alter_vacacionesdetalle_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacaciones',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad'),
        ),
    ]
