# Generated by Django 3.2.12 on 2025-05-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_alter_vacacionesdetalle_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='es_jefe_ventas',
            field=models.BooleanField(default=False, verbose_name='Es Jefe de Ventas'),
        ),
        migrations.AddField(
            model_name='datosusuario',
            name='es_ventas',
            field=models.BooleanField(default=False, verbose_name='Es Ventas'),
        ),
    ]
