# Generated by Django 3.2.12 on 2025-01-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_vacaciones_sociedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacaciones',
            name='periodo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Periodo'),
        ),
    ]
