# Generated by Django 3.2.12 on 2025-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_vacaciones_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacaciones',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Boleta'),
        ),
    ]
