# Generated by Django 3.2.12 on 2022-07-27 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sociedad', '0019_alter_representantelegal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion_compra', '0005_auto_20220727_1717'),
        ('comprobante_compra', '0009_alter_comprobantecompraci_comprobante_compra_pi'),
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota_ingreso', models.CharField(blank=True, help_text='Correlativo', max_length=6, null=True, verbose_name='Número de Nota de Ingreso')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación')),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'FINALIZADO'), (3, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngreso_created_by', to=settings.AUTH_USER_MODEL)),
                ('recepcion_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepcion_compra.recepcioncompra')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngreso_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Ingreso',
                'verbose_name_plural': 'Notas de Ingreso',
            },
        ),
        migrations.CreateModel(
            name='NotaIngresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('cantidad_conteo', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad del conteo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen')),
                ('comprobante_compra_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comprobante_compra.comprobantecomprapidetalle')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoDetalle_nota_ingreso', to='nota_ingreso.notaingreso')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Ingreso Detalle',
                'verbose_name_plural': 'Notas de Ingreso Detalles',
            },
        ),
    ]
