# Generated by Django 3.2.12 on 2022-07-27 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0009_alter_comprobantecompraci_comprobante_compra_pi'),
        ('nota_ingreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaingresodetalle',
            name='comprobante_compra_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoDetalle_comprobante_compra_detalle', to='comprobante_compra.comprobantecomprapidetalle'),
        ),
    ]
