# Generated by Django 3.2.12 on 2022-08-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_ingreso', '0002_alter_notaingresodetalle_comprobante_compra_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaingresodetalle',
            name='cantidad_conteo',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad del conteo'),
        ),
        migrations.AlterField(
            model_name='notaingresodetalle',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
