# Generated by Django 3.2.12 on 2022-08-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota_ingreso', '0003_auto_20220812_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaingresodetalle',
            options={'ordering': ['item'], 'verbose_name': 'Nota de Ingreso Detalle', 'verbose_name_plural': 'Notas de Ingreso Detalles'},
        ),
    ]
