# Generated by Django 3.2.12 on 2022-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_ingreso', '0004_alter_notaingresodetalle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaingreso',
            name='nro_nota_ingreso',
            field=models.IntegerField(blank=True, help_text='Correlativo', null=True, verbose_name='Número de Nota de Ingreso'),
        ),
    ]
