# Generated by Django 3.2.12 on 2022-12-15 00:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0009_auto_20221005_1436'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('nota_ingreso', '0005_alter_notaingreso_nro_nota_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaStockInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota_stock_inicial', models.IntegerField(blank=True, help_text='Correlativo', null=True, verbose_name='Número de Nota de Stock Inicial')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación')),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'FINALIZADO'), (3, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaStockInicial_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaStockInicial_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Stock Inicial',
                'verbose_name_plural': 'Notas de Stock Inicial',
            },
        ),
        migrations.CreateModel(
            name='NotaStockInicialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField()),
                ('cantidad_total', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaStockInicialDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_stock_inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NotaStockInicialDetalle_nota_stock_inicial', to='nota_ingreso.notastockinicial')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaStockInicialDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Stock Inicial Detalle',
                'verbose_name_plural': 'Notas de Stock Inicial Detalles',
                'ordering': ['item'],
            },
        ),
    ]
