# Generated by Django 3.2.12 on 2022-12-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('proveedores', '0009_auto_20221005_1436'),
        ('nota_ingreso', '0006_notastockinicial_notastockinicialdetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaingresodetalle',
            name='comprobante_compra_detalle',
        ),
        migrations.RemoveField(
            model_name='notastockinicialdetalle',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='notaingresodetalle',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaingresodetalle',
            name='id_registro',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaingresodetalle',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
            preserve_default=False,
        ),
    ]
