# Generated by Django 3.2.12 on 2022-12-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota_ingreso', '0007_auto_20221215_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notastockinicialdetalle',
            options={'ordering': ['nota_stock_inicial', 'item'], 'verbose_name': 'Nota de Stock Inicial Detalle', 'verbose_name_plural': 'Notas de Stock Inicial Detalles'},
        ),
    ]
