# Generated by Django 3.2.12 on 2022-12-16 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0009_auto_20221005_1436'),
        ('almacenes', '0003_alter_almacen_estado_alta_baja'),
        ('nota_ingreso', '0008_alter_notastockinicialdetalle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaingresodetalle',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen'),
        ),
        migrations.AlterField(
            model_name='notaingresodetalle',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
