# Generated by Django 3.2.12 on 2022-12-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nota_ingreso', '0009_auto_20221216_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaingreso',
            name='recepcion_compra',
        ),
        migrations.AddField(
            model_name='notaingreso',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaingreso',
            name='id_registro',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
