# Generated by Django 3.2.12 on 2022-12-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota_ingreso', '0010_auto_20221217_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaingresodetalle',
            options={'ordering': ['nota_ingreso', 'item'], 'verbose_name': 'Nota de Ingreso Detalle', 'verbose_name_plural': 'Notas de Ingreso Detalles'},
        ),
    ]
