# Generated by Django 3.2.12 on 2022-05-27 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0011_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.IntegerField(choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)')], verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=15, unique=True, verbose_name='Número de Documento')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Comercial')),
                ('direccion_fiscal', models.CharField(max_length=100, verbose_name='Dirección Fiscal')),
                ('ubigeo', models.CharField(max_length=6, verbose_name='Ubigeo')),
                ('estado_sunat', models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspensión temporal'), (3, 'Baja provisional'), (4, 'Baja definitiva'), (5, 'Baja provisional de oficio'), (6, 'Baja definitiva de oficio'), (7, 'Baja interna')], default=1, verbose_name='Estado SUNAT')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cliente_created_by', to=settings.AUTH_USER_MODEL)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.distrito')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cliente_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['estado_sunat', 'razon_social'],
            },
        ),
        migrations.CreateModel(
            name='InterlocutorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.IntegerField(choices=[('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD')], verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=15, unique=True, verbose_name='Número de Documento')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InterlocutorCliente_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interlocutor Cliente',
                'verbose_name_plural': 'Interlocutores Cliente',
            },
        ),
        migrations.CreateModel(
            name='TipoInterlocutorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoInterlocutorCliente_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoInterlocutorCliente_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Interlocutor Cliente',
                'verbose_name_plural': 'Tipos de Interlocutor Cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TelefonoInterlocutorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Teléfono')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TelefonoInterlocutorCliente_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TelefonoInterlocutorCliente_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telefono Interlocutor Cliente',
                'verbose_name_plural': 'Telefonos Interlocutores Cliente',
                'ordering': ['estado', '-fecha_baja'],
            },
        ),
        migrations.CreateModel(
            name='RepresentanteLegalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_representante_legal', models.IntegerField(choices=[], default=1, verbose_name='Tipo de Representante Legal')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RepresentanteLegalCliente_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RepresentanteLegalCliente_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Representante Legal Cliente',
                'verbose_name_plural': 'Representantes Legales Cliente',
                'ordering': ['estado', '-fecha_baja'],
            },
        ),
        migrations.AddField(
            model_name='interlocutorcliente',
            name='tipo_interlocutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.tipointerlocutorcliente'),
        ),
        migrations.AddField(
            model_name='interlocutorcliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InterlocutorCliente_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CorreoInterlocutorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CorreoInterlocutorCliente_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CorreoInterlocutorCliente_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correo Interlocutor Cliente',
                'verbose_name_plural': 'Correos Interlocutores Cliente',
                'ordering': ['estado', '-fecha_baja'],
            },
        ),
        migrations.CreateModel(
            name='ClienteInterlocutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClienteInterlocutor_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente')),
                ('tipo_interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.tipointerlocutorcliente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClienteInterlocutor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente Interlocutor',
                'verbose_name_plural': 'Cliente Interlocutores',
                'ordering': ['estado', '-interlocutor'],
            },
        ),
    ]
