# Generated by Django 3.2.12 on 2022-05-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_sunat',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspensión temporal'), (3, 'Baja provisional'), (4, 'Baja definitiva'), (5, 'Baja provisional de oficio'), (6, 'Baja definitiva de oficio'), (7, 'Baja interna')], verbose_name='Estado SUNAT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)')], max_length=1, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='representantelegalcliente',
            name='tipo_representante_legal',
            field=models.IntegerField(choices=[('001', 'Administrador'), ('007', 'Contador'), ('013', 'Director Ejecutivo'), ('014', 'Director General'), ('019', 'Gerente'), ('020', 'Gerente Ejecutivo'), ('021', 'Gerente General'), ('022', 'Gestor de Empresas'), ('025', 'Jefe'), ('029', 'Presidente'), ('032', 'Presidente Directorio'), ('033', 'Presidente Ejecutivo'), ('037', 'Representante no domiciliado'), ('040', 'Secretario'), ('043', 'Sub gerente'), ('048', 'Vicepresidente'), ('051', 'Titular gerente'), ('052', 'Socio Administrador'), ('998', 'Otros persona juridica'), ('999', 'Otros persona natural')], verbose_name='Tipo de Representante Legal'),
        ),
    ]
