# Generated by Django 3.2.12 on 2022-05-30 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20220529_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interlocutorcliente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='interlocutorcliente',
            name='nombres',
        ),
        migrations.AddField(
            model_name='interlocutorcliente',
            name='nombre_completo',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Nombre Completo'),
            preserve_default=False,
        ),
    ]
