# Generated by Django 3.2.12 on 2022-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20220530_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interlocutorcliente',
            name='tipo_documento',
            field=models.CharField(choices=[('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD')], max_length=1, verbose_name='Tipo de Documento'),
        ),
    ]
