# Generated by Django 3.2.12 on 2022-05-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interlocutorcliente',
            name='tipo_interlocutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.tipointerlocutorcliente', verbose_name='Tipo de Interlocutor'),
        ),
    ]
