# Generated by Django 3.2.12 on 2022-05-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_interlocutorcliente_tipo_interlocutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representantelegalcliente',
            name='tipo_representante_legal',
            field=models.CharField(choices=[('001', 'Administrador'), ('007', 'Contador'), ('013', 'Director Ejecutivo'), ('014', 'Director General'), ('019', 'Gerente'), ('020', 'Gerente Ejecutivo'), ('021', 'Gerente General'), ('022', 'Gestor de Empresas'), ('025', 'Jefe'), ('029', 'Presidente'), ('032', 'Presidente Directorio'), ('033', 'Presidente Ejecutivo'), ('037', 'Representante no domiciliado'), ('040', 'Secretario'), ('043', 'Sub gerente'), ('048', 'Vicepresidente'), ('051', 'Titular gerente'), ('052', 'Socio Administrador'), ('998', 'Otros persona juridica'), ('999', 'Otros persona natural')], max_length=4, verbose_name='Tipo de Representante Legal'),
        ),
    ]
