# Generated by Django 3.2.12 on 2022-05-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_representantelegalcliente_tipo_representante_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteinterlocutor',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ClienteInterlocutor_cliente', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='clienteinterlocutor',
            name='interlocutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ClienteInterlocutor_interlocutor', to='clientes.interlocutorcliente'),
        ),
        migrations.AlterField(
            model_name='interlocutorcliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD')], max_length=1, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
