# Generated by Django 3.2.12 on 2022-05-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_interlocutorcliente_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interlocutorcliente',
            name='tipo_interlocutor',
        ),
    ]
