# Generated by Django 3.2.12 on 2022-05-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_remove_interlocutorcliente_tipo_interlocutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interlocutorcliente',
            options={'ordering': ['-nombre_completo'], 'verbose_name': 'Interlocutor Cliente', 'verbose_name_plural': 'Interlocutores Cliente'},
        ),
        migrations.AlterModelOptions(
            name='representantelegalcliente',
            options={'ordering': ['estado', '-fecha_baja', '-interlocutor'], 'verbose_name': 'Representante Legal Cliente', 'verbose_name_plural': 'Representantes Legales Cliente'},
        ),
    ]
