# Generated by Django 3.2.12 on 2022-06-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20220531_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Documento'),
        ),
    ]
