# Generated by Django 3.2.12 on 2022-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interlocutorcliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Número de Documento'),
        ),
    ]
