# Generated by Django 3.2.12 on 2022-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_interlocutorcliente_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condicion_sunat',
            field=models.IntegerField(choices=[(1, 'Habido'), (2, 'No hallado'), (3, 'No habido')], default=1, verbose_name='Condición SUNAT'),
        ),
    ]
