# Generated by Django 3.2.12 on 2022-06-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_correocliente'),
        ('clientes', '0014_cliente_condicion_sunat'),
    ]

    operations = [
    ]
