# Generated by Django 3.2.12 on 2022-06-15 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_merge_0012_correocliente_0014_cliente_condicion_sunat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correocliente',
            options={'ordering': ['estado', '-fecha_baja', 'correo'], 'verbose_name': 'Correo Cliente', 'verbose_name_plural': 'Correos Cliente'},
        ),
    ]
