# Generated by Django 3.2.12 on 2022-08-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_alter_correocliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representantelegalcliente',
            name='tipo_representante_legal',
            field=models.CharField(choices=[('001', 'Administrador'), ('002', 'Administrador Judicial'), ('003', 'Albacea'), ('004', 'Alcalde'), ('005', 'Apoderado'), ('007', 'Contador'), ('008', 'Coordinador'), ('009', 'Curador'), ('010', 'Decano'), ('011', 'Director'), ('012', 'Director (centro de estudios)'), ('013', 'Director Ejecutivo'), ('014', 'Director General'), ('015', 'Director Municipal'), ('016', 'Embajador'), ('017', 'Factor'), ('019', 'Gerente'), ('020', 'Gerente Ejecutivo'), ('021', 'Gerente General'), ('022', 'Gestor de Empresas'), ('023', 'Heredero'), ('024', 'Intendente'), ('025', 'Jefe'), ('026', 'Liquidador'), ('027', 'Mandatario'), ('028', 'Ministro'), ('029', 'Presidente'), ('030', 'Presidente Consejo de Vigilancia'), ('031', 'Presidente Consejo Administración'), ('032', 'Presidente Directorio'), ('033', 'Presidente Ejecutivo'), ('034', 'Procurador'), ('035', 'Promotor'), ('036', 'Regidor'), ('037', 'Representante no domiciliado'), ('038', 'Representante religioso'), ('039', 'Representante de universidades'), ('040', 'Secretario'), ('041', 'Síndico'), ('042', 'Sub director'), ('043', 'Sub gerente'), ('044', 'Superintendente'), ('045', 'Teniente alcalde'), ('046', 'Tesorero'), ('047', 'Tutor'), ('048', 'Vicepresidente'), ('049', 'Vice decano'), ('050', 'Vocal'), ('051', 'Titular gerente'), ('052', 'Socio Administrador'), ('998', 'Otros persona jurídica'), ('999', 'Otros persona natural')], max_length=4, verbose_name='Tipo de Representante Legal'),
        ),
    ]
