# Generated by Django 3.2.12 on 2022-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteinterlocutor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='correocliente',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='correointerlocutorcliente',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='representantelegalcliente',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='telefonointerlocutorcliente',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
    ]
