# Generated by Django 3.2.12 on 2022-10-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_auto_20221005_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CorreoCliente_cliente', to='clientes.cliente'),
        ),
    ]
