# Generated by Django 3.2.12 on 2022-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_remove_clienteanexo_ubigeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_id_erp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
