# Generated by Django 3.2.12 on 2022-11-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_cliente_cliente_id_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipointerlocutorcliente',
            name='tipo_interlocutor_id_erp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
