# Generated by Django 3.2.12 on 2022-11-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_tipointerlocutorcliente_tipo_interlocutor_id_erp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_id_erp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tipointerlocutorcliente',
            name='tipo_interlocutor_id_erp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
