# Generated by Django 3.2.12 on 2023-01-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_auto_20221123_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ubigeo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Ubigeo'),
        ),
    ]
