# Generated by Django 3.2.12 on 2023-01-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_alter_cliente_ubigeo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteinterlocutor',
            options={'ordering': ['estado', 'interlocutor'], 'verbose_name': 'Cliente Interlocutor', 'verbose_name_plural': 'Cliente Interlocutores'},
        ),
        migrations.AlterModelOptions(
            name='interlocutorcliente',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'Interlocutor Cliente', 'verbose_name_plural': 'Interlocutores Cliente'},
        ),
        migrations.AlterField(
            model_name='correointerlocutorcliente',
            name='interlocutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CorreoInterlocutorCliente_interlocutor', to='clientes.interlocutorcliente'),
        ),
        migrations.AlterField(
            model_name='telefonointerlocutorcliente',
            name='interlocutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TelefonoInterlocutorCliente_interlocutor', to='clientes.interlocutorcliente'),
        ),
    ]
