# Generated by Django 3.2.12 on 2023-01-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_auto_20230110_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interlocutorcliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Documento'),
        ),
    ]
