# Generated by Django 3.2.12 on 2023-04-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0030_auto_20230401_1229'),
        ('clientes', '0030_auto_20230401_1233'),
    ]

    operations = [
    ]
