# Generated by Django 3.2.12 on 2023-05-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
        ('clientes', '0032_auto_20230411_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.pais'),
        ),
    ]
