# Generated by Django 3.2.12 on 2023-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0033_cliente_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interlocutorcliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('-', 'SIN DOCUMENTO')], max_length=1, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
