# Generated by Django 3.2.12 on 2023-07-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0035_alter_cliente_estado_sunat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('B', 'DOC.IDENT.PAIS.RESIDENCIA-NO.D'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)'), ('G', 'Salvoconducto')], max_length=1, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='interlocutorcliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('B', 'DOC.IDENT.PAIS.RESIDENCIA-NO.D'), ('-', 'SIN DOCUMENTO')], max_length=1, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
