# Generated by Django 3.2.12 on 2023-08-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0036_auto_20230704_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_crm',
            field=models.IntegerField(choices=[(1, 'NUEVO'), (2, 'POTENCIAL'), (3, 'INTERESADO'), (4, 'FINAL'), (5, 'ESTRELLA'), (6, 'DEUDOR')], default=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='medio',
            field=models.IntegerField(blank=True, choices=[(1, 'FACEBOOK'), (2, 'INSTAGRAM'), (3, 'LLAMADA'), (4, 'WEBINAR'), (5, 'EVENTO ISP')], null=True, verbose_name='Medio'),
        ),
    ]
