# Generated by Django 3.2.12 on 2023-08-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0037_auto_20230810_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_crm',
            field=models.IntegerField(blank=True, choices=[(1, 'NUEVO'), (2, 'POTENCIAL'), (3, 'INTERESADO'), (4, 'FINAL'), (5, 'ESTRELLA'), (6, 'DEUDOR')], default=1, null=True, verbose_name='Estado'),
        ),
    ]
