# Generated by Django 3.2.12 on 2023-08-15 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0038_alter_cliente_estado_crm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado_crm',
        ),
        migrations.CreateModel(
            name='HistorialEstadoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_cliente', models.IntegerField(blank=True, choices=[(1, 'NUEVO'), (2, 'POTENCIAL'), (3, 'INTERESADO'), (4, 'FINAL'), (5, 'ESTRELLA'), (6, 'DEUDOR')], default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistorialEstadoCliente_cliente', to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='HistorialEstadoCliente_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='HistorialEstadoCliente_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Estado Cliente',
                'verbose_name_plural': 'Historial Estado Clientes',
                'ordering': ['-updated_at', '-created_at', '-id'],
            },
        ),
    ]
