# Generated by Django 3.2.12 on 2023-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0039_auto_20230815_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_sunat',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspension temporal'), (3, 'Baja provisional'), (4, 'Baja definitiva'), (5, 'Baja provisional de oficio'), (6, 'Baja definitiva de oficio'), (7, 'Baja interna')], default=1, verbose_name='Estado SUNAT'),
        ),
    ]
