# Generated by Django 3.2.12 on 2023-09-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0040_alter_cliente_estado_sunat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[(1, 'NUEVO'), (2, 'POTENCIAL'), (3, 'INTERESADO'), (4, 'FINAL'), (5, 'ESTRELLA'), (6, 'DEUDOR')], default=1, null=True, verbose_name='Estado'),
        ),
    ]
