# Generated by Django 3.2.12 on 2023-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0041_cliente_estado_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='medio',
            field=models.IntegerField(blank=True, choices=[(1, 'FACEBOOK'), (2, 'INSTAGRAM'), (5, 'TIKTOK'), (6, 'YOUTUBE'), (7, 'WHATSAPP'), (3, 'LLAMADA'), (4, 'EVENTOS'), (8, 'PÁGINA WEB'), (9, 'POR RECOMENDACIÓN'), (10, 'PENDIENTE')], null=True, verbose_name='Medio'),
        ),
    ]
