# Generated by Django 3.2.12 on 2023-09-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0041_cliente_estado_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='medio',
            field=models.IntegerField(blank=True, choices=[(1, 'FACEBOOK'), (2, 'INSTAGRAM'), (3, 'LLAMADA'), (4, 'WEBINAR'), (5, 'EVENTO ISP'), (6, 'PAGINA WEB')], null=True, verbose_name='Medio'),
        ),
    ]
