# Generated by Django 3.2.12 on 2023-10-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0042_alter_cliente_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[(1, 'NUEVO'), (2, 'POTENCIAL'), (3, 'INTERESADO'), (4, 'FINAL'), (5, 'ESTRELLA'), (6, 'DEUDOR'), (7, 'DEUDOR ESTRELLA')], default=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historialestadocliente',
            name='estado_cliente',
            field=models.IntegerField(blank=True, choices=[(1, 'NUEVO'), (2, 'POTENCIAL'), (3, 'INTERESADO'), (4, 'FINAL'), (5, 'ESTRELLA'), (6, 'DEUDOR'), (7, 'DEUDOR ESTRELLA')], default=1, null=True),
        ),
    ]
