# Generated by Django 3.2.12 on 2023-01-19 19:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0024_alter_representantelegal_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaIngresoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota_stock_inicial', models.IntegerField(blank=True, help_text='Correlativo', null=True, verbose_name='Número de Nota de Ingreso de Muestra')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación')),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'FINALIZADO'), (3, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMuestra_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMuestra_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Ingreso de Muestra',
                'verbose_name_plural': 'Notas de Ingreso de Muestra',
            },
        ),
        migrations.CreateModel(
            name='NotaIngresoMuestraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField()),
                ('cantidad_total', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMuestraDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_stock_inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMuestraDetalle_nota_stock_inicial', to='muestra.notaingresomuestra')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMuestraDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Ingreso de Muestra Detalle',
                'verbose_name_plural': 'Notas de Ingreso de Muestra Detalles',
                'ordering': ['nota_stock_inicial', 'item'],
            },
        ),
    ]
