# Generated by Django 3.2.12 on 2023-01-19 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaingresomuestradetalle',
            options={'ordering': ['nota_ingreso_muestra', 'item'], 'verbose_name': 'Nota de Ingreso de Muestra Detalle', 'verbose_name_plural': 'Notas de Ingreso de Muestra Detalles'},
        ),
        migrations.RenameField(
            model_name='notaingresomuestra',
            old_name='nro_nota_stock_inicial',
            new_name='nro_nota_ingreso_muestra',
        ),
        migrations.RemoveField(
            model_name='notaingresomuestradetalle',
            name='nota_stock_inicial',
        ),
        migrations.AddField(
            model_name='notaingresomuestradetalle',
            name='nota_ingreso_muestra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='NotaIngresoMuestraDetalle_nota_ingreso_muestra', to='muestra.notaingresomuestra'),
            preserve_default=False,
        ),
    ]
