# Generated by Django 3.2.12 on 2023-01-21 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('calidad', '0030_auto_20230109_1149'),
        ('muestra', '0002_auto_20230119_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieValidar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=200, verbose_name='Nro. Serie')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('estado', models.IntegerField(choices=[(1, 'DISPONIBLE'), (2, 'DUPLICADO')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SerieValidar_created_by', to=settings.AUTH_USER_MODEL)),
                ('falla_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.fallamaterial')),
                ('nota_ingreso_muestra_validar_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SerieValidar_nota_ingreso_muestra_validar_detalle', to='muestra.notaingresomuestradetalle')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SerieValidar_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serie Validar',
                'verbose_name_plural': 'Series Validar',
                'ordering': ['created_at'],
            },
        ),
    ]
