# Generated by Django 3.2.12 on 2023-01-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_auto_20230116_1858'),
        ('muestra', '0003_serievalidar'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaingresomuestra',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
            preserve_default=False,
        ),
    ]
