# Generated by Django 3.2.12 on 2023-01-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0004_notaingresomuestra_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serievalidar',
            name='nota_ingreso_muestra_validar_detalle',
        ),
        migrations.AddField(
            model_name='serievalidar',
            name='nota_ingreso_muestra_detalle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SerieValidar_nota_ingreso_muestra_detalle', to='muestra.notaingresomuestradetalle'),
            preserve_default=False,
        ),
    ]
