# Generated by Django 3.2.12 on 2023-01-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_alter_almacen_sede'),
        ('muestra', '0005_auto_20230123_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaingresomuestradetalle',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen'),
            preserve_default=False,
        ),
    ]
