# Generated by Django 3.2.12 on 2023-01-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0006_notaingresomuestradetalle_almacen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serievalidar',
            name='falla_material',
        ),
        migrations.RemoveField(
            model_name='serievalidar',
            name='observacion',
        ),
    ]
