# Generated by Django 3.2.12 on 2023-01-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0007_auto_20230123_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaingresomuestradetalle',
            name='almacen',
        ),
        migrations.DeleteModel(
            name='SerieValidar',
        ),
    ]
