# Generated by Django 3.2.12 on 2023-01-25 18:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('clientes', '0029_alter_interlocutorcliente_tipo_documento'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muestra', '0008_auto_20230123_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devolucion', models.IntegerField(blank=True, null=True, verbose_name='Número Devolución')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha Devolución')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo Anulación')),
                ('estado', models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'FINALIZADO SIN CONFIRMAR'), (3, 'CONFIRMADO'), (4, 'ANULADO'), (5, 'CONCLUIDO')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionMuestra_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionMuestra_interlocutor_cliente', to='clientes.interlocutorcliente')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionMuestra_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Devolución Materiales',
                'verbose_name_plural': 'Solicitudes Devolución Materiales',
                'ordering': ['numero_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionMuestraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('cantidad_devolucion', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad Devolución')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionMuestraDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('solicitud_devolucion_materiales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DevolucionMuestraDetalle_solicitud_devolucion_materiales', to='muestra.devolucionmuestra')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionMuestraDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Devolución Materiales Detalle',
                'verbose_name_plural': 'Solicitudes Devolución Materiales Detalle',
                'ordering': ['item'],
            },
        ),
    ]
