# Generated by Django 3.2.12 on 2023-01-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_auto_20230116_1858'),
        ('muestra', '0009_devolucionmuestra_devolucionmuestradetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucionmuestra',
            options={'ordering': ['numero_devolucion'], 'verbose_name': 'Devolución Muestras', 'verbose_name_plural': 'Devolución Muestras'},
        ),
        migrations.AlterModelOptions(
            name='devolucionmuestradetalle',
            options={'ordering': ['item'], 'verbose_name': 'Devolución Muestras Detalle', 'verbose_name_plural': 'Devolución Muestras Detalle'},
        ),
        migrations.RenameField(
            model_name='devolucionmuestra',
            old_name='comentario',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='devolucionmuestra',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='devolucionmuestra',
            name='interlocutor_cliente',
        ),
        migrations.AddField(
            model_name='devolucionmuestra',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
            preserve_default=False,
        ),
    ]
