# Generated by Django 3.2.12 on 2023-02-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_alter_almacen_sede'),
        ('sede', '0006_alter_sede_sociedad'),
        ('muestra', '0010_auto_20230128_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucionmuestradetalle',
            name='solicitud_devolucion_materiales',
        ),
        migrations.AddField(
            model_name='devolucionmuestra',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sede.sede'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devolucionmuestradetalle',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devolucionmuestradetalle',
            name='devolucion_muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DevolucionMuestraDetalle_devolucion_muestra', to='muestra.devolucionmuestra'),
        ),
        migrations.AlterField(
            model_name='devolucionmuestra',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'FINALIZADO'), (3, 'ANULADO')], default=1),
        ),
    ]
