# Generated by Django 3.2.12 on 2023-02-02 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0030_auto_20230109_1149'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muestra', '0011_auto_20230202_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidarSerieDevolucionMuestraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieDevolucionMuestraDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('devolucion_muestra_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieDevolucionMuestraDetalle_devolucion_muestra_detalle', to='muestra.devolucionmuestradetalle')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieDevolucionMuestraDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validar Series Devolución Muestra Detalle',
                'verbose_name_plural': 'Validar Series Devolución Muestra Detalle',
                'ordering': ['created_at'],
            },
        ),
    ]
