# Generated by Django 3.2.12 on 2023-03-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0012_validarseriedevolucionmuestradetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucionmuestradetalle',
            options={'ordering': ['devolucion_muestra', 'item'], 'verbose_name': 'Devolución Muestras Detalle', 'verbose_name_plural': 'Devolución Muestras Detalle'},
        ),
    ]
