# Generated by Django 3.2.12 on 2022-05-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0002_auto_20220509_1643'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rangodocumentofisico',
            constraint=models.UniqueConstraint(fields=('modelo', 'serie'), name='RangoDocumentoFisico_modelo_serie'),
        ),
        migrations.AddConstraint(
            model_name='rangodocumentoproceso',
            constraint=models.UniqueConstraint(fields=('modelo', 'serie'), name='RangoDocumentoProceso_modelo_serie'),
        ),
    ]
