# Generated by Django 3.2.12 on 2022-04-25 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0003_area_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.area'),
        ),
    ]
