# Generated by Django 3.2.12 on 2022-05-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0003_auto_20220510_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiasunat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='familiasunat',
            name='segmento',
        ),
        migrations.RemoveField(
            model_name='familiasunat',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='productosunat',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='productosunat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productosunat',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='segmentosunat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='segmentosunat',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ClaseSunat',
        ),
        migrations.DeleteModel(
            name='FamiliaSunat',
        ),
        migrations.DeleteModel(
            name='ProductoSunat',
        ),
        migrations.DeleteModel(
            name='SegmentoSunat',
        ),
    ]
