# Generated by Django 3.2.12 on 2022-04-25 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0004_alter_cargo_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.area'),
        ),
        migrations.CreateModel(
            name='TipoInterlocutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoInterlocutor_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoInterlocutor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Interlocutor',
                'verbose_name_plural': 'Tipos de Interlocutor',
                'ordering': ['nombre'],
            },
        ),
    ]
