# Generated by Django 3.2.12 on 2022-05-10 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0004_auto_20220510_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseSunat',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClaseSunat_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase Sunat',
                'verbose_name_plural': 'Clases Sunat',
            },
        ),
        migrations.CreateModel(
            name='SegmentoSunat',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SegmentoSunat_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SegmentoSunat_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Segmento Sunat',
                'verbose_name_plural': 'Segmentos Sunat',
            },
        ),
        migrations.CreateModel(
            name='ProductoSunat',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_globales.clasesunat')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProductoSunat_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProductoSunat_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto Sunat',
                'verbose_name_plural': 'Productos Sunat',
            },
        ),
        migrations.CreateModel(
            name='FamiliaSunat',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FamiliaSunat_created_by', to=settings.AUTH_USER_MODEL)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_globales.segmentosunat')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FamiliaSunat_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Familia Sunat',
                'verbose_name_plural': 'Familias Sunat',
            },
        ),
        migrations.AddField(
            model_name='clasesunat',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_globales.familiasunat'),
        ),
        migrations.AddField(
            model_name='clasesunat',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClaseSunat_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
