# Generated by Django 3.2.12 on 2022-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0005_auto_20220510_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasesunat',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='familiasunat',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productosunat',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='segmentosunat',
            name='descripcion',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descripción'),
        ),
    ]
