# Generated by Django 3.2.12 on 2022-05-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0006_auto_20220510_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasesunat',
            options={'ordering': ['codigo'], 'verbose_name': 'Clase Sunat', 'verbose_name_plural': 'Clases Sunat'},
        ),
        migrations.AlterModelOptions(
            name='familiasunat',
            options={'ordering': ['codigo'], 'verbose_name': 'Familia Sunat', 'verbose_name_plural': 'Familias Sunat'},
        ),
        migrations.AlterModelOptions(
            name='productosunat',
            options={'ordering': ['codigo'], 'verbose_name': 'Producto Sunat', 'verbose_name_plural': 'Productos Sunat'},
        ),
        migrations.AlterModelOptions(
            name='segmentosunat',
            options={'ordering': ['codigo'], 'verbose_name': 'Segmento Sunat', 'verbose_name_plural': 'Segmentos Sunat'},
        ),
        migrations.AlterField(
            model_name='clasesunat',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='familiasunat',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productosunat',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='segmentosunat',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True, verbose_name='Descripción'),
        ),
    ]
