# Generated by Django 3.2.12 on 2022-05-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0007_auto_20220510_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
