# Generated by Django 3.2.12 on 2022-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0008_auto_20220426_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoproceso',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
    ]
