# Generated by Django 3.2.12 on 2022-05-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0008_auto_20220510_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ['provincia__nombre', 'nombre'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['departamento__nombre', 'nombre'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
    ]
