# Generated by Django 3.2.12 on 2022-05-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0009_auto_20220511_0944'),
        ('datos_globales', '0009_auto_20220511_1425'),
    ]

    operations = [
    ]
