# Generated by Django 3.2.12 on 2022-06-01 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0011_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadImpositivaTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='UnidadImpositivaTributaria_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='UnidadImpositivaTributaria_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad Impositiva Tributaria',
                'verbose_name_plural': 'Unidad Impositiva Tributaria',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RemuneracionMinimaVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RemuneracionMinimaVital_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RemuneracionMinimaVital_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remuneración Mínima Vital',
                'verbose_name_plural': 'Remuneración Mínima Vital',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
