# Generated by Django 3.2.12 on 2022-04-26 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0004_auto_20220422_1537'),
        ('datos_globales', '0011_rangodocumentofisico_rangodocumentoproceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancariaSociedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=10, verbose_name='Número de Cuenta')),
                ('numero_cuenta_interbancaria', models.CharField(max_length=10, verbose_name='Número de Cuenta Interbancaria')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_globales.banco')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CuentaBancariaSociedad_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_globales.moneda')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CuentaBancariaSociedad_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria Sociedad',
                'verbose_name_plural': 'Cuentas Bancarias Sociedad',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancariaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=10, verbose_name='Número de Cuenta')),
                ('numero_cuenta_interbancaria', models.CharField(max_length=10, verbose_name='Número de Cuenta Interbancaria')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_globales.banco')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CuentaBancariaPersonal_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_globales.moneda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CuentaBancariaPersonal_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria Personal',
                'verbose_name_plural': 'Cuentas Bancarias Personal',
            },
        ),
    ]
