# Generated by Django 3.2.12 on 2022-06-01 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0012_remuneracionminimavital_unidadimpositivatributaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('tipo_cambio_venta', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Tipo de Cambio Venta')),
                ('tipo_cambio_compra', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Tipo de Cambio Compra')),
                ('tipo_cambio_venta_sunat', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Tipo de Cambio Venta Sunat')),
                ('tipo_cambio_compra_sunat', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Tipo de Cambio Compra Sunat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TipoCambio_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TipoCambio_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ImpuestoGeneralVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ImpuestoGeneralVentas_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ImpuestoGeneralVentas_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impuesto General a las Ventas',
                'verbose_name_plural': 'Impuesto General a las Ventas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
