# Generated by Django 3.2.12 on 2022-04-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0013_auto_20220426_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnitud',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
