# Generated by Django 3.2.12 on 2022-06-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0014_auto_20220601_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocambio',
            name='tipo_cambio_compra_sunat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Tipo de Cambio Compra Sunat'),
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='tipo_cambio_venta_sunat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Tipo de Cambio Venta Sunat'),
        ),
    ]
