# Generated by Django 3.2.12 on 2022-04-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0014_alter_magnitud_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
