# Generated by Django 3.2.12 on 2022-09-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0015_auto_20220601_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocambio',
            options={'ordering': ['-fecha', '-updated_at'], 'verbose_name': 'Tipo de Cambio', 'verbose_name_plural': 'Tipos de Cambio'},
        ),
    ]
