# Generated by Django 3.2.12 on 2022-04-28 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0015_alter_unidad_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='nombre',
        ),
        migrations.AddField(
            model_name='banco',
            name='nombre_comercial',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='Nombre Comercial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco',
            name='razon_social',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='Razón Social'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
