# Generated by Django 3.2.12 on 2022-04-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0016_auto_20220428_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='abreviatura',
            field=models.CharField(max_length=5, unique=True, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
