# Generated by Django 3.2.12 on 2022-04-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0017_auto_20220428_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cuentabancariapersonal',
            name='numero_cuenta',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuentabancariapersonal',
            name='numero_cuenta_interbancaria',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Cuenta Interbancaria'),
        ),
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='numero_cuenta',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='numero_cuenta_interbancaria',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Cuenta Interbancaria'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documentofisico',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documentoproceso',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='segmentosunat',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='segmentosunat',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipointerlocutor',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
