# Generated by Django 3.2.12 on 2022-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0017_impuestopromocionmunicipal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impuestopromocionmunicipal',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Impuesto de Promoción Municipal', 'verbose_name_plural': 'Impuesto de Promoción Municipal'},
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='tipo_cambio_compra',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Tipo de Cambio Compra'),
        ),
    ]
