# Generated by Django 3.2.12 on 2022-04-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0018_auto_20220428_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='numero_cuenta',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Número de Cuenta'),
        ),
    ]
