# Generated by Django 3.2.12 on 2022-09-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0019_seriescomprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='moneda_pais',
            field=models.BooleanField(default=False, verbose_name='Moneda del país'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moneda',
            name='secundario',
            field=models.BooleanField(default=False),
        ),
    ]
