# Generated by Django 3.2.12 on 2022-05-06 15:57

import applications.funciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0020_alter_cuentabancariasociedad_numero_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancariapersonal',
            name='numero_cuenta',
            field=models.CharField(max_length=20, unique=True, validators=[applications.funciones.validar_numero], verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuentabancariapersonal',
            name='numero_cuenta_interbancaria',
            field=models.CharField(max_length=20, unique=True, validators=[applications.funciones.validar_numero], verbose_name='Número de Cuenta Interbancaria'),
        ),
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='numero_cuenta',
            field=models.CharField(max_length=20, unique=True, validators=[applications.funciones.validar_numero], verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='numero_cuenta_interbancaria',
            field=models.CharField(max_length=20, unique=True, validators=[applications.funciones.validar_numero], verbose_name='Número de Cuenta Interbancaria'),
        ),
    ]
