# Generated by Django 3.2.12 on 2022-09-16 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0020_auto_20220916_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocambio',
            name='tipo_cambio_compra_sunat',
        ),
        migrations.RemoveField(
            model_name='tipocambio',
            name='tipo_cambio_venta_sunat',
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='moneda_destino',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='TipoCambio_moneda_destino', to='datos_globales.moneda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='moneda_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TipoCambio_moneda_origen', to='datos_globales.moneda'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TipoCambioSunat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_cambio_venta', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Tipo de Cambio Venta')),
                ('tipo_cambio_compra', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Tipo de Cambio Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TipoCambioSunat_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TipoCambioSunat_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Cambio Sunat',
                'verbose_name_plural': 'Tipos de Cambio Sunat',
                'ordering': ['-fecha', '-updated_at'],
            },
        ),
    ]
