# Generated by Django 3.2.12 on 2022-09-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0021_auto_20220916_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriescomprobante',
            name='serie',
            field=models.CharField(max_length=4, verbose_name='Serie'),
        ),
    ]
