# Generated by Django 3.2.12 on 2022-05-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0021_auto_20220506_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='id',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='Código'),
        ),
    ]
