# Generated by Django 3.2.12 on 2022-09-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0022_alter_seriescomprobante_serie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentabancariasociedad',
            options={'ordering': ['sociedad', 'banco', 'moneda'], 'verbose_name': 'Cuenta Bancaria Sociedad', 'verbose_name_plural': 'Cuentas Bancarias Sociedad'},
        ),
    ]
