# Generated by Django 3.2.12 on 2022-05-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0022_auto_20220507_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='id',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='id',
        ),
        migrations.AlterField(
            model_name='distrito',
            name='codigo',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
