# Generated by Django 3.2.12 on 2022-10-03 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sociedad', '0022_sociedad_pie_pagina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0023_alter_cuentabancariasociedad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NubefactRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField()),
                ('aceptado', models.BooleanField(default=False)),
                ('envio', models.FileField(upload_to='nubefact/envio/')),
                ('respuesta', models.FileField(upload_to='nubefact/respuesta/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NubefactRespuesta_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NubefactRespuesta_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nubefact Respuesta',
                'verbose_name_plural': 'Nubefact Respuestas',
            },
        ),
        migrations.CreateModel(
            name='NubefactAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.URLField()),
                ('token', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NubefactAcceso_created_by', to=settings.AUTH_USER_MODEL)),
                ('serie_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.seriescomprobante')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NubefactAcceso_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nubefact Acceso',
                'verbose_name_plural': 'Nubefact Accesos',
            },
        ),
    ]
