# Generated by Django 3.2.12 on 2022-10-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0025_auto_20221004_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nubefactacceso',
            name='serie_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NubefactSerie_serie_comprobante', to='datos_globales.seriescomprobante'),
        ),
    ]
