# Generated by Django 3.2.12 on 2022-10-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0026_alter_nubefactacceso_serie_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuentabancariapersonal',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
    ]
