# Generated by Django 3.2.12 on 2022-10-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0027_auto_20221005_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nubefactrespuesta',
            name='envio',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='nubefactrespuesta',
            name='respuesta',
            field=models.JSONField(),
        ),
    ]
