# Generated by Django 3.2.12 on 2022-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0028_auto_20221005_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nubefactrespuesta',
            name='respuesta',
            field=models.JSONField(null=True),
        ),
    ]
