# Generated by Django 3.2.12 on 2022-10-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0030_alter_nubefactrespuesta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='nubefact',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
