# Generated by Django 3.2.12 on 2022-10-06 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0024_alter_representantelegal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('datos_globales', '0032_seriescomprobante_contingencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nubefactacceso',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='nubefactacceso',
            name='serie_comprobante',
        ),
        migrations.RemoveField(
            model_name='nubefactacceso',
            name='sociedad',
        ),
        migrations.CreateModel(
            name='NubefactSerieAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_globales.nubefactacceso')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NubefactSerieAcceso_created_by', to=settings.AUTH_USER_MODEL)),
                ('serie_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NubefactSerieAcceso_serie_comprobante', to='datos_globales.seriescomprobante')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NubefactSerieAcceso_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nubefact Acceso',
                'verbose_name_plural': 'Nubefact Accesos',
            },
        ),
    ]
