# Generated by Django 3.2.12 on 2022-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0033_auto_20221006_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='nubefactacceso',
            name='descripcion',
            field=models.CharField(default='Prueba', max_length=100),
            preserve_default=False,
        ),
    ]
