# Generated by Django 3.2.12 on 2022-10-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0034_nubefactacceso_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nubefactserieacceso',
            options={'verbose_name': 'Nubefact Serie Acceso', 'verbose_name_plural': 'Nubefact Serie Accesos'},
        ),
        migrations.AlterField(
            model_name='nubefactacceso',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
