# Generated by Django 3.2.12 on 2022-10-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0035_auto_20221006_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='nubefactrespuesta',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
