# Generated by Django 3.2.12 on 2022-10-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0036_nubefactrespuesta_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nubefactrespuesta',
            options={'ordering': ['updated_at'], 'verbose_name': 'Nubefact Respuesta', 'verbose_name_plural': 'Nubefact Respuestas'},
        ),
    ]
