# Generated by Django 3.2.12 on 2022-10-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0037_alter_nubefactrespuesta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ['codigo'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
    ]
