# Generated by Django 3.2.12 on 2022-12-13 20:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0039_seriescomprobante_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
