# Generated by Django 3.2.12 on 2022-12-13 20:56

import applications.funciones
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0040_moneda_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancariasociedad',
            name='temporal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.banco'),
        ),
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[applications.funciones.validar_numero], verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='numero_cuenta_interbancaria',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[applications.funciones.validar_numero], verbose_name='Número de Cuenta Interbancaria'),
        ),
    ]
