# Generated by Django 3.2.12 on 2022-12-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0041_auto_20221213_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentabancariasociedad',
            old_name='temporal',
            new_name='efectivo',
        ),
    ]
