# Generated by Django 3.2.12 on 2023-01-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0042_rename_temporal_cuentabancariasociedad_efectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocambiosunat',
            name='tipo_cambio_compra',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Tipo de Cambio Compra'),
        ),
        migrations.AlterField(
            model_name='tipocambiosunat',
            name='tipo_cambio_venta',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Tipo de Cambio Venta'),
        ),
    ]
