# Generated by Django 3.2.12 on 2023-03-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0043_auto_20230125_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriescomprobante',
            options={'ordering': ['-created_at'], 'verbose_name': 'Series Comprobante', 'verbose_name_plural': 'Series Comprobantes'},
        ),
    ]
