# Generated by Django 3.2.12 on 2023-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0044_alter_seriescomprobante_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuentabancariapersonal',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
    ]
