# Generated by Django 3.2.12 on 2023-12-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancariasociedad',
            name='percepcion',
            field=models.BooleanField(default=False),
        ),
    ]
