# Generated by Django 3.2.12 on 2023-10-18 19:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
