# Generated by Django 3.2.12 on 2023-12-21 21:53

import applications.funciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0048_cuentabancariasociedad_percepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[applications.funciones.validar_texto_cuenta], verbose_name='Número de Cuenta'),
        ),
    ]
