# Generated by Django 3.2.12 on 2023-12-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0049_alter_cuentabancariasociedad_numero_cuenta'),
        ('datos_globales', '0049_alter_moneda_color'),
    ]

    operations = [
    ]
