# Generated by Django 3.2.12 on 2024-04-16 17:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0050_merge_20231228_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
