# Generated by Django 3.2.12 on 2024-10-03 16:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0057_alter_moneda_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
