# Generated by Django 3.2.12 on 2024-12-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0043_alter_sociedad_color'),
        ('datos_globales', '0062_alter_moneda_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuentabancariasociedad',
            unique_together={('numero_cuenta', 'sociedad')},
        ),
    ]
