# Generated by Django 3.2.12 on 2024-12-02 21:13

import applications.funciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0063_alter_cuentabancariasociedad_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancariasociedad',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[applications.funciones.validar_texto_cuenta], verbose_name='Número de Cuenta'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentabancariasociedad',
            unique_together=set(),
        ),
    ]
