# Generated by Django 3.2.12 on 2025-04-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrevoWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('request', 'Request'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('click', 'Click'), ('bounce', 'Bounce'), ('spam', 'Spam'), ('blocked', 'Blocked'), ('invalid_email', 'Invalid Email'), ('sent', 'Sent')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('ts', models.BigIntegerField(blank=True, null=True)),
                ('ts_event', models.BigIntegerField(blank=True, null=True)),
                ('ts_epoch', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sending_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('mirror_link', models.URLField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
