# Generated by Django 3.2.12 on 2025-04-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevowebhookevent',
            name='event',
            field=models.CharField(choices=[('request', 'Request (Enviado desde tu sistema)'), ('delivered', 'Delivered'), ('hard_bounce', 'Hard Bounce'), ('soft_bounce', 'Soft Bounce'), ('blocked', 'Blocked'), ('spam', 'Spam (Complaint)'), ('invalid_email', 'Invalid Email'), ('deferred', 'Deferred'), ('click', 'Click'), ('opened', 'Opened'), ('unique_opened', 'First Opening'), ('unsubscribed', 'Unsubscribed'), ('error', 'Error'), ('proxy_open', 'Loaded by Proxy')], max_length=50),
        ),
    ]
