# Generated by Django 3.2.12 on 2025-04-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevo', '0003_alter_brevowebhookevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='brevowebhookevent',
            name='device_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brevowebhookevent',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brevowebhookevent',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brevowebhookevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brevowebhookevent',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
