# Generated by Django 3.2.12 on 2025-04-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevo', '0004_auto_20250407_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevowebhookevent',
            name='event',
            field=models.CharField(choices=[('request', 'Request (Enviado desde tu sistema)'), ('delivered', 'Enviado'), ('hard_bounce', 'Hard Bounce'), ('soft_bounce', 'Soft Bounce'), ('blocked', 'Bloqueado'), ('spam', 'Spam (Complaint)'), ('invalid_email', 'Email inválido'), ('deferred', 'Deferred'), ('click', 'Click'), ('opened', 'Abierto'), ('unique_opened', 'Primera vez abierto'), ('unsubscribed', 'Unsubscribed'), ('error', 'Error'), ('proxy_open', 'Loaded by Proxy'), ('unique_proxy_open', 'Unique proxy open')], max_length=50),
        ),
    ]
