# Generated by Django 3.2.12 on 2022-07-04 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0015_auto_20220601_1956'),
        ('material', '0029_alter_idiomamaterial_options'),
        ('requerimiento_de_materiales', '0022_alter_requerimientomaterialproveedor_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('internacional_nacional', models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], default=1, verbose_name='Internacional-Nacional')),
                ('incoterms', models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], null=True, verbose_name='INCOTERMS')),
                ('numero_oferta', models.CharField(max_length=50, null=True, verbose_name='Número de Oferta')),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento Global')),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Descuento')),
                ('total_anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Anticipo')),
                ('total_gravada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Grabada')),
                ('total_inafecta', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Inafecta')),
                ('total_exonerada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Exonerada')),
                ('total_igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total IGV')),
                ('total_gratuita', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gratuita')),
                ('total_otros_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Otros Cargos')),
                ('total_isc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total ISC')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'FINALIZADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OfertaProveedor_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('requerimiento_material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requerimiento_de_materiales.requerimientomaterialproveedor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OfertaProveedor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta Proveedor',
                'verbose_name_plural': 'Ofertas Proveedor',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OfertaMaterialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Unitario sin IGV')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Unitario con IGV')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Final con IGV')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Anticipo')),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'FINALIZADO')], null=True, verbose_name='Tipo de IGV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OfertaMaterialDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('oferta_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta_proveedor.ofertaproveedor')),
                ('proveedor_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.proveedormaterial')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OfertaMaterialDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta Material Detalle',
                'verbose_name_plural': 'Ofertas Material Detalle',
            },
        ),
    ]
