# Generated by Django 3.2.12 on 2022-07-06 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oferta_proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaproveedor',
            name='archivo',
        ),
        migrations.CreateModel(
            name='ArchivoOfertaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ArchivoOfertaProveedor_created_by', to=settings.AUTH_USER_MODEL)),
                ('oferta_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oferta_proveedor.ofertaproveedor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ArchivoOfertaProveedor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Oferta Proveedor',
                'verbose_name_plural': 'Archivos Oferta Proveedor',
            },
        ),
    ]
