# Generated by Django 3.2.12 on 2022-07-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0022_alter_requerimientomaterialproveedor_estado'),
        ('oferta_proveedor', '0002_auto_20220706_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='incoterms',
            field=models.IntegerField(blank=True, choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], null=True, verbose_name='INCOTERMS'),
        ),
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='numero_oferta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Oferta'),
        ),
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='requerimiento_material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='requerimiento_de_materiales.requerimientomaterialproveedor'),
        ),
    ]
