# Generated by Django 3.2.12 on 2022-07-07 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0022_alter_requerimientomaterialproveedor_estado'),
        ('oferta_proveedor', '0004_auto_20220707_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='requerimiento_material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='OfertaProveedor_requerimiento_material', to='requerimiento_de_materiales.requerimientomaterialproveedor'),
        ),
    ]
