# Generated by Django 3.2.12 on 2022-07-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0007_alter_ofertaproveedor_requerimiento_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproveedordetalle',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='total_gravada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gravada'),
        ),
    ]
