# Generated by Django 3.2.12 on 2022-07-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0008_auto_20220712_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedordetalle',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sub Total'),
        ),
    ]
