# Generated by Django 3.2.12 on 2022-07-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0009_alter_ofertaproveedordetalle_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaproveedor',
            name='total_isc',
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='total_icbper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total ICBPER'),
        ),
        migrations.AlterField(
            model_name='ofertaproveedordetalle',
            name='oferta_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OfertaProveedorDetalle_oferta_proveedor', to='oferta_proveedor.ofertaproveedor'),
        ),
    ]
