# Generated by Django 3.2.12 on 2022-07-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0010_auto_20220714_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertaproveedordetalle',
            options={'ordering': ['item'], 'verbose_name': 'Oferta Proveedor Detalle', 'verbose_name_plural': 'Ofertas Proveedor Detalle'},
        ),
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='incoterms',
            field=models.IntegerField(blank=True, choices=[(1, 'EXW'), (2, 'FOB'), (3, 'FCA'), (4, 'CIF'), (5, 'DDP')], null=True, verbose_name='INCOTERMS'),
        ),
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
