# Generated by Django 3.2.12 on 2022-07-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0011_auto_20220719_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertaproveedordetalle',
            options={'ordering': ['oferta_proveedor', 'item'], 'verbose_name': 'Oferta Proveedor Detalle', 'verbose_name_plural': 'Ofertas Proveedor Detalle'},
        ),
    ]
