# Generated by Django 3.2.12 on 2022-07-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0011_auto_20220719_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'FINALIZADO'), (3, 'RECHAZADO')], default=1, verbose_name='Estado'),
        ),
    ]
