# Generated by Django 3.2.12 on 2022-07-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0012_alter_ofertaproveedor_estado'),
        ('oferta_proveedor', '0012_alter_ofertaproveedordetalle_options'),
    ]

    operations = [
    ]
