# Generated by Django 3.2.12 on 2022-09-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0025_alter_requerimientomaterialproveedor_estado'),
        ('oferta_proveedor', '0013_merge_20220723_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='requerimiento_material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='OfertaProveedor_requerimiento_material', to='requerimiento_de_materiales.requerimientomaterialproveedor'),
        ),
    ]
