# Generated by Django 3.2.12 on 2022-10-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0039_seriescomprobante_mostrar'),
        ('oferta_proveedor', '0015_alter_ofertaproveedordetalle_tipo_igv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda'),
        ),
    ]
