# Generated by Django 3.2.12 on 2022-10-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0016_alter_ofertaproveedor_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproveedordetalle',
            name='especificaciones_tecnicas',
            field=models.FileField(blank=True, null=True, upload_to='file/oferta_proveedor/detalle/especificaciones_tecnicas/', verbose_name='Especificaciones Técnicas'),
        ),
        migrations.AddField(
            model_name='ofertaproveedordetalle',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/oferta_proveedor/detalle/imagen/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='archivoofertaproveedor',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='file/oferta_proveedor/detalle/archivo/', verbose_name='Archivo'),
        ),
    ]
