# Generated by Django 3.2.12 on 2022-10-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0017_auto_20221018_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproveedor',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
    ]
