# Generated by Django 3.2.12 on 2022-10-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0018_ofertaproveedor_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaproveedor',
            name='comentario',
        ),
    ]
