# Generated by Django 3.2.12 on 2022-10-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0019_remove_ofertaproveedor_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproveedor',
            name='forma_pago',
            field=models.TextField(blank=True, null=True, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='puerto_origen',
            field=models.TextField(blank=True, null=True, verbose_name='Puerto de origen'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='tiempo_estimado_entrega',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo estimado de entrega (dias)'),
        ),
    ]
