# Generated by Django 3.2.12 on 2022-11-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0020_auto_20221021_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma de pago'),
        ),
    ]
