# Generated by Django 3.2.12 on 2022-11-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0021_alter_ofertaproveedor_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='forma_pago',
            field=models.TextField(blank=True, null=True, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='puerto_origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Puerto de origen'),
        ),
    ]
