# Generated by Django 3.2.12 on 2022-12-05 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0022_auto_20221128_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertaproveedor',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name': 'Oferta Proveedor', 'verbose_name_plural': 'Ofertas Proveedor'},
        ),
    ]
