# Generated by Django 3.2.12 on 2025-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0023_alter_ofertaproveedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='incoterms',
            field=models.IntegerField(blank=True, choices=[(1, 'EXW'), (2, 'FOB'), (3, 'FCA'), (4, 'CIF'), (5, 'DDP'), (6, 'CNF')], null=True, verbose_name='INCOTERMS'),
        ),
    ]
