# Generated by Django 3.2.12 on 2023-03-07 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('datos_globales', '0043_auto_20230125_1303'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=5, verbose_name='Tipo de Cambio')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto Inicial')),
                ('motivo_rechazo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Motivo de Rechazo')),
                ('dato_rechazado', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dato Rechazado')),
                ('monto_final', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto Final')),
                ('concepto_final', models.CharField(blank=True, max_length=255, null=True, verbose_name='Concepto Final')),
                ('fecha_entrega', models.DateField(null=True, verbose_name='Fecha de Entrega')),
                ('monto_usado', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto Usado')),
                ('redondeo', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Redondeo')),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Vuelto')),
                ('rechazo_rendicion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rechazo de Rendición')),
                ('requerimiento_grande', models.BooleanField(default=False, verbose_name='Requerimiento Grande')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'SOLICITADO'), (3, 'APROBADO'), (4, 'RECHAZADO'), (5, 'REVISAR RENDICIÓN'), (6, 'RENDICIÓN RECHAZADA'), (7, 'FINALIZADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Requerimiento_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Requerimiento_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimiento_usuario', to=settings.AUTH_USER_MODEL)),
                ('usuario_pedido', models.ForeignKey(blank=True, help_text='Usuario al que está dirigido el pedido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimiento_usuario_pedido', to=settings.AUTH_USER_MODEL, verbose_name='Pedir a')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['estado', 'fecha'],
            },
        ),
    ]
