# Generated by Django 3.2.12 on 2023-03-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0043_auto_20230125_1303'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('caja_chica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'SIN DOCUMENTO')], verbose_name='Tipo de Documento')),
                ('numero', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('establecimiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Establecimiento')),
                ('total_documento', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total en Documento')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Tipo de Cambio')),
                ('total_requerimiento', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total en Requerimiento')),
                ('voucher', models.FileField(blank=True, null=True, upload_to='file/caja_chica/requerimiento/documento/', verbose_name='Documento')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
            ],
            options={
                'verbose_name': 'Documento Requerimiento',
                'verbose_name_plural': 'Documentos Requerimientos',
                'ordering': ['tipo', 'fecha', 'establecimiento'],
            },
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='usuario_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimiento_usuario_pedido', to=settings.AUTH_USER_MODEL, verbose_name='Pedir a'),
        ),
        migrations.CreateModel(
            name='RequerimientoVueltoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuelto_original', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Vuelto en Efectivo')),
                ('vuelto_extra', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Vuelto en Moneda del Requerimiento')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Tipo de Cambio')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimiento_vuelto_extra', to='caja_chica.requerimiento')),
            ],
            options={
                'verbose_name': 'Requerimiento Vuelto Extra',
                'verbose_name_plural': 'Requerimiento Vueltos Extras',
            },
        ),
        migrations.CreateModel(
            name='RequerimientoDocumentoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='Item')),
                ('producto', models.CharField(max_length=120, verbose_name='Producto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio Unitario')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/caja chica/requerimiento/producto/', verbose_name='Foto de Producto')),
                ('documento_requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_detalle', to='caja_chica.requerimientodocumento')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.unidad')),
            ],
            options={
                'verbose_name': 'Documento Requerimiento Detalle',
                'verbose_name_plural': 'Documento Requerimiento Detalles',
                'ordering': ['item'],
            },
        ),
        migrations.AddField(
            model_name='requerimientodocumento',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja_chica.requerimiento'),
        ),
        migrations.AddField(
            model_name='requerimientodocumento',
            name='sociedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
        ),
    ]
