# Generated by Django 3.2.12 on 2023-03-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0002_auto_20230309_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimiento',
            name='requerimiento_grande',
        ),
    ]
