# Generated by Django 3.2.12 on 2023-03-16 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caja_chica', '0003_remove_requerimiento_requerimiento_grande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requerimiento',
            options={'ordering': ['estado', 'fecha', 'created_at'], 'verbose_name': 'Requerimiento', 'verbose_name_plural': 'Requerimientos'},
        ),
        migrations.AddField(
            model_name='requerimientodocumento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimientodocumento',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoDocumento_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requerimientodocumento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='requerimientodocumento',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoDocumento_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requerimientodocumentodetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimientodocumentodetalle',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoDocumentoDetalle_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requerimientodocumentodetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='requerimientodocumentodetalle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoDocumentoDetalle_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requerimientovueltoextra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimientovueltoextra',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoVueltoExtra_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requerimientovueltoextra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='requerimientovueltoextra',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoVueltoExtra_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
