# Generated by Django 3.2.12 on 2023-03-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0004_auto_20230316_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientodocumentodetalle',
            name='documento_requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequerimientoDocumentoDetalle_documento_requerimiento', to='caja_chica.requerimientodocumento'),
        ),
        migrations.AlterField(
            model_name='requerimientovueltoextra',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequerimientoVueltoExtra_requerimiento', to='caja_chica.requerimiento'),
        ),
    ]
