# Generated by Django 3.2.12 on 2023-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0005_auto_20230324_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientodocumentodetalle',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/caja_chica/requerimiento/producto/', verbose_name='Foto de Producto'),
        ),
    ]
