# Generated by Django 3.2.12 on 2023-03-25 16:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0044_alter_seriescomprobante_options'),
        ('caja_chica', '0005_auto_20230324_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Saldo Inicial')),
                ('year', models.IntegerField(blank=True, default=2023, null=True, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2023)], verbose_name='Año')),
                ('month', models.IntegerField(blank=True, choices=[(1, 'ENERO'), (2, 'FEBRERO'), (3, 'MARZO'), (4, 'ABRIL'), (5, 'MAYO'), (6, 'JUNIO'), (7, 'JULIO'), (8, 'AGOSTO'), (9, 'SETIEMBRE'), (10, 'OCTUBRE'), (11, 'NOVIEMBRE'), (12, 'DICIEMBRE')], null=True, verbose_name='Mes')),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ingresos')),
                ('egresos', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Egresos')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Saldo Inicial')),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CajaChica_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('saldo_inicial_caja_chica', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja_chica.cajachica')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CajaChica_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CajaChica_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Caja Chica',
                'verbose_name_plural': 'Cajas Chicas',
            },
        ),
        migrations.CreateModel(
            name='ReciboCajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50, null=True, verbose_name='Concepto Salida')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto')),
                ('redondeo', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Redondeo')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('caja_chica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja_chica.cajachica')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReciboCajaChica_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReciboCajaChica_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo Caja Chica',
                'verbose_name_plural': 'Recibos Caja Chica',
            },
        ),
        migrations.CreateModel(
            name='CajaChicaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50, null=True, verbose_name='Concepto Salida')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('caja_chica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja_chica.cajachica')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CajaChicaSalida_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CajaChicaSalida_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CajaChicaSalida_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Caja Chica Salida',
                'verbose_name_plural': 'Caja Chica Salidas',
            },
        ),
        migrations.CreateModel(
            name='CajaChicaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto')),
                ('tipo', models.IntegerField(choices=[(1, 'PRESTAMO')], default=1)),
                ('estado', models.IntegerField(choices=[(1, 'PRESTADO'), (1, 'DEVUELTO')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('caja_orgen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja_chica.cajachica')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CajaChicaPrestamo_created_by', to=settings.AUTH_USER_MODEL)),
                ('devolucion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja_chica.cajachicaprestamo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CajaChicaPrestamo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja Chica Prestamo',
                'verbose_name_plural': 'Caja Chica Prestamos',
            },
        ),
    ]
