# Generated by Django 3.2.12 on 2023-03-25 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0006_cajachica_cajachicaprestamo_cajachicasalida_recibocajachica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajachicaprestamo',
            name='caja_orgen',
        ),
        migrations.AddField(
            model_name='cajachicaprestamo',
            name='caja_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='CajaChicaPrestamo_caja_destino', to='caja_chica.cajachica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cajachicaprestamo',
            name='caja_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='CajaChicaPrestamo_caja_origen', to='caja_chica.cajachica'),
            preserve_default=False,
        ),
    ]
