# Generated by Django 3.2.12 on 2023-03-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0007_auto_20230325_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachicaprestamo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PRESTADO'), (2, 'DEVUELTO')], default=1),
        ),
    ]
