# Generated by Django 3.2.12 on 2023-03-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0006_alter_requerimientodocumentodetalle_foto'),
        ('caja_chica', '0008_alter_cajachicaprestamo_estado'),
    ]

    operations = [
    ]
