# Generated by Django 3.2.12 on 2023-04-01 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0009_merge_20230329_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachica',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1),
        ),
        migrations.AlterField(
            model_name='recibocajachica',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='dato_rechazado',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Detalle del rechazo'),
        ),
        migrations.AlterField(
            model_name='requerimientodocumento',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequerimientoDocumento_requerimiento', to='caja_chica.requerimiento'),
        ),
    ]
