# Generated by Django 3.2.12 on 2023-04-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0010_auto_20230401_1229'),
        ('caja_chica', '0010_auto_20230401_1233'),
    ]

    operations = [
    ]
