# Generated by Django 3.2.12 on 2023-04-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_merge_0017_auto_20230401_1229_0017_auto_20230401_1233'),
        ('caja_chica', '0011_merge_0010_auto_20230401_1229_0010_auto_20230401_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocajachica',
            name='cheque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cheque'),
            preserve_default=False,
        ),
    ]
