# Generated by Django 3.2.12 on 2023-04-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_merge_0017_auto_20230401_1229_0017_auto_20230401_1233'),
        ('caja_chica', '0012_recibocajachica_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibocajachica',
            name='cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cheque'),
        ),
    ]
