# Generated by Django 3.2.12 on 2023-04-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0013_alter_recibocajachica_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibocajachica',
            name='concepto',
            field=models.CharField(max_length=50, null=True, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='recibocajachica',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
    ]
