# Generated by Django 3.2.12 on 2023-04-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0014_auto_20230405_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibocajachica',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'PAGADO')], default=1),
        ),
    ]
