# Generated by Django 3.2.12 on 2023-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0015_alter_recibocajachica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachicaprestamo',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'PRESTAMO'), (2, 'DEVOLUCION')], default=1),
        ),
    ]
