# Generated by Django 3.2.12 on 2023-04-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0016_alter_cajachicaprestamo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachica',
            name='saldo_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Saldo Inicial'),
        ),
    ]
