# Generated by Django 3.2.12 on 2023-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0017_alter_cajachica_saldo_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachicaprestamo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'CANCELADO')], default=1),
        ),
    ]
