# Generated by Django 3.2.12 on 2023-04-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0018_alter_cajachicaprestamo_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajachica',
            options={'ordering': ['-year', '-month', 'estado'], 'verbose_name': 'Caja Chica', 'verbose_name_plural': 'Cajas Chicas'},
        ),
    ]
