# Generated by Django 3.2.12 on 2023-06-19 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0027_alter_sociedad_estado_sunat'),
        ('caja_chica', '0019_alter_cajachica_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajachica',
            options={'ordering': ['estado', '-year', '-month'], 'verbose_name': 'Caja Chica', 'verbose_name_plural': 'Cajas Chicas'},
        ),
        migrations.AlterField(
            model_name='requerimientodocumento',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='requerimientodocumento',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
        ),
    ]
