# Generated by Django 3.2.12 on 2023-06-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0020_auto_20230619_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientodocumento',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Tipo de Cambio'),
        ),
        migrations.AlterField(
            model_name='requerimientodocumento',
            name='total_requerimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total en Requerimiento'),
        ),
    ]
