# Generated by Django 3.2.12 on 2023-06-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0021_auto_20230620_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientodocumento',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5, verbose_name='Tipo de Cambio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requerimientodocumento',
            name='total_requerimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Total en Requerimiento'),
            preserve_default=False,
        ),
    ]
