# Generated by Django 3.2.12 on 2023-06-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0022_auto_20230620_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requerimiento',
            options={'ordering': ['estado', '-fecha', 'created_at'], 'verbose_name': 'Requerimiento', 'verbose_name_plural': 'Requerimientos'},
        ),
    ]
