# Generated by Django 3.2.12 on 2023-06-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0023_alter_requerimiento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibocajachica',
            options={'ordering': ['estado', '-fecha'], 'verbose_name': 'Recibo Caja Chica', 'verbose_name_plural': 'Recibos Caja Chica'},
        ),
    ]
