# Generated by Django 3.2.12 on 2023-07-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0024_alter_recibocajachica_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibocajachica',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'CANCELADO')], default=1),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'SOLICITADO'), (3, 'APROBADO'), (4, 'RECHAZADO'), (5, 'REVISAR RENDICIÓN'), (6, 'RENDICIÓN RECHAZADA'), (7, 'CANCELADO')], default=1, verbose_name='Estado'),
        ),
    ]
