# Generated by Django 3.2.12 on 2023-07-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0025_auto_20230706_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientodocumento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'SIN DOCUMENTO'), (4, 'RECIBO POR HONORARIOS')], verbose_name='Tipo de Documento'),
        ),
    ]
