# Generated by Django 3.2.12 on 2024-03-27 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0026_alter_requerimientodocumento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachica',
            name='year',
            field=models.IntegerField(blank=True, default=2024, null=True, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2024)], verbose_name='Año'),
        ),
    ]
