# Generated by Django 3.2.12 on 2024-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0027_alter_cajachica_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientodocumento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'SIN DOCUMENTO'), (4, 'RECIBO POR HONORARIOS'), (5, 'VOUCHER')], verbose_name='Tipo de Documento'),
        ),
    ]
