# Generated by Django 3.2.12 on 2025-01-07 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0028_alter_requerimientodocumento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachica',
            name='year',
            field=models.IntegerField(blank=True, default=2025, null=True, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2025)], verbose_name='Año'),
        ),
    ]
