# Generated by Django 3.2.12 on 2022-04-22 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelDos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Nivel Dos')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='img/programas/icono', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='Icono PNG o SVG')),
                ('app_name', models.CharField(max_length=50, verbose_name='Nombre de App')),
            ],
            options={
                'verbose_name': 'Nivel Dos',
                'verbose_name_plural': 'Niveles Dos',
                'ordering': ['nivel_uno__orden', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='NivelUno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Nivel Uno')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='img/programas/icono/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='Icono PNG o SVG')),
            ],
            options={
                'verbose_name': 'Nivel Uno',
                'verbose_name_plural': 'Niveles Uno',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='NivelTres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Nivel Tres')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='img/programas/icono', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='Icono PNG o SVG')),
                ('url_name', models.CharField(max_length=50, verbose_name='Nombre de URL')),
                ('nivel_dos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.niveldos')),
            ],
            options={
                'verbose_name': 'Nivel Tres',
                'verbose_name_plural': 'Niveles Tres',
                'ordering': ['nivel_dos__orden', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='niveldos',
            name='nivel_uno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.niveluno'),
        ),
        migrations.CreateModel(
            name='NivelCuatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Nivel Cuatro')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='img/programas/icono', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='Icono PNG o SVG')),
                ('url_name', models.CharField(max_length=50, verbose_name='Nombre de URL')),
                ('nivel_tres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.niveltres')),
            ],
            options={
                'verbose_name': 'Nivel Cuatro',
                'verbose_name_plural': 'Niveles Cuatro',
                'ordering': ['nivel_tres__orden', 'orden'],
            },
        ),
    ]
