# Generated by Django 3.2.12 on 2022-04-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveldos',
            name='nivel_uno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NivelDos_nivel_uno', to='programas.niveluno'),
        ),
        migrations.AlterField(
            model_name='niveltres',
            name='nivel_dos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NivelTres_nivel_dos', to='programas.niveldos'),
        ),
        migrations.AlterField(
            model_name='niveltres',
            name='url_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de URL'),
        ),
    ]
