# Generated by Django 3.2.12 on 2022-04-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_auto_20220422_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelcuatro',
            name='nivel_tres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NivelCuatro_nivel_tres', to='programas.niveltres'),
        ),
    ]
