# Generated by Django 3.2.12 on 2022-04-25 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0002_auto_20220422_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelcuatro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivelcuatro',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NivelCuatro_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nivelcuatro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='nivelcuatro',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NivelCuatro_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='niveldos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='niveldos',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NivelDos_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='niveldos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='niveldos',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NivelDos_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='niveltres',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='niveltres',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NivelTres_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='niveltres',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='niveltres',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NivelTres_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='niveluno',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='niveluno',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NivelUno_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='niveluno',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='niveluno',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NivelUno_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nivelcuatro',
            name='nivel_tres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NivelCuatro_nivel_tres', to='programas.niveltres'),
        ),
    ]
