# Generated by Django 3.2.12 on 2022-04-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_alter_nivelcuatro_nivel_tres'),
        ('programas', '0003_auto_20220425_1949'),
    ]

    operations = [
    ]
