# Generated by Django 3.2.12 on 2022-04-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0004_merge_20220429_1659'),
        ('programas', '0004_merge_20220429_1706'),
    ]

    operations = [
    ]
