# Generated by Django 3.2.12 on 2022-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0005_merge_20220429_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveluno',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de Nivel Uno'),
        ),
    ]
