# Generated by Django 3.2.12 on 2022-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0007_alter_niveluno_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelcuatro',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de App'),
        ),
        migrations.AddField(
            model_name='niveldos',
            name='url_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de URL'),
        ),
        migrations.AddField(
            model_name='niveltres',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de App'),
        ),
        migrations.AlterField(
            model_name='nivelcuatro',
            name='url_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de URL'),
        ),
        migrations.AlterField(
            model_name='niveldos',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de App'),
        ),
    ]
