# Generated by Django 3.2.12 on 2022-09-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0008_auto_20220811_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelcuatro',
            options={'ordering': ['nivel_tres', 'orden'], 'verbose_name': 'Nivel Cuatro', 'verbose_name_plural': 'Niveles Cuatro'},
        ),
        migrations.AlterModelOptions(
            name='niveldos',
            options={'ordering': ['nivel_uno', 'orden'], 'verbose_name': 'Nivel Dos', 'verbose_name_plural': 'Niveles Dos'},
        ),
        migrations.AlterModelOptions(
            name='niveltres',
            options={'ordering': ['nivel_dos', 'orden'], 'verbose_name': 'Nivel Tres', 'verbose_name_plural': 'Niveles Tres'},
        ),
    ]
