# Generated by Django 3.2.12 on 2022-11-08 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sede', '0006_alter_sede_sociedad'),
        ('datos_globales', '0039_seriescomprobante_mostrar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('almacenes', '0003_alter_almacen_estado_alta_baja'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_traslado', models.TextField()),
                ('visible', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='MotivoTraslado_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='MotivoTraslado_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motivo Traslado',
                'verbose_name_plural': 'Motivos Traslado',
            },
        ),
        migrations.CreateModel(
            name='EnvioTrasladoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_envio_traslado', models.IntegerField(blank=True, null=True, verbose_name='Número de Envio Traslado')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('fecha_traslado', models.DateField(verbose_name='Fecha Traslado')),
                ('observaciones', models.TextField()),
                ('estado', models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'TRASLADO ENVIADO'), (3, 'TRASLADO RECEPCIONADO'), (4, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EnvioTrasladoProducto_created_by', to=settings.AUTH_USER_MODEL)),
                ('motivo_traslado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traslado_producto.motivotraslado')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EnvioTrasladoProducto_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('sede_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sede.sede')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EnvioTrasladoProducto_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envio Traslado Producto',
                'verbose_name_plural': 'Envios Traslado Producto',
            },
        ),
        migrations.CreateModel(
            name='DetalleEnvioTrasladoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('cantidad_envio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad de Envio')),
                ('estado', models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'TRASLADO ENVIADO'), (3, 'TRASLADO RECEPCIONADO'), (4, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DetalleEnvioTrasladoProducto_created_by', to=settings.AUTH_USER_MODEL)),
                ('envio_traslado_almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traslado_producto.enviotrasladoproducto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DetalleEnvioTrasladoProducto_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Envio Traslado Producto',
                'verbose_name_plural': 'Detalle Envios Traslado Productos',
            },
        ),
    ]
