# Generated by Django 3.2.12 on 2022-11-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviotrasladoproducto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
