# Generated by Django 3.2.12 on 2022-11-10 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('almacenes', '0003_alter_almacen_estado_alta_baja'),
        ('datos_globales', '0039_seriescomprobante_mostrar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traslado_producto', '0002_alter_enviotrasladoproducto_observaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleEnvioTrasladoProducto',
            new_name='EnvioTrasladoProductoDetalle',
        ),
    ]
