# Generated by Django 3.2.12 on 2022-11-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0003_rename_detalleenviotrasladoproducto_enviotrasladoproductodetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviotrasladoproducto',
            name='direccion',
        ),
        migrations.AddField(
            model_name='enviotrasladoproducto',
            name='direccion_destino',
            field=models.CharField(default=1, max_length=100, verbose_name='Dirección Destino'),
            preserve_default=False,
        ),
    ]
