# Generated by Django 3.2.12 on 2022-11-16 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0006_alter_sede_sociedad'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacenes', '0003_alter_almacen_estado_alta_baja'),
        ('datos_globales', '0039_seriescomprobante_mostrar'),
        ('traslado_producto', '0004_auto_20221111_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviotrasladoproducto',
            options={'ordering': ['-fecha_traslado'], 'verbose_name': 'Envio Traslado Producto', 'verbose_name_plural': 'Envios Traslado Producto'},
        ),
        migrations.AlterModelOptions(
            name='enviotrasladoproductodetalle',
            options={'verbose_name': 'Envio Traslado Producto Detalle ', 'verbose_name_plural': 'Envios Traslado Productos Detalle'},
        ),
        migrations.AlterField(
            model_name='enviotrasladoproducto',
            name='direccion_destino',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección Destino'),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproducto',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'EN PROCESO'), (2, 'TRASLADO ENVIADO'), (3, 'TRASLADO RECEPCIONADO'), (4, 'ANULADO')], default=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproducto',
            name='motivo_traslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traslado_producto.motivotraslado'),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproducto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnvioTrasladoProducto_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproducto',
            name='sede_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sede.sede'),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproducto',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproductodetalle',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen'),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproductodetalle',
            name='cantidad_envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cantidad de Envio'),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproductodetalle',
            name='envio_traslado_almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnvioTrasladoProductoDetalle_envio_traslado_almacen', to='traslado_producto.enviotrasladoproducto'),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproductodetalle',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'EN PROCESO'), (2, 'TRASLADO ENVIADO'), (3, 'TRASLADO RECEPCIONADO'), (4, 'ANULADO')], default=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproductodetalle',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.unidad'),
        ),
    ]
