# Generated by Django 3.2.12 on 2022-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0005_auto_20221116_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviotrasladoproducto',
            name='fecha_traslado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Traslado'),
        ),
    ]
