# Generated by Django 3.2.12 on 2022-11-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0006_alter_enviotrasladoproducto_fecha_traslado'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviotrasladoproductodetalle',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
