# Generated by Django 3.2.12 on 2022-11-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0007_enviotrasladoproductodetalle_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviotrasladoproductodetalle',
            options={'ordering': ['item'], 'verbose_name': 'Envio Traslado Producto Detalle ', 'verbose_name_plural': 'Envios Traslado Productos Detalle'},
        ),
    ]
