# Generated by Django 3.2.12 on 2022-11-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0008_alter_enviotrasladoproductodetalle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviotrasladoproducto',
            options={'ordering': ['-numero_envio_traslado', '-fecha_traslado'], 'verbose_name': 'Envio Traslado Producto', 'verbose_name_plural': 'Envios Traslado Producto'},
        ),
    ]
