# Generated by Django 3.2.12 on 2022-11-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0009_alter_enviotrasladoproducto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviotrasladoproductodetalle',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'EN PROCESO'), (2, 'ENVIADO'), (3, 'RECEPCIONADO PARCIALMENTE'), (4, 'RECEPCIONADO')], default=1, null=True, verbose_name='Estado'),
        ),
    ]
