# Generated by Django 3.2.12 on 2022-11-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0006_alter_sede_sociedad'),
        ('traslado_producto', '0010_alter_enviotrasladoproductodetalle_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionTrasladoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recepcion_traslado', models.IntegerField(blank=True, null=True, verbose_name='Número de sdf Traslado')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha Recepción')),
                ('envio_traslado_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecepcionTrasladoProducto_envio_traslado_producto', to='traslado_producto.enviotrasladoproducto')),
                ('sede_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sede.sede')),
            ],
            options={
                'verbose_name': 'Recepcion Traslado Producto',
                'verbose_name_plural': 'Recepcion Traslado Productos',
            },
        ),
    ]
