# Generated by Django 3.2.12 on 2022-11-23 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('almacenes', '0003_alter_almacen_estado_alta_baja'),
        ('datos_globales', '0039_seriescomprobante_mostrar'),
        ('traslado_producto', '0011_recepciontrasladoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepciontrasladoproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepciontrasladoproducto',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RecepcionTrasladoProducto_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepciontrasladoproducto',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'EN PROCESO'), (2, 'TRASLADO ENVIADO'), (3, 'TRASLADO RECEPCIONADO'), (4, 'ANULADO')], default=1, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='recepciontrasladoproducto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepciontrasladoproducto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RecepcionTrasladoProducto_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='recepciontrasladoproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='recepciontrasladoproducto',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RecepcionTrasladoProducto_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproductodetalle',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EnvioTrasladoProductoDetalle_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enviotrasladoproductodetalle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EnvioTrasladoProductoDetalle_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecepcionTrasladoProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('cantidad_recepcion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cantidad de Recepción')),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'EN PROCESO'), (2, 'ENVIADO'), (3, 'RECEPCIONADO PARCIALMENTE'), (4, 'RECEPCIONADO')], default=1, null=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RecepcionTrasladoProductoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('recepcion_traslado_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecepcionTrasladoProductoDetalle_envio_traslado_almacen', to='traslado_producto.recepciontrasladoproducto')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RecepcionTrasladoProductoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepcion Traslado Producto Detalle',
                'verbose_name_plural': 'Recepcion Traslado Productos Detalle',
            },
        ),
    ]
