# Generated by Django 3.2.12 on 2022-11-25 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0012_auto_20221123_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviotrasladoproductodetalle',
            name='envio_traslado_almacen',
        ),
        migrations.AddField(
            model_name='enviotrasladoproductodetalle',
            name='envio_traslado_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='EnvioTrasladoProductoDetalle_envio_traslado_producto', to='traslado_producto.enviotrasladoproducto'),
            preserve_default=False,
        ),
    ]
