# Generated by Django 3.2.12 on 2022-11-25 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0013_auto_20221125_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepciontrasladoproductodetalle',
            name='recepcion_traslado_almacen',
        ),
        migrations.AddField(
            model_name='recepciontrasladoproductodetalle',
            name='recepcion_traslado_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='RecepcionTrasladoProductoDetalle_envio_traslado_producto', to='traslado_producto.recepciontrasladoproducto'),
            preserve_default=False,
        ),
    ]
