# Generated by Django 3.2.12 on 2022-12-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0014_auto_20221125_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviotrasladoproductodetalle',
            name='id_registro',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
