# Generated by Django 3.2.12 on 2022-12-05 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0015_alter_enviotrasladoproductodetalle_id_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepciontrasladoproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='recepciontrasladoproducto',
            name='envio_traslado_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecepcionTrasladoProducto_envio_traslado_producto', to='traslado_producto.enviotrasladoproducto'),
        ),
        migrations.AlterField(
            model_name='recepciontrasladoproducto',
            name='numero_recepcion_traslado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Recepción Traslado'),
        ),
        migrations.AlterField(
            model_name='recepciontrasladoproductodetalle',
            name='recepcion_traslado_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecepcionTrasladoProductoDetalle_recepcion_traslado_producto', to='traslado_producto.recepciontrasladoproducto'),
        ),
    ]
