# Generated by Django 3.2.12 on 2022-12-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0016_auto_20221205_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivotraslado',
            name='motivo_traslado',
            field=models.CharField(max_length=100),
        ),
    ]
