# Generated by Django 3.2.12 on 2022-12-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0017_alter_motivotraslado_motivo_traslado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviotrasladoproductodetalle',
            name='cantidad_envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cantidad de Envio'),
        ),
        migrations.AlterField(
            model_name='recepciontrasladoproductodetalle',
            name='cantidad_recepcion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cantidad de Recepción'),
        ),
    ]
