# Generated by Django 3.2.12 on 2022-12-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0018_auto_20221221_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepciontrasladoproductodetalle',
            name='envio_traslado_producto_detalle',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='traslado_producto.enviotrasladoproductodetalle'),
            preserve_default=False,
        ),
    ]
