# Generated by Django 3.2.12 on 2022-12-23 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0006_alter_sede_sociedad'),
        ('almacenes', '0004_alter_almacen_sede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0038_proveedormaterial_unidad'),
        ('movimiento_almacen', '0010_alter_movimientosalmacen_movimiento_anterior'),
        ('traslado_producto', '0019_recepciontrasladoproductodetalle_envio_traslado_producto_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraspasoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_traspaso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro. Traspaso')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'EN PROCESO'), (2, 'CONCLUIDO'), (3, 'ANULADO')], default=1, null=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TraspasoStock_created_by', to=settings.AUTH_USER_MODEL)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sede.sede')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TraspasoStock_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traspaso Stock',
                'verbose_name_plural': 'Traspasos Stock',
            },
        ),
        migrations.CreateModel(
            name='TraspasoStockDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad de Traspaso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TraspasoStockDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.material')),
                ('tipo_stock_inicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movimiento_almacen.tipostock')),
                ('traspaso_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traslado_producto.traspasostock')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TraspasoStockDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traspaso Stock Detalle',
                'verbose_name_plural': 'Traspasos Stock Detalle',
            },
        ),
    ]
