# Generated by Django 3.2.12 on 2023-01-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0010_alter_movimientosalmacen_movimiento_anterior'),
        ('traslado_producto', '0019_recepciontrasladoproductodetalle_envio_traslado_producto_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviotrasladoproductodetalle',
            name='tipo_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock'),
            preserve_default=False,
        ),
    ]
