# Generated by Django 3.2.12 on 2022-12-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0010_alter_movimientosalmacen_movimiento_anterior'),
        ('traslado_producto', '0020_traspasostock_traspasostockdetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='traspasostockdetalle',
            name='tipo_stock_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TraspasoStockDetalle_tipo_stock_final', to='movimiento_almacen.tipostock'),
        ),
        migrations.AlterField(
            model_name='traspasostockdetalle',
            name='tipo_stock_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TraspasoStockDetalle_tipo_stock_inicial', to='movimiento_almacen.tipostock'),
        ),
    ]
