# Generated by Django 3.2.12 on 2023-01-03 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0028_alter_serie_serie_movimiento_almacen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traslado_producto', '0020_enviotrasladoproductodetalle_tipo_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidarSerieRecepcionTrasladoProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieRecepcionTrasladoProductoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('recepcion_traslado_producto_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieRecepcionTrasladoProductoDetalle_recepcion_traslado_producto_detalle', to='traslado_producto.recepciontrasladoproductodetalle')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieRecepcionTrasladoProductoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validar Series Recepcion Traslado Producto Detalle',
                'verbose_name_plural': 'Validar Series Recepciones Traslado Producto Detalle',
            },
        ),
        migrations.CreateModel(
            name='ValidarSerieEnvioTrasladoProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieEnvioTrasladoProductoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('envio_traslado_producto_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieEnvioTrasladoProductoDetalle_envio_traslado_producto_detalle', to='traslado_producto.enviotrasladoproductodetalle')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieEnvioTrasladoProductoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validar Series Envio Traslado Producto Detalle',
                'verbose_name_plural': 'Validar Series Envios Traslado Producto Detalle',
            },
        ),
    ]
