# Generated by Django 3.2.12 on 2022-12-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0021_auto_20221223_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traspasostock',
            options={'ordering': ['-nro_traspaso'], 'verbose_name': 'Traspaso Stock', 'verbose_name_plural': 'Traspasos Stock'},
        ),
    ]
