# Generated by Django 3.2.12 on 2023-01-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0021_validarserieenviotrasladoproductodetalle_validarserierecepciontrasladoproductodetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validarserieenviotrasladoproductodetalle',
            options={'ordering': ['created_at'], 'verbose_name': 'Validar Series Envio Traslado Producto Detalle', 'verbose_name_plural': 'Validar Series Envios Traslado Producto Detalle'},
        ),
        migrations.AlterModelOptions(
            name='validarserierecepciontrasladoproductodetalle',
            options={'ordering': ['created_at'], 'verbose_name': 'Validar Series Recepcion Traslado Producto Detalle', 'verbose_name_plural': 'Validar Series Recepciones Traslado Producto Detalle'},
        ),
    ]
