# Generated by Django 3.2.12 on 2023-01-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0022_alter_traspasostock_options'),
        ('traslado_producto', '0022_auto_20230109_1149'),
    ]

    operations = [
    ]
