# Generated by Django 3.2.12 on 2023-01-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('traslado_producto', '0023_merge_20230110_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traspasostockdetalle',
            name='material',
        ),
        migrations.AddField(
            model_name='traspasostock',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
        ),
        migrations.AddField(
            model_name='traspasostockdetalle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='traspasostockdetalle',
            name='id_registro',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
