# Generated by Django 3.2.12 on 2023-01-12 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('movimiento_almacen', '0013_alter_movimientosalmacen_options'),
        ('almacenes', '0004_alter_almacen_sede'),
        ('traslado_producto', '0024_auto_20230111_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traspasostockdetalle',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen'),
        ),
        migrations.AlterField(
            model_name='traspasostockdetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad de Traspaso'),
        ),
        migrations.AlterField(
            model_name='traspasostockdetalle',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='traspasostockdetalle',
            name='tipo_stock_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TraspasoStockDetalle_tipo_stock_final', to='movimiento_almacen.tipostock'),
        ),
        migrations.AlterField(
            model_name='traspasostockdetalle',
            name='tipo_stock_inicial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TraspasoStockDetalle_tipo_stock_inicial', to='movimiento_almacen.tipostock'),
        ),
    ]
