# Generated by Django 3.2.12 on 2023-01-13 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0030_auto_20230109_1149'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traslado_producto', '0025_auto_20230112_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidarSerieTraspasoStockDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieTraspasoStockDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.serie')),
                ('traspaso_stock_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieTraspasoStockDetalle_traspaso_stock_detalle', to='traslado_producto.traspasostockdetalle')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ValidarSerieTraspasoStockDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validar Series Traspaso Stock Detalle',
                'verbose_name_plural': 'Validar Series Traspasos Stock Detalle',
                'ordering': ['created_at'],
            },
        ),
    ]
