# Generated by Django 3.2.12 on 2023-01-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0026_validarserietraspasostockdetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traspasostockdetalle',
            name='traspaso_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TraspasoStockDetalle_traspaso_stock', to='traslado_producto.traspasostock'),
        ),
    ]
