# Generated by Django 3.2.12 on 2023-03-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0027_alter_traspasostockdetalle_traspaso_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validarserieenviotrasladoproductodetalle',
            name='envio_traslado_producto_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ValidarSerieEnvioTrasladoProductoDetalle_envio_traslado_producto_detalle', to='traslado_producto.enviotrasladoproductodetalle'),
        ),
    ]
