# Generated by Django 3.2.12 on 2023-03-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0028_alter_validarserieenviotrasladoproductodetalle_envio_traslado_producto_detalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recepciontrasladoproducto',
            options={'ordering': ['-numero_recepcion_traslado'], 'verbose_name': 'Recepcion Traslado Producto', 'verbose_name_plural': 'Recepcion Traslado Productos'},
        ),
    ]
