# Generated by Django 3.2.12 on 2023-08-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0030_alter_enviotrasladoproductodetalle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traspasostock',
            options={'ordering': ['estado', '-nro_traspaso'], 'verbose_name': 'Traspaso Stock', 'verbose_name_plural': 'Traspasos Stock'},
        ),
        migrations.AlterField(
            model_name='traspasostock',
            name='nro_traspaso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro. Traspaso'),
        ),
    ]
