# Generated by Django 3.2.12 on 2025-04-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_producto', '0031_auto_20230831_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviotrasladoproducto',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'EN PROCESO'), (2, 'TRASLADO ENVIADO'), (3, 'TRASLADO RECEPCIONADO'), (4, 'ANULADO'), (5, 'TRASLADO PARCIAL')], default=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='recepciontrasladoproducto',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'EN PROCESO'), (2, 'TRASLADO ENVIADO'), (3, 'TRASLADO RECEPCIONADO'), (4, 'ANULADO'), (5, 'TRASLADO PARCIAL')], default=1, null=True, verbose_name='Estado'),
        ),
    ]
