# Generated by Django 3.2.12 on 2022-04-27 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('tipo_documento', models.CharField(choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)')], max_length=1, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=15, verbose_name='Número de Documento')),
                ('motivo_visita', models.CharField(max_length=50, verbose_name='Motivo de Visita')),
                ('hora_ingreso', models.TimeField(auto_now_add=True, verbose_name='Hora de Ingreso')),
                ('hora_salida', models.TimeField(auto_now=True, verbose_name='Hora de Salida')),
                ('empresa_cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Visita_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Visita_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario_atendio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuario_Atendio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
    ]
