# Generated by Django 3.2.12 on 2022-04-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
    ]
