# Generated by Django 3.2.12 on 2022-05-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_alter_visita_hora_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
