# Generated by Django 3.2.12 on 2022-05-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_visita_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
