# Generated by Django 3.2.12 on 2022-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0004_alter_visita_fecha_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-fecha_registro', '-hora_ingreso', 'nombre'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AlterField(
            model_name='visita',
            name='tipo_documento',
            field=models.CharField(choices=[('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD')], max_length=1, verbose_name='Tipo de Documento'),
        ),
    ]
