# Generated by Django 3.2.12 on 2022-05-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0005_auto_20220503_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-hora_salida', '-fecha_registro', '-hora_ingreso', 'nombre'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
    ]
