# Generated by Django 3.2.12 on 2022-05-06 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0009_alter_tiporepresentantelegal_nombre'),
        ('recepcion', '0006_alter_visita_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.TimeField(auto_now_add=True, verbose_name='Hora de Ingreso')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Asistencia_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Asistencia_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Asistencia_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
