# Generated by Django 3.2.12 on 2022-05-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0007_asistencia'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha_registro'), name='Asistencia_usuario_fecha_registro'),
        ),
    ]
