# Generated by Django 3.2.12 on 2022-05-10 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0008_asistencia_asistencia_usuario_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso_cambio_ip', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ResponsableAsistencia_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ResponsableAsistencia_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario_a_registrar', models.ManyToManyField(related_name='ResponsableAsistencia_usuario_a_registrar', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios a Registrar')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ResponsableAsistencia_usuario_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'ResponsableAsistencia',
                'verbose_name_plural': 'ResponsableAsistencias',
            },
        ),
        migrations.CreateModel(
            name='IpPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='IpPublica_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='IpPublica_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IpPublica',
                'verbose_name_plural': 'IpPublicas',
            },
        ),
    ]
