# Generated by Django 3.2.12 on 2022-05-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0001_initial'),
        ('recepcion', '0009_ippublica_responsableasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippublica',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sede.sede'),
            preserve_default=False,
        ),
    ]
