# Generated by Django 3.2.12 on 2022-05-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0001_initial'),
        ('recepcion', '0010_ippublica_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sede.sede'),
            preserve_default=False,
        ),
    ]
