# Generated by Django 3.2.12 on 2022-05-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0011_asistencia_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='sede',
        ),
    ]
