# Generated by Django 3.2.12 on 2022-05-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0012_remove_asistencia_sede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-fecha_registro', '-hora_salida', '-hora_ingreso', 'nombre'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
    ]
