# Generated by Django 3.2.12 on 2022-05-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0013_asistencia_sede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-hora_ingreso', '-hora_salida'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
    ]
