# Generated by Django 3.2.12 on 2022-05-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0015_merge_20220516_1009'),
        ('recepcion', '0015_merge_20220516_1012'),
    ]

    operations = [
    ]
