# Generated by Django 3.2.12 on 2022-05-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0016_merge_20220516_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ippublica',
            options={'verbose_name': 'Ip Publica', 'verbose_name_plural': 'Ip Publicas'},
        ),
        migrations.AlterModelOptions(
            name='responsableasistencia',
            options={'verbose_name': 'Responsable Asistencia', 'verbose_name_plural': 'Responsable Asistencias'},
        ),
    ]
