# Generated by Django 3.2.12 on 2022-05-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0018_visita_sede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha_registro', '-hora_salida', '-hora_ingreso', 'usuario'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
    ]
