# Generated by Django 3.2.12 on 2022-05-21 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0002_auto_20220512_1812'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0019_alter_asistencia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Longitud')),
                ('latitud', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Latitud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='GeoLocalizacion_created_by', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sede.sede')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='GeoLocalizacion_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geo Localización',
                'verbose_name_plural': 'Geo Localizaciones',
            },
        ),
    ]
