# Generated by Django 3.2.12 on 2022-05-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0020_geolocalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocalizacion',
            name='distancia',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
