# Generated by Django 3.2.12 on 2022-05-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0021_geolocalizacion_distancia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpPublica',
        ),
    ]
