# Generated by Django 3.2.12 on 2022-05-31 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_remove_interlocutorcliente_tipo_interlocutor'),
        ('recepcion', '0022_delete_ippublica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='empresa_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Empresa Cliente'),
        ),
    ]
