# Generated by Django 3.2.12 on 2022-06-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_merge_0012_correocliente_0014_cliente_condicion_sunat'),
        ('recepcion', '0023_alter_visita_empresa_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='empresa_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Empresa Cliente'),
        ),
    ]
