# Generated by Django 3.2.12 on 2022-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0024_alter_visita_empresa_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='motivo_visita',
            field=models.CharField(max_length=100, verbose_name='Motivo de Visita'),
        ),
    ]
