# Generated by Django 3.2.12 on 2022-11-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0025_alter_visita_motivo_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
