# Generated by Django 3.2.12 on 2022-11-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0026_visita_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='empresa_cliente',
        ),
    ]
