# Generated by Django 3.2.12 on 2023-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0027_remove_visita_empresa_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='tipo_documento',
            field=models.CharField(choices=[('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('-', 'SIN DOCUMENTO')], max_length=1, verbose_name='Tipo de Documento'),
        ),
    ]
