# Generated by Django 3.2.12 on 2023-06-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0028_alter_visita_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='comentario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado_solicitud',
            field=models.IntegerField(blank=True, choices=[(1, 'SOLICITADO'), (2, 'APROBADO'), (3, 'RECHAZADO')], null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='justificacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Justificación'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='motivo_inasistencia',
            field=models.IntegerField(blank=True, choices=[(1, 'ASISTIO'), (2, 'FALTA'), (3, 'PERMISO'), (4, 'VACACIONES')], null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_ingreso',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Hora de Ingreso'),
        ),
    ]
