# Generated by Django 3.2.12 on 2023-06-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0029_auto_20230603_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='motivo_inasistencia',
            field=models.IntegerField(choices=[(1, 'ASISTIO'), (2, 'FALTA'), (3, 'PERMISO'), (4, 'VACACIONES')], default=1, verbose_name='Motivo'),
        ),
    ]
