# Generated by Django 3.2.12 on 2023-06-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0030_alter_asistencia_motivo_inasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='file/asistencia/archivo/', verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha_inasistencia',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Inasistencia'),
        ),
    ]
