# Generated by Django 3.2.12 on 2023-06-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0008_alter_sede_estado'),
        ('recepcion', '0031_auto_20230603_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha_inasistencia',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sede.sede'),
        ),
    ]
