# Generated by Django 3.2.12 on 2023-06-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0032_auto_20230605_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
