# Generated by Django 3.2.12 on 2023-06-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0033_alter_asistencia_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='editar_solcitud',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
