# Generated by Django 3.2.12 on 2023-07-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0033_alter_asistencia_fecha_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-fecha_registro', '-hora_salida', '-hora_ingreso', 'nombre'], 'permissions': [('aprobar_rechazar', 'Aprobar o Rechazar Justificaciones')], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
    ]
