# Generated by Django 3.2.12 on 2023-06-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0034_asistencia_editar_solcitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='editar_solcitud',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='editar_solicitud',
            field=models.BooleanField(default=False, verbose_name='Estado Solicitud'),
        ),
    ]
