# Generated by Django 3.2.12 on 2023-06-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0035_auto_20230619_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='editar_solicitud',
            field=models.BooleanField(default=False, verbose_name='Editar Solicitud'),
        ),
    ]
