# Generated by Django 3.2.12 on 2023-07-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0035_alter_visita_tipo_documento'),
        ('recepcion', '0036_alter_asistencia_editar_solicitud'),
    ]

    operations = [
    ]
