# Generated by Django 3.2.12 on 2025-02-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0037_merge_20230707_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='motivo_inasistencia',
            field=models.IntegerField(choices=[(1, 'ASISTIO'), (2, 'FALTA'), (3, 'PERMISO')], default=1, verbose_name='Motivo'),
        ),
    ]
