# Generated by Django 3.2.12 on 2022-08-10 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0034_auto_20220727_1501'),
        ('datos_globales', '0015_auto_20220601_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_venta', models.CharField(max_length=150, verbose_name='Descripción de Venta')),
                ('descripcion_corta', models.CharField(max_length=150, verbose_name='Descripción Corta')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso')),
                ('depreciacion', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Depreciación')),
                ('estado', models.IntegerField(choices=[('1', 'Activo'), ('2', 'Baja')], verbose_name='Estado Activo')),
                ('traduccion', models.CharField(max_length=255, verbose_name='Traducción')),
                ('partida', models.CharField(max_length=30, verbose_name='Partida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ActivoBase_created_by', to=settings.AUTH_USER_MODEL)),
                ('producto_sunat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.productosunat')),
                ('sub_familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.subfamilia')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ActivoBase_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ActivoBase',
                'verbose_name_plural': 'ActivosBase',
            },
        ),
    ]
