# Generated by Django 3.2.12 on 2022-08-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobase',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='activobase',
            name='partida',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='activobase',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='activobase',
            name='traduccion',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Traducción'),
        ),
    ]
