# Generated by Django 3.2.12 on 2022-08-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_auto_20220811_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobase',
            name='traduccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Traducción'),
        ),
    ]
