# Generated by Django 3.2.12 on 2022-08-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_alter_activobase_traduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobase',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso'),
        ),
    ]
