# Generated by Django 3.2.12 on 2022-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_alter_activobase_peso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activobase',
            options={'ordering': ['descripcion_corta'], 'verbose_name': 'ActivoBase', 'verbose_name_plural': 'ActivosBase'},
        ),
        migrations.AlterField(
            model_name='activobase',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado Activo'),
        ),
    ]
