# Generated by Django 3.2.12 on 2022-08-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_auto_20220811_1301'),
        ('activos', '0005_auto_20220811_1130'),
    ]

    operations = [
    ]
