# Generated by Django 3.2.12 on 2022-08-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_merge_0002_auto_20220811_1301_0005_auto_20220811_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobase',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado Activo'),
        ),
    ]
