# Generated by Django 3.2.12 on 2022-08-11 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_auto_20220811_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcaactivo',
            options={'ordering': ['nombre'], 'verbose_name': 'Marca Activo', 'verbose_name_plural': 'Marcas Activo'},
        ),
    ]
