# Generated by Django 3.2.12 on 2022-08-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_alter_marcaactivo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activobase',
            options={'ordering': ['descripcion_corta'], 'verbose_name': 'Activo Base', 'verbose_name_plural': 'Activos Base'},
        ),
        migrations.AlterModelOptions(
            name='familiaactivo',
            options={'ordering': ['nombre'], 'verbose_name': 'Familia Activo', 'verbose_name_plural': 'Familias Activo'},
        ),
        migrations.AlterModelOptions(
            name='modeloactivo',
            options={'ordering': ['nombre'], 'verbose_name': 'Modelo Activo', 'verbose_name_plural': 'Modelos Activo'},
        ),
        migrations.AlterModelOptions(
            name='subfamiliaactivo',
            options={'ordering': ['nombre'], 'verbose_name': 'SubFamilia Activo', 'verbose_name_plural': 'SubFamilias Activo'},
        ),
    ]
