# Generated by Django 3.2.12 on 2022-08-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_auto_20220811_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='activobase',
            name='vida_util',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vida Útil (meses)'),
        ),
    ]
