# Generated by Django 3.2.12 on 2022-08-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_activobase_vida_util'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobase',
            name='descripcion_venta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción de Venta'),
        ),
    ]
