# Generated by Django 3.2.12 on 2022-08-12 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos', '0012_alter_activobase_descripcion_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=25, verbose_name='Número de Serie')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('id_registro', models.IntegerField()),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('tiempo_garantia', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Garantía')),
                ('color', models.CharField(blank=True, max_length=25, null=True, verbose_name='Color')),
                ('informacion_adicional', models.TextField(blank=True, null=True, verbose_name='Información Adicional')),
                ('declarable', models.BooleanField(default=False, verbose_name='Declarable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('activo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activobase')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Activo_created_by', to=settings.AUTH_USER_MODEL)),
                ('marca_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.marcaactivo')),
                ('modelo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.modeloactivo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Activo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['numero_serie'],
            },
        ),
    ]
