# Generated by Django 3.2.12 on 2022-08-12 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0006_alter_datosusuario_tipo_documento'),
        ('activos', '0012_alter_activobase_descripcion_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha Asignación')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(verbose_name='Fecha Entrega')),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'ENTREGADO'), (3, 'CONCLUIDO SIN ENTREGAR'), (4, 'ANULADO')], default=1, verbose_name='Estado Asignación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.datosusuario')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AsignacionActivo_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AsignacionActivo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignacion Activo',
                'verbose_name_plural': 'Asignacion Activos',
            },
        ),
    ]
