# Generated by Django 3.2.12 on 2022-08-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_asignacionactivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionactivo',
            options={'verbose_name': 'Asignación de Activo', 'verbose_name_plural': 'Asignación de Activos'},
        ),
        migrations.AlterField(
            model_name='asignacionactivo',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Entrega'),
        ),
        migrations.CreateModel(
            name='AsignacionDetalleActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.activobase')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.asignacionactivo')),
            ],
            options={
                'verbose_name': 'Asignación Detalle del Activo',
                'verbose_name_plural': 'Asignación Detalle de Activos',
            },
        ),
    ]
