# Generated by Django 3.2.12 on 2022-08-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activo',
        ),
    ]
