# Generated by Django 3.2.12 on 2022-08-16 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos', '0015_auto_20220813_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciondetalleactivo',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AsignacionDetalleActivo_asignacion', to='activos.asignacionactivo'),
        ),
        migrations.CreateModel(
            name='ArchivoAsignacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.asignacionactivo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ArchivoAsignacionActivo_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ArchivoAsignacionActivo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Asignación de Activos',
                'verbose_name_plural': 'Archivos Asignación de Activos',
            },
        ),
    ]
