# Generated by Django 3.2.12 on 2022-08-13 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0020_sociedad_abreviatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sede', '0003_alter_sede_options'),
        ('activos', '0015_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activo',
            old_name='marca_id',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='activo',
            old_name='modelo_id',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='activo_id',
        ),
        migrations.AddField(
            model_name='activo',
            name='activo_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activobase', verbose_name='Activo Base'),
        ),
        migrations.CreateModel(
            name='ActivoSociedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ActivoSociedad_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ActivoSociedad_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activo Sociedad',
                'verbose_name_plural': 'Activos Sociedad',
                'ordering': ['activo'],
            },
        ),
        migrations.CreateModel(
            name='ActivoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ActivoLugar_created_by', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ActivoLugar_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activo Lugar',
                'verbose_name_plural': 'Activos Lugar',
                'ordering': ['activo'],
            },
        ),
    ]
