# Generated by Django 3.2.12 on 2022-08-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0016_auto_20220816_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciondetalleactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AsignacionDetalleActivo_activo', to='activos.activobase'),
        ),
    ]
