# Generated by Django 3.2.12 on 2022-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0017_auto_20220815_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
