# Generated by Django 3.2.12 on 2022-08-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0019_alter_activo_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tiempo_garantia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Garantía (meses)'),
        ),
    ]
