# Generated by Django 3.2.12 on 2022-08-15 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orden_compra', '0009_alter_ordencompra_orden_compra_anterior'),
        ('sociedad', '0020_sociedad_abreviatura'),
        ('datos_globales', '0015_auto_20220601_1956'),
        ('activos', '0020_alter_activo_tiempo_garantia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteCompraActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internacional_nacional', models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], default=1, verbose_name='Internacional-Nacional')),
                ('incoterms', models.IntegerField(blank=True, choices=[(1, 'EXW'), (2, 'FOB'), (3, 'FCA'), (4, 'CIF'), (5, 'DDP')], null=True, verbose_name='INCOTERMS')),
                ('tipo_comprobante', models.IntegerField(choices=[('1', 'FACTURA'), ('2', 'BOLETA')], default=1, verbose_name='Tipo de Comprobante')),
                ('numero_comprobante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Comprobante')),
                ('fecha_comprobante', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Comprobante')),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento Global')),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Descuento')),
                ('total_anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Anticipo')),
                ('total_gravada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gravada')),
                ('total_inafecta', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Inafecta')),
                ('total_exonerada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Exonerada')),
                ('total_igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total IGV')),
                ('total_gratuita', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gratuita')),
                ('total_otros_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Otros Cargos')),
                ('total_icbper', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total ICBPER')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones')),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación')),
                ('logistico', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Logístico')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ComprobanteCompraActivo_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_compra.ordencompra', verbose_name='Orden de Compra')),
                ('sociedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ComprobanteCompraActivo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comprobante Compra Activo',
                'verbose_name_plural': 'Comprobantes Compra Activo',
                'ordering': ['-fecha_comprobante'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteCompraActivoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('descripcion_comprobante', models.TextField(blank=True, null=True, verbose_name='Descripción Comprobante')),
                ('cantidad', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Unitario sin IGV')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Unitario con IGV')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Final con IGV')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sub Total')),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], null=True, verbose_name='Tipo de IGV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo')),
                ('comprobante_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.comprobantecompraactivo', verbose_name='Comprobante de Compra')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ComprobanteCompraActivoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('orden_compra_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orden_compra.ordencompradetalle', verbose_name='Orden de Compra Detalle')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ComprobanteCompraActivoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comprobante Compra Activo Detalle',
                'verbose_name_plural': 'Comprobantes Compra Activo Detalle',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoComprobanteCompraActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('comprobante_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.comprobantecompraactivo', verbose_name='Comprobante de Compra')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ArchivoComprobanteCompraActivo_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ArchivoComprobanteCompraActivo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Comprobante Compra Activo',
                'verbose_name_plural': 'Archivos Comprobante Compra Activo',
            },
        ),
    ]
