# Generated by Django 3.2.12 on 2022-08-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0021_archivocomprobantecompraactivo_comprobantecompraactivo_comprobantecompraactivodetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantecompraactivo',
            name='motivo_anulacion',
        ),
        migrations.RemoveField(
            model_name='comprobantecompraactivo',
            name='slug',
        ),
    ]
