# Generated by Django 3.2.12 on 2022-08-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0022_auto_20220816_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='fecha_comprobante',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Comprobante'),
        ),
    ]
