# Generated by Django 3.2.12 on 2022-08-16 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0009_alter_ordencompra_orden_compra_anterior'),
        ('activos', '0023_alter_comprobantecompraactivo_fecha_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='internacional_nacional',
            field=models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], verbose_name='Tipo de Compra'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='logistico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Logístico'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orden_compra.ordencompra', verbose_name='Orden de Compra'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[('1', 'FACTURA'), ('2', 'BOLETA')], verbose_name='Tipo de Comprobante'),
        ),
    ]
