# Generated by Django 3.2.12 on 2022-08-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0024_auto_20220816_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA')], verbose_name='Tipo de Comprobante'),
        ),
    ]
