# Generated by Django 3.2.12 on 2022-08-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0025_alter_comprobantecompraactivo_tipo_comprobante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivocomprobantecompraactivo',
            old_name='comprobante_compra',
            new_name='comprobante_compra_activo',
        ),
        migrations.RenameField(
            model_name='comprobantecompraactivodetalle',
            old_name='comprobante_compra',
            new_name='comprobante_compra_activo',
        ),
    ]
