# Generated by Django 3.2.12 on 2022-08-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0017_alter_asignaciondetalleactivo_activo'),
        ('activos', '0026_auto_20220817_1235'),
    ]

    operations = [
    ]
