# Generated by Django 3.2.12 on 2022-08-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0027_merge_20220817_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraactivodetalle',
            name='comprobante_compra_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComprobanteCompraActivoDetalle_comprobante_compra_activo', to='activos.comprobantecompraactivo', verbose_name='Comprobante de Compra'),
        ),
    ]
