# Generated by Django 3.2.12 on 2022-08-20 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0006_alter_datosusuario_tipo_documento'),
        ('activos', '0028_alter_asignaciondetalleactivo_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha Devolución')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'ENTREGADO'), (3, 'CONCLUIDO SIN ENTREGAR'), (4, 'ANULADO')], default=1, verbose_name='Estado Devolución')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.datosusuario')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionActivo_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionActivo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución de Activo',
                'verbose_name_plural': 'Devolución de Activos',
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.AlterModelOptions(
            name='asignacionactivo',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name': 'Asignación de Activo', 'verbose_name_plural': 'Asignación de Activos'},
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'EN PROCESO ASIGNACIÓN'), (3, 'ASIGNADO'), (4, 'EN PROCESO DEVOLUCIÓN'), (5, 'DEVUELTO')], default=1, verbose_name='Estado Activo'),
        ),
        migrations.CreateModel(
            name='DevolucionDetalleActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionDetalleActivo_activo', to='activos.activo')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionDetalleActivo_asignacion', to='activos.asignacionactivo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionActivoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionDetalleActivo_devolucion', to='activos.devolucionactivo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DevolucionActivoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución Detalle del Activo',
                'verbose_name_plural': 'Devolución Detalle de Activos',
            },
        ),
    ]
