# Generated by Django 3.2.12 on 2022-08-20 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos', '0028_alter_comprobantecompraactivodetalle_comprobante_compra_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inventario', models.DateField(blank=True, null=True, verbose_name='Fecha de Inventario')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('documento', models.FileField(blank=True, null=True, upload_to='', verbose_name='Doc. Inventario')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InventarioActivo_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InventarioActivo_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario Activo',
                'verbose_name_plural': 'Inventarios Activo',
            },
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='InventarioActivoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InventarioActivoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('inventario_activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.inventarioactivo', verbose_name='Inventario Activo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InventarioActivoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario Activo Detalle',
                'verbose_name_plural': 'Inventarios Activo Detalle',
            },
        ),
    ]
