# Generated by Django 3.2.12 on 2022-08-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0029_auto_20220820_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucionactivo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'RECEPCIONADO'), (3, 'ANULADO')], default=1, verbose_name='Estado Devolución'),
        ),
    ]
