# Generated by Django 3.2.12 on 2022-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0029_auto_20220820_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioactivodetalle',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
