# Generated by Django 3.2.12 on 2022-08-22 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos', '0030_alter_devolucionactivo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoDevolucionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ArchivodevolucionActivo_created_by', to=settings.AUTH_USER_MODEL)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.devolucionactivo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ArchivodevolucionActivo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Devolución de Activos',
                'verbose_name_plural': 'Archivos Devolución de Activos',
            },
        ),
    ]
