# Generated by Django 3.2.12 on 2022-08-22 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos', '0031_alter_inventarioactivo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioactivo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InventarioActivo_Usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
