# Generated by Django 3.2.12 on 2022-08-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0032_alter_inventarioactivo_usuario'),
        ('activos', '0032_auto_20220822_1521'),
    ]

    operations = [
    ]
