# Generated by Django 3.2.12 on 2022-08-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0033_merge_20220822_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'EN PROCESO ASIGNACIÓN'), (3, 'ASIGNADO'), (4, 'EN PROCESO DEVOLUCIÓN')], default=1, verbose_name='Estado Activo'),
        ),
    ]
