# Generated by Django 3.2.12 on 2022-08-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0034_alter_activo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activosociedad',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActivoSociedad_activo', to='activos.activo'),
        ),
    ]
