# Generated by Django 3.2.12 on 2022-08-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0034_alter_activo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondetalleactivo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO ASIGNACIÓN'), (2, 'ASIGNADO'), (3, 'DEVUELTO')], default=1, verbose_name='Estado Asignación'),
        ),
    ]
