# Generated by Django 3.2.12 on 2022-08-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0035_asignaciondetalleactivo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciondetalleactivo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO ASIGNACIÓN'), (2, 'ASIGNADO'), (3, 'DEVUELTO'), (4, 'CONCLUIDO SIN ENTREGAR'), (5, 'ANULADO')], default=1, verbose_name='Estado Asignación'),
        ),
    ]
