# Generated by Django 3.2.12 on 2022-08-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0035_alter_activosociedad_activo'),
        ('activos', '0036_alter_asignaciondetalleactivo_estado'),
    ]

    operations = [
    ]
