# Generated by Django 3.2.12 on 2022-08-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0037_merge_20220823_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activoubicacion',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActivoUbicacion_activo', to='activos.activo'),
        ),
        migrations.AlterField(
            model_name='inventarioactivodetalle',
            name='inventario_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.inventarioactivo', verbose_name='Inventario Activo'),
        ),
    ]
