# Generated by Django 3.2.12 on 2022-08-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0038_auto_20220827_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'ordering': ['descripcion'], 'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
        migrations.AlterModelOptions(
            name='inventarioactivodetalle',
            options={'ordering': ['activo'], 'verbose_name': 'Inventario Activo Detalle', 'verbose_name_plural': 'Inventarios Activo Detalle'},
        ),
        migrations.AlterField(
            model_name='inventarioactivo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'FINALIZADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inventarioactivodetalle',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Operativo'), (2, 'Extraviado'), (3, 'Malogrado')], default=1, verbose_name='Estado'),
        ),
    ]
