# Generated by Django 3.2.12 on 2022-08-31 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos', '0039_auto_20220829_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioactivo',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='inventarioactivo',
            name='observacion',
        ),
        migrations.AlterField(
            model_name='archivocomprobantecompraactivo',
            name='comprobante_compra_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.comprobantecompraactivo'),
        ),
        migrations.AlterField(
            model_name='inventarioactivodetalle',
            name='inventario_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InventarioActivoDetalle_inventario_activo', to='activos.inventarioactivo', verbose_name='Inventario Activo'),
        ),
        migrations.CreateModel(
            name='DocumentoInventarioActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('documento', models.FileField(blank=True, null=True, upload_to='', verbose_name='Doc. Inventario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DocumentoInventarioActivo_created_by', to=settings.AUTH_USER_MODEL)),
                ('inventario_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.inventarioactivo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DocumentoInventarioActivo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Inventario Activo',
                'verbose_name_plural': 'Documentos Inventario Activo',
            },
        ),
    ]
