# Generated by Django 3.2.12 on 2022-09-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0040_auto_20220831_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='activo_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activobase', verbose_name='Activo Base'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.marcaactivo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.modeloactivo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Número de Serie'),
        ),
    ]
