# Generated by Django 3.2.12 on 2022-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0041_auto_20220903_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='color',
            field=models.CharField(max_length=25, verbose_name='Color'),
        ),
    ]
