# Generated by Django 3.2.12 on 2022-09-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0042_alter_activo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tiempo_garantia',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiempo de Garantía (meses)'),
        ),
    ]
