# Generated by Django 3.2.12 on 2022-09-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0020_sociedad_abreviatura'),
        ('activos', '0043_alter_activo_tiempo_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='fecha_comprobante',
            field=models.DateField(verbose_name='Fecha de Comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='numero_comprobante',
            field=models.CharField(max_length=50, verbose_name='Número de Comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='sociedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad'),
        ),
    ]
