# Generated by Django 3.2.12 on 2022-09-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0015_auto_20220601_1956'),
        ('activos', '0044_auto_20220903_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.unidad'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activos.estadoactivo'),
        ),
    ]
