# Generated by Django 3.2.12 on 2022-09-12 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0045_auto_20220905_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activoubicacion',
            options={'ordering': ['fecha_ubicacion'], 'verbose_name': 'Activo Ubicacion', 'verbose_name_plural': 'Activos Ubicacion'},
        ),
        migrations.AddField(
            model_name='activoubicacion',
            name='fecha_ubicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Ubicación'),
            preserve_default=False,
        ),
    ]
