# Generated by Django 3.2.12 on 2022-09-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0046_auto_20220912_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activoubicacion',
            options={'ordering': ['-fecha_ubicacion'], 'verbose_name': 'Activo Ubicacion', 'verbose_name_plural': 'Activos Ubicacion'},
        ),
    ]
