# Generated by Django 3.2.12 on 2022-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0047_alter_activoubicacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobase',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
    ]
