# Generated by Django 3.2.12 on 2022-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0049_auto_20221005_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'NOTA DE CRÉDITO'), (4, 'NOTA DE DÉBITO')], verbose_name='Tipo de Comprobante'),
        ),
    ]
