# Generated by Django 3.2.12 on 2022-10-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0050_alter_comprobantecompraactivo_tipo_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'NOTA DE CRÉDITO'), (4, 'NOTA DE DÉBITO'), (7, 'GUÍA REMISIÓN REMITENTE')], verbose_name='Tipo de Comprobante'),
        ),
    ]
