# Generated by Django 3.2.12 on 2023-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0051_alter_comprobantecompraactivo_tipo_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobase',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
    ]
