# Generated by Django 3.2.12 on 2023-04-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0053_merge_0052_auto_20230401_1229_0052_auto_20230401_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobase',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
    ]
