# Generated by Django 3.2.12 on 2024-03-07 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0054_auto_20230411_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.estadoactivo'),
        ),
    ]
