# Generated by Django 3.2.12 on 2024-04-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0056_alter_activo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.marcaactivo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.modeloactivo'),
        ),
        migrations.AlterField(
            model_name='subfamiliaactivo',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SubFamiliaActivo_familia', to='activos.familiaactivo'),
        ),
    ]
