# Generated by Django 3.2.12 on 2024-07-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0057_auto_20240416_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activobase',
            name='descripcion_venta',
        ),
        migrations.RemoveField(
            model_name='activobase',
            name='peso',
        ),
    ]
