# Generated by Django 3.2.12 on 2025-01-07 17:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0058_auto_20240704_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraactivodetalle',
            name='precio_final_con_igv',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=14, verbose_name='Precio Final con IGV'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivodetalle',
            name='precio_unitario_con_igv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Precio Unitario con IGV'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivodetalle',
            name='precio_unitario_sin_igv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Precio Unitario sin IGV'),
        ),
    ]
