# Generated by Django 3.2.12 on 2025-01-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0059_auto_20250107_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantecompraactivo',
            name='orden_compra',
        ),
        migrations.RemoveField(
            model_name='comprobantecompraactivodetalle',
            name='orden_compra_detalle',
        ),
    ]
