# Generated by Django 3.2.12 on 2025-01-08 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0060_auto_20250107_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='comprobante_compra_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.comprobantecompraactivo'),
        ),
    ]
