# Generated by Django 3.2.12 on 2025-01-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0061_activo_comprobante_compra_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='comprobante_compra_activo',
        ),
    ]
