# Generated by Django 3.2.12 on 2025-01-09 21:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0062_remove_activo_comprobante_compra_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionactivo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Asignación de Activo', 'verbose_name_plural': 'Asignación de Activos'},
        ),
        migrations.RemoveField(
            model_name='asignacionactivo',
            name='fecha_asignacion',
        ),
        migrations.RemoveField(
            model_name='asignacionactivo',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='asignacionactivo',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'REGISTRADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivodetalle',
            name='descripcion_comprobante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivodetalle',
            name='precio_unitario_sin_igv',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=14, verbose_name='Precio Unitario sin IGV'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraactivodetalle',
            name='tipo_igv',
            field=models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], default=1, null=True, verbose_name='Tipo de IGV'),
        ),
    ]
