# Generated by Django 3.2.12 on 2025-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0063_auto_20250109_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactivo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Asignación'),
        ),
        migrations.AddField(
            model_name='asignacionactivo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Asignación'),
        ),
    ]
