# Generated by Django 3.2.12 on 2025-01-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0064_auto_20250109_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionactivo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Asignación de Activo', 'verbose_name_plural': 'Asignación de Activos'},
        ),
        migrations.AddField(
            model_name='asignaciondetalleactivo',
            name='condicion_devolucion',
            field=models.IntegerField(blank=True, choices=[(1, 'NUEVO'), (2, 'USADO - BUEN ESTADO'), (3, 'USADO - CON DETALLES'), (4, 'DAÑADO')], null=True, verbose_name='Condición de Devolución'),
        ),
        migrations.AddField(
            model_name='asignaciondetalleactivo',
            name='condicion_entrega',
            field=models.IntegerField(choices=[(1, 'NUEVO'), (2, 'USADO - BUEN ESTADO'), (3, 'USADO - CON DETALLES'), (4, 'DAÑADO')], default=1, verbose_name='Condición de Entrega'),
        ),
        migrations.AddField(
            model_name='asignaciondetalleactivo',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Entrega'),
        ),
        migrations.AddField(
            model_name='asignaciondetalleactivo',
            name='observaciones_devolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignaciondetalleactivo',
            name='observaciones_entrega',
            field=models.TextField(blank=True, null=True),
        ),
    ]
