# Generated by Django 3.2.12 on 2025-01-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0065_auto_20250109_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activobase',
            name='depreciacion',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Depreciación'),
        ),
    ]
