# Generated by Django 3.2.12 on 2025-01-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0066_alter_activobase_depreciacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaciondetalleactivo',
            name='estado',
        ),
    ]
