# Generated by Django 3.2.12 on 2022-08-15 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('datos_globales', '0015_auto_20220601_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioListaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro_producto', models.IntegerField()),
                ('id_registro_documento', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio de compra')),
                ('precio_lista', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio de lista')),
                ('precio_sin_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio sin igv')),
                ('logistico', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Logistico')),
                ('margen_venta', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Margen de venta')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PrecioListaMaterial_content_type_documento', to='contenttypes.contenttype')),
                ('content_type_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PrecioListaMaterial_content_type_producto', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='PrecioListaMaterial_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='PrecioListaMaterial_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PrecioListaMateriales',
                'verbose_name_plural': 'PrecioListaMateriales',
            },
        ),
    ]
