# Generated by Django 3.2.12 on 2022-08-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('datos_globales', '0015_auto_20220601_1956'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sociedad', '0020_sociedad_abreviatura'),
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionTerminosCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.TextField()),
                ('condicion_visible', models.BooleanField()),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cotizacion Terminos Condiciones',
                'verbose_name_plural': 'Cotizaciones Terminos Condiciones',
            },
        ),
        migrations.CreateModel(
            name='CotizacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(max_length=50, verbose_name='Número de Cotización')),
                ('fecha_cotizacion', models.DateField(verbose_name='Fecha Cotización')),
                ('fecha_validez', models.DateField(verbose_name='Fecha Validez')),
                ('observaciones_adicionales', models.TextField()),
                ('condiciones_pago', models.TextField()),
                ('tipo_venta', models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CONTADO')], default=1, verbose_name='Tipo de Venta')),
                ('descuento_global', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Descuento global')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total')),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'RESERVADO'), (3, 'CONFIRMADO'), (4, 'VENCIDO'), (5, 'SIN CONFIRMAR'), (6, 'DE BAJA')])),
                ('motivo_anualacion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CotizacionVenta_cliente', to='clientes.cliente')),
                ('cliente_interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CotizacionVenta_cliente_interlocutor', to='clientes.clienteinterlocutor')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('tipo_cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CotizacionVenta_tipo_cambio', to='datos_globales.tipocambio')),
            ],
            options={
                'verbose_name': 'Cotizacion Venta',
                'verbose_name_plural': 'Cotizaciones Venta',
            },
        ),
        migrations.CreateModel(
            name='ReservaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(max_length=50, verbose_name='Núero de cotización')),
                ('fecha_cotizacion', models.DateField(verbose_name='Fecha Cotización')),
                ('fecha_confirmacion', models.DateField(verbose_name='Fecha Confirmación')),
                ('observaciones_adicionales', models.TextField()),
                ('condiciones_pago', models.TextField()),
                ('tipo_venta', models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CONTADO')], default=1, verbose_name='Tipo de Venta')),
                ('descuento_global', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Descuento global')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')])),
                ('motivo_anualacion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReservaVenta_cliente', to='clientes.cliente')),
                ('cliente_interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReservaVenta_cliente_interlocutor', to='clientes.clienteinterlocutor')),
                ('cotizacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.cotizacionventa')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('tipo_cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReservaVenta_tipo_cambio', to='datos_globales.tipocambio')),
            ],
            options={
                'verbose_name': 'Reserva Venta',
                'verbose_name_plural': 'Reservas Venta',
            },
        ),
        migrations.AlterModelOptions(
            name='preciolistamaterial',
            options={'verbose_name': 'Precio Lista Materiales', 'verbose_name_plural': 'Precio Lista Materiales'},
        ),
        migrations.CreateModel(
            name='ReservaVentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField()),
                ('item', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Precio unitario sin IGV')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Precio unitario con IGV')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Precio final con IGV')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Sub Total')),
                ('igv', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='IGV')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], verbose_name='Tipo IGV')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('reserva_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.reservaventa')),
            ],
            options={
                'verbose_name': 'Reserva Venta Detalle',
                'verbose_name_plural': 'Reservas Venta Detalle',
            },
        ),
        migrations.CreateModel(
            name='CotizacionVentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField()),
                ('item', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Precio unitario sin IGV')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Precio unitario con IGV')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Precio final con IGV')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Sub Total')),
                ('igv', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='IGV')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], verbose_name='Tipo IGV')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('cotizacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.cotizacionventa')),
            ],
            options={
                'verbose_name': 'Cotizacion Venta Detalle',
                'verbose_name_plural': 'Cotizaciones Venta Detalle',
            },
        ),
        migrations.CreateModel(
            name='CotizacionOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.TextField()),
                ('fecha_orden', models.DateField(verbose_name='Fecha Orden')),
                ('documento', models.FileField(upload_to=None, verbose_name='Documento')),
                ('cotizacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizacion.cotizacionventa')),
            ],
            options={
                'verbose_name': 'Cotizacion Orden Compra',
                'verbose_name_plural': 'Cotizaciones Orden Compra',
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(max_length=50, verbose_name='Número de Cotización')),
                ('fecha_cotizacion', models.DateField(verbose_name='Fecha Cotización')),
                ('fecha_validez', models.DateField(verbose_name='Fecha Validez')),
                ('observaciones_adicionales', models.TextField()),
                ('condiciones_pago', models.TextField()),
                ('tipo_venta', models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CONTADO')], default=1, verbose_name='Tipo de Venta')),
                ('descuento_global', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Descuento global')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total')),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'RESERVADO'), (3, 'CONFIRMADO'), (4, 'VENCIDO'), (5, 'SIN CONFIRMAR'), (6, 'DE BAJA')])),
                ('motivo_anualacion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ConfirmacionVenta_cliente', to='clientes.cliente')),
                ('cotizacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.cotizacionventa')),
                ('reserva_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cotizacion.reservaventa')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('tipo_cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ConfirmacionVenta_tipo_cambio', to='datos_globales.tipocambio')),
            ],
            options={
                'verbose_name': 'Confirmación Venta',
                'verbose_name_plural': 'Confirmación Ventas',
            },
        ),
    ]
