# Generated by Django 3.2.12 on 2022-08-19 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0002_auto_20220819_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacionventa',
            old_name='motivo_anualacion',
            new_name='motivo_anulacion',
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ConfirmacionVenta_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ConfirmacionVenta_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionordencompra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacionordencompra',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionOrdenCompra_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionordencompra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='cotizacionordencompra',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionOrdenCompra_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionterminoscondiciones',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacionterminoscondiciones',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionTerminosCondiciones_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionterminoscondiciones',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='cotizacionterminoscondiciones',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionTerminosCondiciones_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionVenta_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionVenta_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionventadetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacionventadetalle',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionVentaDetalle_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionventadetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='cotizacionventadetalle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionVentaDetalle_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaventa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaventa',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReservaVenta_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaventa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='reservaventa',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReservaVenta_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaventadetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaventadetalle',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReservaVentaDetalle_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaventadetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='reservaventadetalle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReservaVentaDetalle_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
