# Generated by Django 3.2.12 on 2022-08-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_auto_20220819_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionventa',
            name='tipo_venta',
            field=models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CREDITO')], default=1, verbose_name='Tipo de Venta'),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='tipo_venta',
            field=models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CREDITO')], default=1, verbose_name='Tipo de Venta'),
        ),
        migrations.AlterField(
            model_name='reservaventa',
            name='tipo_venta',
            field=models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CREDITO')], default=1, verbose_name='Tipo de Venta'),
        ),
    ]
