# Generated by Django 3.2.12 on 2022-09-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cotizacion', '0004_auto_20220819_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciolistamaterial',
            name='content_type_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PrecioListaMaterial_content_type_documento', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='preciolistamaterial',
            name='id_registro_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
