# Generated by Django 3.2.12 on 2022-09-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0020_sociedad_abreviatura'),
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('datos_globales', '0015_auto_20220601_1956'),
        ('cotizacion', '0004_auto_20220819_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionventa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CotizacionVenta_cliente', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='cliente_interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CotizacionVenta_cliente_interlocutor', to='clientes.clienteinterlocutor'),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='condiciones_pago',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento global'),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'RESERVADO'), (3, 'CONFIRMADO'), (4, 'VENCIDO'), (5, 'SIN CONFIRMAR'), (6, 'DE BAJA')], default=1),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='fecha_cotizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cotización'),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='fecha_validez',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Validez'),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cotización'),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='tipo_cambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CotizacionVenta_tipo_cambio', to='datos_globales.tipocambio'),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total'),
        ),
    ]
