# Generated by Django 3.2.12 on 2022-09-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0005_auto_20220901_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preciolistamaterial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Precio Lista Materiales', 'verbose_name_plural': 'Precio Lista Materiales'},
        ),
    ]
