# Generated by Django 3.2.12 on 2022-09-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('cotizacion', '0005_auto_20220901_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionventa',
            name='cliente_interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CotizacionVenta_cliente_interlocutor', to='clientes.interlocutorcliente'),
        ),
        migrations.AlterField(
            model_name='reservaventa',
            name='cliente_interlocutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReservaVenta_cliente_interlocutor', to='clientes.interlocutorcliente'),
        ),
    ]
