# Generated by Django 3.2.12 on 2022-09-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_auto_20220902_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='cotizacion_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CotizacionVentaDetalle_cotizacion_venta', to='cotizacion.cotizacionventa'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
