# Generated by Django 3.2.12 on 2022-09-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0007_auto_20220902_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='item',
            field=models.IntegerField(),
        ),
    ]
