# Generated by Django 3.2.12 on 2022-09-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0008_auto_20220902_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='igv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='IGV'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='precio_final_con_igv',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Precio final con IGV'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='precio_unitario_con_igv',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Precio unitario con IGV'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='precio_unitario_sin_igv',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Precio unitario sin IGV'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='tipo_igv',
            field=models.IntegerField(blank=True, choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], null=True, verbose_name='Tipo IGV'),
        ),
    ]
