# Generated by Django 3.2.12 on 2022-09-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0009_auto_20220902_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionventadetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IGV'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='precio_final_con_igv',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio final con IGV'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='precio_unitario_con_igv',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio unitario con IGV'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='precio_unitario_sin_igv',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio unitario sin IGV'),
        ),
        migrations.AlterField(
            model_name='cotizacionventadetalle',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sub Total'),
        ),
    ]
