# Generated by Django 3.2.12 on 2022-09-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_alter_preciolistamaterial_options'),
        ('cotizacion', '0011_alter_cotizacionventadetalle_tipo_igv'),
    ]

    operations = [
    ]
