# Generated by Django 3.2.12 on 2022-09-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0012_merge_20220903_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'RESERVADO'), (4, 'CONFIRMADO'), (5, 'VENCIDO'), (6, 'SIN CONFIRMAR'), (7, 'DE BAJA')]),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'RESERVADO'), (4, 'CONFIRMADO'), (5, 'VENCIDO'), (6, 'SIN CONFIRMAR'), (7, 'DE BAJA')], default=1),
        ),
    ]
