# Generated by Django 3.2.12 on 2022-09-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0020_sociedad_abreviatura'),
        ('cotizacion', '0013_auto_20220903_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionSociedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Cantidad')),
                ('cotizacion_venta_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.cotizacionventadetalle')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
            ],
            options={
                'verbose_name': 'Cotizacion Sociedad',
                'verbose_name_plural': 'Cotizacion Sociedades',
            },
        ),
    ]
