# Generated by Django 3.2.12 on 2022-09-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0015_auto_20220905_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionsociedad',
            name='cotizacion_venta_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CotizacionSociedad_cotizacion_venta_detalle', to='cotizacion.cotizacionventadetalle'),
        ),
    ]
