# Generated by Django 3.2.12 on 2022-09-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0016_alter_cotizacionsociedad_cotizacion_venta_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacionventa',
            name='sociedad',
        ),
    ]
