# Generated by Django 3.2.12 on 2022-09-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0017_remove_cotizacionventa_sociedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionventa',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Número de Cotización'),
        ),
    ]
