# Generated by Django 3.2.12 on 2022-09-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0018_alter_cotizacionventa_numero_cotizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacionventa',
            options={'ordering': ['-fecha_cotizacion', '-numero_cotizacion'], 'verbose_name': 'Cotizacion Venta', 'verbose_name_plural': 'Cotizaciones Venta'},
        ),
        migrations.AlterModelOptions(
            name='cotizacionventadetalle',
            options={'ordering': ['item'], 'verbose_name': 'Cotizacion Venta Detalle', 'verbose_name_plural': 'Cotizaciones Venta Detalle'},
        ),
    ]
