# Generated by Django 3.2.12 on 2022-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0019_auto_20220907_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionventa',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
