# Generated by Django 3.2.12 on 2022-09-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0019_auto_20220907_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaventadetalle',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reservaventadetalle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reservaventadetalle',
            name='reserva_venta',
        ),
        migrations.RemoveField(
            model_name='reservaventadetalle',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='reserva_venta',
        ),
        migrations.DeleteModel(
            name='ReservaVenta',
        ),
        migrations.DeleteModel(
            name='ReservaVentaDetalle',
        ),
    ]
