# Generated by Django 3.2.12 on 2022-09-07 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0020_auto_20220907_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmacionventa',
            options={'ordering': ['-fecha_confirmacion'], 'verbose_name': 'Confirmación Venta', 'verbose_name_plural': 'Confirmación Ventas'},
        ),
        migrations.RenameField(
            model_name='confirmacionventa',
            old_name='condiciones_pago',
            new_name='motivo_anulacion',
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='descuento_global',
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='fecha_cotizacion',
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='fecha_validez',
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='motivo_anualacion',
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='numero_cotizacion',
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='observaciones_adicionales',
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='tipo_venta',
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='total',
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='fecha_confirmacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Confirmación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'RESERVADO'), (4, 'CONFIRMADO'), (5, 'CONFIRMADO'), (6, 'FINALIZADO'), (7, 'VENCIDO'), (8, 'DE BAJA')]),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'RESERVADO'), (4, 'CONFIRMADO'), (5, 'CONFIRMADO'), (6, 'FINALIZADO'), (7, 'VENCIDO'), (8, 'DE BAJA')], default=1),
        ),
    ]
