# Generated by Django 3.2.12 on 2022-09-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0021_auto_20220907_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionVentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_confirmada', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad confirmada')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('confirmacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ConfirmacionVentaDetalle_confirmacion_venta', to='cotizacion.confirmacionventa')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ConfirmacionVentaDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ConfirmacionVentaDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confirmación Venta Detalle',
                'verbose_name_plural': 'Confirmación Ventas Detalle',
                'ordering': ['confirmacion_venta', 'item'],
            },
        ),
    ]
