# Generated by Django 3.2.12 on 2022-09-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0020_cotizacionventa_slug'),
        ('cotizacion', '0022_confirmacionventadetalle'),
    ]

    operations = [
    ]
