# Generated by Django 3.2.12 on 2022-09-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0023_merge_20220908_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacionterminoscondiciones',
            options={'ordering': ['orden'], 'verbose_name': 'Cotizacion Terminos Condiciones', 'verbose_name_plural': 'Cotizaciones Terminos Condiciones'},
        ),
    ]
