# Generated by Django 3.2.12 on 2022-09-09 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0020_sociedad_abreviatura'),
        ('cotizacion', '0024_alter_cotizacionterminoscondiciones_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionDescuentoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento Global')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cotizacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CotizacionDescuentoGlobal_cotizacion_venta', to='cotizacion.cotizacionventa')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionDescuentoGlobal_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionDescuentoGlobal_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotizacion Descuento Global',
                'verbose_name_plural': 'Cotizacion Descuento Globales',
            },
        ),
    ]
