# Generated by Django 3.2.12 on 2022-09-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0025_cotizaciondescuentoglobal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacionventa',
            name='descuento_global',
        ),
    ]
