# Generated by Django 3.2.12 on 2022-09-09 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0020_sociedad_abreviatura'),
        ('cotizacion', '0026_remove_cotizacionventa_descuento_global'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacionventa',
            name='condiciones_pago',
        ),
        migrations.RemoveField(
            model_name='cotizacionventa',
            name='observaciones_adicionales',
        ),
        migrations.RemoveField(
            model_name='cotizacionventa',
            name='tipo_cambio',
        ),
        migrations.RemoveField(
            model_name='cotizacionventa',
            name='tipo_venta',
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='condiciones_pago',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='tipo_venta',
            field=models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CREDITO')], default=1, verbose_name='Tipo de Venta'),
        ),
        migrations.CreateModel(
            name='CotizacionObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cotizacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CotizacionObservacion_cotizacion_venta', to='cotizacion.cotizacionventa')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionObservacion_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CotizacionObservacion_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotizacion Observación',
                'verbose_name_plural': 'Cotizacion Observaciones',
            },
        ),
    ]
