# Generated by Django 3.2.12 on 2022-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0027_auto_20220909_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizaciondescuentoglobal',
            options={'ordering': ['sociedad'], 'verbose_name': 'Cotizacion Descuento Global', 'verbose_name_plural': 'Cotizacion Descuento Globales'},
        ),
        migrations.AlterModelOptions(
            name='cotizacionobservacion',
            options={'ordering': ['sociedad'], 'verbose_name': 'Cotizacion Observación', 'verbose_name_plural': 'Cotizacion Observaciones'},
        ),
        migrations.AlterModelOptions(
            name='cotizacionsociedad',
            options={'ordering': ['sociedad'], 'verbose_name': 'Cotizacion Sociedad', 'verbose_name_plural': 'Cotizacion Sociedades'},
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='confirmacionventadetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='confirmacionventadetalle',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IGV'),
        ),
        migrations.AddField(
            model_name='confirmacionventadetalle',
            name='precio_final_con_igv',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio final con IGV'),
        ),
        migrations.AddField(
            model_name='confirmacionventadetalle',
            name='precio_unitario_con_igv',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio unitario con IGV'),
        ),
        migrations.AddField(
            model_name='confirmacionventadetalle',
            name='precio_unitario_sin_igv',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio unitario sin IGV'),
        ),
        migrations.AddField(
            model_name='confirmacionventadetalle',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sub Total'),
        ),
        migrations.AddField(
            model_name='confirmacionventadetalle',
            name='tipo_igv',
            field=models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], default=1, verbose_name='Tipo IGV'),
        ),
        migrations.AddField(
            model_name='confirmacionventadetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total'),
        ),
    ]
