# Generated by Django 3.2.12 on 2022-09-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0028_auto_20220910_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionventa',
            name='fecha_confirmacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha Confirmación'),
        ),
    ]
