# Generated by Django 3.2.12 on 2022-09-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0029_alter_confirmacionventa_fecha_confirmacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmacionventa',
            options={'ordering': ['-created_at'], 'verbose_name': 'Confirmación Venta', 'verbose_name_plural': 'Confirmación Ventas'},
        ),
        migrations.RemoveField(
            model_name='confirmacionventa',
            name='fecha_confirmacion',
        ),
    ]
