# Generated by Django 3.2.12 on 2022-09-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0030_auto_20220910_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'RESERVADO'), (4, 'CONFIRMADO'), (5, 'CONFIRMADO'), (6, 'FINALIZADO'), (7, 'VENCIDO'), (8, 'DE BAJA')], default=1),
        ),
        migrations.AlterField(
            model_name='confirmacionventa',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
