# Generated by Django 3.2.12 on 2022-09-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0031_auto_20220910_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionventa',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento Global'),
        ),
    ]
