# Generated by Django 3.2.12 on 2022-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0032_confirmacionventa_descuento_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionventa',
            name='condiciones_pago',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Condiciones de Pago'),
        ),
        migrations.AlterField(
            model_name='confirmacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'FINALIZADO'), (3, 'DE BAJA')], default=1),
        ),
    ]
