# Generated by Django 3.2.12 on 2022-09-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0018_auto_20220909_1041'),
        ('cotizacion', '0033_auto_20220912_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionventa',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda'),
        ),
    ]
