# Generated by Django 3.2.12 on 2022-09-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0036_confirmacionventadetalle_otros_cargos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacionventadetalle',
            name='otros_cargos',
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='otros_cargos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Otros cargos'),
        ),
    ]
