# Generated by Django 3.2.12 on 2022-09-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0037_auto_20220912_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionventadetalle',
            name='tiempo_entrega',
            field=models.IntegerField(default=0),
        ),
    ]
