# Generated by Django 3.2.12 on 2022-09-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0038_cotizacionventadetalle_tiempo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'FINALIZADO'), (3, 'ANULADO')], default=1),
        ),
        migrations.AlterField(
            model_name='cotizacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'RESERVADO'), (4, 'CONFIRMADO'), (5, 'CONFIRMADO'), (6, 'CONFIRMADO ANTICIPADO'), (7, 'FINALIZADO'), (8, 'VENCIDO'), (9, 'ANULADO')], default=1),
        ),
    ]
