# Generated by Django 3.2.12 on 2022-09-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('cotizacion', '0039_auto_20220915_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionventa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ConfirmacionVenta_cliente', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='cliente_interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ConfirmacionVenta_cliente_interlocutor', to='clientes.interlocutorcliente'),
        ),
    ]
