# Generated by Django 3.2.12 on 2022-09-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0040_auto_20220916_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionventa',
            name='cotizacion_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ConfirmacionVenta_cotizacion_venta', to='cotizacion.cotizacionventa'),
        ),
    ]
