# Generated by Django 3.2.12 on 2022-09-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0021_auto_20220916_1630'),
        ('cotizacion', '0041_alter_confirmacionventa_cotizacion_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionventa',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda'),
        ),
    ]
