# Generated by Django 3.2.12 on 2022-09-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0039_auto_20220915_1705'),
        ('cotizacion', '0041_alter_confirmacionventa_cotizacion_venta'),
    ]

    operations = [
    ]
