# Generated by Django 3.2.12 on 2022-09-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0042_confirmacionventa_moneda'),
        ('cotizacion', '0042_merge_20220921_1013'),
    ]

    operations = [
    ]
