# Generated by Django 3.2.12 on 2022-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0043_merge_20220921_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionventa',
            name='numero_cotizacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Cotización'),
        ),
    ]
