# Generated by Django 3.2.12 on 2022-10-04 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0045_alter_preciolistamaterial_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionVentaCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dias_pago', models.IntegerField(blank=True, null=True, verbose_name='Días de pago')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('dias_calculo', models.IntegerField(blank=True, null=True, verbose_name='Días de calculo')),
                ('fecha_calculo', models.DateField(blank=True, null=True, verbose_name='Fecha de calculo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('confirmacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ConfirmacionVentaCuota_confirmacion_venta', to='cotizacion.confirmacionventa')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ConfirmacionVentaCuota_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ConfirmacionVentaCuota_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Credito Cuota',
                'verbose_name_plural': 'Solicitud de Credito Cuotas',
                'ordering': ['confirmacion_venta', 'fecha_calculo'],
            },
        ),
    ]
