# Generated by Django 3.2.12 on 2022-10-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0046_confirmacionventacuota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmacionventacuota',
            options={'ordering': ['confirmacion_venta', 'dias_calculo'], 'verbose_name': 'Confirmación Venta Cuota', 'verbose_name_plural': 'Confirmación Venta Cuotas'},
        ),
        migrations.RemoveField(
            model_name='confirmacionventacuota',
            name='fecha_calculo',
        ),
    ]
