# Generated by Django 3.2.12 on 2022-10-05 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0047_auto_20221004_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.TextField()),
                ('fecha_orden', models.DateField(verbose_name='Fecha Orden')),
                ('documento', models.FileField(upload_to=None, verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('confirmacion_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ConfirmacionOrdenCompra_confirmacion_venta', to='cotizacion.confirmacionventa')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ConfirmacionOrdenCompra_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ConfirmacionOrdenCompra_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confirmacion Orden Compra',
                'verbose_name_plural': 'Confirmaciones Orden Compra',
            },
        ),
        migrations.AlterField(
            model_name='preciolistamaterial',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='CotizacionOrdenCompra',
        ),
    ]
