# Generated by Django 3.2.12 on 2022-10-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0048_auto_20221005_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionventa',
            name='sunat_transaction',
            field=models.IntegerField(choices=[(1, 'VENTA INTERNA'), (2, 'EXPORTACIÓN'), (4, 'VENTA INTERNA - ANTICIPOS'), (29, 'VENTAS NO DOMICILIADOS QUE NO CALIFICAN COMO EXPORTACIÓN.'), (30, 'OPERACIÓN SUJETA A DETRACCIÓN.'), (33, 'DETRACCIÓN - SERVICIOS DE TRANSPORTE CARGA '), (34, 'OPERACIÓN SUJETA A PERCEPCIÓN'), (32, 'DETRACCIÓN - SERVICIOS DE TRANSPORTE DE PASAJEROS.'), (31, 'DETRACCIÓN - RECURSOS HIDROBIOLÓGICOS')], default=1),
        ),
    ]
