# Generated by Django 3.2.12 on 2022-10-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0050_auto_20221005_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionventa',
            name='total_anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Anticipo'),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='total_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Descuento'),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='total_exonerada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Exonerada'),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='total_gratuita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gratuita'),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='total_gravada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gravada'),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='total_igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total IGV'),
        ),
        migrations.AddField(
            model_name='confirmacionventa',
            name='total_inafecta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Inafecta'),
        ),
    ]
