# Generated by Django 3.2.12 on 2022-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0051_auto_20221005_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionordencompra',
            name='numero_orden',
            field=models.CharField(max_length=100, verbose_name='Número de Orden'),
        ),
    ]
