# Generated by Django 3.2.12 on 2022-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0052_alter_confirmacionordencompra_numero_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionordencompra',
            name='documento',
            field=models.FileField(upload_to='confirmacion_venta/orden_compra/', verbose_name='Documento'),
        ),
    ]
