# Generated by Django 3.2.12 on 2022-10-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0053_alter_confirmacionordencompra_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'RESERVADO'), (4, 'CONFIRMADO'), (5, 'CONFIRMADO'), (6, 'CONFIRMADO ANTICIPADO'), (7, 'FINALIZADO'), (8, 'VENCIDO'), (9, 'ANULADO'), (10, 'BORRADOR PRÉSTAMO'), (11, 'PRÉSTAMO'), (12, 'CONFIRMADO')], default=1),
        ),
    ]
