# Generated by Django 3.2.12 on 2022-10-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0054_alter_cotizacionventa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionventa',
            name='condiciones_pago',
            field=models.CharField(blank=True, help_text='Factura a 30 días', max_length=50, null=True, verbose_name='Condiciones de Pago'),
        ),
    ]
