# Generated by Django 3.2.12 on 2022-11-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0055_alter_confirmacionventa_condiciones_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionordencompra',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='confirmacion_venta/orden_compra/', verbose_name='Documento'),
        ),
    ]
