# Generated by Django 3.2.12 on 2022-11-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0056_alter_confirmacionordencompra_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacionventadetalle',
            options={'ordering': ['cotizacion_venta', 'item'], 'verbose_name': 'Cotizacion Venta Detalle', 'verbose_name_plural': 'Cotizaciones Venta Detalle'},
        ),
    ]
