# Generated by Django 3.2.12 on 2022-12-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0057_alter_cotizacionventadetalle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionordencompra',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='file/confirmacion_venta/orden_compra/', verbose_name='Documento'),
        ),
    ]
