# Generated by Django 3.2.12 on 2022-12-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0059_cotizacionventa_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'CON COMPROBANTE DE VENTA'), (3, 'ANULADO')], default=1),
        ),
    ]
