# Generated by Django 3.2.12 on 2023-01-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0060_alter_confirmacionventa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionventa',
            name='observacion_adicional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
