# Generated by Django 3.2.12 on 2023-01-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0061_confirmacionventa_observacion_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'CON COMPROBANTE DE VENTA'), (3, 'ANULADO'), (4, 'DESPACHO COMPLETO'), (5, 'DESPACHO COMPLETO SIN COMPROBANTE')], default=1),
        ),
    ]
