# Generated by Django 3.2.12 on 2023-01-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0062_alter_confirmacionventa_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizaciondescuentoglobal',
            old_name='descuento_global',
            new_name='descuento_cotizacion',
        ),
        migrations.AddField(
            model_name='cotizacionventadetalle',
            name='en_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
