# Generated by Django 3.2.12 on 2023-01-14 15:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0063_auto_20230114_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciondescuentoglobal',
            name='descuento_cotizacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Descuento Cotización'),
        ),
    ]
