# Generated by Django 3.2.12 on 2023-01-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0064_alter_cotizaciondescuentoglobal_descuento_cotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizaciondescuentoglobal',
            old_name='descuento_cotizacion',
            new_name='descuento_global_cotizacion',
        ),
    ]
