# Generated by Django 3.2.12 on 2023-01-16 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0065_rename_descuento_cotizacion_cotizaciondescuentoglobal_descuento_global_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionventadetalle',
            name='precio_oferta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Precio de Oferta'),
        ),
    ]
