# Generated by Django 3.2.12 on 2023-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0066_cotizacionventadetalle_precio_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciolistamaterial',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
    ]
