# Generated by Django 3.2.12 on 2023-07-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0069_alter_confirmacionventa_sunat_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacionsociedad',
            options={'ordering': ['id'], 'verbose_name': 'Cotizacion Sociedad', 'verbose_name_plural': 'Cotizacion Sociedades'},
        ),
    ]
