# Generated by Django 3.2.12 on 2023-07-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0070_alter_cotizacionsociedad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacionsociedad',
            options={'ordering': ['sociedad__id'], 'verbose_name': 'Cotizacion Sociedad', 'verbose_name_plural': 'Cotizacion Sociedades'},
        ),
    ]
