# Generated by Django 3.2.12 on 2023-08-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0071_alter_cotizacionsociedad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacionsociedad',
            options={'ordering': ['sociedad__estado_sunat', 'sociedad__id'], 'verbose_name': 'Cotizacion Sociedad', 'verbose_name_plural': 'Cotizacion Sociedades'},
        ),
    ]
