# Generated by Django 3.2.12 on 2024-05-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0072_alter_cotizacionsociedad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionventa',
            name='rotulado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
