# Generated by Django 3.2.12 on 2024-05-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0073_confirmacionventa_rotulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionventa',
            name='rotulado_estado',
            field=models.BooleanField(default=False),
        ),
    ]
