# Generated by Django 3.2.12 on 2022-07-15 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_globales', '0015_auto_20220601_1956'),
        ('oferta_proveedor', '0010_auto_20220714_1552'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0019_alter_representantelegal_estado'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internacional_nacional', models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], default=1, verbose_name='INTERNACIONAL-NACIONAL')),
                ('incoterms', models.IntegerField(blank=True, choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], null=True, verbose_name='INCOTERMS')),
                ('numero_orden_compra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Orden Compra')),
                ('fecha_orden', models.DateField(verbose_name='Fecha de Orden')),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento global')),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total descuento')),
                ('total_anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total anticipo')),
                ('total_gravada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total anticipo')),
                ('total_inafacta', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total anticipo')),
                ('total_exonerada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total descuento')),
                ('total_igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total descuento')),
                ('total_gratuita', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total descuento')),
                ('total_otros_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total descuento')),
                ('total_isc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='file/orden_compra/', verbose_name='Archivo')),
                ('condiciones', models.TextField()),
                ('motivo_anulacion', models.TextField()),
                ('estado', models.IntegerField(choices=[(1, 'POR VERIFICAR'), (2, 'ENVIADO'), (3, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OrdenCompra_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_globales.moneda')),
                ('oferta_proveedor', models.ManyToManyField(blank=True, to='oferta_proveedor.OfertaProveedor')),
                ('orden_compra_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orden_compra.ordencompra')),
                ('sociedad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SociedadOrdenCompra', to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OrdenCompra_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OrdenCompra',
                'verbose_name_plural': 'OrdenCompras',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio unitario sin igv')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio unitario con igv')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio final con igv')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sub Total')),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], null=True, verbose_name='Tipo de IGV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OrdenCompraDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_compra.ordencompra')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OrdenCompraDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OrdenCompraDetalle',
                'verbose_name_plural': 'OrdenesCompraDetalle',
            },
        ),
    ]
