# Generated by Django 3.2.12 on 2022-07-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0010_auto_20220714_1552'),
        ('datos_globales', '0015_auto_20220601_1956'),
        ('orden_compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'verbose_name': 'Orden Compra', 'verbose_name_plural': 'Ordenes Compra'},
        ),
        migrations.AlterModelOptions(
            name='ordencompradetalle',
            options={'verbose_name': 'Orden Compra Detalle', 'verbose_name_plural': 'Ordenes Compra Detalle'},
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda'),
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='oferta_proveedor',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='oferta_proveedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oferta_proveedor.ofertaproveedor'),
        ),
    ]
