# Generated by Django 3.2.12 on 2022-07-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0002_auto_20220716_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrdenCompraDetalle_orden_compra', to='orden_compra.ordencompra'),
        ),
    ]
