# Generated by Django 3.2.12 on 2022-07-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0002_auto_20220716_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
