# Generated by Django 3.2.12 on 2022-07-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0003_alter_ordencompra_motivo_anulacion'),
        ('orden_compra', '0003_alter_ordencompradetalle_orden_compra'),
    ]

    operations = [
    ]
