# Generated by Django 3.2.12 on 2022-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0004_merge_20220720_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompradetalle',
            options={'ordering': ['orden_compra', 'item'], 'verbose_name': 'Orden Compra Detalle', 'verbose_name_plural': 'Ordenes Compra Detalle'},
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='incoterms',
            field=models.IntegerField(blank=True, choices=[(1, 'EXW'), (2, 'FOB'), (3, 'FCA'), (4, 'CIF'), (5, 'DDP')], null=True, verbose_name='INCOTERMS'),
        ),
    ]
