# Generated by Django 3.2.12 on 2022-07-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0004_merge_20220720_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.IntegerField(choices=[(0, 'NUEVA VERSIÓN'), (1, 'POR VERIFICAR'), (2, 'ENVIADO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
    ]
