# Generated by Django 3.2.12 on 2022-07-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0005_alter_ordencompra_estado'),
        ('orden_compra', '0005_auto_20220723_0946'),
    ]

    operations = [
    ]
