# Generated by Django 3.2.12 on 2022-08-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0006_merge_20220727_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='total_exonerada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total exonerada'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total_gratuita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total gratuita'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total_gravada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total gravada'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total_igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total igv'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total_inafacta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total inafacta'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total_isc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total isc'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total_otros_cargos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total otros cargos'),
        ),
    ]
