# Generated by Django 3.2.12 on 2022-08-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0007_auto_20220804_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='condiciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
