# Generated by Django 3.2.12 on 2022-08-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0008_alter_ordencompra_condiciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='orden_compra_anterior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OrdenCompra_orden_compra_anterior', to='orden_compra.ordencompra'),
        ),
    ]
