# Generated by Django 3.2.12 on 2022-08-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0009_alter_ordencompra_orden_compra_anterior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-numero_orden_compra', '-created_at'], 'verbose_name': 'Orden Compra', 'verbose_name_plural': 'Ordenes Compra'},
        ),
    ]
