# Generated by Django 3.2.12 on 2022-09-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0010_alter_ordencompra_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='sociedad_id',
            new_name='sociedad',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.IntegerField(choices=[(0, 'NUEVA VERSIÓN'), (1, 'POR VERIFICAR'), (2, 'ENVIADO'), (3, 'CONFIRMADO'), (4, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
    ]
