# Generated by Django 3.2.12 on 2022-09-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_proveedor', '0014_alter_ofertaproveedor_requerimiento_material'),
        ('orden_compra', '0011_auto_20220914_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='oferta_proveedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OrdenCompra_oferta_proveedor', to='oferta_proveedor.ofertaproveedor'),
        ),
    ]
