# Generated by Django 3.2.12 on 2023-01-16 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_auto_20230116_1858'),
        ('orden_compra', '0012_alter_ordencompra_oferta_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='interlocutor_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.interlocutorproveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
