# Generated by Django 3.2.12 on 2023-02-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0013_auto_20230116_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.IntegerField(choices=[(0, 'NUEVA VERSIÓN'), (1, 'POR VERIFICAR'), (2, 'ENVIADO'), (3, 'CONFIRMADO'), (4, 'ANULADO'), (5, 'INICIAL')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad'),
        ),
    ]
