# Generated by Django 3.2.12 on 2023-02-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_auto_20230116_1858'),
        ('orden_compra', '0014_auto_20230209_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
    ]
