# Generated by Django 3.2.12 on 2025-03-28 23:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0016_alter_ordencompra_incoterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='flete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Flete'),
        ),
    ]
