# Generated by Django 3.2.12 on 2022-07-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0002_alter_usuarioaptc_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioaptc',
            old_name='numero_ticket',
            new_name='ticket',
        ),
    ]
