# Generated by Django 3.2.12 on 2022-07-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0003_rename_numero_ticket_usuarioaptc_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioaptc',
            name='bloqueo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarioaptc',
            name='elegido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarioaptc',
            name='premio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Premio'),
        ),
    ]
