# Generated by Django 3.2.12 on 2022-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0004_auto_20220718_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioaptc',
            name='dni',
        ),
        migrations.AddField(
            model_name='usuarioaptc',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='usuarioaptc',
            name='tipo_documento',
            field=models.CharField(choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)')], default=1, max_length=1, verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
    ]
