# Generated by Django 3.2.12 on 2022-07-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0005_auto_20220719_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioaptc',
            options={'ordering': ['ticket'], 'verbose_name': 'UsuarioAPTC', 'verbose_name_plural': 'UsuarioAPTCs'},
        ),
        migrations.AlterField(
            model_name='usuarioaptc',
            name='tipo_documento',
            field=models.CharField(choices=[('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD')], max_length=1, verbose_name='Tipo de Documento'),
        ),
    ]
