# Generated by Django 3.2.12 on 2022-08-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0006_auto_20220720_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioaptc',
            name='ticket',
            field=models.CharField(max_length=4, verbose_name='numero_ticket'),
        ),
    ]
