# Generated by Django 3.2.12 on 2022-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0007_alter_usuarioaptc_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioaptc',
            options={'ordering': ['premio', 'ticket'], 'verbose_name': 'UsuarioAPTC', 'verbose_name_plural': 'UsuarioAPTCs'},
        ),
        migrations.AlterField(
            model_name='usuarioaptc',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='usuarioaptc',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='empresa'),
        ),
    ]
