# Generated by Django 3.2.12 on 2022-08-17 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0008_auto_20220817_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioaptc',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
