# Generated by Django 3.2.12 on 2022-08-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0009_usuarioaptc_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioaptc',
            options={'ordering': ['fecha', 'premio', 'ticket'], 'verbose_name': 'UsuarioAPTC', 'verbose_name_plural': 'UsuarioAPTCs'},
        ),
        migrations.AlterUniqueTogether(
            name='usuarioaptc',
            unique_together={('fecha', 'tipo_documento', 'numero_documento')},
        ),
    ]
