# Generated by Django 3.2.12 on 2022-08-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0010_auto_20220817_1501'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarioaptc',
            unique_together=set(),
        ),
    ]
