# Generated by Django 3.2.12 on 2022-08-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0011_alter_usuarioaptc_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioaptc',
            options={'ordering': ['-fecha', 'premio', 'ticket'], 'verbose_name': 'UsuarioAPTC', 'verbose_name_plural': 'UsuarioAPTCs'},
        ),
    ]
