# Generated by Django 3.2.12 on 2023-07-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_aptc', '0013_alter_usuarioaptc_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioaptc',
            name='tipo_documento',
            field=models.CharField(choices=[('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('B', 'DOC.IDENT.PAIS.RESIDENCIA-NO.D'), ('-', 'SIN DOCUMENTO')], max_length=1, verbose_name='Tipo de Documento'),
        ),
    ]
