# Generated by Django 3.2.12 on 2022-07-20 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0019_alter_representantelegal_estado'),
        ('almacenes', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Código SAP')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción del movimiento')),
                ('signo_factor_multiplicador', models.IntegerField(choices=[(1, '+1'), (0, '0'), (-1, '-1')], verbose_name='Signo Factor Multiplicador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoMovimiento_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoMovimiento_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
            },
        ),
        migrations.CreateModel(
            name='MovimientosAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro_producto', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('id_registro_documento_proceso', models.IntegerField()),
                ('movimiento_reversion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen')),
                ('content_type_documento_proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MovimientosAlmacen_content_type_documento_proceso', to='contenttypes.contenttype')),
                ('content_type_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MovimientosAlmacen_content_type_producto', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MovimientosAlmacen_created_by', to=settings.AUTH_USER_MODEL)),
                ('movimiento_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimiento_almacen.movimientosalmacen')),
                ('sociedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimiento_almacen.tipomovimiento')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MovimientosAlmacen_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Almacen',
                'verbose_name_plural': 'Movimientos de Almacenes',
            },
        ),
    ]
