# Generated by Django 3.2.12 on 2022-07-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipomovimiento',
            name='signo_factor_multiplicador',
        ),
        migrations.AddField(
            model_name='movimientosalmacen',
            name='signo_factor_multiplicador',
            field=models.IntegerField(choices=[(1, '+1'), (0, '0'), (-1, '-1')], default=1, verbose_name='Signo Factor Multiplicador'),
            preserve_default=False,
        ),
    ]
