# Generated by Django 3.2.12 on 2022-07-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0002_auto_20220720_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosalmacen',
            name='movimiento_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movimiento_almacen.movimientosalmacen'),
        ),
    ]
