# Generated by Django 3.2.12 on 2022-08-09 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimiento_almacen', '0003_alter_movimientosalmacen_movimiento_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomovimiento',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='TipoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción del movimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoStock_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoStock_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Stock',
                'verbose_name_plural': 'Tipos de Stocks',
            },
        ),
        migrations.AddField(
            model_name='tipomovimiento',
            name='tipo_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock'),
            preserve_default=False,
        ),
    ]
