# Generated by Django 3.2.12 on 2022-08-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0004_auto_20220809_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomovimiento',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipomovimiento',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descripción del movimiento'),
        ),
        migrations.AlterField(
            model_name='tipostock',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipostock',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descripción del movimiento'),
        ),
    ]
