# Generated by Django 3.2.12 on 2022-08-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0005_auto_20220809_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipomovimiento',
            old_name='tipo_stock',
            new_name='tipo_stock_final',
        ),
    ]
