# Generated by Django 3.2.12 on 2022-08-13 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0006_rename_tipo_stock_tipomovimiento_tipo_stock_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomovimiento',
            name='tipo_stock_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoMovimiento_tipo_stock_inicial', to='movimiento_almacen.tipostock'),
        ),
        migrations.AlterField(
            model_name='tipomovimiento',
            name='tipo_stock_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TipoMovimiento_tipo_stock_final', to='movimiento_almacen.tipostock'),
        ),
    ]
