# Generated by Django 3.2.12 on 2022-08-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0007_auto_20220813_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosalmacen',
            name='tipo_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock'),
            preserve_default=False,
        ),
    ]
