# Generated by Django 3.2.12 on 2022-09-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0008_movimientosalmacen_tipo_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomovimiento',
            name='tipo_stock_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoMovimiento_tipo_stock_final', to='movimiento_almacen.tipostock'),
        ),
    ]
