# Generated by Django 3.2.12 on 2022-09-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0009_alter_tipomovimiento_tipo_stock_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosalmacen',
            name='movimiento_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MovimientosAlmacen_movimiento_anterior', to='movimiento_almacen.movimientosalmacen'),
        ),
    ]
