# Generated by Django 3.2.12 on 2023-01-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0010_alter_movimientosalmacen_movimiento_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipostock',
            name='serie_registrada',
            field=models.BooleanField(default=False),
        ),
    ]
