# Generated by Django 3.2.12 on 2023-01-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0011_tipostock_serie_registrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomovimiento',
            options={'ordering': ['codigo'], 'verbose_name': 'Tipo de Movimiento', 'verbose_name_plural': 'Tipos de Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='tipostock',
            options={'ordering': ['codigo'], 'verbose_name': 'Tipo de Stock', 'verbose_name_plural': 'Tipos de Stocks'},
        ),
    ]
