# Generated by Django 3.2.12 on 2023-01-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0012_auto_20230107_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientosalmacen',
            options={'ordering': ['id'], 'verbose_name': 'Movimiento de Almacen', 'verbose_name_plural': 'Movimientos de Almacenes'},
        ),
    ]
