# Generated by Django 3.2.12 on 2023-03-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0013_alter_movimientosalmacen_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosalmacen',
            name='transformacion',
            field=models.BooleanField(default=False),
        ),
    ]
