# Generated by Django 3.2.12 on 2023-10-07 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0014_movimientosalmacen_transformacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosalmacen',
            name='fecha_documento',
            field=models.DateField(default=datetime.date(2023, 10, 7)),
        ),
    ]
