# Generated by Django 3.2.12 on 2023-10-09 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0016_alter_movimientosalmacen_fecha_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosalmacen',
            name='fecha_documento',
            field=models.DateField(default=datetime.date(2023, 10, 9)),
        ),
    ]
