# Generated by Django 3.2.12 on 2023-10-09 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0017_alter_movimientosalmacen_fecha_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosalmacen',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
