# Generated by Django 3.2.12 on 2022-07-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('datos_globales', '0015_auto_20220601_1956'),
        ('orden_compra', '0002_auto_20220716_1016'),
        ('sociedad', '0019_alter_representantelegal_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteCompraCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internacional_nacional', models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], default=1, verbose_name='Internacional-Nacional')),
                ('incoterms', models.IntegerField(blank=True, choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], null=True, verbose_name='INCOTERMS')),
                ('numero_comprobante_compra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Comprobante de Compra')),
                ('fecha_comprobante', models.DateField(verbose_name='Fecha del Comprobante')),
                ('descuento_global', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Descuento Global')),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Descuento')),
                ('total_anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Anticipo')),
                ('total_gravada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gravada')),
                ('total_inafecta', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Inafecta')),
                ('total_exonerada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Exonerada')),
                ('total_igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total IGV')),
                ('total_gratuita', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gratuita')),
                ('total_otros_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Otros Cargos')),
                ('total_icbper', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total ICBPER')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='file/comprobante compra/comprobante compra CI/', verbose_name='Archivo')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('motivo_anulacion', models.CharField(max_length=50, verbose_name='Motivo de anulación')),
            ],
            options={
                'verbose_name': 'Comprobante de Compra CI',
                'verbose_name_plural': 'Comprobantes de Compra CIs',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteCompraPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internacional_nacional', models.IntegerField(choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], default=1, verbose_name='Internacional-Nacional')),
                ('incoterms', models.IntegerField(blank=True, choices=[(1, 'INTERNACIONAL'), (2, 'NACIONAL')], null=True, verbose_name='INCOTERMS')),
                ('numero_comprobante_compra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Comprobante de Compra')),
                ('fecha_comprobante', models.DateField(verbose_name='Fecha del Comprobante')),
                ('descuento_global', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Descuento Global')),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Descuento')),
                ('total_anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Anticipo')),
                ('total_gravada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gravada')),
                ('total_inafecta', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Inafecta')),
                ('total_exonerada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Exonerada')),
                ('total_igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total IGV')),
                ('total_gratuita', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gratuita')),
                ('total_otros_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Otros Cargos')),
                ('total_icbper', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total ICBPER')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='file/comprobante compra/comprobante compra PI/', verbose_name='Archivo')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('motivo_anulacion', models.CharField(max_length=50, verbose_name='Motivo de anulación')),
                ('logistico', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Margen logístico')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('orden_compra', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orden_compra.ordencompra')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
            ],
            options={
                'verbose_name': 'Comprobante de Compra PI',
                'verbose_name_plural': 'Comprobantes de Compra PIs',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteCompraPIDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Unitario Sin IGV')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Unitario Con IGV')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Final Con IGV')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sub Total')),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')])),
                ('comprobante_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobante_compra.comprobantecomprapi')),
                ('orden_compra_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orden_compra.ordencompradetalle')),
            ],
            options={
                'verbose_name': 'Comprobante de Compra PI Detalle',
                'verbose_name_plural': 'Comprobantes de Compra PI Detalles',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteCompraCIDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Unitario Sin IGV')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Unitario Con IGV')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio Final Con IGV')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sub Total')),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')])),
                ('comprobante_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobante_compra.comprobantecompraci')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Comprobante de Compra CI Detalle',
                'verbose_name_plural': 'Comprobantes de Compra CI Detalles',
            },
        ),
        migrations.AddField(
            model_name='comprobantecompraci',
            name='comprobante_compra_PI',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comprobante_compra.comprobantecomprapi'),
        ),
        migrations.AddField(
            model_name='comprobantecompraci',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda'),
        ),
        migrations.AddField(
            model_name='comprobantecompraci',
            name='sociedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
        ),
        migrations.CreateModel(
            name='ArchivoComprobanteCompraPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='file/comprobante compra/archivo comprobante compra PI/', verbose_name='Archivo')),
                ('comprobante_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobante_compra.comprobantecomprapi')),
            ],
            options={
                'verbose_name': 'Archivo de Comprobante de Compra PI',
                'verbose_name_plural': 'Archivos de Comprobantes de Compra PIs',
            },
        ),
    ]
