# Generated by Django 3.2.12 on 2022-07-19 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comprobante_compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocomprobantecomprapi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivocomprobantecomprapi',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArchivoComprobanteCompraPI_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivocomprobantecomprapi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='archivocomprobantecomprapi',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArchivoComprobanteCompraPI_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobantecompraci',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobantecompraci',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraCI_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobantecompraci',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='comprobantecompraci',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraCI_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobantecompracidetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobantecompracidetalle',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraCIDetalle_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobantecompracidetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='comprobantecompracidetalle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraCIDetalle_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobantecomprapi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobantecomprapi',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraPI_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobantecomprapi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='comprobantecomprapi',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraPI_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobantecomprapidetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobantecomprapidetalle',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraPIDetalle_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobantecomprapidetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='comprobantecomprapidetalle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraPIDetalle_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
