# Generated by Django 3.2.12 on 2022-07-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0002_auto_20220719_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraci',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Motivo de anulación'),
        ),
        migrations.AlterField(
            model_name='comprobantecomprapi',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Motivo de anulación'),
        ),
    ]
