# Generated by Django 3.2.12 on 2022-07-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0003_alter_ordencompra_motivo_anulacion'),
        ('comprobante_compra', '0003_auto_20220719_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraci',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'CANCELADO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraci',
            name='incoterms',
            field=models.IntegerField(blank=True, choices=[(1, 'EXW'), (2, 'FOB'), (3, 'FCA'), (4, 'CIF'), (5, 'DDP')], null=True, verbose_name='INCOTERMS'),
        ),
        migrations.AlterField(
            model_name='comprobantecomprapi',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'CANCELADO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='comprobantecomprapi',
            name='incoterms',
            field=models.IntegerField(blank=True, choices=[(1, 'EXW'), (2, 'FOB'), (3, 'FCA'), (4, 'CIF'), (5, 'DDP')], null=True, verbose_name='INCOTERMS'),
        ),
        migrations.AlterField(
            model_name='comprobantecomprapidetalle',
            name='orden_compra_detalle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orden_compra.ordencompradetalle'),
        ),
    ]
