# Generated by Django 3.2.12 on 2022-07-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0004_auto_20220719_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecomprapidetalle',
            name='comprobante_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComprobanteCompraPIDetalle_comprobante_compra', to='comprobante_compra.comprobantecomprapi'),
        ),
    ]
