# Generated by Django 3.2.12 on 2022-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0005_alter_comprobantecomprapidetalle_comprobante_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraci',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'RECIBIDO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='comprobantecomprapi',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'RECIBIDO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
    ]
