# Generated by Django 3.2.12 on 2022-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0006_auto_20220721_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobantecompracidetalle',
            options={'ordering': ['comprobante_compra', 'item'], 'verbose_name': 'Comprobante de Compra CI Detalle', 'verbose_name_plural': 'Comprobantes de Compra CI Detalles'},
        ),
        migrations.AlterModelOptions(
            name='comprobantecomprapidetalle',
            options={'ordering': ['comprobante_compra', 'item'], 'verbose_name': 'Comprobante de Compra PI Detalle', 'verbose_name_plural': 'Comprobantes de Compra PI Detalles'},
        ),
        migrations.AlterField(
            model_name='comprobantecompraci',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento Global'),
        ),
        migrations.AlterField(
            model_name='comprobantecompraci',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'FINALIZADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='comprobantecomprapi',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento Global'),
        ),
        migrations.AlterField(
            model_name='comprobantecomprapi',
            name='estado',
            field=models.IntegerField(choices=[(0, 'PARCIAL'), (1, 'PENDIENTE'), (2, 'RECIBIDO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
    ]
