# Generated by Django 3.2.12 on 2022-07-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0007_auto_20220723_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompracidetalle',
            name='comprobante_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComprobanteCompraCIDetalle_comprobante_compra', to='comprobante_compra.comprobantecompraci'),
        ),
    ]
