# Generated by Django 3.2.12 on 2022-07-27 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0008_alter_comprobantecompracidetalle_comprobante_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompraci',
            name='comprobante_compra_PI',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraCI_comprobante_compra_PI', to='comprobante_compra.comprobantecomprapi'),
        ),
    ]
