# Generated by Django 3.2.12 on 2022-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0009_alter_comprobantecompraci_comprobante_compra_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecomprapi',
            name='fecha_comprobante',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Comprobante'),
        ),
    ]
