# Generated by Django 3.2.12 on 2022-08-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0010_alter_ordencompra_options'),
        ('comprobante_compra', '0010_alter_comprobantecomprapi_fecha_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecomprapidetalle',
            name='orden_compra_detalle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraPIDetalle_orden_compra_detalle', to='orden_compra.ordencompradetalle'),
        ),
    ]
