# Generated by Django 3.2.12 on 2022-12-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0011_alter_comprobantecomprapidetalle_orden_compra_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecomprapi',
            name='estado',
            field=models.IntegerField(choices=[(0, 'BORRADOR'), (1, 'PENDIENTE'), (2, 'RECIBIDO'), (3, 'ANULADO')], default=0, verbose_name='Estado'),
        ),
    ]
