# Generated by Django 3.2.12 on 2022-12-16 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0012_alter_ordencompra_oferta_proveedor'),
        ('comprobante_compra', '0012_alter_comprobantecomprapi_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecomprapi',
            name='orden_compra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ComprobanteCompraPI_orden_compra', to='orden_compra.ordencompra'),
        ),
    ]
