# Generated by Django 3.2.12 on 2023-01-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0013_alter_comprobantecomprapi_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompracidetalle',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
