# Generated by Django 3.2.12 on 2023-01-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0014_comprobantecompracidetalle_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantecomprapi',
            name='archivo',
        ),
    ]
