# Generated by Django 3.2.12 on 2023-01-24 15:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0015_remove_comprobantecomprapi_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecomprapi',
            name='logistico',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='Margen logístico'),
        ),
    ]
