# Generated by Django 3.2.12 on 2023-02-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0016_alter_comprobantecomprapi_logistico'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecomprapi',
            name='fecha_estimada_llegada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Llegada'),
        ),
    ]
