# Generated by Django 3.2.12 on 2023-05-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0017_comprobantecomprapi_fecha_estimada_llegada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobantecomprapi',
            options={'ordering': ['estado', 'fecha_estimada_llegada'], 'verbose_name': 'Comprobante de Compra PI', 'verbose_name_plural': 'Comprobantes de Compra PIs'},
        ),
    ]
