# Generated by Django 3.2.12 on 2023-07-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_compra', '0018_alter_comprobantecomprapi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobantecomprapi',
            options={'ordering': ['estado', '-fecha_estimada_llegada'], 'verbose_name': 'Comprobante de Compra PI', 'verbose_name_plural': 'Comprobantes de Compra PIs'},
        ),
    ]
