# Generated by Django 3.2.12 on 2022-12-20 20:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('clientes', '0025_auto_20221123_1859'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0042_rename_temporal_cuentabancariasociedad_efectivo'),
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notacredito',
            options={'verbose_name': 'Nota de Credito', 'verbose_name_plural': 'Notas de Credito'},
        ),
        migrations.AddField(
            model_name='notacredito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito_cliente', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='cliente_interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito_interlocutor', to='clientes.interlocutorcliente'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='condiciones_pago',
            field=models.CharField(blank=True, help_text='Factura a 30 días', max_length=250, null=True, verbose_name='Condiciones de Pago'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='content_type_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito_content_type_documento', to='datos_globales.documentofisico'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='content_type_reclamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito_content_type_reclamo', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notacredito',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NotaCredito_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Descuento Global'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='detraccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO'), (4, 'ACEPTADO POR SUNAT'), (5, 'RECHAZADO POR SUNAT'), (6, 'CON ERRORES'), (7, 'FINTA')], default=1),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Emisión'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='id_registro_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='id_registro_reclamo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de Anulación'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='nubefact',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='numero_nota',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro. Nota'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='percepcion_base_imponible',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Percepcion Base Imponible'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='percepcion_tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'PERCEPCIÓN VENTA INTERNA - TASA 2%'), (2, 'PERCEPCIÓN ADQUISICIÓN DE COMBUSTIBLE-TASA 1%'), (3, 'PERCEPCIÓN REALIZADA AL AGENTE DE PERCEPCIÓN CON TASA ESPECIAL - TASA 0.5%')], null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='retencion_base_imponible',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Retencion Base Imponible'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='retencion_tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'TASA 3%'), (2, 'TASA 6%')], null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='serie_comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.seriescomprobante'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='sociedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notacredito',
            name='tipo_cambio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito_tipo_cambio', to='datos_globales.tipocambio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notacredito',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'NOTA DE CRÉDITO'), (4, 'NOTA DE DÉBITO'), (7, 'GUÍA REMISIÓN REMITENTE')], default=1, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='tipo_venta',
            field=models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CREDITO')], default=1, verbose_name='Tipo de Venta'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_anticipo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Anticipo'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Descuento'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_exonerada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Exonerada'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_gratuita',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Gratuita'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_gravada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Gravada'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_igv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total IGV'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_impuestos_bolsas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Total Impuestos Bolsas'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_inafecta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Inafecta'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_incluido_percepcion',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Total Incluido Percepcion'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_otros_cargos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Otros Cargos'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_percepcion',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Total Percepcion'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Total Retencion'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NotaCredito_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
