# Generated by Django 3.2.12 on 2022-12-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0002_auto_20221220_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='tipo_nota_credito',
            field=models.IntegerField(blank=True, choices=[(6, 'DEVOLUCIÓN TOTAL'), (7, 'DEVOLUCIÓN POR ÍTEM'), (1, 'ANULACIÓN DE LA OPERACIÓN'), (2, 'ANULACIÓN POR ERROR EN EL RUC'), (4, 'DESCUENTO GLOBAL'), (5, 'DESCUENTO POR ÍTEM'), (8, 'BONIFICACIÓN'), (9, 'DISMINUCIÓN EN EL VALOR'), (10, 'OTROS CONCEPTOS'), (11, 'AJUSTES AFECTOS AL IVAP'), (12, 'AJUSTES DE OPERACIONES DE EXPORTACIÓN'), (13, 'AJUSTES - MONTOS Y/O FECHAS DE PAGO'), (3, 'CORRECCIÓN POR ERROR EN LA DESCRIPCIÓN')], null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'NOTA DE CRÉDITO'), (4, 'NOTA DE DÉBITO'), (7, 'GUÍA REMISIÓN REMITENTE')], default=3, verbose_name='Tipo de Comprobante'),
        ),
    ]
