# Generated by Django 3.2.12 on 2022-12-20 22:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('datos_globales', '0042_rename_temporal_cuentabancariasociedad_efectivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nota', '0003_auto_20221220_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=250, null=True, verbose_name='Código Interno')),
                ('descripcion_documento', models.CharField(max_length=250, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio unitario sin IGV')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio unitario con IGV')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio final con IGV')),
                ('descuento', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Sub Total')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], default=1, verbose_name='Tipo IGV')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('anticipo_regularizacion', models.BooleanField(default=False)),
                ('anticipo_documento_numero', models.IntegerField(blank=True, null=True)),
                ('codigo_producto_sunat', models.CharField(blank=True, max_length=8)),
                ('tipo_de_isc', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True)),
                ('isc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ISC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('anticipo_documento_serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.seriescomprobante')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NotaCreditoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotaCreditoDetalle_nota_credito', to='nota.notacredito')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NotaCreditoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Crédito Detalle',
                'verbose_name_plural': 'Notas de Crédito Detalle',
                'ordering': ['nota_credito', 'item'],
            },
        ),
    ]
