# Generated by Django 3.2.12 on 2023-02-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0004_notacreditodetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacredito',
            name='condiciones_pago',
        ),
        migrations.RemoveField(
            model_name='notacredito',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='notacredito',
            name='tipo_venta',
        ),
    ]
