# Generated by Django 3.2.12 on 2023-02-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0005_auto_20230209_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notacredito',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nota de Credito', 'verbose_name_plural': 'Notas de Credito'},
        ),
    ]
