# Generated by Django 3.2.12 on 2023-02-21 23:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0006_alter_notacredito_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='descripcion_documento',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=22, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='igv',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='IGV'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='precio_final_con_igv',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=22, null=True, verbose_name='Precio final con IGV'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='precio_unitario_con_igv',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=22, null=True, verbose_name='Precio unitario con IGV'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='precio_unitario_sin_igv',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), max_digits=22, null=True, verbose_name='Precio unitario sin IGV'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Total'),
        ),
    ]
