# Generated by Django 3.2.12 on 2023-02-21 23:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0007_auto_20230221_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacreditodetalle',
            name='anticipo_documento_numero',
        ),
        migrations.RemoveField(
            model_name='notacreditodetalle',
            name='anticipo_documento_serie',
        ),
        migrations.RemoveField(
            model_name='notacreditodetalle',
            name='anticipo_regularizacion',
        ),
        migrations.RemoveField(
            model_name='notacreditodetalle',
            name='isc',
        ),
        migrations.RemoveField(
            model_name='notacreditodetalle',
            name='tipo_de_isc',
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IGV'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='precio_final_con_igv',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio final con IGV'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='precio_unitario_con_igv',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio unitario con IGV'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='precio_unitario_sin_igv',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio unitario sin IGV'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total'),
        ),
    ]
