# Generated by Django 3.2.12 on 2023-02-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0043_auto_20230125_1303'),
        ('nota', '0008_auto_20230221_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditodetalle',
            name='anticipo_documento_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodetalle',
            name='anticipo_documento_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.seriescomprobante'),
        ),
        migrations.AddField(
            model_name='notacreditodetalle',
            name='anticipo_regularizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notacreditodetalle',
            name='isc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ISC'),
        ),
        migrations.AddField(
            model_name='notacreditodetalle',
            name='tipo_de_isc',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
    ]
