# Generated by Django 3.2.12 on 2023-02-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0009_auto_20230222_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='sunat_transaction',
            field=models.IntegerField(choices=[(1, 'VENTA INTERNA'), (2, 'EXPORTACIÓN'), (4, 'VENTA INTERNA - ANTICIPOS'), (29, 'VENTAS NO DOMICILIADOS QUE NO CALIFICAN COMO EXPORTACIÓN.'), (30, 'OPERACIÓN SUJETA A DETRACCIÓN.'), (33, 'DETRACCIÓN - SERVICIOS DE TRANSPORTE CARGA'), (34, 'OPERACIÓN SUJETA A PERCEPCIÓN'), (32, 'DETRACCIÓN - SERVICIOS DE TRANSPORTE DE PASAJEROS.'), (31, 'DETRACCIÓN - RECURSOS HIDROBIOLÓGICOS')], default=1),
        ),
    ]
