# Generated by Django 3.2.12 on 2023-07-01 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0013_auto_20230411_0924'),
        ('almacenes', '0006_alter_almacen_estado_alta_baja'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sociedad', '0027_alter_sociedad_estado_sunat'),
        ('nota', '0010_notacredito_sunat_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota_devolucion', models.IntegerField(blank=True, help_text='Correlativo', null=True, verbose_name='Número de Nota de Devolucion')),
                ('id_registro', models.IntegerField()),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolucion')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación')),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'FINALIZADO'), (3, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaDevolucion_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaDevolucion_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Devolucion',
                'verbose_name_plural': 'Notas de Devolucion',
            },
        ),
        migrations.CreateModel(
            name='NotaDevolucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField()),
                ('cantidad_conteo', models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad del conteo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaDevolucionDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NotaDevolucionDetalle_nota_devolucion', to='nota.notadevolucion')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaDevolucionDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Devolucion Detalle',
                'verbose_name_plural': 'Notas de Devolucion Detalles',
                'ordering': ['nota_devolucion', 'item'],
            },
        ),
    ]
