# Generated by Django 3.2.12 on 2023-07-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0036_auto_20230704_1617'),
        ('nota', '0012_alter_notacredito_sunat_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notadevoluciondetalle',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='notadevoluciondetalle',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
