# Generated by Django 3.2.12 on 2023-07-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0013_auto_20230718_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notadevolucion',
            old_name='nro_nota_devolucion',
            new_name='numero_devolucion',
        ),
    ]
