# Generated by Django 3.2.12 on 2023-07-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0014_rename_nro_nota_devolucion_notadevolucion_numero_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notadevolucion',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Devolucion'),
        ),
    ]
