# Generated by Django 3.2.12 on 2023-07-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0015_alter_notadevolucion_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notadevoluciondetalle',
            name='nota_devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotaDevolucionDetalle_nota_devolucion', to='nota.notadevolucion'),
        ),
    ]
