# Generated by Django 3.2.12 on 2023-07-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0036_auto_20230704_1617'),
        ('nota', '0016_alter_notadevoluciondetalle_nota_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notadevolucion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
