# Generated by Django 3.2.12 on 2023-08-08 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nota', '0017_notadevolucion_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dias_pago', models.IntegerField(blank=True, null=True, verbose_name='Días de pago')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('dias_calculo', models.IntegerField(blank=True, null=True, verbose_name='Días de calculo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NotaCreditoCuota_created_by', to=settings.AUTH_USER_MODEL)),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotaCreditoCuota_nota_credito', to='nota.notacredito')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='NotaCreditoCuota_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Crédito Cuota',
                'verbose_name_plural': 'Nota de Crédito Cuotas',
                'ordering': ['nota_credito', 'dias_calculo'],
            },
        ),
    ]
