# Generated by Django 3.2.12 on 2022-05-17 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0010_merge_0009_auto_20220511_0944_0009_auto_20220511_1425'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_venta', models.CharField(max_length=500, verbose_name='Descripción Venta')),
                ('descripcion_corta', models.CharField(max_length=150, verbose_name='Descripción Corta')),
                ('peso_unidad_base', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso Unidad Base')),
                ('control_serie', models.BooleanField(default=False, verbose_name='Control Serie')),
                ('control_lote', models.BooleanField(default=False, verbose_name='Control Lote')),
                ('control_calidad', models.BooleanField(default=False, verbose_name='Control Calidad')),
                ('estado_alta_baja', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('mostrar', models.BooleanField(default=False, verbose_name='Mostrar')),
                ('traduccion', models.CharField(max_length=255, verbose_name='Traducción')),
                ('partida', models.CharField(max_length=30, verbose_name='Partida')),
                ('uso_funcion', models.CharField(max_length=500, verbose_name='Traducción')),
                ('compuesto_por', models.CharField(max_length=255, verbose_name='Compuesto por')),
                ('es_componente', models.BooleanField(default=False, verbose_name='Es componente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('atributo', models.ManyToManyField(related_name='Material_atributo', to='material.Atributo', verbose_name='Atributo')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Material_clase', to='material.clase')),
                ('componente', models.ManyToManyField(related_name='Material_componente', to='material.Componente', verbose_name='Componente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Material_created_by', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Material_marca', to='material.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Material_modelo', to='material.modelo')),
                ('producto_sunat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Material_producto_sunat', to='datos_globales.productosunat')),
                ('subfamilia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Material_subfamilia', to='material.subfamilia')),
                ('unidad_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Material_unidad_base', to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Material_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
