# Generated by Django 3.2.12 on 2022-05-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='atributo',
            field=models.ManyToManyField(blank=True, null=True, related_name='Material_atributo', to='material.Atributo', verbose_name='Atributo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='componente',
            field=models.ManyToManyField(blank=True, null=True, related_name='Material_componente', to='material.Componente', verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='material',
            name='compuesto_por',
            field=models.CharField(blank=True, max_length=255, verbose_name='Compuesto por'),
        ),
        migrations.AlterField(
            model_name='material',
            name='partida',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='material',
            name='traduccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Traducción'),
        ),
        migrations.AlterField(
            model_name='material',
            name='uso_funcion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Traducción'),
        ),
    ]
