# Generated by Django 3.2.12 on 2022-05-17 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20220517_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='atributo',
            field=models.ManyToManyField(blank=True, related_name='Material_atributo', to='material.Atributo', verbose_name='Atributo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='componente',
            field=models.ManyToManyField(blank=True, related_name='Material_componente', to='material.Componente', verbose_name='Componente'),
        ),
        migrations.CreateModel(
            name='RelacionMaterialComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('componentematerial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.componente')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
            options={
                'verbose_name': 'RelacionMaterialComponente',
                'verbose_name_plural': 'RelacionMaterialComponentes',
            },
        ),
    ]
