# Generated by Django 3.2.12 on 2022-05-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20220517_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='componente',
        ),
    ]
