# Generated by Django 3.2.12 on 2022-05-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_remove_material_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='componente',
            field=models.ManyToManyField(blank=True, related_name='Material_componente', through='material.RelacionMaterialComponente', to='material.Componente', verbose_name='Componente'),
        ),
    ]
