# Generated by Django 3.2.12 on 2022-05-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_especificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacion',
            name='atributomaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.atributo', verbose_name='Atributo material'),
        ),
        migrations.AlterField(
            model_name='relacionmaterialcomponente',
            name='componentematerial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.componente', verbose_name='Componente material'),
        ),
        migrations.CreateModel(
            name='Datasheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='file/materiales/archivo_datasheet/', verbose_name='Archivo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
            options={
                'verbose_name': 'Datasheet',
                'verbose_name_plural': 'Datasheets',
            },
        ),
    ]
