# Generated by Django 3.2.12 on 2022-05-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_auto_20220519_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='uso_funcion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Uso función'),
        ),
    ]
