# Generated by Django 3.2.12 on 2022-05-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0010_merge_0009_auto_20220511_0944_0009_auto_20220511_1425'),
        ('material', '0013_alter_material_producto_sunat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='producto_sunat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Material_producto_sunat', to='datos_globales.productosunat'),
        ),
    ]
