# Generated by Django 3.2.12 on 2022-05-20 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_alter_material_producto_sunat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Material_clase', to='material.clase'),
        ),
    ]
