# Generated by Django 3.2.12 on 2022-05-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0015_alter_material_clase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['descripcion_venta'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
    ]
