# Generated by Django 3.2.12 on 2022-05-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0017_imagenmaterial_videomaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenmaterial',
            options={'verbose_name': 'Imagen Material', 'verbose_name_plural': 'Imagen Materiales'},
        ),
        migrations.AlterModelOptions(
            name='relacionmaterialcomponente',
            options={'verbose_name': 'Relacion Material Componente', 'verbose_name_plural': 'Relacion Material Componentes'},
        ),
        migrations.AlterModelOptions(
            name='videomaterial',
            options={'verbose_name': 'Video Material', 'verbose_name_plural': 'Video Materiales'},
        ),
    ]
