# Generated by Django 3.2.12 on 2022-05-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0018_auto_20220523_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenmaterial',
            options={'ordering': ['estado_alta_baja'], 'verbose_name': 'Imagen Material', 'verbose_name_plural': 'Imagen Materiales'},
        ),
        migrations.AlterModelOptions(
            name='videomaterial',
            options={'ordering': ['estado_alta_baja'], 'verbose_name': 'Video Material', 'verbose_name_plural': 'Video Materiales'},
        ),
    ]
