# Generated by Django 3.2.12 on 2022-05-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0019_auto_20220523_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributo',
            options={'ordering': ['nombre'], 'verbose_name': 'Atributo', 'verbose_name_plural': 'Atributos'},
        ),
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['nombre'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ['nombre'], 'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
        migrations.AlterModelOptions(
            name='familia',
            options={'ordering': ['nombre'], 'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nombre'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ['nombre'], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelOptions(
            name='subfamilia',
            options={'ordering': ['nombre'], 'verbose_name': 'SubFamilia', 'verbose_name_plural': 'SubFamilias'},
        ),
    ]
