# Generated by Django 3.2.12 on 2022-05-24 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0011_pais'),
        ('material', '0020_proveedormaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalenciaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_base', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad Base')),
                ('cantidad_nueva_unidad', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad Nueva')),
                ('estado_alta_baja', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EquivalenciaUnidad_created_by', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('nueva_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EquivalenciaUnidad_nueva_unidad', to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EquivalenciaUnidad_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equivalencia Unidad',
                'verbose_name_plural': 'Equivalencia Unidades',
            },
        ),
    ]
