# Generated by Django 3.2.12 on 2022-05-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0020_auto_20220524_1527'),
        ('material', '0021_equivalenciaunidad'),
    ]

    operations = [
    ]
