# Generated by Django 3.2.12 on 2022-05-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0022_merge_0020_auto_20220524_1527_0021_equivalenciaunidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especificacion',
            options={'ordering': ['orden'], 'verbose_name': 'Especificacion', 'verbose_name_plural': 'Especificaciones'},
        ),
    ]
