# Generated by Django 3.2.12 on 2022-05-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0023_alter_especificacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equivalenciaunidad',
            options={'ordering': ['estado_alta_baja'], 'verbose_name': 'Equivalencia Unidad', 'verbose_name_plural': 'Equivalencia Unidades'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['estado_alta_baja', 'descripcion_venta'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='proveedormaterial',
            options={'ordering': ['estado_alta_baja'], 'verbose_name': 'Proveedor Material', 'verbose_name_plural': 'Proveedor Materiales'},
        ),
    ]
