# Generated by Django 3.2.12 on 2022-05-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0023_alter_especificacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Material_marca', to='material.marca'),
        ),
        migrations.AlterField(
            model_name='material',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Material_modelo', to='material.modelo'),
        ),
    ]
