# Generated by Django 3.2.12 on 2022-05-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0024_auto_20220524_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='atributos',
            field=models.ManyToManyField(blank=True, to='material.Atributo'),
        ),
        migrations.AlterField(
            model_name='subfamilia',
            name='componentes',
            field=models.ManyToManyField(blank=True, to='material.Componente'),
        ),
    ]
