# Generated by Django 3.2.12 on 2022-05-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0024_auto_20220526_0934'),
        ('material', '0025_auto_20220525_1731'),
    ]

    operations = [
    ]
