# Generated by Django 3.2.12 on 2022-05-26 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0027_idioma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idioma',
            options={'ordering': ['nombre'], 'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.CreateModel(
            name='IdiomaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traduccion', models.CharField(max_length=50, verbose_name='Traducción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='IdiomaMaterial_created_by', to=settings.AUTH_USER_MODEL)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.idioma')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='IdiomaMaterial_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idioma Material',
                'verbose_name_plural': 'Idioma Materiales',
                'ordering': ['idioma'],
            },
        ),
    ]
