# Generated by Django 3.2.12 on 2022-05-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0028_auto_20220526_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idiomamaterial',
            options={'verbose_name': 'Idioma Material', 'verbose_name_plural': 'Idioma Materiales'},
        ),
    ]
