# Generated by Django 3.2.12 on 2022-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0029_alter_idiomamaterial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='id_producto_temporal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
