# Generated by Django 3.2.12 on 2022-07-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('material', '0030_remove_proveedormaterial_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedormaterial',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedormaterial',
            name='id_registro',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
