# Generated by Django 3.2.12 on 2022-07-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0031_auto_20220713_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='atributo',
            field=models.ManyToManyField(related_name='Material_atributo', to='material.Atributo', verbose_name='Atributo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='componente',
            field=models.ManyToManyField(related_name='Material_componente', through='material.RelacionMaterialComponente', to='material.Componente', verbose_name='Componente'),
        ),
    ]
