# Generated by Django 3.2.12 on 2022-07-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0030_material_id_producto_temporal'),
        ('material', '0031_auto_20220704_1122'),
    ]

    operations = [
    ]
