# Generated by Django 3.2.12 on 2022-07-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0032_auto_20220713_1532'),
        ('material', '0032_merge_20220714_1317'),
    ]

    operations = [
    ]
