# Generated by Django 3.2.12 on 2022-07-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('material', '0033_merge_20220715_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedormaterial',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='proveedormaterial',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
