# Generated by Django 3.2.12 on 2022-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0034_auto_20220727_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=42, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion_corta',
            field=models.CharField(max_length=55, verbose_name='Descripción Corta'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion_venta',
            field=models.CharField(max_length=150, verbose_name='Descripción Venta'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=41, verbose_name='Nombre'),
        ),
    ]
