# Generated by Django 3.2.12 on 2022-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0035_auto_20220921_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalenciaunidad',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='imagenmaterial',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedormaterial',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='videomaterial',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
    ]
