# Generated by Django 3.2.12 on 2022-10-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0036_auto_20221004_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalenciaunidad',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='imagenmaterial',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedormaterial',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='videomaterial',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
    ]
