# Generated by Django 3.2.12 on 2022-11-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0039_seriescomprobante_mostrar'),
        ('material', '0037_auto_20221005_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedormaterial',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.unidad'),
        ),
    ]
