# Generated by Django 3.2.12 on 2023-01-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0038_proveedormaterial_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='id_multiplay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
