# Generated by Django 3.2.12 on 2023-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0039_material_id_multiplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalenciaunidad',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='imagenmaterial',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedormaterial',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='videomaterial',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
    ]
