# Generated by Django 3.2.12 on 2023-04-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0040_auto_20230401_1229'),
        ('material', '0040_auto_20230401_1233'),
    ]

    operations = [
    ]
