# Generated by Django 3.2.12 on 2022-09-12 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('datos_globales', '0018_auto_20220909_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto')),
                ('condiciones_pago', models.CharField(max_length=250, verbose_name='Condiciones de pago')),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LineaCredito_cliente', to='clientes.cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
            ],
            options={
                'verbose_name': 'Linea de Credito',
                'verbose_name_plural': 'Lineas de Credito',
            },
        ),
    ]
