# Generated by Django 3.2.12 on 2022-09-12 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobranza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacredito',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineacredito',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='LineaCredito_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineacredito',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='lineacredito',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='LineaCredito_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
