# Generated by Django 3.2.12 on 2022-09-16 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0040_auto_20220916_0948'),
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobranza', '0002_auto_20220912_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cotizado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Cotizado')),
                ('total_credito', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Crédito')),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ESPERA DE APROBACIÓN'), (3, 'APROBADO'), (4, 'RECHAZADO')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('confirmacion_venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.confirmacionventa')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SolicitudCredito_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor_solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='SolicitudCredito_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Credito',
                'verbose_name_plural': 'Solicitudes de Credito',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCreditoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dias_pago', models.IntegerField(blank=True, null=True, verbose_name='Días de pago')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('solicitud_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.solicitudcredito')),
            ],
            options={
                'verbose_name': 'Solicitud de Credito Cuota',
                'verbose_name_plural': 'Solicitud de Credito Cuotas',
            },
        ),
    ]
