# Generated by Django 3.2.12 on 2022-09-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0040_auto_20220916_0948'),
        ('cobranza', '0003_solicitudcredito_solicitudcreditocuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='confirmacion_venta',
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='cotizacion_venta',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizacion.cotizacionventa'),
            preserve_default=False,
        ),
    ]
