# Generated by Django 3.2.12 on 2022-09-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('cobranza', '0005_auto_20220916_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='interlocutor_solicita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='total_cotizado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Cotizado'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='total_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Crédito'),
        ),
    ]
