# Generated by Django 3.2.12 on 2022-09-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0006_auto_20220916_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='condiciones_pago',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Condiciones de pago'),
        ),
    ]
