# Generated by Django 3.2.12 on 2022-09-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0007_solicitudcredito_condiciones_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcreditocuota',
            options={'ordering': ['solicitud_credito', 'fecha_calculo'], 'verbose_name': 'Solicitud de Credito Cuota', 'verbose_name_plural': 'Solicitud de Credito Cuotas'},
        ),
        migrations.AddField(
            model_name='solicitudcreditocuota',
            name='dias_calculo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días de calculo'),
        ),
        migrations.AddField(
            model_name='solicitudcreditocuota',
            name='fecha_calculo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de calculo'),
        ),
        migrations.AlterField(
            model_name='solicitudcreditocuota',
            name='solicitud_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SolicitudCreditoCuota_solicitud_credito', to='cobranza.solicitudcredito'),
        ),
    ]
