# Generated by Django 3.2.12 on 2022-09-22 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0022_sociedad_pie_pagina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0022_alter_seriescomprobante_serie'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('cobranza', '0008_auto_20220919_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('fecha_deuda', models.DateField(verbose_name='Fecha de deuda')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Deuda_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Deuda_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('numero_operacion', models.CharField(max_length=100, verbose_name='Número de operación')),
                ('cuenta_destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuenta de Origen')),
                ('comision', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comisión')),
                ('tipo_cambio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tipo de Cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Egreso_created_by', to=settings.AUTH_USER_MODEL)),
                ('cuenta_bamcaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.cuentabancariasociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Egreso_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('tipo_cambio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tipo de cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Retiro_created_by', to=settings.AUTH_USER_MODEL)),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.egreso')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Retiro_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
            },
        ),
        migrations.CreateModel(
            name='Redondeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tipo de cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Redondeo_created_by', to=settings.AUTH_USER_MODEL)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.deuda')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Redondeo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redondeo',
                'verbose_name_plural': 'Redondeos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('tipo_cambio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tipo de cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Pago_created_by', to=settings.AUTH_USER_MODEL)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.deuda')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Pago_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('numero_operacion', models.CharField(max_length=100, verbose_name='Número de operación')),
                ('cuenta_origen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuenta de Origen')),
                ('comision', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comisión')),
                ('tipo_cambio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tipo de Cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Ingreso_created_by', to=settings.AUTH_USER_MODEL)),
                ('cuenta_bamcaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.cuentabancariasociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Ingreso_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Cuota_created_by', to=settings.AUTH_USER_MODEL)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.deuda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Cuota_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
    ]
