# Generated by Django 3.2.12 on 2022-09-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('cobranza', '0009_cuota_deuda_egreso_ingreso_pago_redondeo_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=3, default=3.9, max_digits=5, verbose_name='Tipo de Cambio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deuda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Deuda_cliente', to='clientes.cliente'),
        ),
    ]
