# Generated by Django 3.2.12 on 2022-09-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0010_auto_20220923_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='retiro',
            name='moneda',
        ),
    ]
