# Generated by Django 3.2.12 on 2022-09-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0011_auto_20220923_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pago_deuda', to='cobranza.deuda'),
        ),
    ]
