# Generated by Django 3.2.12 on 2022-09-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0012_alter_pago_deuda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['deuda', 'fecha'], 'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.RenameField(
            model_name='egreso',
            old_name='cuenta_bamcaria',
            new_name='cuenta_bancaria',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='cuenta_bamcaria',
            new_name='cuenta_bancaria',
        ),
        migrations.AlterField(
            model_name='cuota',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cuota_deuda', to='cobranza.deuda'),
        ),
    ]
