# Generated by Django 3.2.12 on 2022-09-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0013_auto_20220927_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario'),
        ),
    ]
