# Generated by Django 3.2.12 on 2022-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0014_auto_20220927_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Tipo de cambio'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Tipo de cambio'),
        ),
    ]
