# Generated by Django 3.2.12 on 2022-10-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0015_auto_20220930_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redondeo',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Redondeo_deuda', to='cobranza.deuda'),
        ),
    ]
