# Generated by Django 3.2.12 on 2022-10-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0018_alter_lineacredito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineacredito',
            name='condiciones_pago',
            field=models.CharField(help_text='Factura a 30 días', max_length=250, verbose_name='Condiciones de pago'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='condiciones_pago',
            field=models.CharField(blank=True, help_text='Factura a 30 días', max_length=250, null=True, verbose_name='Condiciones de pago'),
        ),
    ]
