# Generated by Django 3.2.12 on 2022-12-10 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_auto_20221123_1859'),
        ('proveedores', '0009_auto_20221005_1436'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('datos_globales', '0039_seriescomprobante_mostrar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('nota', '0001_initial'),
        ('cobranza', '0019_auto_20221020_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiro',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Retiro_egreso', to='cobranza.egreso'),
        ),
        migrations.CreateModel(
            name='RedondeoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tipo de cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RedondeoProveedor_created_by', to=settings.AUTH_USER_MODEL)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RedondeoProveedor_deuda', to='cobranza.deuda')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RedondeoProveedor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redondeo Proveedor',
                'verbose_name_plural': 'Redondeos Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('tipo_cambio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tipo de Cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Nota_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota.notacredito')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Nota_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='DeudaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('tipo_cambio', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tipo de Cambio')),
                ('fecha_deuda', models.DateField(verbose_name='Fecha de deuda')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DeudaProveedor_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DeudaProveedor_proveedor', to='proveedores.proveedor')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DeudaProveedor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deuda Proveedor',
                'verbose_name_plural': 'Deudas Proeveedor',
            },
        ),
        migrations.CreateModel(
            name='CuotaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CuotaProveedor_created_by', to=settings.AUTH_USER_MODEL)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuotaProveedor_deuda', to='cobranza.deuda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CuotaProveedor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuota Proveedor',
                'verbose_name_plural': 'Cuotas Proveedor',
                'ordering': ['deuda', 'fecha'],
            },
        ),
    ]
