# Generated by Django 3.2.12 on 2022-12-13 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobranza', '0020_auto_20221210_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Monto')),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Tipo de cambio')),
                ('comentario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='PagoProveedor_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
            },
        ),
        migrations.AddField(
            model_name='egreso',
            name='es_pago',
            field=models.BooleanField(default=False, verbose_name='Para pagar Deudas'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='es_pago',
            field=models.BooleanField(default=False, verbose_name='Para pagar Deudas'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to='ingreso/voucher/'),
        ),
        migrations.AlterField(
            model_name='cuotaproveedor',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuotaProveedor_deuda', to='cobranza.deudaproveedor'),
        ),
        migrations.AlterField(
            model_name='redondeoproveedor',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RedondeoProveedor_deuda', to='cobranza.deudaproveedor'),
        ),
        migrations.DeleteModel(
            name='Retiro',
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PagoProveedor_egreso', to='cobranza.egreso'),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='PagoProveedor_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
