# Generated by Django 3.2.12 on 2022-12-14 19:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0021_auto_20221213_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Comisión'),
        ),
    ]
