# Generated by Django 3.2.12 on 2022-12-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0022_alter_ingreso_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to='img/ingreso/voucher/'),
        ),
    ]
