# Generated by Django 3.2.12 on 2022-12-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0023_alter_ingreso_voucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deuda',
            options={'ordering': ['-fecha_deuda'], 'verbose_name': 'Deuda', 'verbose_name_plural': 'Deudas'},
        ),
    ]
