# Generated by Django 3.2.12 on 2022-12-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0024_alter_deuda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-fecha', 'cuenta_bancaria'], 'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
    ]
