# Generated by Django 3.2.12 on 2022-12-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0025_alter_ingreso_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='estado_cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
