# Generated by Django 3.2.12 on 2023-01-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0026_deuda_estado_cancelado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egreso',
            options={'ordering': ['-fecha', 'cuenta_bancaria'], 'verbose_name': 'Egreso', 'verbose_name_plural': 'Egresos'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['deuda'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='pagoproveedor',
            options={'ordering': ['egreso'], 'verbose_name': 'Pago Proveedor', 'verbose_name_plural': 'Pagos a Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='solicitudcredito',
            options={'permissions': [('aprobar_solicitudcredito', 'Puede aprobar o rechazar solicitud de créditos')], 'verbose_name': 'Solicitud de Credito', 'verbose_name_plural': 'Solicitudes de Credito'},
        ),
    ]
