# Generated by Django 3.2.12 on 2023-01-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_alter_interlocutorcliente_tipo_documento'),
        ('cobranza', '0027_auto_20230106_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='interlocutor_solicita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SolicitudCredito_interlocutor_solicita', to='clientes.interlocutorcliente'),
        ),
    ]
