# Generated by Django 3.2.12 on 2023-01-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0028_alter_solicitudcredito_interlocutor_solicita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deudaproveedor',
            options={'verbose_name': 'Deuda Proveedor', 'verbose_name_plural': 'Deudas Proveedor'},
        ),
    ]
