# Generated by Django 3.2.12 on 2023-03-22 16:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0029_alter_deudaproveedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='voucher',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='img/ingreso/voucher/'),
        ),
    ]
