# Generated by Django 3.2.12 on 2023-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0031_alter_ingreso_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineacredito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
    ]
