# Generated by Django 3.2.12 on 2023-04-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0032_alter_lineacredito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineacredito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
    ]
