# Generated by Django 3.2.12 on 2023-05-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0033_alter_lineacredito_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineacredito',
            options={'ordering': ['cliente', 'estado'], 'verbose_name': 'Linea de Credito', 'verbose_name_plural': 'Lineas de Credito'},
        ),
    ]
