# Generated by Django 3.2.12 on 2023-05-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0034_alter_lineacredito_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineacredito',
            options={'ordering': ['cliente', 'estado', 'created_at'], 'verbose_name': 'Linea de Credito', 'verbose_name_plural': 'Lineas de Credito'},
        ),
    ]
