# Generated by Django 3.2.12 on 2023-05-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0035_alter_lineacredito_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='pendiente_usar',
            field=models.BooleanField(default=True, verbose_name='Saldo Pendiente para Usar'),
        ),
        migrations.AddField(
            model_name='nota',
            name='pendiente_usar',
            field=models.BooleanField(default=True, verbose_name='Saldo Pendiente para Usar'),
        ),
    ]
