# Generated by Django 3.2.12 on 2024-01-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0036_auto_20230511_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'SOLICITADO'), (2, 'APROBADO'), (3, 'RECHAZADO')], default=1),
        ),
    ]
