# Generated by Django 3.2.12 on 2024-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0037_alter_solicitudcredito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'NUEVO'), (2, 'SOLICITADO'), (3, 'APROBADO'), (4, 'RECHAZADO'), (5, 'RESUELTO')], default=1),
        ),
    ]
