# Generated by Django 3.2.12 on 2024-10-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0041_auto_20241015_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviodeuda',
            name='sociedad',
        ),
    ]
