# Generated by Django 3.2.12 on 2024-10-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0042_remove_enviodeuda_sociedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
