# Generated by Django 3.2.12 on 2022-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedad',
            name='condicion',
            field=models.IntegerField(choices=[(1, 'Habido'), (2, 'No hallado'), (3, 'No habido')], default=1, verbose_name='Condición SUNAT'),
        ),
        migrations.AlterField(
            model_name='representantelegal',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ACTIVO'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sociedad',
            name='estado_sunat',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspensión temporal'), (3, 'Baja provisional'), (4, 'Baja definitiva'), (5, 'Baja provisional de oficio'), (6, 'Baja definitiva de oficio'), (7, 'Baja interna')], default=1, verbose_name='Estado SUNAT'),
        ),
    ]
