# Generated by Django 3.2.12 on 2022-04-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0002_auto_20220421_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociedad',
            old_name='condicion',
            new_name='condicion_sunat',
        ),
    ]
