# Generated by Django 3.2.12 on 2022-04-28 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0004_auto_20220422_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representantelegal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario', to=settings.AUTH_USER_MODEL, verbose_name='Representante Legal'),
        ),
    ]
