# Generated by Django 3.2.12 on 2022-04-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0005_alter_representantelegal_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='ruc',
            field=models.CharField(max_length=15, unique=True, verbose_name='RUC'),
        ),
    ]
