# Generated by Django 3.2.12 on 2022-04-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0006_alter_sociedad_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='ruc',
            field=models.CharField(max_length=11, unique=True, verbose_name='RUC'),
        ),
    ]
