# Generated by Django 3.2.12 on 2022-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0007_alter_sociedad_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='sociedad',
            name='tipo_documento',
            field=models.CharField(choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)')], default='6', max_length=1, verbose_name='Tipo de Documento'),
        ),
    ]
