# Generated by Django 3.2.12 on 2022-05-06 15:57

import applications.funciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0009_alter_tiporepresentantelegal_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='ruc',
            field=models.CharField(max_length=11, unique=True, validators=[applications.funciones.validar_numero], verbose_name='RUC'),
        ),
    ]
