# Generated by Django 3.2.12 on 2022-05-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0010_alter_sociedad_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='condicion_sunat',
            field=models.IntegerField(choices=[(1, 'Habido'), (2, 'No hallado'), (3, 'No habido')], verbose_name='Condición SUNAT'),
        ),
        migrations.AlterField(
            model_name='sociedad',
            name='estado_sunat',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspensión temporal'), (3, 'Baja provisional'), (4, 'Baja definitiva'), (5, 'Baja provisional de oficio'), (6, 'Baja definitiva de oficio'), (7, 'Baja interna')], verbose_name='Estado SUNAT'),
        ),
    ]
