# Generated by Django 3.2.12 on 2022-05-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0011_auto_20220506_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociedad',
            options={'permissions': [('Dar de baja', 'baja_sociedad')], 'verbose_name': 'Sociedad', 'verbose_name_plural': 'Sociedades'},
        ),
    ]
