# Generated by Django 3.2.12 on 2022-05-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0012_alter_sociedad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociedad',
            options={'permissions': [('baja_sociedad', 'Dar de baja a Sociedad')], 'verbose_name': 'Sociedad', 'verbose_name_plural': 'Sociedades'},
        ),
    ]
