# Generated by Django 3.2.12 on 2022-05-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0014_auto_20220509_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociedad',
            options={'verbose_name': 'Sociedad', 'verbose_name_plural': 'Sociedades'},
        ),
    ]
