# Generated by Django 3.2.12 on 2022-05-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0009_auto_20220511_1425'),
        ('sociedad', '0015_alter_sociedad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedad',
            name='distrito',
            field=models.ForeignKey(default='010101', on_delete=django.db.models.deletion.CASCADE, to='datos_globales.distrito'),
            preserve_default=False,
        ),
    ]
