# Generated by Django 3.2.12 on 2022-05-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0009_auto_20220511_1425'),
        ('sociedad', '0016_sociedad_distrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.distrito'),
        ),
    ]
