# Generated by Django 3.2.12 on 2022-05-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0017_alter_sociedad_distrito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociedad',
            options={'ordering': ['estado_sunat', 'razon_social'], 'verbose_name': 'Sociedad', 'verbose_name_plural': 'Sociedades'},
        ),
    ]
