# Generated by Django 3.2.12 on 2022-08-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0019_alter_representantelegal_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedad',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Abreviatura'),
        ),
    ]
