# Generated by Django 3.2.12 on 2022-09-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0020_sociedad_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedad',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias'),
        ),
    ]
