# Generated by Django 3.2.12 on 2022-09-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0021_sociedad_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedad',
            name='pie_pagina',
            field=models.TextField(blank=True, null=True),
        ),
    ]
