# Generated by Django 3.2.12 on 2023-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0026_alter_representantelegal_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='estado_sunat',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspension temporal'), (3, 'Baja provisional'), (4, 'Baja definitiva'), (5, 'Baja provisional de oficio'), (6, 'Baja definitiva de oficio'), (7, 'Baja interna')], default=1, verbose_name='Estado SUNAT'),
        ),
    ]
