# Generated by Django 3.2.12 on 2023-07-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0028_alter_sociedad_tipo_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociedad',
            options={'ordering': ['estado_sunat', 'id'], 'verbose_name': 'Sociedad', 'verbose_name_plural': 'Sociedades'},
        ),
    ]
