# Generated by Django 3.2.12 on 2024-09-12 19:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0036_alter_sociedad_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
