# Generated by Django 3.2.12 on 2025-05-05 17:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0049_alter_sociedad_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
