# Generated by Django 3.2.12 on 2022-09-15 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0019_seriescomprobante'),
        ('sociedad', '0022_sociedad_pie_pagina'),
        ('activos', '0040_auto_20220831_1540'),
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, verbose_name='Nro. Factura')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('tipo_venta', models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CREDITO')], default=1, verbose_name='Tipo de Venta')),
                ('condiciones_pago', models.CharField(max_length=250, verbose_name='Condiciones de Pago')),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento Global')),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Descuento')),
                ('total_anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Anticipo')),
                ('total_gravada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gravada')),
                ('total_inafecta', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Inafecta')),
                ('total_exonerada', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Exonerada')),
                ('total_gratuita', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Gratuita')),
                ('total_otros_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Otros Cargos')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('percepcion_tipo', models.IntegerField(choices=[(1, 'PERCEPCIÓN VENTA INTERNA - TASA 2%'), (2, 'PERCEPCIÓN ADQUISICIÓN DE COMBUSTIBLE-TASA 1%'), (3, 'PERCEPCIÓN REALIZADA AL AGENTE DE PERCEPCIÓN CON TASA ESPECIAL - TASA 0.5%')])),
                ('percepcion_base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Percepcion Base Imponible')),
                ('total_percepcion', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Percepcion')),
                ('total_incluido_percepcion', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Incluido Percepcion')),
                ('retencion_tipo', models.IntegerField(choices=[(1, 'TASA 3%'), (2, 'TASA 6%')])),
                ('retencion_base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Retencion Base Imponible')),
                ('total_retencion', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Retencion')),
                ('total_impuestos_bolsas', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Impuestos Bolsas')),
                ('detraccion', models.BooleanField()),
                ('url', models.TextField()),
                ('observaciones', models.TextField()),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FacturaVenta', to='clientes.cliente')),
                ('cliente_interlocutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FacturaVenta_interlocutor', to='clientes.interlocutorcliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FacturaVenta_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('serie_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.seriescomprobante')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('tipo_cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FacturaVenta_tipo_cambio', to='datos_globales.tipocambio')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FacturaVenta_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura Venta',
                'verbose_name_plural': 'Facturas Venta',
            },
        ),
        migrations.CreateModel(
            name='FacturaVentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio unitario sin IGV')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio unitario con IGV')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio final con IGV')),
                ('descuento', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Descuento')),
                ('descuento_sin_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Descuento Sin IGV')),
                ('descuento_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Descuento Con IGV')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sub Total')),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IGV')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], default=1, verbose_name='Tipo IGV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FacturaVentaDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('factura_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FacturaVentaDetalle_cotizacion_venta', to='comprobante_venta.facturaventa')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.marcaactivo')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FacturaVentaDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura Venta Detalle',
                'verbose_name_plural': 'Facturas Venta Detalle',
            },
        ),
    ]
