# Generated by Django 3.2.12 on 2022-09-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventadetalle',
            name='factura_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FacturaVentaDetalle_factura_venta', to='comprobante_venta.facturaventa'),
        ),
    ]
