# Generated by Django 3.2.12 on 2022-09-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0021_auto_20220916_1630'),
        ('comprobante_venta', '0002_alter_facturaventadetalle_factura_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='detraccion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro. Factura'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='percepcion_base_imponible',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Percepcion Base Imponible'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='percepcion_tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'PERCEPCIÓN VENTA INTERNA - TASA 2%'), (2, 'PERCEPCIÓN ADQUISICIÓN DE COMBUSTIBLE-TASA 1%'), (3, 'PERCEPCIÓN REALIZADA AL AGENTE DE PERCEPCIÓN CON TASA ESPECIAL - TASA 0.5%')], null=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='retencion_base_imponible',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Retencion Base Imponible'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='retencion_tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'TASA 3%'), (2, 'TASA 6%')], null=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='serie_comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.seriescomprobante'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total_anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Anticipo'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Descuento'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total_exonerada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Exonerada'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total_gratuita',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Gratuita'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total_gravada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Gravada'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total_impuestos_bolsas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Impuestos Bolsas'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total_inafecta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Inafecta'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total_incluido_percepcion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Incluido Percepcion'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total_percepcion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Percepcion'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Retencion'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
