# Generated by Django 3.2.12 on 2022-09-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0003_auto_20220921_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaventadetalle',
            name='marca',
        ),
        migrations.AddField(
            model_name='facturaventadetalle',
            name='descripcion_documento',
            field=models.CharField(default='Hola', max_length=250, verbose_name='Descripción para documento'),
            preserve_default=False,
        ),
    ]
