# Generated by Django 3.2.12 on 2022-09-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0022_alter_seriescomprobante_serie'),
        ('comprobante_venta', '0004_auto_20220921_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaventadetalle',
            name='descuento_con_igv',
        ),
        migrations.RemoveField(
            model_name='facturaventadetalle',
            name='descuento_sin_igv',
        ),
        migrations.AddField(
            model_name='facturaventadetalle',
            name='anticipo_documento_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaventadetalle',
            name='anticipo_documento_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.seriescomprobante'),
        ),
        migrations.AddField(
            model_name='facturaventadetalle',
            name='anticipo_regularizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facturaventadetalle',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Código Interno'),
        ),
        migrations.AddField(
            model_name='facturaventadetalle',
            name='codigo_producto_sunat',
            field=models.CharField(default='000', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaventadetalle',
            name='isc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ISC'),
        ),
        migrations.AddField(
            model_name='facturaventadetalle',
            name='tipo_de_isc',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AddField(
            model_name='facturaventadetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='numero_factura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro. Factura'),
        ),
    ]
