# Generated by Django 3.2.12 on 2022-09-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0005_auto_20220921_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
