# Generated by Django 3.2.12 on 2022-09-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0006_facturaventa_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='condiciones_pago',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Condiciones de Pago'),
        ),
    ]
