# Generated by Django 3.2.12 on 2022-09-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0007_alter_facturaventa_condiciones_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
