# Generated by Django 3.2.12 on 2022-09-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0008_alter_facturaventa_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventadetalle',
            name='codigo_producto_sunat',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
