# Generated by Django 3.2.12 on 2022-09-27 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0022_sociedad_pie_pagina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0022_alter_seriescomprobante_serie'),
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('comprobante_venta', '0009_alter_facturaventadetalle_codigo_producto_sunat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.IntegerField(blank=True, null=True, verbose_name='Nro. Factura')),
                ('dni', models.IntegerField(max_length='8')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento Global')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total')),
                ('url', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BoletaVenta_cliente', to='clientes.cliente')),
                ('cliente_interlocutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BoletaVenta_interlocutor', to='clientes.interlocutorcliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='BoletaVenta_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('serie_comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.seriescomprobante')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('tipo_cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BoletaVenta_tipo_cambio', to='datos_globales.tipocambio')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='BoletaVenta_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleta Venta',
                'verbose_name_plural': 'Boletas Venta',
            },
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FacturaVenta_cliente', to='clientes.cliente'),
        ),
        migrations.CreateModel(
            name='BoletaVentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio unitario sin IGV')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio unitario con IGV')),
                ('descuento', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Descuento')),
                ('descuento_sin_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Descuento sin IGV')),
                ('descuento_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Descuento con IGV')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, default=0, max_digits=22, verbose_name='Precio final con IGV')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sub Total')),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IGV')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], default=1, verbose_name='Tipo IGV')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('boleta_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoletaVentaDetalle_boleta_venta', to='comprobante_venta.boletaventa')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='BoletaVentaDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='BoletaVentaDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleta Venta Detalle',
                'verbose_name_plural': 'Boletas Venta Detalle',
            },
        ),
    ]
