# Generated by Django 3.2.12 on 2022-09-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0010_auto_20220927_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
