# Generated by Django 3.2.12 on 2022-09-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0011_alter_boletaventa_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletaventa',
            name='numero_factura',
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='numero_boleta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro. Boleta'),
        ),
    ]
