# Generated by Django 3.2.12 on 2022-09-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0012_auto_20220928_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
