# Generated by Django 3.2.12 on 2022-09-29 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0043_merge_20220921_1056'),
        ('comprobante_venta', '0013_alter_boletaventa_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='confirmacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FacturaVenta_confirmacion', to='cotizacion.confirmacionventa'),
        ),
    ]
