# Generated by Django 3.2.12 on 2022-09-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0014_facturaventa_confirmacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletaventa',
            options={'ordering': ['-created_at'], 'verbose_name': 'Boleta Venta', 'verbose_name_plural': 'Boletas Venta'},
        ),
        migrations.AlterModelOptions(
            name='facturaventadetalle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Factura Venta Detalle', 'verbose_name_plural': 'Facturas Venta Detalle'},
        ),
    ]
