# Generated by Django 3.2.12 on 2022-10-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0022_alter_seriescomprobante_serie'),
        ('cotizacion', '0043_merge_20220921_1056'),
        ('comprobante_venta', '0015_auto_20220930_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturaventa',
            options={'ordering': ['-created_at'], 'verbose_name': 'Factura Venta', 'verbose_name_plural': 'Facturas Venta'},
        ),
        migrations.AlterModelOptions(
            name='facturaventadetalle',
            options={'verbose_name': 'Factura Venta Detalle', 'verbose_name_plural': 'Facturas Venta Detalle'},
        ),
        migrations.RemoveField(
            model_name='boletaventa',
            name='dni',
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='condiciones_pago',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Condiciones de Pago'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='confirmacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BoletaVenta_confirmacion', to='cotizacion.confirmacionventa'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='detraccion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='percepcion_base_imponible',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Percepcion Base Imponible'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='percepcion_tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'PERCEPCIÓN VENTA INTERNA - TASA 2%'), (2, 'PERCEPCIÓN ADQUISICIÓN DE COMBUSTIBLE-TASA 1%'), (3, 'PERCEPCIÓN REALIZADA AL AGENTE DE PERCEPCIÓN CON TASA ESPECIAL - TASA 0.5%')], null=True),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='retencion_base_imponible',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Retencion Base Imponible'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='retencion_tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'TASA 3%'), (2, 'TASA 6%')], null=True),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)')], max_length=1, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='tipo_venta',
            field=models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CREDITO')], default=1, verbose_name='Tipo de Venta'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Anticipo'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Descuento'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_exonerada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Exonerada'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_gratuita',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Gratuita'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_gravada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Gravada'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_impuestos_bolsas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Impuestos Bolsas'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_inafecta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Inafecta'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_incluido_percepcion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Incluido Percepcion'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_otros_cargos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Otros Cargos'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_percepcion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Percepcion'),
        ),
        migrations.AddField(
            model_name='boletaventa',
            name='total_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Total Retencion'),
        ),
        migrations.AddField(
            model_name='boletaventadetalle',
            name='anticipo_documento_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boletaventadetalle',
            name='anticipo_documento_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.seriescomprobante'),
        ),
        migrations.AddField(
            model_name='boletaventadetalle',
            name='anticipo_regularizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boletaventadetalle',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Código Interno'),
        ),
        migrations.AddField(
            model_name='boletaventadetalle',
            name='codigo_producto_sunat',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='boletaventadetalle',
            name='descripcion_documento',
            field=models.CharField(default=1, max_length=250, verbose_name='Descripción para documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletaventadetalle',
            name='isc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ISC'),
        ),
        migrations.AddField(
            model_name='boletaventadetalle',
            name='tipo_de_isc',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
    ]
