# Generated by Django 3.2.12 on 2022-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0016_auto_20221001_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1),
        ),
    ]
