# Generated by Django 3.2.12 on 2022-10-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0017_auto_20221004_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletaventa',
            name='url',
        ),
        migrations.RemoveField(
            model_name='facturaventa',
            name='url',
        ),
    ]
