# Generated by Django 3.2.12 on 2022-10-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0018_auto_20221004_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO'), (4, 'ENVIADO A NUBEFACT')], default=1),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO'), (4, 'ENVIADO A NUBEFACT')], default=1),
        ),
    ]
