# Generated by Django 3.2.12 on 2022-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0019_auto_20221005_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletaventa',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'NOTA DE CRÉDITO'), (4, 'NOTA DE DÉBITO')], default=2, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'NOTA DE CRÉDITO'), (4, 'NOTA DE DÉBITO')], default=1, verbose_name='Tipo de Comprobante'),
        ),
    ]
