# Generated by Django 3.2.12 on 2022-10-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0020_auto_20221005_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletaventa',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='boletaventa',
            name='tipo_documento',
        ),
    ]
