# Generated by Django 3.2.12 on 2022-10-05 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comprobante_venta', '0022_auto_20221005_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventadetalle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='boletaventadetalle',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaventadetalle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='facturaventadetalle',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
