# Generated by Django 3.2.12 on 2022-10-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0023_auto_20221005_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='detraccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='detraccion',
            field=models.BooleanField(default=False),
        ),
    ]
