# Generated by Django 3.2.12 on 2022-10-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0024_auto_20221005_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO'), (4, 'ACEPTADO POR SUNAT'), (5, 'RECHAZADO POR SUNAT'), (6, 'CON ERRORES')], default=1),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO'), (4, 'ACEPTADO POR SUNAT'), (5, 'RECHAZADO POR SUNAT'), (6, 'CON ERRORES')], default=1),
        ),
    ]
