# Generated by Django 3.2.12 on 2022-10-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0051_auto_20221005_1744'),
        ('comprobante_venta', '0025_auto_20221006_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='confirmacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BoletaVenta_confirmacion', to='cotizacion.confirmacionventa'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='confirmacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FacturaVenta_confirmacion', to='cotizacion.confirmacionventa'),
        ),
    ]
