# Generated by Django 3.2.12 on 2022-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0026_auto_20221006_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de Anulación'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de Anulación'),
        ),
    ]
