# Generated by Django 3.2.12 on 2022-10-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0027_auto_20221007_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletaventadetalle',
            options={'ordering': ['boleta_venta', 'item'], 'verbose_name': 'Boleta Venta Detalle', 'verbose_name_plural': 'Boletas Venta Detalle'},
        ),
        migrations.AlterModelOptions(
            name='facturaventadetalle',
            options={'ordering': ['factura_venta', 'item'], 'verbose_name': 'Factura Venta Detalle', 'verbose_name_plural': 'Facturas Venta Detalle'},
        ),
    ]
