# Generated by Django 3.2.12 on 2022-10-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0028_auto_20221010_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'NOTA DE CRÉDITO'), (4, 'NOTA DE DÉBITO'), (7, 'GUÍA REMISIÓN REMITENTE')], default=2, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AlterField(
            model_name='boletaventadetalle',
            name='descripcion_documento',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'NOTA DE CRÉDITO'), (4, 'NOTA DE DÉBITO'), (7, 'GUÍA REMISIÓN REMITENTE')], default=1, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AlterField(
            model_name='facturaventadetalle',
            name='descripcion_documento',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
    ]
