# Generated by Django 3.2.12 on 2022-10-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0030_auto_20221012_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
