# Generated by Django 3.2.12 on 2022-10-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0028_auto_20221011_1607'),
        ('comprobante_venta', '0031_auto_20221012_1532'),
    ]

    operations = [
    ]
