# Generated by Django 3.2.12 on 2022-10-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0032_merge_0028_auto_20221011_1607_0031_auto_20221012_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaventa',
            name='condiciones_pago',
            field=models.CharField(blank=True, help_text='Factura a 30 días', max_length=250, null=True, verbose_name='Condiciones de Pago'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='condiciones_pago',
            field=models.CharField(blank=True, help_text='Factura a 30 días', max_length=250, null=True, verbose_name='Condiciones de Pago'),
        ),
    ]
