# Generated by Django 3.2.12 on 2022-12-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0033_auto_20221020_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletaventa',
            name='nubefact',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='nubefact',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
