# Generated by Django 3.2.12 on 2022-12-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0034_auto_20221205_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Orden'),
        ),
    ]
