# Generated by Django 3.2.12 on 2024-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_venta', '0035_facturaventa_numero_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletaventa',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
