# Generated by Django 3.2.12 on 2022-05-31 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0005_auto_20220523_1140'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('version', models.IntegerField()),
                ('slug', models.SlugField()),
                ('estado', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterial_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='InterlocutorProveedor', to='proveedores.interlocutorproveedor')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Proveedor', to='proveedores.proveedor')),
                ('requerimiento_material_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requerimiento_de_materiales.requerimientomaterial')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterial_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimiento de Material',
                'verbose_name_plural': 'Requerimiento de Materiales',
            },
        ),
    ]
