# Generated by Django 3.2.12 on 2022-05-31 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('requerimiento_de_materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoMaterialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterialDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('requerimiento_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimiento_de_materiales.requerimientomaterial')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterialDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimiento de Material Detalle',
                'verbose_name_plural': 'Requerimiento de Material Detalles',
            },
        ),
    ]
