# Generated by Django 3.2.12 on 2022-05-31 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('proveedores', '0005_auto_20220523_1140'),
        ('requerimiento_de_materiales', '0002_requerimientomaterialdetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoMaterialTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterialTemporal_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='InterlocutorProveedor_Temporal', to='proveedores.interlocutorproveedor')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Proveedor_Temporal', to='proveedores.proveedor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterialTemporal_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimiento Material Temporal',
                'verbose_name_plural': 'Requerimiento Material Temporales',
            },
        ),
        migrations.CreateModel(
            name='RequerimientoMaterialTemporalDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterialTemporalDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('requerimiento_material_temporal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimiento_de_materiales.requerimientomaterialtemporal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterialTemporalDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimiento Material Temporal Detalle',
                'verbose_name_plural': 'Requerimiento Material Temporal Detalles',
            },
        ),
    ]
