# Generated by Django 3.2.12 on 2022-05-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0003_requerimientomaterialtemporal_requerimientomaterialtemporaldetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requerimientomaterialdetalle',
            options={'verbose_name': 'Requerimiento de Material Detalle', 'verbose_name_plural': 'Requerimiento de Materiales Detalle'},
        ),
        migrations.AlterModelOptions(
            name='requerimientomaterialtemporal',
            options={'verbose_name': 'Requerimiento de Material Temporal', 'verbose_name_plural': 'Requerimiento de Materiales Temporal'},
        ),
        migrations.AlterModelOptions(
            name='requerimientomaterialtemporaldetalle',
            options={'verbose_name': 'Requerimiento de Material Temporal Detalle', 'verbose_name_plural': 'Requerimiento de Materiales Temporal Detalle'},
        ),
    ]
