# Generated by Django 3.2.12 on 2022-05-31 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_auto_20220523_1140'),
        ('requerimiento_de_materiales', '0004_auto_20220531_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientomaterialtemporal',
            name='interlocutor_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InterlocutorProveedor_Temporal', to='proveedores.interlocutorproveedor'),
        ),
        migrations.AlterField(
            model_name='requerimientomaterialtemporal',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Proveedor_Temporal', to='proveedores.proveedor'),
        ),
    ]
