# Generated by Django 3.2.12 on 2022-06-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0005_auto_20220531_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimientomaterialtemporaldetalle',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='requerimientomaterialtemporaldetalle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='requerimientomaterialtemporaldetalle',
            name='requerimiento_material_temporal',
        ),
        migrations.RemoveField(
            model_name='requerimientomaterialtemporaldetalle',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='requerimientomaterial',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'ENVIADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='requerimientomaterial',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='requerimientomaterial',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requerimientomaterial',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='requerimientomaterial',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RequerimientoMaterialTemporal',
        ),
        migrations.DeleteModel(
            name='RequerimientoMaterialTemporalDetalle',
        ),
    ]
