# Generated by Django 3.2.12 on 2022-06-01 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_auto_20220523_1140'),
        ('requerimiento_de_materiales', '0006_auto_20220601_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientomaterial',
            name='interlocutor_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InterlocutorProveedor', to='proveedores.interlocutorproveedor'),
        ),
        migrations.AlterField(
            model_name='requerimientomaterial',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Proveedor', to='proveedores.proveedor'),
        ),
    ]
