# Generated by Django 3.2.12 on 2022-06-01 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0007_auto_20220601_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientomaterialdetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='requerimientomaterialdetalle',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requerimientomaterialdetalle',
            name='requerimiento_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequerimientoMaterialDetalle_requerimiento_material', to='requerimiento_de_materiales.requerimientomaterial'),
        ),
    ]
