# Generated by Django 3.2.12 on 2022-06-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0008_auto_20220601_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requerimientomaterial',
            options={'ordering': ['-fecha'], 'verbose_name': 'Requerimiento de Material', 'verbose_name_plural': 'Requerimiento de Materiales'},
        ),
        migrations.AlterModelOptions(
            name='requerimientomaterialdetalle',
            options={'ordering': ['item'], 'verbose_name': 'Requerimiento de Material Detalle', 'verbose_name_plural': 'Datos de Contratos de Planilla'},
        ),
    ]
