# Generated by Django 3.2.12 on 2022-06-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0009_auto_20220606_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requerimientomaterialdetalle',
            options={'ordering': ['item'], 'verbose_name': 'Requerimiento de Material Detalle', 'verbose_name_plural': 'Requerimiento de Materiales Detalle'},
        ),
    ]
