# Generated by Django 3.2.12 on 2022-06-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0010_alter_requerimientomaterialdetalle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientomaterial',
            name='fecha',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha'),
        ),
    ]
