# Generated by Django 3.2.12 on 2022-06-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0011_alter_requerimientomaterial_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientomaterial',
            name='fecha',
            field=models.DateField(editable=False, verbose_name='Fecha'),
        ),
    ]
