# Generated by Django 3.2.12 on 2022-06-15 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requerimiento_de_materiales', '0013_alter_requerimientomaterial_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaRequerimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ListaRequerimientoMaterial_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ListaRequerimientoMaterial_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Requerimiento Material',
                'verbose_name_plural': 'Listas de Requerimiento Material',
            },
        ),
        migrations.CreateModel(
            name='ListaRequerimientoMaterialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ListaRequerimientoMaterialDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('lista_requerimiento_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ListaRequerimientoMaterialDetalle_requerimiento_material', to='requerimiento_de_materiales.listarequerimientomaterial')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ListaRequerimientoMaterialDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Requerimiento Material Detalle',
                'verbose_name_plural': 'Listas de Requerimiento Material Detalle',
            },
        ),
    ]
