# Generated by Django 3.2.12 on 2022-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0014_listarequerimientomaterial_listarequerimientomaterialdetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='listarequerimientomaterialdetalle',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
