# Generated by Django 3.2.12 on 2022-06-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0015_listarequerimientomaterialdetalle_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listarequerimientomaterial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lista de Requerimiento Material', 'verbose_name_plural': 'Listas de Requerimiento Material'},
        ),
        migrations.AlterModelOptions(
            name='listarequerimientomaterialdetalle',
            options={'ordering': ['item'], 'verbose_name': 'Lista de Requerimiento Material Detalle', 'verbose_name_plural': 'Listas de Requerimiento Material Detalle'},
        ),
    ]
