# Generated by Django 3.2.12 on 2022-06-17 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0005_auto_20220523_1140'),
        ('requerimiento_de_materiales', '0016_auto_20220616_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoMaterialProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'ENVIADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterialProveedor_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InterlocutorProveedorMaterial', to='proveedores.interlocutorproveedor')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProveedorMaterial', to='proveedores.proveedor')),
                ('requerimiento_material_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requerimiento_de_materiales.requerimientomaterialproveedor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterialProveedor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimiento Material Proveedor',
                'verbose_name_plural': 'Requerimientos Material Proveedor',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoMaterialProveedorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterialProveedorDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('id_registro_material_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requerimiento_de_materiales.listarequerimientomaterialdetalle')),
                ('requerimiento_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequerimientoMaterialProveedorDetalle_requerimiento_material', to='requerimiento_de_materiales.requerimientomaterialproveedor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='RequerimientoMaterialProveedorDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimiento Material Proveedor Detalle',
                'verbose_name_plural': 'Requerimientos Material Proveedor Detalle',
                'ordering': ['item'],
            },
        ),
    ]
