# Generated by Django 3.2.12 on 2022-06-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0017_requerimientomaterialproveedor_requerimientomaterialproveedordetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requerimientomaterialproveedordetalle',
            old_name='id_registro_material_detalle',
            new_name='id_requerimiento_material_detalle',
        ),
    ]
