# Generated by Django 3.2.12 on 2022-06-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0018_rename_id_registro_material_detalle_requerimientomaterialproveedordetalle_id_requerimiento_material_'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientomaterialproveedor',
            name='lista_requerimiento',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='requerimiento_de_materiales.listarequerimientomaterial'),
            preserve_default=False,
        ),
    ]
