# Generated by Django 3.2.12 on 2022-06-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0019_requerimientomaterialproveedor_lista_requerimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimientomaterialdetalle',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='requerimientomaterialdetalle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='requerimientomaterialdetalle',
            name='requerimiento_material',
        ),
        migrations.RemoveField(
            model_name='requerimientomaterialdetalle',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='RequerimientoMaterial',
        ),
        migrations.DeleteModel(
            name='RequerimientoMaterialDetalle',
        ),
    ]
