# Generated by Django 3.2.12 on 2022-06-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0020_auto_20220630_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientomaterialproveedor',
            name='lista_requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requerimiento_de_materiales.listarequerimientomaterial'),
        ),
        migrations.AlterField(
            model_name='requerimientomaterialproveedor',
            name='requerimiento_material_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='requerimiento_de_materiales.requerimientomaterialproveedor'),
        ),
    ]
