# Generated by Django 3.2.12 on 2022-07-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0021_auto_20220630_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientomaterialproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE DE ENVÍO'), (3, 'ENVIADO')], default=1, verbose_name='Estado'),
        ),
    ]
