# Generated by Django 3.2.12 on 2022-07-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0022_alter_requerimientomaterialproveedor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listarequerimientomaterialdetalle',
            name='comentario',
            field=models.TextField(),
        ),
    ]
