# Generated by Django 3.2.12 on 2022-07-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0023_alter_listarequerimientomaterialdetalle_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listarequerimientomaterialdetalle',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
