# Generated by Django 3.2.12 on 2022-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento_de_materiales', '0024_alter_listarequerimientomaterialdetalle_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientomaterialproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'PENDIENTE DE ENVÍO'), (3, 'ENVIADO'), (4, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
    ]
