# Generated by Django 3.2.12 on 2022-10-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('requerimiento_de_materiales', '0025_alter_requerimientomaterialproveedor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientomaterialproveedor',
            name='sociedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad'),
            preserve_default=False,
        ),
    ]
