"""
Django settings for sistema_django_postgresql project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from unipath import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).ancestor(3)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-40&-8pm55n048*=6c4a!4aj&$^+igu0=xc7dj5bm8(2$0r*itu'

# Application definition

DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.postgres',
)
LOCAL_APPS = (
    'applications.home',
    'applications.usuario',
    'applications.sorteo',
    'applications.sociedad',
    'applications.programas',
    'applications.datos_globales',
    'applications.recepcion',
    'applications.colaborador',
    'applications.sede',
    'applications.material',
    'applications.proveedores',
    'applications.almacenes',
    'applications.clientes',
    'applications.requerimiento_de_materiales',
    'applications.oferta_proveedor',
    'applications.orden_compra',
    'applications.comprobante_compra',
    'applications.movimiento_almacen',
    'applications.recepcion_compra',
    'applications.nota_ingreso',
    'applications.activos',
    'applications.encuesta',
    'applications.sorteo_aptc',
    'applications.cotizacion',
    'applications.cobranza',
    'applications.logistica',
    'applications.comprobante_venta',
    'applications.envio_clientes',
    'applications.comprobante_despacho',
    'applications.sorteo_webinar',
    'applications.calidad',
    'applications.soporte_sistema',
    'applications.traslado_producto',

)

THIRD_PARTY_APPS = (
    'phonenumber_field',
    'bootstrap_modal_forms',
    'widget_tweaks',
    'colorfield',
    'django_cleanup.apps.CleanupConfig',
)

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_django_postgresql.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.child('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'django.template.context_processors.media',

                'applications.programas.context.contexto_menu',
                'applications.programas.context.cache_bust',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_django_postgresql.wsgi.application'

LOGIN_URL = '/login/'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL SETTINGS
EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.multiplay.com.pe'
EMAIL_HOST_USER = "no-responder@multiplay.com.pe"
EMAIL_HOST_PASSWORD = "MPqap4ca8SBjFuN"
EMAIL_PORT = 587

FTP_ROOT = BASE_DIR.ancestor(1).child('sistema').child('ftp')
