# Generated by Django 3.2.12 on 2022-10-03 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0017_alter_representantelegalcliente_tipo_representante_legal'),
        ('envio_clientes', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sociedad', '0022_sociedad_pie_pagina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0022_alter_seriescomprobante_serie'),
        ('sede', '0003_alter_sede_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.IntegerField()),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha Emisión')),
                ('fecha_traslado', models.DateField(blank=True, null=True, verbose_name='Fecha Traslado')),
                ('observaciones', models.TextField()),
                ('numero_bultos', models.IntegerField()),
                ('direccion_partida', models.TextField()),
                ('direccion_destino', models.TextField()),
                ('ubigeo_partida', models.IntegerField()),
                ('ubigeo_destino', models.IntegerField()),
                ('url', models.URLField(verbose_name='URL Guia')),
                ('estado', models.IntegerField()),
                ('motivo_anulación', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Guia_cliente', to='clientes.cliente')),
                ('cliente_interlocutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Guia_interlocutor', to='clientes.interlocutorcliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Guia_created_by', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
                ('serie_comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.seriescomprobante')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='envio_clientes.transportista')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Guia_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
            },
        ),
        migrations.CreateModel(
            name='GuiaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=10, max_digits=22, verbose_name='Cantidad')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='GuiaDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GuiaDetalle_guia_venta', to='comprobante_despacho.guia')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='GuiaDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Detalle',
                'verbose_name_plural': 'Guias Detalle',
            },
        ),
    ]
