# Generated by Django 3.2.12 on 2022-10-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'EN PROCESO'), (2, 'EMITIDA'), (3, 'ANULADA')], default=1, verbose_name='Estado'),
        ),
    ]
