# Generated by Django 3.2.12 on 2022-10-05 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0003_alter_sede_options'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sociedad', '0022_sociedad_pie_pagina'),
        ('comprobante_despacho', '0002_alter_guia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='direccion_destino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='direccion_partida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='motivo_anulación',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo Anulación'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='numero_bultos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='numero_guia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Guía'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='sociedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.sociedad'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='ubigeo_destino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='ubigeo_partida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guiadetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='guiadetalle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='guiadetalle',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guiadetalle',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso'),
        ),
    ]
