# Generated by Django 3.2.12 on 2022-10-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0003_auto_20221005_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiadetalle',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
