# Generated by Django 3.2.12 on 2022-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0004_alter_guiadetalle_id_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Guia'),
        ),
    ]
