# Generated by Django 3.2.12 on 2022-10-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0037_alter_nubefactrespuesta_options'),
        ('comprobante_despacho', '0005_alter_guia_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='url',
        ),
        migrations.AlterField(
            model_name='guia',
            name='ubigeo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Guia_ubigeo_destino', to='datos_globales.distrito'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='ubigeo_partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Guia_ubigeo_partida', to='datos_globales.distrito'),
        ),
    ]
