# Generated by Django 3.2.12 on 2022-10-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0006_auto_20221010_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='sede',
        ),
    ]
