# Generated by Django 3.2.12 on 2022-10-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0006_auto_20221010_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='conductor_denominacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='guia',
            name='conductor_numero_documento',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='guia',
            name='conductor_tipo_documento',
            field=models.CharField(blank=True, choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)')], max_length=1, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='guia',
            name='motivo_traslado',
            field=models.CharField(choices=[('01', 'VENTA'), ('14', 'VENTA SUJETA A CONFIRMACION DEL COMPRADOR'), ('02', 'COMPRA'), ('04', 'TRASLADO ENTRE ESTABLECIMIENTOS DE LA MISMA EMPRESA'), ('18', 'TRASLADO EMISOR ITINERANTE CP'), ('08', 'IMPORTACION'), ('09', 'EXPORTACION'), ('19', 'TRASLADO A ZONA PRIMARIA'), ('13', 'OTROS')], default='01', max_length=2, verbose_name='Motivo de Traslado'),
        ),
        migrations.AddField(
            model_name='guia',
            name='placa_numero',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Número de placa'),
        ),
        migrations.AddField(
            model_name='guia',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(1, 'FACTURA'), (2, 'BOLETA'), (3, 'NOTA DE CRÉDITO'), (4, 'NOTA DE DÉBITO'), (7, 'GUÍA REMISIÓN REMITENTE')], default=7, verbose_name='Tipo de Comprobante'),
        ),
    ]
