# Generated by Django 3.2.12 on 2022-10-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0007_auto_20221010_1445'),
        ('comprobante_despacho', '0007_remove_guia_sede'),
    ]

    operations = [
    ]
