# Generated by Django 3.2.12 on 2022-10-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0008_merge_0007_auto_20221010_1445_0007_remove_guia_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='direccion_destino',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección de Destino'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='direccion_partida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección de Partida'),
        ),
    ]
