# Generated by Django 3.2.12 on 2022-10-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0009_auto_20221011_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'EMITIDA'), (3, 'RECHAZADO'), (4, 'ANULADA'), (5, 'FINTA')], default=1, verbose_name='Estado'),
        ),
    ]
