# Generated by Django 3.2.12 on 2022-10-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0010_alter_movimientosalmacen_movimiento_anterior'),
        ('comprobante_despacho', '0010_alter_guia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='movimientos_almacen',
            field=models.ManyToManyField(to='movimiento_almacen.MovimientosAlmacen'),
        ),
    ]
