# Generated by Django 3.2.12 on 2022-10-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0011_guia_movimientos_almacen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='movimientos_almacen',
        ),
    ]
