# Generated by Django 3.2.12 on 2022-10-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0038_alter_distrito_options'),
        ('comprobante_despacho', '0012_remove_guia_movimientos_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiadetalle',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_globales.unidad'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO'), (4, 'ACEPTADO POR SUNAT'), (5, 'RECHAZADO POR SUNAT'), (6, 'CON ERRORES'), (7, 'FINTA')], default=1, verbose_name='Estado'),
        ),
    ]
