# Generated by Django 3.2.12 on 2022-10-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0013_auto_20221012_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiadetalle',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Código Interno'),
        ),
    ]
