# Generated by Django 3.2.12 on 2022-10-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0014_guiadetalle_codigo_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiadetalle',
            name='descripcion_documento',
            field=models.CharField(default='ADAPTADOR SC/APC SIMPLEX, S/M', max_length=250, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
