# Generated by Django 3.2.12 on 2022-10-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0015_guiadetalle_descripcion_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guia',
            old_name='motivo_anulación',
            new_name='motivo_anulacion',
        ),
    ]
