# Generated by Django 3.2.12 on 2022-10-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0016_rename_motivo_anulación_guia_motivo_anulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de Anulación'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
