# Generated by Django 3.2.12 on 2022-12-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0017_auto_20221012_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='nubefact',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
