# Generated by Django 3.2.12 on 2022-12-26 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0028_alter_validarserienotasalidadetalle_nota_salida_detalle'),
        ('comprobante_despacho', '0018_guia_nubefact'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Guia_despacho', to='logistica.despacho'),
        ),
    ]
