# Generated by Django 3.2.12 on 2022-12-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0019_guia_despacho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiadetalle',
            options={'ordering': ['guia', 'item'], 'verbose_name': 'Guia Detalle', 'verbose_name_plural': 'Guias Detalle'},
        ),
        migrations.RemoveField(
            model_name='guia',
            name='conductor_denominacion',
        ),
        migrations.AddField(
            model_name='guia',
            name='conductor_apellidos',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='guia',
            name='conductor_nombre',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='guia',
            name='conductor_numero_licencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Licencia'),
        ),
    ]
