# Generated by Django 3.2.12 on 2022-12-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_despacho', '0020_auto_20221227_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guia', 'verbose_name_plural': 'Guias'},
        ),
    ]
