# Generated by Django 3.2.12 on 2022-07-21 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante_compra', models.CharField(max_length=50, verbose_name='Número de Comprobante de Compra')),
                ('id_registro', models.IntegerField()),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de Recepción')),
                ('nro_bultos', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Número de Bultos')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'RECIBIDO'), (3, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RecepcionCompra_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RecepcionCompra_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RecepcionCompra_usuario_recepcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de Compra',
                'verbose_name_plural': 'Recepciones de Compras',
            },
        ),
        migrations.CreateModel(
            name='FotoRecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/recepcion compra/foto recepcion compra/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FotoRecepcionCompra_created_by', to=settings.AUTH_USER_MODEL)),
                ('recepcion_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion_compra.recepcioncompra')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FotoRecepcionCompra_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de Comprobante de Compra PI',
                'verbose_name_plural': 'Fotos de Comprobantes de Compra PIs',
            },
        ),
        migrations.CreateModel(
            name='ArchivoRecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='file/recepcion compra/archivo recepcion compra/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArchivoRecepcionCompra_created_by', to=settings.AUTH_USER_MODEL)),
                ('recepcion_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion_compra.recepcioncompra')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArchivoRecepcionCompra_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Comprobante de Compra PI',
                'verbose_name_plural': 'Archivos de Comprobantes de Compra PIs',
            },
        ),
    ]
