# Generated by Django 3.2.12 on 2022-07-21 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion_compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcioncompra',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AlterField(
            model_name='recepcioncompra',
            name='nro_bultos',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Número de Bultos'),
        ),
        migrations.AlterField(
            model_name='recepcioncompra',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RecepcionCompra_usuario_recepcion', to=settings.AUTH_USER_MODEL),
        ),
    ]
