# Generated by Django 3.2.12 on 2022-07-21 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion_compra', '0002_auto_20220721_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcioncompra',
            name='fecha_recepcion',
            field=models.DateField(verbose_name='Fecha de Recepción'),
        ),
        migrations.AlterField(
            model_name='recepcioncompra',
            name='nro_bultos',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Número de Bultos'),
        ),
        migrations.AlterField(
            model_name='recepcioncompra',
            name='usuario_recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RecepcionCompra_usuario_recepcion', to='auth.user'),
        ),
    ]
