# Generated by Django 3.2.12 on 2022-07-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_compra', '0004_alter_recepcioncompra_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivorecepcioncompra',
            options={'ordering': ['recepcion_compra', 'archivo'], 'verbose_name': 'Archivo de Comprobante de Compra PI', 'verbose_name_plural': 'Archivos de Comprobantes de Compra PIs'},
        ),
        migrations.AlterModelOptions(
            name='fotorecepcioncompra',
            options={'ordering': ['recepcion_compra', 'foto'], 'verbose_name': 'Foto de Comprobante de Compra PI', 'verbose_name_plural': 'Fotos de Comprobantes de Compra PIs'},
        ),
    ]
