# Generated by Django 3.2.12 on 2023-05-30 21:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion_compra', '0005_auto_20220727_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField(verbose_name='Fecha de Documento')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'ANULADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoReclamo_created_by', to=settings.AUTH_USER_MODEL)),
                ('recepcion_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion_compra.recepcioncompra')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoReclamo_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoReclamo_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Reclamo',
                'verbose_name_plural': 'Documentos de Reclamos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoReclamoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Cantidad')),
                ('precio_unitario_sin_igv', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio unitario sin igv')),
                ('precio_unitario_con_igv', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio unitario con igv')),
                ('precio_final_con_igv', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=22, verbose_name='Precio final con igv')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Sub Total')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('tipo_igv', models.IntegerField(choices=[(1, 'Gravado - Operación Onerosa'), (2, 'Gravado - Retiro por premio'), (3, 'Gravado - Retiro por donación'), (4, 'Gravado - Retiro'), (5, 'Gravado - Retiro por publicidad'), (6, 'Gravado - Bonificaciones'), (7, 'Gravado - Retiro por entrega a trabajadores'), (8, 'Exonerado - Operación Onerosa'), (9, 'Inafecto - Operación Onerosa'), (10, 'Inafecto - Retiro por Bonificación'), (11, 'Inafecto - Retiro'), (12, 'Inafecto - Retiro por Muestras Médicas'), (13, 'Inafecto - Retiro por Convenio Colectivo'), (14, 'Inafecto - Retiro por premio'), (15, 'Inafecto - Retiro por publicidad'), (16, 'Exportación'), (17, 'Exonerado - Transferencia Gratuita')], null=True, verbose_name='Tipo de IGV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DocumentoReclamoDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('documento_reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion_compra.documentoreclamo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DocumentoReclamoDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Reclamo Detalle',
                'verbose_name_plural': 'Documentos de Reclamo Detalles',
            },
        ),
    ]
