# Generated by Django 3.2.12 on 2023-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_compra', '0006_documentoreclamo_documentoreclamodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoreclamo',
            name='nro_documento_reclamo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentoreclamodetalle',
            name='tipo',
            field=models.IntegerField(choices=[(-1, 'DEFECTO'), (1, 'EXCESO')], default=1),
            preserve_default=False,
        ),
    ]
