# Generated by Django 3.2.12 on 2023-06-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_compra', '0007_auto_20230602_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoreclamo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'ANULADO'), (3, 'FINALIZADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='recepcioncompra',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'ANULADO'), (3, 'FINALIZADO')], default=1, verbose_name='Estado'),
        ),
    ]
