# Generated by Django 3.2.12 on 2023-06-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_compra', '0008_auto_20230603_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoreclamo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'ACTIVO'), (3, 'FINALIZADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='documentoreclamo',
            name='recepcion_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentoReclamo_recepcion_compra', to='recepcion_compra.recepcioncompra'),
        ),
        migrations.AlterField(
            model_name='documentoreclamodetalle',
            name='documento_reclamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentoReclamoDetalle_documento_reclamo', to='recepcion_compra.documentoreclamo'),
        ),
    ]
