# Generated by Django 3.2.12 on 2023-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_compra', '0009_auto_20230607_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoreclamodetalle',
            name='accion',
            field=models.IntegerField(choices=[(1, 'DESCONTAR'), (2, 'NO HACER NADA'), (3, 'POR PAGAR')], default=2),
        ),
        migrations.AlterField(
            model_name='documentoreclamo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'CONFIRMADO'), (3, 'FINALIZADO')], default=1, verbose_name='Estado'),
        ),
    ]
