# Generated by Django 3.2.12 on 2023-06-12 15:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_compra', '0010_auto_20230612_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoreclamodetalle',
            name='adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Adicional'),
        ),
        migrations.AddField(
            model_name='documentoreclamodetalle',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Factor'),
        ),
        migrations.AddField(
            model_name='documentoreclamodetalle',
            name='nuevo_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Nuevo Total'),
        ),
    ]
