# Generated by Django 3.2.12 on 2023-06-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_compra', '0011_auto_20230612_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoreclamodetalle',
            options={'ordering': ['documento_reclamo', 'item'], 'verbose_name': 'Documento de Reclamo Detalle', 'verbose_name_plural': 'Documentos de Reclamo Detalles'},
        ),
    ]
