# Generated by Django 3.2.12 on 2022-05-09 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0020_alter_cuentabancariasociedad_numero_cuenta'),
        ('sociedad', '0009_alter_tiporepresentantelegal_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de Alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('sueldo_bruto', models.BooleanField()),
                ('movilidad', models.BooleanField(default=False, verbose_name='Movilidad')),
                ('asignacion_familiar', models.BooleanField(default=False, verbose_name='Asignación familiar')),
                ('archivo_contrato', models.FileField(blank=True, null=True, upload_to='file/colaboradores/archivo_contrato/', verbose_name='Archivo Contrato')),
                ('estado_alta_baja', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.cargo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DatosContrato_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DatosContrato_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DatosColaborador_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'DatosContrato',
                'verbose_name_plural': 'DatosContratos',
            },
        ),
    ]
