# Generated by Django 3.2.12 on 2022-05-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datoscontratoplanilla',
            options={'verbose_name': 'Datos de Contrato de Planilla', 'verbose_name_plural': 'Datos de Contratos de Planilla'},
        ),
    ]
