# Generated by Django 3.2.12 on 2022-05-10 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0002_auto_20220509_1643'),
        ('sociedad', '0015_alter_sociedad_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colaborador', '0002_alter_datoscontratoplanilla_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscontratoplanilla',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DatosColaboradorPlanilla_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
        migrations.CreateModel(
            name='DatosContratoHonorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de Alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Sueldo')),
                ('suspension_cuarta', models.BooleanField(default=False, verbose_name='Suspención de Cuarta Categoria')),
                ('archivo_suspension_cuarta', models.FileField(blank=True, null=True, upload_to='file/colaboradores/archivo_suspension/', verbose_name='Archivo Suspensión Cuarta Categoría')),
                ('archivo_contrato', models.FileField(blank=True, null=True, upload_to='file/colaboradores/archivo_contrato/', verbose_name='Archivo Contrato')),
                ('estado_alta_baja', models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.cargo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DatosContratoHonorarios_created_by', to=settings.AUTH_USER_MODEL)),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DatosContratoHonorarios_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DatosColaboradorHonorariosusuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'Datos de Contrato de Honorarios',
                'verbose_name_plural': 'Datos de Contratos de Honorarios',
            },
        ),
    ]
