# Generated by Django 3.2.12 on 2022-05-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_alter_datoscontrato_sueldo_bruto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoscontrato',
            name='sueldo_bruto',
        ),
    ]
