# Generated by Django 3.2.12 on 2022-05-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0003_remove_datoscontrato_sueldo_bruto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontrato',
            name='sueldo_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Sueldo Bruto'),
            preserve_default=False,
        ),
    ]
