# Generated by Django 3.2.12 on 2022-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0003_auto_20220510_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontratohonorarios',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Año'),
            preserve_default=False,
        ),
    ]
