# Generated by Django 3.2.12 on 2022-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0004_datoscontratohonorarios_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscontratohonorarios',
            name='archivo_suspension_cuarta',
            field=models.FileField(blank=True, null=True, upload_to='file/colaboradores/archivo_suspension/', verbose_name='Archivo Suspensión 4ta categoria'),
        ),
        migrations.AlterField(
            model_name='datoscontratohonorarios',
            name='suspension_cuarta',
            field=models.BooleanField(default=False, verbose_name='Suspención de 4ta categoria'),
        ),
        migrations.AlterField(
            model_name='datoscontratohonorarios',
            name='year',
            field=models.IntegerField(max_length=4, verbose_name='Año suspención 4ta categoria'),
        ),
    ]
