# Generated by Django 3.2.12 on 2022-05-14 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0005_auto_20220514_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscontratohonorarios',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año suspención 4ta categoria'),
        ),
    ]
