# Generated by Django 3.2.12 on 2022-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0005_remove_datoscontrato_movilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontrato',
            name='movilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Movilidad'),
            preserve_default=False,
        ),
    ]
