# Generated by Django 3.2.12 on 2022-05-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0006_alter_datoscontratohonorarios_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datoscontratohonorarios',
            options={'ordering': ['-fecha_alta'], 'verbose_name': 'Datos de Contrato de Honorarios', 'verbose_name_plural': 'Datos de Contratos de Honorarios'},
        ),
        migrations.AlterModelOptions(
            name='datoscontratoplanilla',
            options={'ordering': ['-fecha_alta'], 'verbose_name': 'Datos de Contrato de Planilla', 'verbose_name_plural': 'Datos de Contratos de Planilla'},
        ),
    ]
