# Generated by Django 3.2.12 on 2022-05-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0007_auto_20220509_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscontratoplanilla',
            name='movilidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Movilidad'),
        ),
    ]
