# Generated by Django 3.2.12 on 2022-05-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0007_auto_20220514_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datoscontratohonorarios',
            options={'ordering': ['-fecha_alta'], 'verbose_name': 'Datos de Contrato por Honorarios', 'verbose_name_plural': 'Datos de Contratos por Honorarios'},
        ),
    ]
