# Generated by Django 3.2.12 on 2022-05-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0008_alter_datoscontratohonorarios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscontratoplanilla',
            name='movilidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Movilidad'),
        ),
    ]
