# Generated by Django 3.2.12 on 2023-05-16 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0034_alter_interlocutorcliente_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.IntegerField(choices=[(1, 'FACEBOOK'), (2, 'INSTAGRAM'), (3, 'LLAMADA'), (4, 'WEBINAR'), (5, 'EVENTO ISP')], default=1, verbose_name='Medio')),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente_crm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClienteCRM_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClienteCRM_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente CRM',
                'verbose_name_plural': 'Clientes CRM',
            },
        ),
    ]
