# Generated by Django 3.2.12 on 2023-05-25 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0034_alter_interlocutorcliente_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientecrm',
            name='interlocutor_principal',
        ),
        migrations.AlterField(
            model_name='clientecrm',
            name='estado',
            field=models.IntegerField(choices=[(1, 'NUEVO'), (2, 'POTENCIAL'), (3, 'INTERESADO'), (4, 'FINAL'), (5, 'ESTRELLA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='clientecrm',
            name='medio',
            field=models.IntegerField(choices=[(1, 'FACEBOOK'), (2, 'INSTAGRAM'), (3, 'LLAMADA'), (4, 'WEBINAR'), (5, 'EVENTO ISP')], verbose_name='Medio'),
        ),
        migrations.CreateModel(
            name='ClienteDetalleCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente_crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clientecrm')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClienteDetalleCRM_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClienteDetalleCRM_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente Detalle CRM',
                'verbose_name_plural': 'Clientes Detalle CRM',
            },
        ),
    ]
