# Generated by Django 3.2.12 on 2023-05-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0034_alter_interlocutorcliente_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_auto_20230525_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCRMDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente_crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clientecrm')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.correointerlocutorcliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClienteCRMDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.interlocutorcliente')),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.telefonointerlocutorcliente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClienteCRMDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente CRM Detalle ',
                'verbose_name_plural': 'Clientes CRM Detalle ',
            },
        ),
        migrations.DeleteModel(
            name='ClienteDetalleCRM',
        ),
    ]
