# Generated by Django 3.2.12 on 2023-05-29 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0011_auto_20230120_2210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_auto_20230525_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha Cierre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('presupuesto_asignado', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Presupuesto asignado')),
                ('presupuesto_utilizado', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Presupuesto utilizado')),
                ('estado', models.IntegerField(choices=[(1, 'ASIGNADO'), (2, 'EN PROCESO'), (3, 'FINALIZADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EventoCRM_created_by', to=settings.AUTH_USER_MODEL)),
                ('sorteo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Sorteo', to='sorteo.sorteo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EventoCRM_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento CRM',
                'verbose_name_plural': 'Eventos CRM',
            },
        ),
    ]
