# Generated by Django 3.2.12 on 2023-05-30 22:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20230525_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='interlocutor',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='telefono',
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='archivo_enviado',
            field=models.FileField(blank=True, null=True, upload_to='img/crm/cliente_crm/', verbose_name='Archivo Enviado'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='archivo_recibido',
            field=models.FileField(blank=True, null=True, upload_to='img/crm/cliente_crm/', verbose_name='Archivo Recibido'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto'),
        ),
    ]
