# Generated by Django 3.2.12 on 2023-05-29 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
        ('crm', '0005_eventocrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocrm',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Sorteo', to='datos_globales.pais'),
        ),
    ]
