# Generated by Django 3.2.12 on 2023-05-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20230530_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecrm',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
