# Generated by Django 3.2.12 on 2023-05-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_eventocrm_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocrm',
            name='presupuesto_asignado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Presupuesto asignado'),
        ),
        migrations.AlterField(
            model_name='eventocrm',
            name='presupuesto_utilizado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Presupuesto utilizado'),
        ),
    ]
