# Generated by Django 3.2.12 on 2023-07-03 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0013_auto_20230411_0924'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_clientecrm_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProveedorCRM_created_by', to=settings.AUTH_USER_MODEL)),
                ('proveedor_crm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProveedorCRM_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor CRM',
                'verbose_name_plural': 'Proveedores CRM',
            },
        ),
    ]
