# Generated by Django 3.2.12 on 2023-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20230528_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocrm',
            name='titulo',
            field=models.CharField(default=1, max_length=50, verbose_name='Titulo Evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventocrm',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
