# Generated by Django 3.2.12 on 2023-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_proveedorcrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecrm',
            name='estado',
            field=models.IntegerField(choices=[(1, 'NUEVO'), (2, 'POTENCIAL'), (3, 'INTERESADO'), (4, 'FINAL'), (5, 'ESTRELLA'), (6, 'DEUDOR')], default=1, verbose_name='Estado'),
        ),
    ]
