# Generated by Django 3.2.12 on 2023-06-20 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0035_alter_cliente_estado_sunat'),
        ('crm', '0008_auto_20230530_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativaCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('texto', models.CharField(max_length=100, verbose_name='Alternativa')),
                ('mostrar', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AlternativaCRM_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alternativa CRM',
                'verbose_name_plural': 'Alternativas CRM',
            },
        ),
        migrations.CreateModel(
            name='EncuestaCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_encuesta', models.IntegerField(blank=True, choices=[(1, 'VENTA'), (2, 'EVENTO'), (3, 'SATISFACCION')], null=True, verbose_name='Tipo Encuesta')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo Encuesta')),
                ('mostrar', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EncuestaCRM_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta CRM',
                'verbose_name_plural': 'Encuestas CRM',
            },
        ),
        migrations.CreateModel(
            name='PreguntaCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_presgunta', models.IntegerField(blank=True, choices=[(1, 'UNICA OPCION'), (2, 'MULTIPLE'), (3, 'ABIERTA')], null=True, verbose_name='Tipo Pregunta')),
                ('texto', models.CharField(max_length=100, verbose_name='Pregunta')),
                ('orden', models.IntegerField()),
                ('mostrar', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PreguntaCRM_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PreguntaCRM_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregunta CRM',
                'verbose_name_plural': 'Preguntas CRM',
            },
        ),
        migrations.CreateModel(
            name='RespuestaCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interlocutor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Interlocutor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cliente_crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RespuestaCRM_created_by', to=settings.AUTH_USER_MODEL)),
                ('encuesta_crm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.encuestacrm')),
                ('interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RespuestaCRM_interlocutor', to='clientes.interlocutorcliente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RespuestaCRM_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta CRM',
                'verbose_name_plural': 'Respuestas CRM',
            },
        ),
        migrations.CreateModel(
            name='RespuestaDetalleCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, verbose_name='Alternativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('alternativa_crm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.alternativacrm')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RespuestaDetalleCRM_created_by', to=settings.AUTH_USER_MODEL)),
                ('pregunta_crm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.preguntacrm')),
                ('respuesta_crm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.respuestacrm')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RespuestaDetalleCRM_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta CRM',
                'verbose_name_plural': 'Respuestas CRM',
            },
        ),
        migrations.AddField(
            model_name='encuestacrm',
            name='pregunta_crm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.preguntacrm'),
        ),
        migrations.AddField(
            model_name='encuestacrm',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EncuestaCRM_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alternativacrm',
            name='pregunta_crm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.preguntacrm'),
        ),
        migrations.AddField(
            model_name='alternativacrm',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AlternativaCRM_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
