# Generated by Django 3.2.12 on 2023-07-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_clientecrm_estado'),
        ('crm', '0008_auto_20230530_1241'),
    ]

    operations = [
    ]
