# Generated by Django 3.2.12 on 2023-06-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20230620_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestacrm',
            name='pregunta_crm',
        ),
        migrations.AddField(
            model_name='encuestacrm',
            name='pregunta_crm',
            field=models.ManyToManyField(blank=True, to='crm.PreguntaCRM'),
        ),
    ]
