# Generated by Django 3.2.12 on 2023-07-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20230620_1758'),
        ('crm', '0009_merge_20230703_1416'),
    ]

    operations = [
    ]
