# Generated by Django 3.2.12 on 2023-07-12 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0027_alter_sociedad_estado_sunat'),
        ('datos_globales', '0047_auto_20230411_0924'),
        ('almacenes', '0006_alter_almacen_estado_alta_baja'),
        ('movimiento_almacen', '0014_movimientosalmacen_transformacion'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sede', '0008_alter_sede_estado'),
        ('crm', '0009_merge_20230703_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocrm',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='eventocrm',
            name='sede_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sede.sede'),
        ),
        migrations.AddField(
            model_name='eventocrm',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
        ),
        migrations.AddField(
            model_name='eventocrm',
            name='total_merchandising',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Total Merchandising'),
        ),
        migrations.AddField(
            model_name='eventocrm',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='eventocrm',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ACTIVO'), (2, 'EN PROCESO'), (3, 'FINALIZADO')], default=1, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='EventoCRMDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('id_registro', models.IntegerField()),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EventoCRMDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('evento_crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventoCRMDetalle_evento_crm', to='crm.eventocrm')),
                ('tipo_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.unidad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EventoCRMDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento CRM Detalle ',
                'verbose_name_plural': 'Eventos CRM Detalle',
                'ordering': ['evento_crm', 'item'],
            },
        ),
    ]
