# Generated by Django 3.2.12 on 2023-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20230712_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocrmdetalle',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='eventocrmdetalle',
            name='cantidad_asignada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cantidad Asignada'),
        ),
        migrations.AddField(
            model_name='eventocrmdetalle',
            name='cantidad_restante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cantidad Restante'),
        ),
        migrations.AddField(
            model_name='eventocrmdetalle',
            name='cantidad_utilizada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cantidad Utilizada'),
        ),
    ]
