# Generated by Django 3.2.12 on 2023-06-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20230621_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestadetallecrm',
            options={'verbose_name': 'Respuesta Detalle CRM', 'verbose_name_plural': 'Respuestas Detalle CRM'},
        ),
        migrations.RenameField(
            model_name='preguntacrm',
            old_name='tipo_presgunta',
            new_name='tipo_pregunta',
        ),
    ]
