# Generated by Django 3.2.12 on 2023-07-13 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0011_auto_20230713_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCRMDetalleInformacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EventoCRMDetalleInformacionAdicional_created_by', to=settings.AUTH_USER_MODEL)),
                ('evento_crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.eventocrm')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EventoCRMDetalleInformacionAdicional_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento CRM Detalle Informacion Adicional',
                'verbose_name_plural': 'Eventos CRM Detalle Informacion Adicional',
            },
        ),
    ]
