# Generated by Django 3.2.12 on 2023-06-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20230626_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativacrm',
            name='mostrar',
            field=models.BooleanField(default=False, verbose_name='Mostrar'),
        ),
        migrations.AlterField(
            model_name='encuestacrm',
            name='mostrar',
            field=models.BooleanField(default=False, verbose_name='Mostrar'),
        ),
        migrations.AlterField(
            model_name='preguntacrm',
            name='mostrar',
            field=models.BooleanField(default=False, verbose_name='Mostrar'),
        ),
    ]
