# Generated by Django 3.2.12 on 2023-06-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
        ('crm', '0012_auto_20230626_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestacrm',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Pais', to='datos_globales.pais'),
        ),
        migrations.AlterField(
            model_name='eventocrm',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pais', to='datos_globales.pais'),
        ),
    ]
