# Generated by Django 3.2.12 on 2023-06-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20230627_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestacrm',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
