# Generated by Django 3.2.12 on 2023-06-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_encuestacrm_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntacrm',
            name='tipo_pregunta',
            field=models.IntegerField(choices=[(1, 'UNICA OPCION'), (2, 'MULTIPLE'), (3, 'ABIERTA')], default=1, verbose_name='Tipo Pregunta'),
            preserve_default=False,
        ),
    ]
