# Generated by Django 3.2.12 on 2023-07-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_preguntacrm_tipo_pregunta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativacrm',
            options={'ordering': ['orden'], 'verbose_name': 'Alternativa CRM', 'verbose_name_plural': 'Alternativas CRM'},
        ),
        migrations.AlterModelOptions(
            name='preguntacrm',
            options={'ordering': ['orden'], 'verbose_name': 'Pregunta CRM', 'verbose_name_plural': 'Preguntas CRM'},
        ),
        migrations.AddField(
            model_name='alternativacrm',
            name='valor',
            field=models.CharField(default=0, max_length=100, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
