# Generated by Django 3.2.12 on 2023-07-04 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20230704_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntacrm',
            options={'ordering': ['orden', 'tipo_pregunta', 'mostrar', 'created_at'], 'verbose_name': 'Pregunta CRM', 'verbose_name_plural': 'Preguntas CRM'},
        ),
        migrations.AddField(
            model_name='respuestacrm',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ENVIADO'), (3, 'EXPIRADO')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestacrm',
            name='fecha_vencimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Vencimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestacrm',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestadetallecrm',
            name='borrador',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
