# Generated by Django 3.2.12 on 2023-07-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20230704_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativacrm',
            options={'ordering': ['pregunta_crm', 'orden', 'texto', 'created_at'], 'verbose_name': 'Alternativa CRM', 'verbose_name_plural': 'Alternativas CRM'},
        ),
        migrations.AlterModelOptions(
            name='encuestacrm',
            options={'ordering': ['created_at'], 'verbose_name': 'Encuesta CRM', 'verbose_name_plural': 'Encuestas CRM'},
        ),
        migrations.AlterField(
            model_name='alternativacrm',
            name='pregunta_crm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AlternativaCRM_pregunta_crm', to='crm.preguntacrm'),
        ),
    ]
