# Generated by Django 3.2.12 on 2023-07-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0035_alter_cliente_estado_sunat'),
        ('crm', '0018_auto_20230704_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestacrm',
            name='interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RespuestaCRM_interlocutor', to='clientes.interlocutorcliente'),
        ),
    ]
