# Generated by Django 3.2.12 on 2023-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_respuestacrm_interlocutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestacrm',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ENVIADO'), (3, 'EXPIRADO')], default=1),
        ),
        migrations.AlterField(
            model_name='respuestacrm',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
