# Generated by Django 3.2.12 on 2023-07-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20230705_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntacrm',
            options={'ordering': ['orden', '-created_at', 'mostrar'], 'verbose_name': 'Pregunta CRM', 'verbose_name_plural': 'Preguntas CRM'},
        ),
        migrations.AlterField(
            model_name='respuestadetallecrm',
            name='respuesta_crm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RespuestaDetalleCRM_respuesta_crm', to='crm.respuestacrm'),
        ),
        migrations.AlterField(
            model_name='respuestadetallecrm',
            name='texto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto'),
        ),
    ]
