# Generated by Django 3.2.12 on 2023-07-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20230707_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuestacrm',
            options={'ordering': ['-created_at'], 'verbose_name': 'Encuesta CRM', 'verbose_name_plural': 'Encuestas CRM'},
        ),
        migrations.AlterModelOptions(
            name='respuestacrm',
            options={'ordering': ['-created_at'], 'verbose_name': 'Respuesta CRM', 'verbose_name_plural': 'Respuestas CRM'},
        ),
    ]
