# Generated by Django 3.2.12 on 2023-07-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_merge_20230707_1214'),
        ('crm', '0022_auto_20230712_0905'),
    ]

    operations = [
    ]
