# Generated by Django 3.2.12 on 2023-07-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_merge_20230714_1636'),
        ('crm', '0023_merge_20230714_1731'),
    ]

    operations = [
    ]
