# Generated by Django 3.2.12 on 2023-07-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_alter_eventocrm_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='compromiso',
            field=models.TextField(blank=True, null=True, verbose_name='Compromiso'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='mejoras',
            field=models.TextField(blank=True, null=True, verbose_name='Mejoras'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='objetivo',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='quejas',
            field=models.TextField(blank=True, null=True, verbose_name='Quejas'),
        ),
        migrations.AlterField(
            model_name='clientecrmdetalle',
            name='archivo_enviado',
            field=models.ImageField(blank=True, null=True, upload_to='img/crm/cliente_crm/', verbose_name='Archivo Enviado'),
        ),
        migrations.AlterField(
            model_name='clientecrmdetalle',
            name='archivo_recibido',
            field=models.ImageField(blank=True, null=True, upload_to='img/crm/cliente_crm/', verbose_name='Archivo Recibido'),
        ),
    ]
