# Generated by Django 3.2.12 on 2023-07-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20230720_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocrm',
            name='presupuesto_asignado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Presupuesto asignado'),
        ),
        migrations.AlterField(
            model_name='eventocrm',
            name='presupuesto_utilizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Presupuesto utilizado'),
        ),
    ]
