# Generated by Django 3.2.12 on 2023-07-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
        ('crm', '0027_auto_20230720_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocrm',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.pais'),
        ),
    ]
