# Generated by Django 3.2.12 on 2023-08-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0039_auto_20230815_1747'),
        ('crm', '0028_alter_eventocrm_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecrmdetalle',
            name='cliente_crm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.DeleteModel(
            name='ClienteCRM',
        ),
    ]
