# Generated by Django 3.2.12 on 2023-08-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_eventocrm_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativacrm',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
        migrations.AlterField(
            model_name='encuestacrm',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
        migrations.AlterField(
            model_name='preguntacrm',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
        migrations.AlterField(
            model_name='preguntacrm',
            name='texto',
            field=models.CharField(max_length=150, verbose_name='Pregunta'),
        ),
    ]
