# Generated by Django 3.2.12 on 2023-08-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20230815_1728'),
        ('crm', '0029_auto_20230815_1747'),
    ]

    operations = [
    ]
