# Generated by Django 3.2.12 on 2023-08-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
        ('crm', '0030_merge_0029_auto_20230815_1728_0029_auto_20230815_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocrm',
            name='moneda',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda'),
        ),
    ]
