# Generated by Django 3.2.12 on 2023-08-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_merge_0029_auto_20230815_1728_0029_auto_20230815_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientecrmdetalle',
            options={'verbose_name': 'Cliente CRM Detalle', 'verbose_name_plural': 'Clientes CRM Detalle'},
        ),
        migrations.AlterModelOptions(
            name='eventocrmdetalle',
            options={'ordering': ['evento_crm', 'item'], 'verbose_name': 'Evento CRM Detalle', 'verbose_name_plural': 'Eventos CRM Detalle'},
        ),
    ]
