# Generated by Django 3.2.12 on 2023-09-04 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
        ('crm', '0031_eventocrm_moneda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventocrm',
            options={'ordering': ['-created_at', '-fecha_inicio'], 'verbose_name': 'Evento CRM', 'verbose_name_plural': 'Eventos CRM'},
        ),
        migrations.AlterField(
            model_name='eventocrm',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda'),
        ),
    ]
