# Generated by Django 3.2.12 on 2023-09-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0041_cliente_estado_cliente'),
        ('crm', '0031_auto_20230825_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='monto',
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fin'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicio'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='interlocutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClienteCRMDetalle_interlocutor', to='clientes.interlocutorcliente'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='tipo_actividad',
            field=models.CharField(choices=[(1, 'REUNIÓN'), (2, 'VISITA'), (3, 'LLAMADA'), (4, 'SOPORTE TÉCNICO')], default=1, max_length=1, verbose_name='Tipo de Actividad'),
            preserve_default=False,
        ),
    ]
