# Generated by Django 3.2.12 on 2023-09-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_auto_20230911_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecrmdetalle',
            name='tipo_actividad',
            field=models.IntegerField(choices=[(1, 'REUNIÓN'), (2, 'VISITA'), (3, 'LLAMADA'), (4, 'SOPORTE TÉCNICO')], verbose_name='Tipo de Actividad'),
        ),
    ]
