# Generated by Django 3.2.12 on 2023-09-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_auto_20230903_1953'),
        ('crm', '0033_alter_clientecrmdetalle_tipo_actividad'),
    ]

    operations = [
    ]
