# Generated by Django 3.2.12 on 2023-09-28 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0034_merge_20230912_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='archivo_enviado',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='archivo_recibido',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='compromiso',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='interlocutor',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='mejoras',
        ),
        migrations.RemoveField(
            model_name='clientecrmdetalle',
            name='objetivo',
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='acuerdos',
            field=models.TextField(blank=True, null=True, verbose_name='Acuerdos'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='img/crm/cliente_crm/', verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='nombre',
            field=models.CharField(default=1, max_length=50, verbose_name='Nombre Evento/Webinar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='numero_caso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro. Caso'),
        ),
        migrations.AddField(
            model_name='clientecrmdetalle',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientecrmdetalle',
            name='tipo_actividad',
            field=models.IntegerField(choices=[(1, 'REUNIÓN'), (2, 'VISITA'), (3, 'LLAMADA'), (4, 'CORREO'), (5, 'EVENTO'), (6, 'SOPORTE TÉCNICO'), (7, 'CARACTERÍSTICAS TÉCNICAS'), (8, 'NUEVOS PRODUCTOS SOLICITADOS')], verbose_name='Tipo de Actividad'),
        ),
    ]
