# Generated by Django 3.2.12 on 2023-10-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_auto_20230928_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntacrm',
            options={'ordering': ['-created_at', 'mostrar'], 'verbose_name': 'Pregunta CRM', 'verbose_name_plural': 'Preguntas CRM'},
        ),
        migrations.AlterField(
            model_name='preguntacrm',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
