# Generated by Django 3.2.12 on 2023-10-30 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_almacen', '0016_alter_movimientosalmacen_fecha_documento'),
        ('crm', '0036_auto_20231018_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocrmdetalle',
            name='tipo_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimiento_almacen.tipostock'),
        ),
    ]
