# Generated by Django 3.2.12 on 2024-06-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_alter_eventocrmdetalle_tipo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestacrm',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
