# Generated by Django 3.2.12 on 2024-06-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_encuestacrm_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestacrm',
            name='orden',
        ),
    ]
