# Generated by Django 3.2.12 on 2022-06-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=4, verbose_name='Ticket')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=12, verbose_name='RUC')),
                ('contacto', models.CharField(max_length=120, verbose_name='Contacto')),
                ('elegido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
