# Generated by Django 3.2.12 on 2022-06-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='premio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Premio'),
        ),
    ]
