# Generated by Django 3.2.12 on 2022-06-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0002_ticket_premio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='elegido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
