# Generated by Django 3.2.12 on 2022-06-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0003_alter_ticket_elegido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='elegido',
            field=models.BooleanField(default=False),
        ),
    ]
