# Generated by Django 3.2.12 on 2022-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0004_alter_ticket_elegido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['premio', '-elegido', 'ticket'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='bloqueo',
            field=models.BooleanField(default=False),
        ),
    ]
