# Generated by Django 3.2.12 on 2023-01-21 01:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0005_auto_20220623_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sorteo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sorteo',
                'verbose_name_plural': 'Sorteos',
            },
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['sorteo', 'premio', '-elegido', 'id'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ruc',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='dato_dos',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='dato_uno',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='nombre_dato_dos',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='nombre_dato_uno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='sorteo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sorteo.sorteo'),
            preserve_default=False,
        ),
    ]
