# Generated by Django 3.2.12 on 2023-01-21 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sorteo', '0006_auto_20230120_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sorteo',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Sorteo_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Sorteo_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Ticket_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Ticket_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
