# Generated by Django 3.2.12 on 2023-01-21 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0007_auto_20230120_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sorteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ticket_sorteo', to='sorteo.sorteo'),
        ),
    ]
