# Generated by Django 3.2.12 on 2023-01-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0008_alter_ticket_sorteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
