# Generated by Django 3.2.12 on 2023-01-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0009_sorteo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='nombre_dato_dos',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='nombre_dato_uno',
        ),
        migrations.AddField(
            model_name='sorteo',
            name='nombre_dato_dos',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sorteo',
            name='nombre_dato_uno',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
