# Generated by Django 3.2.12 on 2023-01-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0010_auto_20230120_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='nombre_dato_cuatro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='nombre_dato_tres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dato_cuatro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dato_tres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
