# Generated by Django 3.2.12 on 2024-05-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL video material'),
        ),
    ]
