# Generated by Django 3.2.12 on 2022-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
    ]
