# Generated by Django 3.2.12 on 2022-10-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_alter_almacen_estado_alta_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
    ]
