# Generated by Django 3.2.12 on 2022-12-20 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0006_alter_sede_sociedad'),
        ('almacenes', '0003_alter_almacen_estado_alta_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Almacen_sede', to='sede.sede'),
        ),
    ]
