# Generated by Django 3.2.12 on 2023-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_alter_almacen_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='estado_alta_baja',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
    ]
