# Generated by Django 3.2.12 on 2023-03-07 17:53

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_globales', '0043_auto_20230125_1303'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2015)])),
                ('month', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('haber_mensual', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Haber Mensual')),
                ('lic_con_goce_haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Licencia con goce de haber')),
                ('dominical', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Dominical')),
                ('movilidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Movilidad')),
                ('asig_familiar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Asignación Familiar')),
                ('vacaciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Vacaciones')),
                ('gratificacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Gratificación')),
                ('ley29351', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Ley29351')),
                ('bonif_1mayo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Bonificación 1 Mayo')),
                ('essalud', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Essalud')),
                ('aporte_obligatorio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Aporte Obligatorio')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Comisión Porcentaje')),
                ('prima_seguro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Prima Seguro')),
                ('impuesto_quinta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Impuesto de Quinta')),
                ('neto_recibido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Neto Recibido')),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='BoletaPago_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleta de Pago',
                'verbose_name_plural': 'Boletas de Pago',
            },
        ),
        migrations.CreateModel(
            name='ReciboBoletaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pagar', models.DateField(verbose_name='Fecha Pagar')),
                ('tipo_pago', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto')),
                ('redondeo', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Redondeo')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto Pagado')),
                ('voucher', models.FileField(upload_to=None, verbose_name='Voucher')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('boleta_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.boletapago')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReciboBoletaPago_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReciboBoletaPago_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo Boleta Pago',
                'verbose_name_plural': 'Recibos Boleta Pago',
            },
        ),
        migrations.CreateModel(
            name='FondoPensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Fondo de Pensiones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FondoPensiones_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FondoPensiones_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fondo de Pension',
                'verbose_name_plural': 'Fondo de Pensiones',
            },
        ),
        migrations.CreateModel(
            name='EsSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('porcentaje', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Porcentaje')),
                ('ley30334', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EsSalud_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EsSalud_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EsSalud',
                'verbose_name_plural': 'Es Salud',
            },
        ),
        migrations.CreateModel(
            name='DatosPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_baja', models.DateField(verbose_name='Fecha Baja')),
                ('sueldo_bruto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Sueldo Bruto')),
                ('movilidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Movilidad')),
                ('planilla', models.BooleanField()),
                ('suspension_cuarta', models.BooleanField(default=False, verbose_name='Suspención de 4ta categoria')),
                ('tipo_comision', models.IntegerField(choices=[(1, 'MIXTA'), (2, 'SOBRE FLUJO')], default=1)),
                ('asignacion_familiar', models.BooleanField()),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.area')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.cargo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DatosPlanilla_created_by', to=settings.AUTH_USER_MODEL)),
                ('fondo_pensiones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.fondopensiones')),
                ('moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('sociedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='DatosPlanilla_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DatosPlanilla_suspension_cuarta', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'Datos Planilla',
                'verbose_name_plural': 'Datos Planillas',
            },
        ),
        migrations.CreateModel(
            name='ComisionFondoPensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vigencia', models.DateField(verbose_name='Fecha Vigencia')),
                ('aporte_obligatorio', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Aporte Obligatorio')),
                ('comision_flujo', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Comision Flujo')),
                ('comision_flujo_mixta', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Comision Flujo Mixta')),
                ('prima_seguro', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Prima Seguro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ComisionFondoPensiones_created_by', to=settings.AUTH_USER_MODEL)),
                ('fondo_pensiones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.fondopensiones')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ComisionFondoPensiones_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comision Fondo Pension',
                'verbose_name_plural': 'Comision Fondos Pensiones',
            },
        ),
        migrations.AddField(
            model_name='boletapago',
            name='datos_planilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.datosplanilla'),
        ),
        migrations.AddField(
            model_name='boletapago',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='BoletaPago_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
