# Generated by Django 3.2.12 on 2023-03-08 22:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0043_auto_20230125_1303'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosplanilla',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.area'),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.cargo'),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Baja'),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='fondo_pensiones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.fondopensiones'),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda'),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='movilidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Movilidad'),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='sueldo_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Sueldo Bruto'),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='tipo_comision',
            field=models.IntegerField(blank=True, choices=[(1, 'MIXTA'), (2, 'SOBRE FLUJO')], null=True),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DatosPlanilla_suspension_cuarta', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
