# Generated by Django 3.2.12 on 2023-03-09 16:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_auto_20230308_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletapago',
            name='aporte_obligatorio',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Aporte Obligatorio'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='asig_familiar',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Asignación Familiar'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='bonif_1mayo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Bonificación 1 Mayo'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='comision_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Comisión Porcentaje'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='dominical',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Dominical'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='essalud',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Essalud'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='gratificacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Gratificación'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='haber_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Haber Mensual'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='impuesto_quinta',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Impuesto de Quinta'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='ley29351',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Ley29351'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='lic_con_goce_haber',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Licencia con goce de haber'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='movilidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Movilidad'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='neto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Neto Recibido'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='prima_seguro',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Prima Seguro'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='tipo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='vacaciones',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Vacaciones'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2015)]),
        ),
    ]
