# Generated by Django 3.2.12 on 2023-03-14 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20230309_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletapago',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'ENERO'), (2, 'FEBRERO'), (3, 'MARZO'), (4, 'ABRIL'), (5, 'MAYO'), (6, 'JUNIO'), (7, 'JULIO'), (8, 'AGOSTO'), (9, 'SETIEMBRE'), (10, 'OCTUBRE'), (11, 'NOVIEMBRE'), (12, 'DICIEMBRE')], null=True, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'QUINCENA'), (2, 'FIN DE MES')], null=True),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2023)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='redondeo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Redondeo'),
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='tipo_pago',
            field=models.IntegerField(blank=True, choices=[(1, 'QUINCENA'), (2, 'FIN DE MES'), (3, 'GRATIFICACION'), (4, 'VACACIONES'), (5, 'LIQUIDACION')], null=True),
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Voucher'),
        ),
    ]
