# Generated by Django 3.2.12 on 2023-03-15 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_globales', '0043_auto_20230125_1303'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('contabilidad', '0004_auto_20230314_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Institución')),
                ('url', models.URLField(null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Institucion_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Medio de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='MedioPago_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='MedioPago_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Servicio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TipoServicio_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TipoServicio_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_referencia', models.CharField(max_length=50, verbose_name='Número de referencia')),
                ('titular_servicio', models.CharField(max_length=50, verbose_name='Titular del servicio')),
                ('direccion', models.CharField(max_length=255, null=True, verbose_name='Dirección')),
                ('alias', models.CharField(max_length=50, verbose_name='Alias')),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Servicio_created_by', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.institucion')),
                ('medio_pago', models.ManyToManyField(to='contabilidad.MedioPago')),
                ('sociedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('tipo_servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.tiposervicio')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Servicio_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ReciboServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(null=True, upload_to='', verbose_name='Foto')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emision')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Monto')),
                ('mora', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Mora')),
                ('redondeo', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Redondeo')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto Pagado')),
                ('voucher', models.FileField(null=True, upload_to='', verbose_name='Voucher')),
                ('fecha_pago', models.DateField(null=True, verbose_name='Fecha de Pago')),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReciboServicio_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.servicio')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ReciboServicio_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo de Servicio',
                'verbose_name_plural': 'Recibos de Servicios',
            },
        ),
        migrations.AddField(
            model_name='institucion',
            name='tipo_servicio',
            field=models.ManyToManyField(to='contabilidad.TipoServicio'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Institucion_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
