# Generated by Django 3.2.12 on 2023-03-15 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0043_auto_20230125_1303'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('contabilidad', '0005_auto_20230315_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciboservicio',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda'),
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.servicio'),
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Voucher'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.institucion'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='numero_referencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de referencia'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titular_servicio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titular del servicio'),
        ),
    ]
