# Generated by Django 3.2.12 on 2023-03-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_auto_20230315_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Monto'),
        ),
    ]
