# Generated by Django 3.2.12 on 2023-03-22 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_auto_20230317_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletapago',
            options={'ordering': ['-id'], 'verbose_name': 'Boleta de Pago', 'verbose_name_plural': 'Boletas de Pago'},
        ),
        migrations.AlterModelOptions(
            name='reciboboletapago',
            options={'ordering': ['-id'], 'verbose_name': 'Recibo Boleta Pago', 'verbose_name_plural': 'Recibos Boleta Pago'},
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='year',
            field=models.IntegerField(blank=True, default=2023, null=True, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2023)], verbose_name='Año'),
        ),
    ]
