# Generated by Django 3.2.12 on 2023-03-22 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('datos_globales', '0044_alter_seriescomprobante_options'),
        ('contabilidad', '0008_auto_20230322_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosplanilla',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DatosPlanilla_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Telecredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50, verbose_name='Concepto')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_cobro', models.DateField(verbose_name='Fecha de Emisión')),
                ('foto', models.FileField(null=True, upload_to='', verbose_name='Foto')),
                ('monto_usado', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto Usado')),
                ('estado', models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.banco')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Telecredito_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('sociedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Telecredito_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Telecredito_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Telecredito',
                'verbose_name_plural': 'Telecreditos',
            },
        ),
    ]
