# Generated by Django 3.2.12 on 2023-03-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_auto_20230322_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='medio_pago',
        ),
        migrations.AddField(
            model_name='institucion',
            name='medio_pago',
            field=models.ManyToManyField(to='contabilidad.MedioPago'),
        ),
        migrations.AlterField(
            model_name='boletapago',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'FIN DE MES'), (2, 'GRATIFICACION')], null=True),
        ),
        migrations.AlterField(
            model_name='comisionfondopensiones',
            name='fondo_pensiones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ComisionFondoPensiones_fondo_pensiones', to='contabilidad.fondopensiones'),
        ),
    ]
