# Generated by Django 3.2.12 on 2023-03-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_auto_20230322_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='institucion',
            name='tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.tiposervicio'),
            preserve_default=False,
        ),
    ]
