# Generated by Django 3.2.12 on 2023-03-25 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0044_alter_seriescomprobante_options'),
        ('sociedad', '0024_alter_representantelegal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0011_auto_20230322_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(default='Nuevo Cheque', max_length=50, verbose_name='Concepto')),
                ('monto_cheque', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto del cheque')),
                ('monto_usado', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto Usado')),
                ('redondeo', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Redondeo')),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Vuelto')),
                ('estado', models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'SOLICITADO'), (3, 'POR CERRAR'), (4, 'CERRADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Cheque_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Cheque_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cheque_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'ordering': ['estado', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='ChequeVueltoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuelto_original', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Vuelto en Efectivo')),
                ('vuelto_extra', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Vuelto en Moneda del Cheque')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Tipo de Cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChequeVueltoExtra_cheque', to='contabilidad.cheque')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ChequeVueltoExtra_created_by', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.moneda')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ChequeVueltoExtra_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque Vuelto Extra',
                'verbose_name_plural': 'Cheque Vueltos Extras',
            },
        ),
        migrations.CreateModel(
            name='ChequeFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de cheque')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto del cheque')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión del cheque')),
                ('fecha_cobro', models.DateField(blank=True, null=True, verbose_name='Fecha de cobro del cheque')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/caja chica/cheque/', verbose_name='Foto del cheque')),
                ('estado', models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'SOLICITADO'), (3, 'POR CERRAR'), (4, 'CERRADO')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datos_globales.banco')),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChequeFisico_cheque', to='contabilidad.cheque')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ChequeFisico_created_by', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ChequeFisico_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque Fisico',
                'verbose_name_plural': 'Cheques Fisicos',
            },
        ),
    ]
