# Generated by Django 3.2.12 on 2023-03-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_auto_20230322_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecredito',
            name='fecha_cobro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cobro'),
        ),
    ]
