# Generated by Django 3.2.12 on 2023-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_cheque_chequefisico_chequevueltoextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequefisico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/contabilidad/cheque/', verbose_name='Foto del cheque'),
        ),
    ]
