# Generated by Django 3.2.12 on 2023-03-28 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0013_alter_chequefisico_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cheque_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
