# Generated by Django 3.2.12 on 2023-03-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0024_alter_representantelegal_estado'),
        ('contabilidad', '0014_alter_cheque_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='sociedad',
        ),
        migrations.AddField(
            model_name='chequefisico',
            name='sociedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
            preserve_default=False,
        ),
    ]
