# Generated by Django 3.2.12 on 2023-04-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_alter_telecredito_fecha_cobro'),
        ('contabilidad', '0014_alter_cheque_usuario'),
    ]

    operations = [
    ]
