# Generated by Django 3.2.12 on 2023-04-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_auto_20230330_1010'),
        ('contabilidad', '0015_merge_20230401_1150'),
    ]

    operations = [
    ]
