# Generated by Django 3.2.12 on 2023-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0016_merge_20230401_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletapago',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1),
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1),
        ),
        migrations.AlterField(
            model_name='telecredito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1),
        ),
    ]
