# Generated by Django 3.2.12 on 2023-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_merge_0017_auto_20230401_1229_0017_auto_20230401_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecredito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'SOLICITADO'), (3, 'RECEPCIONADO'), (4, 'PAGADO')], default=1),
        ),
        migrations.AlterField(
            model_name='telecredito',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
    ]
