# Generated by Django 3.2.12 on 2023-04-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_merge_0017_auto_20230401_1229_0017_auto_20230401_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletapago',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='datosplanilla',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
        migrations.AlterField(
            model_name='telecredito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1),
        ),
    ]
