# Generated by Django 3.2.12 on 2023-04-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_merge_0017_auto_20230401_1229_0017_auto_20230401_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequefisico',
            name='comision',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=4, verbose_name='Comision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequefisico',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto Recibido'),
        ),
        migrations.AlterField(
            model_name='chequefisico',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'COBRADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Documento Recibo'),
        ),
    ]
