# Generated by Django 3.2.12 on 2023-04-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0019_auto_20230405_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telecredito',
            options={'ordering': ['-id'], 'verbose_name': 'Telecredito', 'verbose_name_plural': 'Telecreditos'},
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'BORRADOR'), (2, 'PENDIENTE'), (3, 'PAGADO')], default=1, null=True),
        ),
    ]
