# Generated by Django 3.2.12 on 2023-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0019_auto_20230405_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequefisico',
            name='comision',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4, verbose_name='Comision'),
        ),
    ]
