# Generated by Django 3.2.12 on 2023-04-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0019_auto_20230411_0924'),
        ('contabilidad', '0020_alter_chequefisico_comision'),
    ]

    operations = [
    ]
