# Generated by Django 3.2.12 on 2023-04-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0020_auto_20230405_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecredito',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión'),
        ),
    ]
