# Generated by Django 3.2.12 on 2023-04-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_merge_20230411_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'SOLICITADO'), (3, 'COBRADO'), (4, 'FINALIZADO')], default=1, verbose_name='Estado'),
        ),
    ]
