# Generated by Django 3.2.12 on 2023-04-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0022_alter_cheque_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.tiposervicio'),
        ),
    ]
