# Generated by Django 3.2.12 on 2023-04-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0023_alter_institucion_tipo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletapago',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'FIN DE MES'), (2, 'GRATIFICACION'), (3, 'LIQUIDACIÓN')], null=True),
        ),
    ]
