# Generated by Django 3.2.12 on 2023-05-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0024_alter_boletapago_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosplanilla',
            options={'ordering': ['estado', '-fecha_inicio'], 'verbose_name': 'Datos Planilla', 'verbose_name_plural': 'Datos Planillas'},
        ),
    ]
