# Generated by Django 3.2.12 on 2023-05-15 17:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0025_alter_datosplanilla_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletapago',
            name='comision_porcentaje',
        ),
        migrations.AddField(
            model_name='boletapago',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Comisión'),
        ),
    ]
