# Generated by Django 3.2.12 on 2023-05-15 19:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0026_auto_20230515_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletapago',
            name='cts',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='CTS'),
        ),
    ]
