# Generated by Django 3.2.12 on 2023-05-17 16:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0027_boletapago_cts'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletapago',
            name='compra_vacaciones',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True, verbose_name='Compra de Vacaciones'),
        ),
    ]
