# Generated by Django 3.2.12 on 2023-05-19 16:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0028_boletapago_compra_vacaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletapago',
            name='dias_trabajados',
            field=models.DecimalField(blank=True, decimal_places=0, default=Decimal('30'), max_digits=2, null=True, verbose_name='Días Trabajados'),
        ),
    ]
