# Generated by Django 3.2.12 on 2023-05-19 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0026_alter_representantelegal_estado'),
        ('contabilidad', '0029_boletapago_dias_trabajados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamañoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.IntegerField(choices=[(1, 'MICRO EMPRESA'), (2, 'PEQUEÑA EMPRESA'), (3, 'MEDIANA EMPRESA'), (4, 'GRAN EMPRESA')])),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TamañoEmpresa_sociedad', to='sociedad.sociedad')),
            ],
            options={
                'verbose_name': 'Tamaño de Empresa',
                'verbose_name_plural': 'Tamaño de Empresas',
            },
        ),
    ]
