# Generated by Django 3.2.12 on 2023-06-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0031_auto_20230519_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletapago',
            options={'ordering': ['-year', '-month', 'tipo', 'datos_planilla'], 'verbose_name': 'Boleta de Pago', 'verbose_name_plural': 'Boletas de Pago'},
        ),
        migrations.AlterModelOptions(
            name='comisionfondopensiones',
            options={'ordering': ['-fecha_vigencia', 'fondo_pensiones'], 'verbose_name': 'Comision Fondo Pension', 'verbose_name_plural': 'Comision Fondos Pensiones'},
        ),
        migrations.AlterModelOptions(
            name='reciboboletapago',
            options={'ordering': ['-fecha_pagar', 'boleta_pago'], 'verbose_name': 'Recibo Boleta Pago', 'verbose_name_plural': 'Recibos Boleta Pago'},
        ),
        migrations.AlterModelOptions(
            name='reciboservicio',
            options={'ordering': ['-fecha_emision', 'servicio'], 'verbose_name': 'Recibo de Servicio', 'verbose_name_plural': 'Recibos de Servicios'},
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'CANCELADO'), (2, 'PENDIENTE'), (3, 'ANULADO')], default=1),
        ),
    ]
