# Generated by Django 3.2.12 on 2023-06-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0032_auto_20230617_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciboservicio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'CANCELADO'), (3, 'ANULADO')], default=1),
        ),
    ]
