# Generated by Django 3.2.12 on 2023-06-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0033_alter_reciboservicio_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['institucion', 'alias', 'sociedad'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
