# Generated by Django 3.2.12 on 2023-06-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0035_alter_servicio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['institucion', 'tipo_servicio', 'alias', 'sociedad'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
