# Generated by Django 3.2.12 on 2023-06-23 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0036_alter_servicio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['nombre'], 'verbose_name': 'Institucion', 'verbose_name_plural': 'Instituciones'},
        ),
    ]
