# Generated by Django 3.2.12 on 2023-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0037_alter_institucion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Comisión'),
        ),
    ]
