# Generated by Django 3.2.12 on 2023-07-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0038_cheque_comision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'ordering': ['estado', 'created_at', 'concepto'], 'verbose_name': 'Cheque', 'verbose_name_plural': 'Cheques'},
        ),
    ]
