# Generated by Django 3.2.12 on 2023-07-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0047_auto_20230411_0924'),
        ('contabilidad', '0039_alter_cheque_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequefisico',
            name='moneda',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, to='datos_globales.moneda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'PENDIENTE'), (2, 'CANCELADO'), (3, 'ANULADO')], default=1, null=True),
        ),
    ]
