# Generated by Django 3.2.12 on 2023-07-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0040_auto_20230703_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciboboletapago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='reciboboletapago',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto Pagado'),
        ),
    ]
