# Generated by Django 3.2.12 on 2023-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0041_auto_20230710_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telecredito',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Telecredito', 'verbose_name_plural': 'Telecreditos'},
        ),
        migrations.AlterField(
            model_name='telecredito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'SOLICITADO'), (3, 'REGISTRADO'), (4, 'CERRADO')], default=1),
        ),
    ]
