# Generated by Django 3.2.12 on 2024-01-04 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0042_auto_20230713_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletapago',
            name='year',
            field=models.IntegerField(blank=True, default=2024, null=True, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2024)], verbose_name='Año'),
        ),
    ]
