# Generated by Django 3.2.12 on 2024-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0043_alter_boletapago_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Baja'),
        ),
    ]
