# Generated by Django 3.2.12 on 2024-01-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemadetalle',
            name='item',
        ),
    ]
