# Generated by Django 3.2.12 on 2024-01-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_remove_problemadetalle_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(choices=[(1, 'SOLICITADO'), (2, 'APROBADO'), (3, 'RECHAZADO')], default=1, verbose_name='Estado'),
        ),
    ]
