# Generated by Django 3.2.12 on 2024-02-05 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0003_solicitud_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemadetalle',
            options={'verbose_name': 'Problema Detalle', 'verbose_name_plural': 'Problemas Detalle'},
        ),
        migrations.AlterField(
            model_name='problemadetalle',
            name='problema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProblemaDetalle_problema', to='soporte.problema'),
        ),
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/soporte/solicitud/', verbose_name='Imagen')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SolicitudDetalle_created_by', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SolicitudDetalle_solicitud', to='soporte.solicitud')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SolicitudDetalle_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Detalle',
                'verbose_name_plural': 'Solicitudes Detalle',
            },
        ),
    ]
