# Generated by Django 3.2.12 on 2024-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0004_auto_20240205_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='estado',
            field=models.IntegerField(choices=[(1, 'NUEVO'), (2, 'SOLICITADO'), (3, 'EN PROCESO'), (4, 'RESUELTO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(choices=[(1, 'NUEVO'), (2, 'SOLICITADO'), (3, 'APROBADO'), (4, 'RECHAZADO'), (5, 'RESUELTO')], default=1, verbose_name='Estado'),
        ),
    ]
