# Generated by Django 3.2.12 on 2024-02-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0005_auto_20240207_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemadetalle',
            name='nota_solucion',
            field=models.TextField(blank=True, null=True, verbose_name='Nota de Solución'),
        ),
    ]
