# Generated by Django 3.2.12 on 2024-02-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0006_problemadetalle_nota_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(choices=[(1, 'NUEVO'), (2, 'SOLICITADO'), (3, 'APROBADO'), (4, 'RECHAZADO'), (5, 'EN PROCESO'), (6, 'RESUELTO')], default=1, verbose_name='Estado'),
        ),
    ]
