# Generated by Django 3.2.12 on 2024-03-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0007_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Motivo de Rechazo'),
        ),
    ]
