# Generated by Django 3.2.12 on 2024-03-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0008_solicitud_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='comentario',
            field=models.CharField(default=1, max_length=100, verbose_name='Comentario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='comentario',
            field=models.CharField(default=1, max_length=100, verbose_name='Comentario'),
            preserve_default=False,
        ),
    ]
