# Generated by Django 3.2.12 on 2022-05-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_globales', '0011_pais'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_globales.pais'),
        ),
    ]
