# Generated by Django 3.2.12 on 2022-05-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
