# Generated by Django 3.2.12 on 2022-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='correointerlocutorproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='telefonointerlocutorproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Baja')], default=1, verbose_name='Estado'),
        ),
    ]
