# Generated by Django 3.2.12 on 2022-05-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_auto_20220521_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correointerlocutorproveedor',
            options={'ordering': ['estado', '-fecha_baja'], 'verbose_name': 'Correo Interlocutor Proveedor', 'verbose_name_plural': 'Correos Interlocutores Proveedor'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['estado', 'nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedorinterlocutor',
            options={'ordering': ['estado', '-interlocutor'], 'verbose_name': 'Proveedor Interlocutor', 'verbose_name_plural': 'Proveedor Interlocutores'},
        ),
        migrations.AlterModelOptions(
            name='telefonointerlocutorproveedor',
            options={'ordering': ['estado', '-fecha_baja'], 'verbose_name': 'Telefono Interlocutor Proveedor', 'verbose_name_plural': 'Telefonos Interlocutores Proveedor'},
        ),
    ]
