# Generated by Django 3.2.12 on 2022-07-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_auto_20220523_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correointerlocutorproveedor',
            name='interlocutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CorreoInterlocutorProveedor_interlocutor', to='proveedores.interlocutorproveedor'),
        ),
        migrations.AlterField(
            model_name='proveedorinterlocutor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProveedorInterlocutor_proveedor', to='proveedores.proveedor'),
        ),
    ]
