# Generated by Django 3.2.12 on 2022-09-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_auto_20220707_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='RUC'),
        ),
    ]
