# Generated by Django 3.2.12 on 2022-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_proveedor_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correointerlocutorproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedorinterlocutor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='telefonointerlocutorproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'BORRADOR'), (2, 'ACTIVO'), (3, 'ANULADO')], default=1, verbose_name='Estado'),
        ),
    ]
