# Generated by Django 3.2.12 on 2022-10-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_auto_20221004_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correointerlocutorproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedorinterlocutor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='telefonointerlocutorproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
    ]
