# Generated by Django 3.2.12 on 2023-01-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0009_auto_20221005_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='interlocutorproveedor',
            name='id_antiguo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_antiguo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
