# Generated by Django 3.2.12 on 2023-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_auto_20230116_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correointerlocutorproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedorinterlocutor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='telefonointerlocutorproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ABIERTO'), (2, 'CERRADO'), (3, 'USADO')], default=1, verbose_name='Estado'),
        ),
    ]
