# Generated by Django 3.2.12 on 2023-04-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0012_merge_0011_auto_20230401_1229_0011_auto_20230401_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correointerlocutorproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedorinterlocutor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='telefonointerlocutorproveedor',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ALTA'), (2, 'BAJA')], default=1, verbose_name='Estado'),
        ),
    ]
